### ISSUE TITLE
Feature request: Disable auto-linking

### ISSUE THREAD

**Issue by y-lohse** [remarkjs/react-markdown#139]
Hi, and thanks your work on this!

I can't find a way to disable auto-linking, at all. Is there an option to do that?

The closest I've found is `transformLinkUri` which does get called with the link text, but it doesn't seem to do much..?

- If I provide a custom function, the return value is ignored : https://codesandbox.io/s/0p1o5vq8jv
- Passing `null` still renders a link : https://codesandbox.io/s/yv0yvpvwwz

The documentation also says `Function that gets called for each encountered link with a single argument - uri`, whereas it actually [also receives child nodes and a node title](https://github.com/rexxars/react-markdown/blob/0eee2c2f55a66e4c550162cab6fed90eda63ab55/src/ast-to-react.js#L79). It's also not quite clear if this function is used when encountering `https://github.com` or `[github](https://github.com)` or both.

Did I misinterpret the use of `transformLinkUri` or is there a problem with it?

If anyone else has the issue, I eventually disabled the `link` type with `disallowedTypes` and set `unwrapDisallowed` to `true` — but that worked because I didn't have other links in the `source`.

**Comment by rexxars** [comment]
This sounds like a combination of a documentation bug and a shortcoming in not being able to disable autolinking.

**Comment by ChristianMurphy** [comment]
autolinking is a feature of GFM, disabling GFM would also disable autolinking.
This may become easier with https://github.com/remarkjs/remark/issues/439 which breaks the GFM features out, so they can be more easily enabled/disabled independently (https://github.com/micromark/micromark-extension-gfm-autolink-literal)

**Comment by wooorm** [comment]
The v5 branch is updated with the latest remark which no longer supports autolink literals by default, as that is a GFM feature.
The plan is to release it soon.

**Comment by wooorm** [comment]
Fixed in 5.0.0!

**Comment by y-lohse** [comment]
Too late for me, but thank you anyway 😅 💙

**Comment by bartecargo** [comment]
Just in time for me, though, thanks!

**Comment by ruohola** [comment]
Is there any way to re-enable autolinking in v5?

**Comment by wooorm** [comment]
@ruohola See the changelog: https://github.com/remarkjs/react-markdown/blob/main/changelog.md#500---2020-10-19

**Comment by ruohola** [comment]
@wooorm I'm sorry I don't quite understand how that changelog shows how to do it?

**Comment by ruohola** [comment]
> @ruohola See the changelog: https://github.com/remarkjs/react-markdown/blob/main/changelog.md#500---2020-10-19

I'm sorry I don't quite understand how that changelog shows how to do it?

**Comment by ChristianMurphy** [comment]
> to match how Markdown works on GitHub, use the [remark-gfm](https://github.com/remarkjs/remark-gfm) plugin.

For more information on how that looks, see the usage guide in the readme https://github.com/remarkjs/react-markdown#use

**Comment by juanrules** [comment]
The workaround from OP (@y-lohse) worked for me: 
> If anyone else has the issue, I eventually disabled the link type with disallowedTypes and set unwrapDisallowed to true — but that worked because I didn't have other links in the source.

```
<ReactMarkdown
  source={source}
  escapeHtml={escapeHtml}
 disallowedTypes: ['link'], // This will make ReactMarkdown ignore link nodes
 unwrapDisallowed: true, // Extract (unwrap) the children of not allowed elements. By default, when strong is not allowed, it and it’s children is dropped, but with unwrapDisallowed the element itself is dropped but the children used
/>
```

Cheers
