### ISSUE TITLE
<div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by smmoosavi** [remarkjs/react-markdown#184]
I am setting `imageReference` in `renderers` wich wrap img with div and I got this error

```js
const imageRenderer = ({src, alt}) => {
  return (
    <div className="markdown-image__wrapper">
      <img src={src} alt={alt || ''}/>
    </div>
  )
}

const renderers = {imageReference: imageRenderer}
const md = <ReactMarkdown source={value}renderers={renderers}/>
```
error:
```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (at ...)
    in imageRenderer (created by ReactMarkdown)
    in p (created by ReactMarkdown)
    in div (created by ReactMarkdown)
```
how I can fix this?

Note: It render correctly, but error shown in console

**Comment by Charlicus** [comment]
I would really like to know that to if someone finds the solution..

**Comment by EKMN** [comment]
I used something like this to fix img-tags from being wrapped in p-tags:

```js
const ParagraphRenderer = (props) => {
  const hasImage = !!props.children.find(
    (child) => typeof child === 'object' && child.key && !!child.key.match(/image/g)
  )
  return hasImage ? props.children : <p>{props.children}</p>
}
```

**Comment by DoneDeal0** [comment]
The issue happens because you can't have div inside of a paragraph. So You may write:

`  <ReactMarkdown
            source={yourContent}
            renderers={{
             paragraph: props => <div {...props} />,
            }}
          />`

Now, the paragraph becomes a div, and there is no more troubles ;).

**Comment by yassinebridi** [comment]
Or you can check, if it is an image make the container as a **div**, other than that make the container as a **paragraph**.

like this:
```jsx
<ReactMarkdown
  source={source}
  renderers={{
    paragraph: props =>
      props.children[0].type.name === "image" ? (
        <div {...props} />
      ) : (
        <p {...props} />
      )
  }}
/>
```
one could argue this better for the sake of SEO

**Comment by magoz** [comment]
@EKMN and @yassinebridi code didn't work for me.

Here is how I removed `<p>` tags around images:

``` jsx
const ImagesWithoutPTags = (props) => {
  const element = props.children[0];
  return element.type === 'img' ? { ...element } : <p {...props} />;
};

<ReactMarkdown
  source={source}
  escapeHtml={false}
  renderers={{paragraph: ImagesWithoutPTags}}
/>
```

**Comment by circuitsyn** [comment]
Thank you @magoz ! This did the trick for me :D

**Comment by wooorm** [comment]
Markdown does not allow images outside of paragraphs/headings, so you can’t just add a div there.

You can unwrap them though, e.g., with https://github.com/remarkjs/remark-unwrap-images. Or you can make your own plugin.

**Comment by SalahAdDin** [comment]
@magoz Your solution just works with isolated images.
@EKMN your solution makes inline images with `div` but their companion text out to any tag.

**Comment by wooorm** [comment]
Why not?

**Comment by SalahAdDin** [comment]
@wooorm  I don't know, I'm passing it like:
```
import unwrapImages from "remark-unwrap-images"

const _mapProps = (props) => ({
  ...props,
  escapeHtml: false,
  plugins: [
    // RemarkMathPlugin,
    // RemarkHighlightPlugin,
    unwrapImages,
    VideoPlugin,
  ],
  renderers: {
    ...props.renderers,
    // math: ({ value }) => <BlockMath>{value}</BlockMath>,
    // inlineMath: ({ value }) => <InlineMath>{value}</InlineMath>,
    code: CodeBlock,
    image: ImageBlock,
    video: VideoBlock,
    paragraph: ParagraphBlock,
  },
})

const Content = (props) => <ReactMarkdown {..._mapProps(props)} />
```

But it does not unwrap the image.

**Comment by wooorm** [comment]
And if you try the v5 branch? https://github.com/remarkjs/react-markdown/commits/v5

**Comment by SalahAdDin** [comment]
@wooorm, how can I install it? because it is not available right now.

**Comment by wooorm** [comment]
npm can install from git(hub): `npm install remarkjs/remark#v5`

**Comment by SalahAdDin** [comment]
@wooorm 
I'm getting this problem all time: `Module not found: Can't resolve 'react-markdown'`

**Comment by wooorm** [comment]
whoops, that was a typo, as we’re talking about react-markdown here, it should’ve been: `npm install remarkjs/react-markdown#v5`

**Comment by SalahAdDin** [comment]
@wooorm Actually i installed it like that but it didn't work even when the package was installed.

**Comment by wooorm** [comment]
Hmm, I guess a `dist/` is built from `src/` here, so you’re missing that. An alternative is to clone this project, npm install and npm link it, and then use the link locally.

But, this works for me. It might be because I’m on v5. We’re launching a version soon that’ll definitely support this: https://github.com/remarkjs/react-markdown/issues/470

**Comment by SalahAdDin** [comment]
@wooorm Thanks, it is great.

**Comment by SalahAdDin** [comment]
@wooorm The new version breaks any solution on this issue and it reopens the problem, is there any solution for this issue with the new version?

**Comment by ChristianMurphy** [comment]
@SalahAdDin no, it makes the first suggestion from @wooorm work, as you can see here https://codesandbox.io/s/react-markdown-debug-forked-75h2t

**Comment by ChristianMurphy** [comment]
Also please direct general questions to https://github.com/remarkjs/remark/discussions

**Comment by kolyabres** [comment]
"react-markdown": "^7.1.0", does not support renderers property anymore

**Comment by ChristianMurphy** [comment]
@kolyabres yes, that happened several major versions ago.
You can learn more about the change from the changelog https://github.com/remarkjs/react-markdown/blob/main/changelog.md#600---2021-04-15
If you have questions, feel free to ask in the Q&A forum https://github.com/orgs/remarkjs/discussions
