### ISSUE TITLE
Q: Is there any way to get AST 

### ISSUE THREAD

**Issue by HairyRabbit** [remarkjs/react-markdown#198]
Hi, :)

Some reason I need get parsed ast from remark, so is there better way to get this by Component props or states or ... others?

**Comment by ChristianMurphy** [comment]
@HairyRabbit You could use `remark-parse` directly to get the AST https://github.com/remarkjs/remark/tree/master/packages/remark-parse

**Comment by wooorm** [comment]
Well, if you need the remark ast, then you can use remark? 🤔

Do let us know if we misunderstood your question
