### ISSUE TITLE
Grab all headings

### ISSUE THREAD

**Issue by oskaryil** [remarkjs/react-markdown#234]
Is there any way to grab all headings? I want to make a drawer navigation with all the headings as links that links to each section in the rendered markdown.

**Comment by std4453** [comment]
Maybe it's a better way to disallow all elements except `headings` and set `unwrapDisallowed` to `true`?

**Comment by ChristianMurphy** [comment]
this can be done with a remark plugin.
You can find more information on plugins here: https://unifiedjs.com/learn/
https://github.com/remarkjs/remark-toc may provide some inspiration, as it serves a similar goal.
