### ISSUE TITLE
Seems lists lists are broken

### ISSUE THREAD

**Issue by alisman** [remarkjs/react-markdown#235]
Getting very strange result for nested links list at top.  Verified this on your live preview.  Other markdown engines render it correctly

https://raw.githubusercontent.com/cBioPortal/cbioportal/master/docs//FAQ.md

**Comment by rexxars** [comment]
Seems like there is a long-standing issue with tabs in lists in the underlying parser: https://github.com/remarkjs/remark/issues/198

**Comment by chenhebing** [comment]
> Seems like there is a long-standing issue with tabs in lists in the underlying parser: [remarkjs/remark#198](https://github.com/remarkjs/remark/issues/198)

How to fix it? Use plugins?

**Comment by dparkar** [comment]
Facing same issue. Which other markdown engines render correctly ?

**Comment by brianlovin** [comment]
This was fixed with https://github.com/remarkjs/remark/releases/tag/remark-parse%408.0.1

Because `react-markdown` seems to be on ice right now, you can add this to your `package.json` to use the latest `remark-parse` version:

```
"resolutions": {
    "remark-parse": "^8.0.1"
  },
```

**Comment by ChristianMurphy** [comment]
will be resolved when #425 is released

**Comment by wooorm** [comment]
Fixed in 5.0.0!
