### ISSUE TITLE
If  no lines between quote and other, it display unexpected.

### ISSUE THREAD

**Issue by leavest** [remarkjs/react-markdown#238]
In demo https://rexxars.github.io/react-markdown/
This display normal.
```
> text

# h1
```

But if no lines between quote and other, it display unexpected.
```
> text
# h1
```

**Comment by ChristianMurphy** [comment]
this is an upstream problem https://github.com/remarkjs/remark/issues/306 and will be resolved by https://github.com/remarkjs/remark/issues/439

**Comment by wooorm** [comment]
Fixed in 5.0.0!
