### ISSUE TITLE
Can't get newlines to work properly

### ISSUE THREAD

**Issue by Tresky** [remarkjs/react-markdown#240]
I'm attempting to render a string with newlines. I'm pulling my string from an object thats storing a whole mess of metadata for the application. When I try to render it from the object, no newlines are created and the `\n`'s are left in the string to be displayed as normal characters.

However, if I put the *exact same string* as a string literal (rather than from the object), the newlines work properly.

**Works**
```
description () {
  return 'this is my new\nline string'
}
...
<ReactMarkdown source={this.description()} />
```

**Does Not Work**
```
constructor () {
  this.myDescription = 'this is my new\nline string'
}

description () {
  return this.myDescription
}
...
<ReactMarkdown source={this.description()} />
```

Any insight into this?

**Comment by pan-tom** [comment]
For me it works only when I put double space before \n.

**Comment by jonathanmv** [comment]
See #105. As @pan-tom says, you need double space before the `\n` to break a line

**Comment by NishidaRyu416** [comment]
In my case, I could resolve the issue by replacing \n with \n
I mean \n was considered as a string somehow without the process.

**Comment by wooorm** [comment]
newlines in paragraphs in markdown are just that: newlines. If you want them to cause `br` elements, use remark-breaks
