### ISSUE TITLE
ID's passed to ReactMarkdown not showing in the output

### ISSUE THREAD

**Issue by niccololampa** [remarkjs/react-markdown#242]
I need to pass down an id and class  to a component.  
However the id is not showing in the output. 

`<ReactMarkdown
      id="preview"
      className="markdown-output"
      source={display}
      skipHtml={false}
      escapeHtml={false}
      renderers={{ code: CodeBlock , link: LinkRenderer }}
    />
  );
}`

Only results to :

`<div class="markdown-output">`

Can you please  guide me so that the output includes the id ="preview". 

Thank you very much.

**Comment by ChristianMurphy** [comment]
@niccololampa if you are interested in adding an id/class, consider using a custom renderer https://github.com/rexxars/react-markdown#options and/or using a remark plugin https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins

**Comment by wooorm** [comment]
This issue is not enough to go on, but Christian’s answer should indeed work.
