### ISSUE TITLE
editor only accept one letter at a time  

### ISSUE THREAD

**Issue by lizhoucheng** [remarkjs/react-markdown#246]
I am using markdown editor in Typescript and I put it in a rodal(react modal). When I click the input area, I only can type in one letter; and I have to click it again to type another letter. Could someone help me with that?
`<MarkdownInput
									onChange={(val: any) => this.handleDescriptionChange(val)}
									
onBlur={() => console.log('blur')}
									value={this.state.mealDescription}
									autoFocus={false}
									readOnly={false}
									showFullScreenButton={true}
									hideToolbar={false}
									// locale='en'
									additionalButtons={[
										{
											iconElement: (<i className="fa fa-search"></i>),
											// tslint:disable-next-line
											handleButtonPress(params: any) {
												params.insertAtCursorPosition('#Product.old');
											},
											label: 'Product'
										},
									]}
								/>`

`	public handleDescriptionChange(value: any): void {

		this.setState({ mealDescription: value });
	}`

**Comment by ChristianMurphy** [comment]
@lizhoucheng for an example of how to make an editor experience see the source for the demo https://github.com/rexxars/react-markdown/tree/master/demo/src

**Comment by wooorm** [comment]
This is outside of the scope of this project
