### ISSUE TITLE
Links with underscores and italic

### ISSUE THREAD

**Issue by manelmadeira** [remarkjs/react-markdown#263]
I'm having an issue parsing some URLs in my project. The URLs have `-_-` sequence in them. 

Examples:
`_**[Google](www.google.com?params=hello-_-world)**_`
`[_**Google**_](http://www.google.com)`

**Comment by ChristianMurphy** [comment]
@manelmadeira this isn't an issue in react-markdown, it is an instance of https://github.com/remarkjs/remark/issues/306 and will be resolved by https://github.com/remarkjs/remark/issues/439
