### ISSUE TITLE
Support for declaring size on images

### ISSUE THREAD

**Issue by LinusU** [remarkjs/react-markdown#265]
It would be great if we could get support for the syntax for sizing images that some<sup>[(ref)](https://stackoverflow.com/a/21242579/148072)</sup> markdown renderers support.

```md
![Thumbnail image](foobar.png =50x50)
```

When there is a space in the url the current parser doesn't seem to treat it as an image at all, so it's not possible to add this via a custom `image` renderer.

I've used the following (super ugly 😂) workaround for now, but would be great if it was supported out of the box ☺️ 

```js
import ReactMarkdown from 'react-markdown'

const imageSizeRegex = /_33B2BF251EFD_([0-9]+x|x[0-9]+|[0-9]+x[0-9]+)$/
const imagePreprocessor = (source) => source.replace(/(!\[[^\]]*\]\([^)\s]+) =([0-9]+x|x[0-9]+|[0-9]+x[0-9]+)\)/g, '$1_33B2BF251EFD_$2)')

function imageRenderer ({ src, ...props }) {
  const match = imageSizeRegex.exec(src)

  if (!match) {
    return <img src={src} {...props} />
  }

  const [width, height] = match[1].split('x').map(s => s === '' ? undefined : Number(s))
  return <img src={src.replace(imageSizeRegex, '')} width={width} height={height} {...props} />
}

/**
 * @param {ReactMarkdown.ReactMarkdownProps} props
 */
const Markdown = ({ source, ...props }) => {
  /** @type {ReactMarkdown.ReactMarkdownProps['renderers']} */
  const renderers = {}

  source = imagePreprocessor(source)
  renderers['image'] = imageRenderer

  return <ReactMarkdown source={source} renderers={renderers} {...props} />
}

export default Markdown
```

**Comment by krymen** [comment]
👍 Would love to have it too!

**Comment by YibingMu** [comment]
So, what is the newest and easiest way to adjust image size if I use ![img](xxx.png)?

**Comment by YibingMu** [comment]
what is the newest and easiest way to change image size if I use '![]()'.

**Comment by YibingMu** [comment]
what is the newest and easiest way to change image size?

**Comment by bj00rn** [comment]
https://github.com/rexxars/react-markdown/issues/384

**Comment by ChristianMurphy** [comment]
This is not a feature of CommonMark, and so would not be added to core.
However it could be added through a remark plugin.
You can find more information on creating plugins at https://unifiedjs.com/learn/

**Comment by Flo0806** [comment]
Here is a custom Plugin. This Plugin add a width="100%" property to every image component in the markdown:

`function imageWidthPlugin() {
    return (node) => {
      for (let test in node.children) {
        if (node.children[test].type === "paragraph") {
          if (
            node.children[test].children &&
            node.children[test].children.length > 0
          ) {
            for (let child in node.children[test].children) {
              if (node.children[test].children[child].type === "image") {
                const data = (node.children[test].children[child].data = {});

                const props = (data.hProperties = {});
                props.width = "100%";
              }
            }
          }
        }
      }
    };
  }`
