### ISSUE TITLE
Allowed type problem

### ISSUE THREAD

**Issue by elir92** [remarkjs/react-markdown#266]
Hi,
I have a problem with allowed type option.
I received data from the server as string which contains html elements. 
For example: 

Data from the server: `'<p>blabla</p>'
`
I want to allow only paragraph type for this case. for example

```
payload.text // '<p>blabla</p>'

let text = payload.text;

    <div> 
       <ReactMarkdown source={text} allowedTypes={['paragraph']}/>
   </div>

```

The problem is that the text isn't render at all. i have an empty div.

It is working with this code

`<ReactMarkdown source={text} escapeHtml={false} />`

But it is not secure.

What should i do?

Thanks.

**Comment by benliger1987** [comment]
experiencing the same issue

**Comment by doaashafik** [comment]
@elir92 
try to add text in allowTypes
`allowedTypes={['paragraph','text']}` 

look at  this
```
Upgrading to 4.0
Should be straightforward. You might need to alter you code slightly if you:
Are using allowedTypes (add text to the list)
Rely on there being a container <div> without a class name around your rendered markdown
```
