### ISSUE TITLE
HTML parser: Collapsible content

### ISSUE THREAD

**Issue by NorthDecoder** [remarkjs/react-markdown#267]
Although react-markdown package claims to do Github Flavored
Markdown (GFM), the  [demo](https://rexxars.github.io/react-markdown/) appears to implement the
syntax differently than the marked.js [demo](https://marked.js.org/demo/).

The following works in marked.js demo (and on github flavored markdown):

    ## collapsible markdown?

    <details><summary>CLICK ME</summary>
    <p>

    #### yes, even hidden code blocks!

    ```python
    print("hello world!")
    ```

    </p>
    </details>

By removing spacing you can coax the react-markdown
demo to sort of work, but the collapsed content loses 
the markdown translation:

    ## collapsible markdown?

    <details><summary>CLICK ME</summary>
    <p>
    #### yes, even hidden code blocks!
    ```python
    print("hello world!")
    ```

    </p>
    </details>

----

### The collapsible markdown works in GFM

<details><summary>CLICK ME</summary>
<p>

#### yes, even hidden code blocks!

```python
print("hello world!")
```

</p>
</details>

----

Reference PrISM isssue (84)[https://github.com/NorthwestGreenChemistry/PrISM/issues/84]

**Comment by ChristianMurphy** [comment]
This will be resolved by #428 

> implement the syntax differently than the marked.js

Right, because marked.js isn't commonmark or GFM compatible, see https://github.com/markedjs/marked/issues/1202

**Comment by wooorm** [comment]
This should be solved by landing GH-563 today, which will soon be released in v6.0.0!

**Comment by murugaratham** [comment]
Does it work just by adding GFM? when i add GFM plug-in, it just render them as text

**Comment by wooorm** [comment]
`<details>` has nothing to do with GFM. It is an HTML feature. So see the [HTML in markdown](https://github.com/remarkjs/react-markdown#appendix-a-html-in-markdown) section in the readme.
