### ISSUE TITLE
Provide esm bundle

### ISSUE THREAD

**Issue by dmtrKovalenko** [remarkjs/react-markdown#268]
Provide `esm` bundle to be sure the code is correctly treeshaked and adopted by rollup. I can help with creation of `esm` build and open a PR.

**Comment by dmtrKovalenko** [comment]
We are the group of people who [treeshakes](https://github.com/Treeshakers) packages on github and fight for `esm` adoption

**Comment by wooorm** [comment]
You can shake cjs: https://github.com/indutny/webpack-common-shake
