### ISSUE TITLE
how to line break ?

### ISSUE THREAD

**Issue by converge** [remarkjs/react-markdown#273]
Tried different ways, and couldn't find it. Is there some way to break lines ?

**Comment by danyx23** [comment]
Two spaces at the end of a line as per markdown conventions (weird, but that is markdown for you)

**Comment by converge** [comment]
thanks @danyx23 , I can break one line, is it possible to break multiple lines ?

**Comment by converge** [comment]
just figured it out:
&nbsp;  
( with two spaces after &nbsp; )

**Comment by Resin01** [comment]
How did you get this working? Cannot get it to break multiple lines

**Comment by converge** [comment]
@Resin01 just updated my answer above.

**Comment by niculistana** [comment]
see: https://github.com/rexxars/react-markdown/issues/190

**Comment by telmotrooper** [comment]
Sorry to bump up this issue, but **the way it worked for me** was to use **two spaces followed by \n**.
Example: `<ReactMarkdown source={"Test  \nTest  \nTest"} />` which turns into
```
Test
Test
Test
```

**Comment by sreerampr** [comment]
How about "Test \n\nTest \n\nTest" ?

**Comment by LinusU** [comment]
Keep in mind that many editors strip out trailing whitespace by default, I usually do it like this to make it extra clear:

```js
const source = `
# Demo

Line 1${'  '}
Line 2${'  '}
Line 3
`

const Demo = () => {
  return <Markdown source={source} />
}
```

**Comment by jonathanmv** [comment]
What about empty lines?
I want to achieve

```
Line 1

Line 2
```

But when my string is `Line 1.  \n  \nLine 2` the output is the same as doing just `Line 1.  \n  Line 2`, which is 
```
Line 1
Line 2
```

**Comment by jonathanmv** [comment]
I just noticed that the output, although it looks the same, has a different html structure. From my observations when the input is `Line 1  \nLine 2`, the output is `<p>Line 1<br>Line 2</p>`. However, when adding two line break, it creates another `p` element. So, when the input is `Line 1  \n  \nLine 2`, the output is `<p>Line 1</p><p>Line 2</p>`. This let me have the *empty line* I wanted by setting the `p` margin-bottom

**Comment by JulesPatry** [comment]
I found that adding a `&nbsp` after the `\n` solved this. This is the magic line `value.replace(/\n/gi, '\n &nbsp;')`

```
const source =  value.replace(/\n/gi, '\n &nbsp;');
...
<ReactMarkdown
      source={source}
      className="reactMarkDown"
    />
```

Cheers.

**Comment by omril1** [comment]
How do I use it in a table?

```
| Option | Description |
| -------- | ------------ |
| -e     | line1&nbsp;  
line2
```

Doesn't seem to work in tables.

**Comment by shinyuy** [comment]
To get spaces between paragraphs, I tried many things but this is what worked for me, give a className to react markdown component like so <ReackMarkdown className="paragraph" source="your source" />  and in your stylesheet, pick the paragraph className and style it p tags like so .paragraph p { margin-bottom: 20px; } and this gets you spaces between your paragraphs.

**Comment by ntltd** [comment]
A very simple solution here could be to do it using [pure CSS](https://developer.mozilla.org/fr/docs/Web/CSS/white-space):
```css
white-space: pre-wrap;
```

**Comment by wooorm** [comment]
use two spaces for standard markdown breaks, or use `commonmark:true` in `parserOptions ` and then a backslash before a newline for commonmark breaks, or use remark-breaks for any newline as a break

**Comment by mzrzvi** [comment]
The solution using

```
.line-break {
  white-space: pre-wrap;
}
```

works for me locally on my dev server, but doesn't work when I build my app locally or in production (Netlify). Has anyone run into this issue before?

**Comment by quolpr** [comment]
This is a plugin that solves the issue perfectly:

https://github.com/remarkjs/remark-breaks/issues/2#issuecomment-671081891

Usage:

```tsx
import ReactMarkdown from 'react-markdown';
import breaks from 'remark-breaks';
import {
  Settings,
  Processor,
  ParserConstructor,
  ParserFunction,
} from 'unified/types';
import { Node } from 'unist';

const reBlankLine = /^[ \t]*(\n|$)/;

export function blankLines(this: Processor<Settings>) {
  const parser = this.Parser;

  if (!isRemarkParser(parser)) {
    throw new Error('Missing parser to attach `blankLines` to');
  }

  parser.prototype.blockTokenizers.blankLine = blankLine;
  // NOTE react-markdown@4.3.1 we use depends on remark-parse@5.0.0  while we use remark-parse@8.0.3
  if (parser.prototype.blockMethods.indexOf('blankLine') === -1) {
    parser.prototype.blockMethods.unshift('blankLine');
  }

  function blankLine(
    this: Tokenizer,
    eat: (consumed: string) => (node: Node) => void,
    value: string,
    silent: boolean
  ): true | void {
    let index = 0;
    const length = value.length;
    let eatenLines = 0;
    while (index < length) {
      const match = reBlankLine.exec(value.slice(index));

      if (match == null) {
        break;
      }
      if (silent) {
        return true;
      }
      // debugger;
      const line = match[0];
      index += line.length;

      const add = eat(line);
      // NOTE if we are at start we add break for each line
      // otherwise we ignore first line as it's newline of previous block
      if (this.atStart === true || eatenLines > 0) {
        add({ type: 'break' });
      }
      eatenLines++;
    }
  }
}

function isRemarkParser(parser: ParserConstructor | ParserFunction) {
  return (
    parser != null &&
    parser.prototype != null &&
    parser.prototype.blockTokenizers != null
  );
}

type Tokenizer = {
  atStart: boolean;
  inBlock: boolean;
  inLink: boolean;
  inList: boolean;
};

const Show = ({content}: {content: string}) => {
  return(
    <ReactMarkdown
      plugins={[blankLines]}
      children={content}
    />
  )
}
```

**Comment by wooorm** [comment]
@quolpr glad it worked for you, but that’s not a good solution: it doesn’t work with the current react-markdown and so folks copy-pasting it will be at a loss, so I’ll hide it.

Empty lines in markdown or HTML don’t do anything. Use code. Or don‘t use Markdown and use CSS.

Furthermore this issue is about something else
