### ISSUE TITLE
Code blocks settings/modifiers

### ISSUE THREAD

**Issue by diegohaz** [remarkjs/react-markdown#275]
Hello,

I've been trying to get the string after the language on a code block like this one:

> \`\`\`jsx **static**

The idea is to pass it to my custom `Code` component so as to configure it in different ways. Unfortunately, [this commit](https://github.com/rexxars/react-markdown/commit/51d71988191252ec74b3457561bc4f1330604b2e) strips that part away on this line:  https://github.com/rexxars/react-markdown/blob/51d71988191252ec74b3457561bc4f1330604b2e/src/ast-to-react.js#L70

I'd like to know if it's possible to overwrite this behavior and pass that part as a prop to my component.

Thank you

**Comment by ChristianMurphy** [comment]
That information should be part of the meta attribute, see https://astexplorer.net/#/gist/03012fdfbeda182699c47e5816a5d11e/f84c0be87ac972ac8e180db7fe81d4f4b51a3d9c
If it isn't available, it may be resolved by #425 and/or #428

**Comment by wooorm** [comment]
should be solved indeed
