### ISSUE TITLE
Allow multiple new lines in markdown

### ISSUE THREAD

**Issue by sinnbeck** [remarkjs/react-markdown#278]
Is there a way to allow multiple newlines in markdown?
I am running data from draftjs to markdown, which then later can be converted to html when needed. But if people add multiple new lines, these are always removed.

**Comment by Dozalex** [comment]
Hi @rexxars , could you answer on this question, please?
Why `'\n\n\n\n'` doesn't replaced by `<br /><br /><br /><br />`?
Maybe some property 'allowMultipleBreak'?

**Comment by bithavoc** [comment]
Yeah, even the demo page is broken and doesn't let use more than one empty line https://rexxars.github.io/react-markdown/

**Comment by mcknight89** [comment]
Have any of you worked around this yet? I have the same issue and need a quick solution?

**Comment by azirbel** [comment]
Not sure this will work for converting draftjs to markdown, but the setting that works for me is passing `options` to `ReactMarkdown`. Enabling the [commonmark option](https://github.com/remarkjs/remark/tree/master/packages/remark-parse#optionscommonmark) allows you to add backslashes to create extra line breaks.

```
<ReactMarkdown parserOptions={{ commonmark: true }} source={source} />
```

With `source` set to:

```
Paragraph 1
\
\
Paragraph 2
```

**Comment by JulesPatry** [comment]
To get multiple line breaks after another, I found that adding a `&nbsp` after the `\n` solved this. This is the magic line `value.replace(/\n/gi, '\n &nbsp;')`



```
const value = `hello
\n
\n
world
`

const source =  value.replace(/\n/gi, '\n &nbsp;');
...
<ReactMarkdown
      source={source}
      className="reactMarkDown"
    />
```

Cheers.

**Comment by davidcalhoun** [comment]
@azirbel Didn't work for me unfortunately.

@JulesPatry That works, it's ugly though.  Seems that I've been doing `nbsp` hacks for over ten years now...

**Comment by carlitosz** [comment]
@azirbel worked for me! Thanks!

**Comment by shinyuy** [comment]
To get spaces between paragraphs, I tried many things but this is what worked for me, give a className to react markdown component like so , className paragraph and in your stylesheet, pick the paragraph className and style it p tags like so .paragraph p { margin-bottom: 20px; } and this gets you spaces between your paragraphs. Just so it is clear, my react markdown component with the class name is stripped out of my answer.

**Comment by wooorm** [comment]
This is a feature of markdown. Multiple EOLs turn into multiple paragraphs.

**Comment by Adverbly** [comment]
I'm seeing some weird behaviour with the backslash approach on the demo page... It looks like one of the backslashes is not turning into a linebreak.

![image](https://user-images.githubusercontent.com/2197957/117477002-76695080-af2b-11eb-8a34-f1d1aea309a9.png)

Am I doing something wrong or is this a bug? I can workaround by copy pasting the unicode "blank" character, but that feels like a hack.

**Comment by wooorm** [comment]
This behavior is spec compliant: https://github.com/commonmark/commonmark-spec/issues/677#issuecomment-810462826

**Comment by vanoMekantsishvili** [comment]
> To get multiple line breaks after another, I found that adding a `&nbsp` after the `\n` solved this. This is the magic line `value.replace(/\n/gi, '\n &nbsp;')`
> 
> ```
> const value = `hello
> \n
> \n
> world
> `
> 
> const source =  value.replace(/\n/gi, '\n &nbsp;');
> ...
> <ReactMarkdown
>       source={source}
>       className="reactMarkDown"
>     />
> ```
> 
> Cheers.

Not really good solution though, it prevents to display headlines and cause other small issues, looking for proper solution, but couldn't find any. I am using markdown-to-jsx but there is no clear explanation how to achieve multiple line breaks/empty lines. Does anyone figured sth out?

**Comment by scriptify** [comment]
This little remark plugin did the job for me:
```javascript
//@ts-expect-error
import findAndReplace from 'mdast-util-find-and-replace';

function remarkBreaks() {
  function replace(match: string) {
    return {
      type: 'text',
      // value: '',
      data: {
        hName: 'br',
      },
    };
  }

  function transform(markdownAST: any) {
    findAndReplace(markdownAST, /\n/g, replace);
    return markdownAST;
  }

  return transform;
}

export default remarkBreaks;

```

Just copy pasta it

**Comment by wooorm** [comment]
Why didn’t you use remark-breaks? 🤔

**Comment by scriptify** [comment]
> Why didn’t you use remark-breaks? 🤔

For some reason, it led to multiple errors with other remark dependencies like `remark-gfm`, and I didn't figure out why, also because I had to fulfill a deadline and just make it work™

**Comment by wooorm** [comment]
I can’t see why `remark-breaks`, whether with or without `remark-gfm`, would throw an error. 🤷‍♂️

**Comment by scriptify** [comment]
It also didn't make a lot of sense to me, I was probably giving up too early. Installing `remark-breaks` results in the following type errors for me:

![image](https://user-images.githubusercontent.com/20152692/142609019-e8d87341-cbb3-4e3a-8bff-8121a87b6570.png)

Additionally, this error is thrown:

![image](https://user-images.githubusercontent.com/20152692/142609673-2ad22062-b40e-4e3d-b87f-6b1aba163c16.png)

I'm using the following package versions:

```json
{
  "remark-breaks": "^3.0.2",
  "react-markdown": "^6.0.1",
}
```

**Comment by wooorm** [comment]
I’m guessing your imports or types of `remarkCenter` are wrong.

**Comment by scriptify** [comment]
That could definitely be the case, it's a custom plugin.
Thanks for your help!

**Comment by Royal-lobster** [comment]
For someone like me who wasted hours figuring this out,  try this out -

```js
content.replace(/(?<=\n\n)(?![*-])\n/gi, "&nbsp;\n ");
```

This should escape the other markdown elements not rendering correctly.
https://codesandbox.io/s/newline-problem-rh98l5?file=/src/App.js

**Comment by artsx** [comment]
hello @Royal-lobster do you have a solution when you add several line breaks in the `<code>` because there is the `&nbsp;` which appears in the render

**Comment by yosipy** [comment]
To make line breaks similar to Github issue comments, you can do:

```ts
import { FC } from "react"

import ReactMarkdown from "react-markdown"
import remarkBreaks from "remark-breaks"

type Props = {
  body: string
}

export const Markdown: FC<Props> = (props) => {
  return (
    <ReactMarkdown
      remarkPlugins={[remarkBreaks]}
      components={{
        p: ({ children }) => <p style={{ marginBottom: "1em" }}>{children}</p>,
      }}
    >
      {props.body}
    </ReactMarkdown>
  )
}
```

Two or more consecutive newlines are grouped together, but I think this works well enough for most people.

**Comment by eeshankeni** [comment]
@Royal-lobster saved me a lot of trouble. Thanks!

**Comment by Royal-lobster** [comment]
> hello @Royal-lobster do you have a solution when you add several line breaks in the `<code>` because there is the `&nbsp;` which appears in the render

Oh thats a edge. I tried to tweak the regex for a while, ended up with this which works 

```ts
  let md = markdownSource;
  md = markdownSource.replace(/```[\s\S]*?```/g, (m) =>
    m.replace(/\n/g, "\n ")
  );
  md = md.replace(/(?<=\n\n)(?![*-])\n/g, "&nbsp;\n ");
  ```
  
Updated the demo too: https://codesandbox.io/s/newline-problem-rh98l5?file=/src/App.js

**Comment by Torsteinws** [comment]
This is fantastic @Royal-lobster, thank you!

I'd just like to add that if you also want to support single line linebreaks, you can try this:
```js
let md = markdownSource;

// Support multiple linebreaks
md = markdownSource.replace(/```[\s\S]*?```/g, (m) =>
  m.replace(/\n/g, "\n ")
);
md = md.replace(/(?<=\n\n)(?![*-])\n/g, "&nbsp;\n ");

// Support single linebreak
md = md.replace(/(\n)/gm, "  \n");
``` 

Someone smarter than me can probably simplify this, I have already accepted this regex magic in my app :)

**Comment by UPSQUARED** [comment]
As you need a char to apply the new line I tried to add an invisible character and it works. So you can use ALT + 0160 which is a Non-breaking-space
Hope this helps for you as well! Good Luck

**Comment by asantos00** [comment]
Btw, the regex expression from @Royal-lobster doesn't work on safari pre 16.6, since it doesn't support look behind

**Comment by RareParsec** [comment]
Here:
``` <textarea
        onChange={(e) => {
          const value = e.target.value;

          const result = value.replace(/\n{2,}/g, (match) => {
            const count = match.length - 1; // 2 newlines = 1 uwu, 3 = 2 uwu, etc.
            return "\n &nbsp; \n".repeat(count);
          });

          setText(result);
        }}
      />```


```          <ReactMarkdown>{text}</ReactMarkdown>
```

**Comment by vadimkantorov** [comment]
I've tried the following
```markdown
\
\
\
# hello
```

but this shows the last backslash:

<img width="1919" height="586" alt="Image" src="https://github.com/user-attachments/assets/b12d5222-143d-477b-a07e-0288d35409b0" />

How can I make represent natively multiple line breaks in Markdown (to control margin) without resorting to explicit `<br>` or `&nbsp;`?

I've tried using https://github.com/remarkjs/remark-breaks, but it seems to have no effect for multiple line breaks / enters

The only workaround I found so far is using code block to force some margin - which is less elegant than pure enters / remark plugin:

````markdown
```




```
# hello

````

Thanks!

**Comment by remcohaszing** [comment]
Use CSS. Line breaks have a semantic meaning. That meaning isn’t margin.

**Comment by vadimkantorov** [comment]
For my usecase, some abusing of semantics is okay, because I'm doing some postprocessing with rehype/CSS anyway. And these markdown documents are for some internal CMS, so I'm adding some custom project-specific conventions (e.g. markdown lists of images end up displayed as image carousels; or separator `---` splits the document into `<div>`s).

Basically I'm looking for a way to generate multiple `<br>`, or to at least preserve multiple line-breaks `\n` in the generated HTML (so that I can use some CSS as you are suggesting)

Is there a way to prevent the backslash from being displayed, or why is it being displayed?

Thanks!
