### ISSUE TITLE
"show more" mark / tag - hidden text

### ISSUE THREAD

**Issue by rootsher** [remarkjs/react-markdown#282]
I would like to achieve the following behavior using the `react-markdown` package: in `source` prop insert a tag `[more]`, which would show the content that is hidden behind it.

For example:

* source (contains `[more]` mark):
```
Lorem ipsum dolor sit amet, [more] consectetur adipiscing elit.
``` 

* result (modifies `[more]` to text `Show more...`, and hides rest of sentence):
```
Lorem ipsum dolor sit amet, Show more...
``` 

By default, the plugin would show only the first part of the sentence, and when you click `Show more...`, it would show the rest of the sentence:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
```

If someone has an idea of how I can have this effect in another way, I would ask for a hint.

**Comment by ChristianMurphy** [comment]
This isn't part of markdown or commonmark, it could be added with a parser plugin.
plugins are unified/remark based, you can find more information here: https://unifiedjs.com/learn
For specific questions on implementation, feel free to reach out at https://spectrum.chat/unified/remark
