### ISSUE TITLE
Add 'data' as valid URI protocol

### ISSUE THREAD

**Issue by fxh1357** [remarkjs/react-markdown#283]
I would like to render anchor tags with [data-URIs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs). Right now links passed via source property will be sanitized by react-markdown/src/uri-transformer.js to match one of the predefined protocols 'http', 'https', 'mailto' or 'tel'. 

Adding 'data' to the collection would allow me to render asynchronously loaded files as links inside of localized markdown.

**Comment by rexxars** [comment]
Sure - would happily accept a pull request for this.

**Comment by juancarlosqr** [comment]
You got a PR for this!

**Comment by MajorSaheb** [comment]
please add other uri too..
sms: 
skype:
whatsapp: 
market:
@rexxars kindly look into it.

**Comment by c7hudson** [comment]
+1 for SMS capabilities.

**Comment by juancarlosqr** [comment]
Hey @rexxars have you looked into this one? Please provide your opinion on adding more protocols as requested, thanks. I can gladly add them

**Comment by ChristianMurphy** [comment]
this will be supported in #428

**Comment by wooorm** [comment]
Not going to happen by default. It introduces serious security issues ([e.g., this](https://snyk.io/vuln/npm:markdown-it:20160912)). And you can already live dangerously with the `transformLinkUri` option.
