### ISSUE TITLE
Cannot use renderer for FontAwesomeIcon

### ISSUE THREAD

**Issue by AlexCppns** [remarkjs/react-markdown#286]
I am trying to inject some icons inside the markdown. So far I managed to insert one with the `html` renderer but it seems like I am limited to one and it breaks all my other html tags (eg anchor tag).

**Comment by rexxars** [comment]
How can I reproduce this? Could you make a repository showcasing the issue? I'm not sure I fully understand what is happening.

**Comment by mDibyo** [comment]
(Might be related to #244)

**Comment by AlexCppns** [comment]
something like:

```
<ReactMarkdown 
       renderers={{ html: BookIcon }}
        linkTarget="_blank"
        source="<html id=\"book-icon\" /> <a href="/test">test</a>" />
```
Everything is a book icon.

**Comment by ChristianMurphy** [comment]
usually this would be done through a remark plugin, for example https://github.com/remarkjs/remark-external-links can add icons to external links.
For more information on remark plugins and working with ASTs see https://unifiedjs.com/learn/
