### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by fcostarodrigo** [remarkjs/react-markdown#289]
I have a big markdown file to parse, and it takes 100% of the CPU to parse it, but in the process my animations become frozen.

If there were calls to setTimeout between calls to `tokenize`, maybe the animation would run smoothly. I know we are using unified to do the parsing and it supports promises.

Is there a way to achieve this or is this out of the scope of the project?

<img width="2032" alt="profile" src="https://user-images.githubusercontent.com/16693844/55479518-29ad4000-5616-11e9-9556-bc33de806551.png">

**Comment by rexxars** [comment]
I think this is more of a question for [remark-parse](https://github.com/remarkjs/remark/tree/master/packages/remark-parse). We're not on the latest version, so things _may_ be more optimal in the updated versions.

Unless `tokenize`/`parse` can be done asynchronously, I'm not sure there is much we can do. Wrapping them in a promise will still have them take up CPU time and block other operations, given they don't somehow yield to the event loop every once in a while.

Perhaps someone has experimented with moving the parsing to a web worker and delivering the AST to the main thread when complete? That would probably help free up paint time, at least.

**Comment by fcostarodrigo** [comment]
Ok, I opened an issue on remark-parse
https://github.com/remarkjs/remark/issues/392

**Comment by ChristianMurphy** [comment]
> Unless `tokenize`/`parse` can be done asynchronously

https://github.com/remarkjs/remark/issues/392#issuecomment-479649462

> Perhaps someone has experimented with moving the parsing to a web worker and delivering the AST to the main thread when complete?

https://github.com/remarkjs/remark/issues/392#issuecomment-479786883

**Comment by ChristianMurphy** [comment]
facebook/create-react-app#3660 provides some interesting thoughts and pointers on using web workers in React with CRA.
For https://codesandbox.io/embed/qvrw2ywwww, since the animation is handled purely through CSS, https://github.com/web-perf/react-worker-dom may be another option.

**Comment by fcostarodrigo** [comment]
Ok, I will try to integrate web workers in ReactMarkdown.

**Comment by 1999** [comment]
@fcostarodrigo just a small reminder that "react-markdown" is universal aka can be used on both server and client.

**Comment by fcostarodrigo** [comment]
> @fcostarodrigo just a small reminder that "react-markdown" is universal aka can be used on both server and client.

True, I made a pull request with a web worker implementation, but I moved it to a separate import to not break server side rendering.

Maybe we should add a fallback to the regular implementation in the web worker version. And I was not able to pass all data to the web worker too.

**Comment by ChristianMurphy** [comment]
Another note remark, the library used for parsing is migrating to a smaller and faster system https://github.com/remarkjs/remark/issues/439 which should improve performance without need of workers.

**Comment by ChristianMurphy** [comment]
https://github.com/remarkjs/react-markdown/pull/476 brought in the new faster parser, it has been released as part of [version 5](https://github.com/remarkjs/react-markdown/blob/main/changelog.md#500---2020-10-19)

**Comment by stevemk14ebr** [comment]
Hi I'm coming from https://github.com/remarkjs/remark/issues/392 where web-worker api was discussed. On my application what i've found is that even though the parsing is relatively fast this blocks the main JS thread at one of the most critical times for updates, during user input into  text field. From the user perspective there appears to be tiny hitches. From what i've read humans can percieve lag over a few tens of milliseconds which appears to be what I'm noticing, not big lag, but tiny hitches.

To fix this I put all my code into a web-worker using https://github.com/GoogleChromeLabs/comlink and https://github.com/GoogleChromeLabs/worker-plugin (I did have to eject from create-react-app sadly). And then I split my Unified.js pipeline into seperate parts, parse and run on the web-worker, then stringify with rehyperreact on the main thread. This lets me just marshal simple text and json across the worker. 

The results are awesome! User input is now lag free and the live-preview looks fast enough to the user that it's really live but there's almost no delay just from a glance. I would absolutely suggest this avenue be pursued further it has bin a significant UX improvement for me.

**Comment by RabbitHols** [comment]
@ stevemk14ebr your solution seems interesting, can you share a working example on codesandbox?

**Comment by RabbitHols** [comment]
> Hi I'm coming from [remarkjs/remark#392](https://github.com/remarkjs/remark/issues/392) where web-worker api was discussed. On my application what i've found is that even though the parsing is relatively fast this blocks the main JS thread at one of the most critical times for updates, during user input into text field. From the user perspective there appears to be tiny hitches. From what i've read humans can percieve lag over a few tens of milliseconds which appears to be what I'm noticing, not big lag, but tiny hitches. (NOTE: I'm rendering lots of nested things so there can be many .parse() passes for me)
> 
> To fix this I put all my code into a web-worker using https://github.com/GoogleChromeLabs/comlink and https://github.com/GoogleChromeLabs/worker-plugin (I did have to eject from create-react-app sadly). And then I split my Unified.js pipeline into seperate parts, parse and run on the web-worker, then stringify with rehyperreact on the main thread. This lets me just marshal simple text and json across the worker.
> 
> The results are awesome! User input is now lag free and the live-preview looks fast enough to the user that it's really live but there's almost no delay just from a glance. I would absolutely suggest this avenue be pursued further it has been a significant UX improvement for me.
> 
> NOTE: I did try react 18s deferred rendering first and unfortunately it did not help much. Although I deferred the text for the live preview all unified parsing still occured on the main thread blocker all other progress for 10s of milliseconds. I think using a web worker to seperate UI from background parsing is the only feasible path for improvement in this way.
> 
> Code: worker.js
> 
> ```
> import { expose } from 'comlink'
> async function RemarkPipeline(disallowedElements, markdown) {
>     const markdownConverter = Remark().use([RemarkParse, ...remarkPlugins, [RehypeUnwrap, { disallowedElements: disallowedElements, unwrapDisallowed: true }]]).freeze();
>     const parsed = markdownConverter.parse(markdown);
>     const transformed = await markdownConverter.run(parsed);
>     return transformed;
> }
> 
> expose(RemarkPipeline);
> ```
> 
> main.js
> 
> ```
> // be sure to create worker once globally
> import * as Comlink from 'comlink';
> const parserWorker = new Worker('./worker.js', { type: 'module' });
> const parser = Comlink.wrap(parserWorker);
> 
> // be sure to memoize this with React.Memo so it only mounts one time then just re-renders
> function MarkdownContent(props) {
>     const editorState = useSelector(selectEditorState);
>     const [transformed, setTransformed] = React.useState(null);
>     const { components, disallowedElements, ...restProps } = props;
> 
>     const stringifier = Remark().use([[RehypeReact, { createElement: React.createElement, Fragment: React.Fragment, components: components }]]).freeze();
> 
>     // this is a very heavy operation
>     React.useEffect(() => {
>         (async () => {
>             const txt = editorStateToText(editorState);
>             const tmp = await parser(disallowedElements, txt);
>             setTransformed(tmp);
>         })();
>     }, [editorState]);
> 
>     // call stringifier now so react elements are only created when needed
>     const htmlmarkdown = transformed ? stringifier.stringify(transformed) : null;
>         return (
>             <span className={'markdown'}>{htmlmarkdown}</span>
>         );
> }
> ```

your solution seems interesting, can you share a working example on codesandbox?

**Comment by stevemk14ebr** [comment]
> your solution seems interesting, can you share a working example on codesandbox or a git repo?

Sorry I cannot. I've shared the relevant code. My solution does not use react-markdown itself. Rather I use the remark parsing libraries in a web worker like I showed and then I use draft-js for user input and render the output of the remark parsing into a div next to it. It works well. Note, that the easiest setup for me was to use `vite` as a bundler which supports webworkers, then I used thread.js for a webworker thread pool.

Slightly updated this looks like:
```
import ParserWorker from './remark/parserWorker?worker';

// NOTE: for dev, you must use chrome. Release works in all browsers.
const parserPool = Pool(() => spawn(new ParserWorker()), 8);

function MainAsyncMarkdownContent(props) {
    const dispatch = useDispatch();
    const { inline, onClick, components, ...restProps } = props;
    const editorState = useSelector(selectEditorState);
    const [transformed, setTransformed] = React.useState(null);

    const stringifier = Remark().use([[RehypeReact, { createElement: React.createElement, Fragment: React.Fragment, components: components }]]).freeze();

    // this is a very heavy operation
    React.useEffect(() => {
        let isMounted = true;
        const txt = editorStateToText(editorState);
        const task = parserPool.queue(parser => parser.parse(txt));
        task.then(result => {
            const { parsed, suggestions } = result;
            if (isMounted) {
                setTransformed(parsed);
                dispatch(setSuggestions(suggestions));
            }
        });
        return () => {
            isMounted = false;
            task.cancel();
        }
    }, [editorState, dispatch]);

    const htmlmarkdown = transformed ? stringifier.stringify(transformed) : null;
    const istable = htmlmarkdown && htmlmarkdown.props && htmlmarkdown.props.children?.length > 0 ? htmlmarkdown.props.children[0].type === "table" : false;

    // it is invalid to put a table inside of a span, inline makes no sense for them
    if (inline && !istable) {
        // Must be an 'inline' element type since its parent is <p> which enforces that: https://www.w3schools.com/html/html_blocks.asp
        return (
            <span className={'markdown'} style={{ display: "inline", fontFamily: "monospace", textDecoration: "none", whiteSpace: "pre-wrap" }} onClick={onClick} {...restProps}>{htmlmarkdown}</span>
        );
    } else {
        return (<span style={{ margin: "0px", textDecoration: "none", whiteSpace: 'pre-wrap' }} className={'markdown'} onClick={onClick}>{htmlmarkdown}</span>);
    }
}
```

**Comment by aFcFzF** [comment]
this my solution in webpack:

```
// resolve document in worker
const decodePath = require.resolve('decode-named-character-reference');
const decodeDir = path.dirname(decodePath); // 提取模块所在目录


config.resolve.alias = {
     'decode-named-character-reference$': path.join(decodeDir, 'index.js'),
}
```
