### ISSUE TITLE
is there any options to set lazy load or pre load for video

### ISSUE THREAD

**Issue by lizziejc** [remarkjs/react-markdown#299]
I'm looking for a solution for plenty videos loading. the node type in 'renderers' doesn't include video. so I have to verify the link type to custom my own video components. or I could add loading js to the video elements after parse. Is there any other better solutions.

**Comment by ChristianMurphy** [comment]
markdown doesn't have a video type.
However it can support embedded HTML, anything supported in HTML https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video can be used.
