### ISSUE TITLE
Split parse & render

### ISSUE THREAD

**Issue by jamiebuilds** [remarkjs/react-markdown#301]
It would be really great if `parse` and `render` (astToReact) were methods as part of this package. Where `parse()` produces an AST that `render()` accepts and produces a fragment from.

This would make it easier to use the underlying AST to do things like pulling out the title or producing a table of contents from headings.

For example, it could be used in a React hook like this:

```js
import React, { useMemo } from "react"
import { parse, render } from "react-markdown"

function useMarkdown(content) {
  return useMemo(() => {
    let ast = parse(content)
    let title = getTitleFromAst(ast)
    let toc = getTocFromAst(ast)
    let fragment = render(ast)
    return { title, toc, fragment }
  }, [content])
}

function MyComponent(props) {
  let { title, toc, fragment } = useMarkdown(props.content)

  return (
    <Page title={title} toc={toc}>
      {fragment}
    </Page>
  )
}

```

**Comment by rexxars** [comment]
I like this idea. Feel free to take a stab at a PR if you want.

**Comment by ChristianMurphy** [comment]
#428 solves this in a way, by leveraging remark-rehype and rehype-react, both of which can be leveraged directly as well.
It also offers a react hook based API.

**Comment by wooorm** [comment]
While the question here, splitting the two, hasn’t been solved, it is now possible to access the AST at several stages. For example, it is now possible to use `remark-toc` to get a ToC *inside* the document, or to write a custom plugin, for example using [`mdast-util-toc`](https://github.com/syntax-tree/mdast-util-toc), to generate a ToC and use it *outside* the document. Hence, I think this can be closed.

**Comment by tobz1000** [comment]
> it is now possible to access the AST at several stages

Is it now possible to access the AST as described in this issue - for both `<ReactMarkdown />`-rendering, and for some other arbitrary usage - without simply parsing the input twice?

**Comment by wooorm** [comment]
It is indeed possible to access the AST. I tried to explain that in my last comment. Could you explain what about my comment is unclear?
See also the [§ Architecture](https://github.com/remarkjs/react-markdown#architecture) section in the readme.

**Comment by tobz1000** [comment]
Apologies if I'm missing something. Do you mean that we can access the AST with a plugin passed into the component? e.g.:

```jsx
<ReactMarkdown remarkPlugins=[pluginWithSideEffects] />
```

As I understand it, this generally isn't a good idea because render functionality doesn't run deterministically and shouldn't have side effects. Or is there another mechanism available?

**Comment by wooorm** [comment]
I don’t see a problem personally here, but if you want to discuss it further I suggest posting a new question, so we can delve into your unique needs.
As my previous comment also linked, see the [§ Architecture](https://github.com/remarkjs/react-markdown#architecture) section in the readme: it is possible to use the underlying tools in a way that’s very close to the original feature request.
