### ISSUE TITLE
htmlParser isValidNode: img tag not work

### ISSUE THREAD

**Issue by 345ml** [remarkjs/react-markdown#308]
I tested with the following simple code:
The use case I want to achieve is simple. allow HTML embedding but block the img tag.
However, strange behavior often occurs.

In the example below, I thought that the image was not displayed under "A".

### Sample code
``` jsx
import React from 'react';
import ReactMarkdown from 'react-markdown';
import htmlParser from 'react-markdown/plugins/html-parser';

const parseHtml = htmlParser({
  isValidNode: node => false,
  // processingInstructions: [/* ... */]
})

const markdown = `
Hello world!

<h1>h1</h1>

## A
<img src="https://camo.githubusercontent.com/343b352623ee1da65fe9a76d25d821ef1e5f3c64/68747470733a2f2f7777772e73616e6974792e696f2f7374617469632f696d616765732f6c6f676f5f7265642e7376673f763d32" />

<img src="https://camo.githubusercontent.com/343b352623ee1da65fe9a76d25d821ef1e5f3c64/68747470733a2f2f7777772e73616e6974792e696f2f7374617469632f696d616765732f6c6f676f5f7265642e7376673f763d32" />

## B
![aaa](https://camo.githubusercontent.com/343b352623ee1da65fe9a76d25d821ef1e5f3c64/68747470733a2f2f7777772e73616e6974792e696f2f7374617469632f696d616765732f6c6f676f5f7265642e7376673f763d32)
`;

function App() {
  return (
    <div>
      <ReactMarkdown
        source={markdown}
        escapeHtml={false}
        plugins={[require('remark-breaks')]}
        astPlugins={[parseHtml]}
      />
    </div>
  );
}

export default App;

```

### Output
<img width="508" alt="スクリーンショット 2019-05-14 21 49 14" src="https://user-images.githubusercontent.com/8254811/57699344-82024380-7692-11e9-91f3-3870b2ba3cff.png">

**Comment by 345ml** [comment]
![aaa](javascript:alert(0);)

**Comment by 345ml** [comment]
Use versions.
```
"react": "^16.8.6",
"react-markdown": "^4.0.8",
"remark-breaks": "^1.0.2"
```

**Comment by fes300** [comment]
Hi everyone,
I think I have the same issue, apparently everything I put in my custom `htmlParser` is being ignored. Anyone can help with this?

**Comment by ChristianMurphy** [comment]
@345ml yes, commonmark needs two newline to create a break, using `remark-breaks` allows changing that behavior.
@fes300 your issue sounds unrelated, could you open a new issue and provide additional context on the issue you are seeing?

**Comment by 345ml** [comment]
@ChristianMurphy 
Thank you!
I'm sorry I left the Issue out.
