### ISSUE TITLE
HTML parser: incompatible w/ React 15

### ISSUE THREAD

**Issue by ujovlado** [remarkjs/react-markdown#313]
Hi, looks like react-markdown is not compatible with React 15, because html-to-react 1.3.4. requires React 16 as peerDependency.

https://github.com/aknuds1/html-to-react/blob/eea2ee18196bb002746bdcb91a8a596e4a8cdd61/package.json#L44

**Comment by ChristianMurphy** [comment]
#428 may resolve this, as it removes the dependency on html-to-react

**Comment by ChristianMurphy** [comment]
With React 16 being stable, and [React 17 around the corner](https://reactjs.org/blog/2020/08/10/react-v17-rc.html), I'm not sure if officially trying to support React <16 makes sense.
Maintaining support for a version of React that is no longer supported by the React team itself, seems outside the scope of this project.

**Comment by wooorm** [comment]
The suggestion here is to upgrade React. React 17 is indeed around the corner, React 16 is in a good place, and React 15 is from 4 years ago.
I am not too happy with the fact that `html-to-react` has this peer dependency, the plan is to change that to a rehype version in the next major, but it’s not something we can change without breaking things.
If you really need to, you could use an older unmaintained version of react-markdown. Or: don’t support dangerous HTML.

**Comment by ujovlado** [comment]
The issue wasn't about support for React 15. It was about "claim" that specific version is compatible with React 15, but it wasn't. 😉 

In the meantime, we upgraded to latest React, so everything works as expected (no warnings, etc.).

Thanks for the great library!
