### ISSUE TITLE
Access text from renderer

### ISSUE THREAD

**Issue by eatoncw** [remarkjs/react-markdown#315]
I'm currently doing the following:
```
...
<ReactMarkdown
  source={client.body}
  renderers={{
     heading: HeadingComponent,
   }}
 />
...
```
```
const HeadingComponent = ({ level, children }) => {
  switch (level) {
    case 1:
      return <h1 className={styles.myh1component}>{children[0].props.value}</h1>
    ...
```

Is `children[0].props.value` the expected way to access the text passed in props to the custom component? I'm not seeing any value without drilling down into the children array.

An example would be super helpful. Thanks!

**Comment by ChristianMurphy** [comment]
Each renderer is passed a syntax tree, you can learn more about syntax trees here https://unifiedjs.com/learn/
and can find utilities to work with syntax trees here: https://github.com/syntax-tree/awesome-syntax-tree
