### ISSUE TITLE
Mis-matched renderers types

### ISSUE THREAD

**Issue by mykter** [remarkjs/react-markdown#327]
I'm having problems with the types of my custom renderers, but I did this sanity check using the default renderers which suggests to me the types are probably inconsistent.

In `index.d.ts` we have:
```ts
export interface ReactMarkdownProps {
    ...
    readonly renderers?: {[nodeType: string]: ReactType}
}
...
interface Renderers {
    [key: string]: string | Renderer<any>
  }
...
export var renderers: Renderers
```

Which leads to a problem when you try and do:
```tsx
<ReactMarkdown source={source} renderers={ReactMarkdown.renderers} />
```
```
Type 'Renderers' is not assignable to type '{ [nodeType: string]: ElementType<any>; }'.
  Index signatures are incompatible.
    Type 'string | Renderer<any>' is not assignable to type 'ElementType<any>'.
      Type 'string' is not assignable to type 'ElementType<any>'.ts(2322)
index.d.ts(82, 14): The expected type comes from property 'renderers' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactMarkdown> & Readonly<ReactMarkdownProps> & Readonly<{ children?: ReactNode; }>'
```

It might be that this pull request fixes it: https://github.com/rexxars/react-markdown/pull/261

**Comment by ChristianMurphy** [comment]
This may also be resolved by #428, which converts the project to native TypeScript.

**Comment by n-lam** [comment]
Since #428 was closed, I was wondering if we could reopen #261 as a temporary solution while waiting for the complete refactor? I'm also happy to open a new PR to make additional changes if needed.

**Comment by ChristianMurphy** [comment]
> Since #428 was closed

https://github.com/remarkjs/react-markdown/pull/428#issuecomment-717633714 the work is still planned, the closing was a quirk of GitHub and branch renaming.

**Comment by wooorm** [comment]
this should be solved by https://github.com/remarkjs/react-markdown/pull/566
