### ISSUE TITLE
Error: Renderer for type `footnoteReference` not defined or is not renderable

### ISSUE THREAD

**Issue by mwaeckerlin** [remarkjs/react-markdown#337]
When I enable footnotes with:
```
                      parserOptions={{
                        footnotes: true
                      }}
```

Then enter `[^1]` into the source, it crashes with:

```
Error: Renderer for type `footnoteReference` not defined or is not renderable
```

**Comment by kingbrendann** [comment]
I just ran into the same issue.

**Comment by Andrewjeska** [comment]
Also having the same issue, are footnotes simply not supported?

**Comment by ChristianMurphy** [comment]
footnotes are supported through a remark plugin https://github.com/remarkjs/remark-footnotes, add the plugin and you should be able to handle footnotes

**Comment by nephlin7** [comment]
@charlex, I added the plugin but I don't get the expected behavior.

Did I miss something?

``` javascript
const ReactMarkdown = require("react-markdown")
const footnotes = require('remark-footnotes')

<ReactMarkdown
      plugins={[[footnotes, { inlineNotes: true }]]}
      source={source}
      escapeHtml={false}
    />
```

Result:

<img width="456" alt="Captura de Pantalla 2020-10-19 a la(s) 12 00 27 a  m" src="https://user-images.githubusercontent.com/22168189/96407211-1f25ad80-119e-11eb-8711-ce20466fc694.png">

**Comment by wooorm** [comment]
@nephlin7 https://github.com/remarkjs/react-markdown/issues/470

**Comment by laem** [comment]
Hi, 
I'm getting the same error as above.

`Renderer for type `footnoteReference` not defined or is not renderable`

Using `react-markdown` version 5.0.3 and `remark-footnotes` version 3.0.0.

With this code : 

```
<ReactMarkdown children={'My markdown'} plugins={[remarkFootnotes]} />
```

**Comment by ChristianMurphy** [comment]
@laem this issue is specific to remark 12, what you're seeing appears to be with remark 13, and as such should probably be it's own question, react-markdown as a forum for asking questions here: https://github.com/remarkjs/remark/discussions

**Comment by laem** [comment]
Thanks, this one seems to handle the issue : https://github.com/remarkjs/remark/discussions/554
