### ISSUE TITLE
Adjacent bold and italic text are parsed incorrectly

### ISSUE THREAD

**Issue by chenxinyanc** [remarkjs/react-markdown#338]
From nteract/nteract#4562

I'm not sure whether it's a bug or fault with configuration, but the following markdown source
```markdown
**bold***italic*
```
is rendered incorrectly as
> **bold**<wbr />*italic\*

rather than
> **bold***italic*

![image](https://user-images.githubusercontent.com/50703224/64668610-cd85fc00-d490-11e9-8909-19c09c18d6f5.png)

**Comment by ChristianMurphy** [comment]
This is part of https://github.com/remarkjs/remark/issues/306 and will be resolved by https://github.com/remarkjs/remark/issues/439.
This isn't a bug in react-markdown itself.
