### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by ericsoco** [remarkjs/react-markdown#339]
I recently updated my app to `4.2.2` (from an old, `2.x` version) and am seeing an NPE on `process` when attempting to render a `<ReactMarkdown>`.

It appears that ReactMarkdown [calls `unified.parse()`](https://github.com/rexxars/react-markdown/blob/master/src/react-markdown.js#L32), which in turn instantiates a `VFile`, which accesses `process`, but `process` is not available in a browser.

It is easy enough to reproduce (for me) that I'm surprised others haven't reported it, so I'm guessing there's something unique in my setup that is triggering this. Still debugging, but am I correct to assume that this codepath shouldn't be running in the browser?

Will add more information as I dig it up.

**Comment by ericsoco** [comment]
It turns out that `process` is [mocked by default by Webpack](https://webpack.js.org/configuration/node/#nodeprocess). Browserify [does something similar](https://github.com/browserify/insert-module-globals).

The bug here is really with unified/vfile, so I've also filed it there:
https://github.com/vfile/vfile/issues/38

but note that this issue renders `react-markdown` effectively unusable in environments that don't mock/polyfill `process`.

**Comment by Colkadome** [comment]
I have a similar issue. Requiring unified/vfile is a bit tricky here, as they both use node.js functions so things like `process` need to be explicitly shimmed in for some build tools. If this project is to be browser compatible, you could fork unified/vfile and replace the node.js-dependant functions (like `is-plain-obj`, `path.dirname`) with custom ones (there aren't many of them).

**Comment by AmirTugi** [comment]
Having the same results :(
Can't use this lib because of this.
Bummer

**Comment by flybayer** [comment]
The solution is to set this in your webpack config:

```js
webpackConfig.node.process = true;
```

**Comment by shengliangli** [comment]
webpack v5,same thing happend.

**Comment by Falci** [comment]
Workaround:
```javascript
window.process = { cwd: () => '' };
```

**Comment by greybax** [comment]
@Falci where to put this code?

**Comment by Falci** [comment]
@greybax I'm using like this: 

```jsx
import React from 'react';
import ReactMarkdown from 'react-markdown/with-html';

window.process = { cwd: () => '' };

const MyComponent = ({data}) => (
    <LayoutWrapper>
        <ReactMarkdown source={data} escapeHtml={false} />
    </LayoutWrapper>
)
```

**Comment by govizlora** [comment]
A temporary solution for me: https://github.com/vfile/vfile/issues/38#issuecomment-683198538

**Comment by ChristianMurphy** [comment]
This is in vfile, not in react-markdown itself.
See the suggestion @govizlora linked

**Comment by zjjjjjjjjjjd** [comment]
```
module.exports = {
  module: {
    rules: [
      {
        test: /node_modules(\/|\\)vfile(\/|\\)core\.js/,
        use: [{
          loader: 'imports-loader',
          options: {
            type: 'commonjs',
            imports: ['single process/browser process'],
          },
        }],
      },
    ],
  },
};
```

**Comment by guguji5** [comment]
if you use vite, add variable in vite.config.js to fix it
```
define: {
    'process.env': {},
  },
```
