### ISSUE TITLE
Default node rendering

### ISSUE THREAD

**Issue by michelhelms-tdg** [remarkjs/react-markdown#342]
Hi!

I just wrote a plugin for a tab element and the whole process was really easy and straightforward. What a blessing, am really happy!

That "tabs" plugin replaces existing nodes in the AST with a node of type "tabswitch" that has the replaced nodes as children. My plugin tries to default-render those "normal" nodes, and it works.

But I feel like this is not the "proper" way to do it, as probably configuration to renderers is not passed. Can anyone confirm/correct how to properly default-render nodes please?

```js
function renderDefault(node) {
	const renderer = ReactMarkdown.renderers[node.type]
	if (typeof node.type === 'function') {
		return node.type(node.props)
	} else if (typeof renderer === 'string') {
		return React.createElement(renderer, node.value)
	} else {
		return renderer(node)
	}
}
```

**Comment by ChristianMurphy** [comment]
I'm not quite following what you are asking @michelhelms-tdg...
For transforming content, I'd generally recommend working with the AST directly using remark plugins.
You can find more information on this at https://unifiedjs.com/learn/

**Comment by wooorm** [comment]
@michelhelms-tdg Please open a discussion if you still need an answer to your question
