### ISSUE TITLE
[feature request] Audio / video html tag rendering with native markdown

### ISSUE THREAD

**Issue by vadimkantorov** [remarkjs/react-markdown#343]
E.g. even `![](asd.wav)` / `![](asd.mp3)` -> `<audio src="asd.wav" />` would be super-useful.

**Comment by francisrod01** [comment]
It doesn't belong to the "native" markdown.
I'm going to work on something related to it this month (but not on video tag). :+1:

**Comment by francisrod01** [comment]
Well, as I tested, Markdown has a native way to show a thumb to your video link:

```md
[![The Waffle Ninja](https://img.youtube.com/vi/StTqXEQ2l-Y/0.jpg "This is my Youtube video")](https://www.youtube.com/watch?v=aeiou)
```

It will generate the preview:

[![The Waffle Ninja](https://img.youtube.com/vi/StTqXEQ2l-Y/0.jpg "This is my Youtube video")](https://www.youtube.com/watch?v=aoeiu)

You can read more here: https://stackoverflow.com/a/29862668/3332734

**Comment by vadimkantorov** [comment]
I'm actually more concerned about embedding HTML5-audio player that can work on the page without having to navigate away to youtube.

**Comment by SalahAdDin** [comment]
@francisrod01 It is good for common providers, but what if we want to render the video inside of content? For instance, using _React Player_, we can get, as @vadimkantorov, video from the _markdown_ and rendering it with custom components.
Is there any way to get a video from its file extension as Gitlab does?

**Comment by francisrod01** [comment]
I see. You're right!!
I look forward to see that here but I'll think in something related to it also.

**Comment by SalahAdDin** [comment]
How is this going on guys?

**Comment by ChristianMurphy** [comment]
> It doesn't belong to the "native" markdown.

Correct, this is not native markdown,
however it can be supported through a remark plugin.
You can find more information on creating plugins see https://unifiedjs.com/learn/

**Comment by SalahAdDin** [comment]
@ChristianMurphy `retext` or `remark` plugin?

**Comment by ChristianMurphy** [comment]
a [remark](https://github.com/remarkjs/remark) plugin.

---
[retext](https://github.com/retextjs/retext) is another unified project, specifically for [NLP](https://en.wikipedia.org/wiki/Natural_language_processing) applications.
Both [remark](https://github.com/remarkjs/remark) and [retext](https://github.com/retextjs/retext) (as well as [rehype](https://github.com/rehypejs/rehype) and [redot](https://github.com/redotjs/redot)) build off [unist](https://github.com/syntax-tree/unist), but are designed for different languages/goals.

**Comment by SalahAdDin** [comment]
Is anyone working on this?

**Comment by wooorm** [comment]
working on what?

**Comment by SalahAdDin** [comment]
@wooorm a plugin for videos.

**Comment by wooorm** [comment]
You can search online, such as here on GitHub, or on npm, for remark + video and it seems there are some plugins yeah. But I haven’t tried them.

I think it’s a bad idea to add a custom syntax for things to markdown though. It means it won’t render as such here on GitHub, or on any other platform. My suggestions is: use an image, with a link.
