### ISSUE TITLE
Rendering error: <tr> cannot appear as a child of <table>

### ISSUE THREAD

**Issue by olipo186** [remarkjs/react-markdown#344]
Hi,

I'm receiving an error using react-markdown 4.2.2 while trying to render the following markdown:

```
Hello world

| a | b |
|---|---|
| c | d |
```

It looks like the library forgets to insert the `<thead>` and `<tbody>` tags properly, resulting in the following error in the console:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/1056476/65524432-12c51780-deee-11e9-8dd6-3e970b4fd25e.png">

Is this a know problem?

**Comment by ChristianMurphy** [comment]
@olipo186 try running 4.3.1 on the demo https://rexxars.github.io/react-markdown  the table markdown you shared has a `<tbody>`
