### ISSUE TITLE
Double nested blockquotes

### ISSUE THREAD

**Issue by martin3walker** [remarkjs/react-markdown#351]
On our company blog it seems that blockquotes are rendering in as a blockquote wrapped in a blockquote (see picture). Anyone have an idea why that is happening?

<img width="400" alt="Screen Shot 2019-10-07 at 6 09 39 PM" src="https://user-images.githubusercontent.com/35141192/66329018-039e8a80-e92e-11e9-8e6e-9684e5144824.png">

**Comment by ChristianMurphy** [comment]
@martin3walker could you share the markdown that causes this?
Trying

```markdown
> blockquote
```

on the demo site appears to render as expected https://rexxars.github.io/react-markdown/
