### ISSUE TITLE
auto render link err

### ISSUE THREAD

**Issue by viewerw** [remarkjs/react-markdown#353]
code:

```
const md = "request('https://google.com')";

render(
  <ReactMarkdown 
    source={md}
/>, document.getElementById('root'));
```

render result:

<a>https://google.com%27</a>

expect:
<a>https://google.com</a>

**Comment by ChristianMurphy** [comment]
@viewerw try upgrading to the latest version of react-markdown, trying your example in the demo https://rexxars.github.io/react-markdown this doesn't appear to be an issue.
