### ISSUE TITLE
Should Markdown headings become anchor links?

### ISSUE THREAD

**Issue by ch2ch3** [remarkjs/react-markdown#358]
Question on functionality, potentially related to #319.

The table of contents in the demo suggests that I should be able to click on one of the items to navigate directly to that section, but that doesn't work. The expected behaviour is similar to how GitHub handles headings so that I can link to a specific section in e.g. this project's README https://github.com/rexxars/react-markdown#upgrading-to-40.

However from the documentation and test cases it doesn't seem like this is a supported feature. Would you be able to clarify? If it's not supported, it might be clearer to remove that from the demo.

**Comment by PsychoXIVI** [comment]
Still not resolved? :/

**Comment by bel0v** [comment]
if you look into [remark-toc documentation](https://github.com/remarkjs/remark-toc) you'll see it also requires `remark-slug` to turn headers into anchors. 

`remark-slug` didn't work with `react-markdown` for me. It'd be also cool to use some other plugins like [remark-autolink-headings ](https://github.com/remarkjs/remark-autolink-headings), but they are not supported either, it seems :(

**Comment by dreamer01** [comment]
Hey any update on above issue, also did any one was able to find a plugin or work around to convert heading to internal # links.

**Comment by timofeysie** [comment]
I usually use the following:
```
- [Title Id](#title-id)
...
## Title Id
```

This will create a list of sections and link to them (at least on GitHub README files).  Is that the behaviour that this issue is regarding?

**Comment by xQsme** [comment]
This [issue](https://github.com/rexxars/react-markdown/issues/404) has a solution.

**Comment by eegli** [comment]
If anyone still has this problem and just wants **simple, clean anchor links for headings**, here's a type-safe custom headings renderer with auto-generated anchors based on the actual heading values.

```tsx
type HeadingResolverProps = {
  level: number;
  children: JSX.Element[];
};

const Headings: React.FC<HeadingResolverProps> = ({ level, children }) => {
  // Access actual (string) value of heading
  const heading = children[0].props.value;

  // If we have a heading, make it lower case
  let anchor = typeof heading === 'string' ? heading.toLowerCase() : '';

  // Clean anchor (replace special characters whitespaces).
  // Alternatively, use encodeURIComponent() if you don't care about
  // pretty anchor links
  anchor = anchor.replace(/[^a-zA-Z0-9 ]/g, '');
  anchor = anchor.replace(/ /g, '-');

  // Utility
  const container = (children: React.ReactNode): JSX.Element => (
    <a id={anchor} href={`#${anchor}`}>
      <span>{children}</span>
    </a>
  );

  switch (level) {
    case 1:
      return <h1>{container(children)}</h1>;
    case 2:
      return <h2>{container(children)}</h2>;
    case 3:
      return <h3>{container(children)}</h3>;

    default:
      return <h6>{container(children)}</h6>;
  }
};

export default Headings;
```

And then just pass your custom renderer like so:
```tsx
renderers={{
  heading: Headings,
}}
```

**Comment by Brenndoerfer** [comment]
With components (not renderers) I had to call h1, h2, h3.. etc individually 


```

**Comment by yinleiCoder** [comment]
> if you look into [remark-toc documentation](https://github.com/remarkjs/remark-toc) you'll see it also requires `remark-slug` to turn headers into anchors.
> 
> `remark-slug` didn't work with `react-markdown` for me. It'd be also cool to use some other plugins like [remark-autolink-headings ](https://github.com/remarkjs/remark-autolink-headings), but they are not supported either, it seems :( `remark-slug` 对我不起作用 `react-markdown` 。使用其他一些插件也很酷，例如 remark-autolink-headings ，但它们也不受支持，似乎:(



> if you look into [remark-toc documentation](https://github.com/remarkjs/remark-toc) you'll see it also requires `remark-slug` to turn headers into anchors.
> 
> `remark-slug` didn't work with `react-markdown` for me. It'd be also cool to use some other plugins like [remark-autolink-headings ](https://github.com/remarkjs/remark-autolink-headings), but they are not supported either, it seems :(

hi! there is already a good solution : rehypeSlug.

here is my code:
```typescript
import rehypeSlug from 'rehype-slug'
 <ReactMarkdown
      remarkPlugins={[
        [remarkGfm],
        [remarkToc, { tight: true, maxDepth: 5, ordered: true, prefix: '' }],
      ]}
      rehypePlugins={[rehypeSlug]}
      components={{
        code(props) {
          const { children, className, node, ...rest } = props
          const match = /language-(\w+)/.exec(className || '')
          return (
            <SyntaxHighlighter
              PreTag="div"
              language={match ? match[1] : ''}
              customStyle={{ padding: 0 }}
              style={atomDark}
              showLineNumbers
              showInlineLineNumbers
            >
              {String(children).replace(/\n$/, '')}
            </SyntaxHighlighter>
          )
        },
      }}
      {...props}
    >
      {children}
    </ReactMarkdown>
```
