### ISSUE TITLE
Incompatible with IE11

### ISSUE THREAD

**Issue by martpie** [remarkjs/react-markdown#359]
This is a side effect of `unified`'s sub-dependency `is-plain-obj` and `react-markdown` is not directly responsible for this issue.

`is-plain-obj@2.0.0` use fat arrows notation which are not compatible with IE11. `is-plain-obj` maintainer said [he would not make it browser-compatible](https://github.com/sindresorhus/is-plain-obj/issues/6).

There are a few solutions to this issue right now:

- tell Webpack to transpile this module during build time (for example for Next.js with `next-transpile-modules`)
- ensure `is-plain-obj` is not updated to `2.0.0` (via Yarn resolutions or similar)
- something is done at `react-markdown`'s level.

Any thoughts on how to address this issue?

**Comment by gwillz** [comment]
I think it's just a reality that more and more packages are not (immediately) compatible with IE11 and you have to go through the effort of transpiling it yourself.

It's a similar situation with a lot of d3 packages.

You've highlighted very practical solutions already, as well as the `is-plain-obj` maintainer. It's certainly not something I think react-markdown is responsible for.

It's an annoying problem but I don't mind it much. The more hostile things become for IE - the sooner it might just disappear.
