### ISSUE TITLE
Header broke images

### ISSUE THREAD

**Issue by IrenKomar** [remarkjs/react-markdown#360]
I try to make a document and set header in the top and image then, like that:
# Header

some text
![Photo](http://www.somelink.com/image.jpg)

And insteat of picture I get text '![Photo](http://www.somelink.com/image.jpg)'
http://prntscr.com/ptq4jq

But when I delete header and set it like similar text, image works

**Comment by ChristianMurphy** [comment]
@IrenKomar could you share the markdown you tried and the version of react-markdown you are using?
