### ISSUE TITLE
Text appends to last item of list

### ISSUE THREAD

**Issue by IrenKomar** [remarkjs/react-markdown#361]
I try to make a list and a text after it? but all text after list appends to last <li> tag and become a part of this list
![Screenshot_3](https://user-images.githubusercontent.com/33083924/68390848-d5031200-016e-11ea-87a7-164c0aa757a0.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/33083924/68390849-d5031200-016e-11ea-91c3-fd0467ece6c3.jpg)

**Comment by pflenker** [comment]
You can work around this by passing `parserOptions={{ commonmark: true }}` to ReactMarkdown.
