### ISSUE TITLE
Can't get shortcodes to work...

### ISSUE THREAD

**Issue by KevBelisle** [remarkjs/react-markdown#363]
I saw issue #113, but even the code given in the comments doesn't work for me - and unlike the person who opened that issue, I'm not trying to have opening and closing shortcode tags, I just want to have shortcodes for custom icons.

Here's a codesandbox with the code from issue 113: https://codesandbox.io/s/cocky-jang-dw6si?fontsize=14

Thanks for any help!

**Comment by phanatuan** [comment]
I also cannot get `shortcode` to work. Don't know if this package is still actively maintained ..

**Comment by VincentCtr** [comment]
Hi @phanatuan , did you manage to make it work ? Same issue here.

**Comment by phanatuan** [comment]
Hey Vincent, 

Yes I manage to make it work. The missing piece is `inlineMode: true` option. 

Without it, this will not work. ```markdownContent = `hello {{ Button color="red" }}` will not work. 

```javascript
<ReactMarkdown
	className={className}
	source={markdownContent}
	plugins={[
	      [shortcodes, { startBlock: '{{', endBlock: '}}', inlineMode: true }],
	]}
        renderers={{ shortcode: ShortcodeRenderer }}
/>
```

```javascript
const ShortcodeRenderer = ({ identifier, attributes }) => {
		
		return <div>{JSON.stringify({identifier, attributes})</div>
	}
```

**Comment by VincentCtr** [comment]
Thank you Phanatuan,

For information my source string is html. I managed to make it work by inserting breakline before my shortcodes like this : 


``` javascript
const source = "<h2>test</h2> [myShortCode]";

const testDescriptionWithBreakLines = source?.split('[').join('\n\n[');

<ReactMarkdown
	source={testDescriptionWithBreakLines}
	plugins={[
	      [shortcodes, { startBlock: '{{', endBlock: '}}' }],
	]}
        renderers={{ shortcode: ShortcodeRenderer }}
        escapeHtml={false}
/>

```

It looks to be a bug with react markdown.

**Comment by phanatuan** [comment]
Nice, glad it works! 

Happy coding : )
