### ISSUE TITLE
<p> added to list, checkbox not rendered like in GFM

### ISSUE THREAD

**Issue by max-favilli** [remarkjs/react-markdown#367]
> Fixed in v3.1.0, thanks for bringing this to my attention!
> 
> _Originally posted by @rexxars in https://github.com/rexxars/react-markdown/issues/110#issuecomment-348280810_
> 

I am using 4.2.2 but doesn't seems fixed, to-do are not rendered in _github style_ and a weird `<p>` is added to the last item:

![image](https://user-images.githubusercontent.com/1472899/69017532-09b16d80-09a8-11ea-9352-8c28a42b7bec.png)

If I inspect the generated html is also weird, adding a `<p>` to the last element:
![image](https://user-images.githubusercontent.com/1472899/69017548-1afa7a00-09a8-11ea-87db-e63f47c7b8e0.png)

Unless an empty line is added after the list like this:
![image](https://user-images.githubusercontent.com/1472899/69017588-539a5380-09a8-11ea-95b0-8564c27548bb.png)

Which prevent the `<p>` from being inserted:
![image](https://user-images.githubusercontent.com/1472899/69017606-6ad94100-09a8-11ea-93b7-6010bf41cfe6.png)

Source:
![image](https://user-images.githubusercontent.com/1472899/69017625-86444c00-09a8-11ea-9fd4-83e5b03c9636.png)

**Comment by zwhitchcox** [comment]
Was having same problem. Workaround:

```css
ul p {
  display: inline;
}
```

**Comment by ChristianMurphy** [comment]
@max-favilli trying
```markdown
- [x] one
- [x] two
- [ ] three

hello
```
on https://remarkjs.github.io/react-markdown/
this renders as expected.
as @zwhitchcox mentions this is most likely an issue with a stylesheet not the library.
