### ISSUE TITLE
I want to be able to specify target per link inline in markdown

### ISSUE THREAD

**Issue by IgorSzyporyn** [remarkjs/react-markdown#370]
Having a one for all link handler like linkTarget function seems like... not enough.

I want to be able to handle the target per link - inline in the markdown.

This will require a change in the syntax, or rather an addition - so far I have gotten around this in a link renderer, but thought I might share this syntax I came up with - and suggest it gets added directly to react-markdown.

Syntax proposal is as follows
```
[Here my link](http://www.google.com|_self "Here a title")
```

**Comment by IgorSzyporyn** [comment]
Tried to make a new branch with fix and push - but ran into problems

Code is not pretty, so do with that as you please - some lint rules forced me out into this

In the file "src/ast-to-react.js" add the following to line 73
```
  // Clean up url and target from url target syntax in case of link
  // [Here link](http://www.google.com|_blank "here title")
  let { url, target } = node

  if (node.type === 'link') {
    const hrefSplit = url.split('|')

    if (hrefSplit[1]) {
      target = hrefSplit[1]
      url = hrefSplit[0]
    } else {
      target = typeof opts.linkTarget === 'function'
      ? opts.linkTarget(node.url, node.children, node.title)
      : opts.linkTarget
    }
  }
```

And then in the switch go to case "link" (line 109) and swap this...

```
    case 'link':
      assignDefined(props, {
        title: node.title || undefined,
        target:
          typeof opts.linkTarget === 'function'
            ? opts.linkTarget(node.url, node.children, node.title)
            : opts.linkTarget,
        href: opts.transformLinkUri
          ? opts.transformLinkUri(node.url, node.children, node.title)
          : node.url
      })
      break
```

With this....

```
    case 'link':
      assignDefined(props, {
        title: node.title || undefined,
        target: target,
        href: opts.transformLinkUri
          ? opts.transformLinkUri(url, node.children, node.title)
          : url
      })
      break
```

**Comment by bj00rn** [comment]
could be fixed by implementing https://github.com/rexxars/react-markdown/issues/384?

**Comment by ChristianMurphy** [comment]
a few options, may people find https://github.com/remarkjs/remark-external-links meets their needs, it may meet yours as well.
If you want something more custom, creating a remark plugin is usually the way to go to add new functionality that is not a part of commonmark.
You can find more on creating a remark plugin and working with ASTs at https://unifiedjs.com/learn/

**Comment by vidyashv-carbon** [comment]
We also had similar requirement of opening some links in same tab and some in new tab. using https://github.com/remarkjs/remark-external-links  plug in did resolve the issue.

You have to use this plug in and do not pass linkTarget props
