### ISSUE TITLE
Emphasis with extra whitespace inside is parsed when it should not be

### ISSUE THREAD

**Issue by mariechatfield** [remarkjs/react-markdown#371]
According to the [GitHub Flavored Markdown Spec](https://github.github.com/gfm/#emphasis-and-strong-emphasis), emphasis and strong emphasis should only be parsed when opened by a left-flanking delimiter run and closed by a right-flanking delimiter run, where:

- a left-flanking delimiter run is `not followed by Unicode whitespace` 
- a right-flanking delimiter run is `not preceded by Unicode whitespace`

In [Example 361](https://github.github.com/gfm/#example-361), they show that `a * foo bar*` should _not_ be parsed as emphasis since there is white-space between the opening asterisk and the text.

react-markdown is incorrectly parsing emphasis and strong emphasis with white space before and after the text.

### react-markdown
```
| Sample                   | Should it parse? | Correct Behavior? |
|--------------------------|------------------|-------------------|
| __bold__                 | yes              | ✅                |
| __ starting space bold__ | no               | ❌                |
| __ending space bold __   | no               | ❌                |
| _italic_                 | yes              | ✅                |
| _ starting space italic_ | no               | ❌                |
| _ending space italic _   | no               | ❌                |
```

<img width="1543" alt="Screen Shot 2019-12-02 at 11 09 18 AM" src="https://user-images.githubusercontent.com/4974085/69979592-37dc9480-14f4-11ea-97e7-44e1150daf06.png">

### GitHub
```
| Sample                   | Should it parse? | Correct Behavior? |
|--------------------------|------------------|-------------------|
| __bold__                 | yes              | ✅                |
| __ starting space bold__ | no               | ✅                |
| __ending space bold __   | no               | ✅                |
| _italic_                 | yes              | ✅                |
| _ starting space italic_ | no               | ✅                |
| _ending space italic _   | no               | ✅                |
```
<img width="515" alt="Screen Shot 2019-12-02 at 11 08 22 AM" src="https://user-images.githubusercontent.com/4974085/69980410-d0274900-14f5-11ea-977c-b97c5a825a47.png">

### Workaround

It looks like setting `parserOptions.pedantic` prevents this behavior:

```jsx
<ReactMarkdown parserOptions={{ pedantic: true }} />
```

But I'm fairly certain that React Markdown is meant to support GFM out of the box, so I _think_ this is still a bug.

**Comment by ChristianMurphy** [comment]
this is an upstream issue being tracked at https://github.com/remarkjs/remark/issues/306 and will be resolved by https://github.com/remarkjs/remark/issues/439
