### ISSUE TITLE
Does react-markdown sanitize the markdown?

### ISSUE THREAD

**Issue by joanned** [remarkjs/react-markdown#373]

**Comment by studyhog** [comment]
I think `escapeHtml` is what you're looking for:
https://github.com/rexxars/react-markdown#options

Also, `transformLinkUri` seems to be the default transformer 
> * transformLinkUri - function|null Function that gets called for each encountered link with a single argument - uri. The returned value is used in place of the original. The default link URI transformer acts as an XSS-filter, neutralizing things like javascript:, vbscript: and file: protocols. If you specify a custom function, this default filter won't be called, but you can access it as require('react-markdown').uriTransformer. If you want to disable the default transformer, pass null to this option.
