### ISSUE TITLE
lifecycle related event

### ISSUE THREAD

**Issue by cheungseol** [remarkjs/react-markdown#375]
is there any way to hook into the rendering-finished event of this library.

eg. i want to visit related dom element after rendering markdown text to html

**Comment by ChristianMurphy** [comment]
I'm not sure this could/should be provided by the library, react handles the actual render.
See https://stackoverflow.com/questions/44798159/react-how-can-we-know-that-all-component-has-been-mounted-rendered-after-setsta for a solution
