### ISSUE TITLE
iframe and open link in new tab

### ISSUE THREAD

**Issue by bsde1234** [remarkjs/react-markdown#379]
I have a project in which react-markdownv2.4.2 is using. Can I use iframe, and open link in new tab feature in input textarea field. What is the procedure/code for that?

**Comment by davalapar** [comment]
on new tab, in readme look for `linkTarget` in options

**Comment by ChristianMurphy** [comment]
> Can I use iframe

yes https://github.com/remarkjs/react-markdown/issues/419

> open link in new tab feature

yes, see `linkTarget` https://github.com/remarkjs/react-markdown#options

> input textarea field

I'm not sure what you are asking, `textarea` isn't a link or an iframe, so it wouldn't do link or iframe behaviors.
