### ISSUE TITLE
Not able to pass id's to heading tag 

### ISSUE THREAD

**Issue by mayankbytes** [remarkjs/react-markdown#380]
**"### My Great Heading {#custom-id} "**

should be converted to following according Markdown document

**"&lt; h3 id="custom-id"&gt;'My Great Heading &lt;/h3 &gt;"**

but using react-markdown, it is getting converted to 
**"&lt; h3 &gt; My Great Heading {#custom-id}&lt;/h3 &gt;"**

**Comment by mayankbytes** [comment]
@rexxars - Do we have any way by which I could achieve this?

**Comment by bj00rn** [comment]
https://github.com/rexxars/react-markdown/issues/384

**Comment by viktor-yakubiv** [comment]
I found:
- [`getCoreProps`](https://github.com/rexxars/react-markdown/blob/master/src/renderers.js#L66) does not pass additional props but only extracts a source position
- _Heading_ renderer does not pass additional props neither

As a solution I would either split props or pass the rest to renderer.

**Comment by ChristianMurphy** [comment]
This is not a feature of markdown, and as such would not be supported in core.
However it can be added through a remark plugin by adding https://github.com/imcuttle/remark-heading-id
