### ISSUE TITLE
Feature Request: Support for MDX files

### ISSUE THREAD

**Issue by aaron-origin** [remarkjs/react-markdown#381]
Support for MDX files would be amazing for this very useful and stable package.

https://mdxjs.com/

**Comment by ChristianMurphy** [comment]
@aaron-origin this already exists https://mdxjs.com/advanced/runtime

**Comment by melvin2016** [comment]
Support for MDX files would be helpful.

**Comment by wooorm** [comment]
Support for MDX is called MDX ;)
