### ISSUE TITLE
Bold italics adjacent to italics parsed incorrectly

### ISSUE THREAD

**Issue by PaulKleinschmidt** [remarkjs/react-markdown#383]
This may be an issue with my configuration. See the following example:

`***bold-italic** italic*`

should render as:

>_**bold-italic**_ _italic_

but instead it renders as:

>\***bold-italic** italic\*

<img width="822" alt="Screen Shot 2020-01-21 at 9 50 36 AM" src="https://user-images.githubusercontent.com/32469657/72829380-84f70000-3c33-11ea-9037-11c0ee4889f6.png">

**Comment by al222** [comment]
This seems like a fringe case, I don't know if it **should** work like you want, but a workaround (maybe obvious, sorry if you already thought of that) would be :

`***bold-italic*** *italic*`

> ***bold-italic*** *italic*

Bold inside italic, not at the begining works fine :

`*text italic with **bold** inside*`

> *text italic with **bold** inside*

Note : the same problem exists if the bold part is at the end.

**Comment by ChristianMurphy** [comment]
@PaulKleinschmidt This is likely a bug in the underlying parser, `remark-parse` could you report this upstream at https://github.com/remarkjs/remark/issues ?

**Comment by hypirion** [comment]
As mentioned in remarkjs/remark#504, this was resolved in the recently released version of remark-parse, `"9.0.0"`. I hope it may not be too much effort to piggyback this bump onto #428, or perhaps in a PR after that one is merged.

**Comment by wooorm** [comment]
This is solved on the v5 branch which will be released soon

**Comment by wooorm** [comment]
Fixed in 5.0.0!
