### ISSUE TITLE
Soft-hyphens not parsing correctly

### ISSUE THREAD

**Issue by jdahdah** [remarkjs/react-markdown#390]
I have the issue that soft hyphens (`&shy;`) are being parsed incorrectly when the content is passed in as a string, e.g. it's not being displayed.

It doesn't matter if it's via the `children` prop or as a `{"child"}`. It works fine when the child is a text node, but this doesn't work for dynamic content, e.g. content coming from an API. To demonstrate that it's specific to `&shy;` and not generally an html-entity issue, I have included `&reg;`, which works fine in either case.

### This example displays a soft hyphen after the word "Reaaaaaally"

```
<ReactMarkdown>
  ThisIsAReaaaaaally&shy;Looooooong&reg;Word
</ReactMarkdown>
```

**Result:**
ThisIsAReaaaaaally-
Looooooong®Word

### These ones don't:

```
<ReactMarkdown>
  {"ThisIsAReaaaaaally&shy;Looooooong&reg;Word"}
</ReactMarkdown>
```
```
<ReactMarkdown
  children={"ThisIsAReaaaaaally&shy;Looooooong&reg;Word"}
/>
```

**Result:**
ThisIsAReaaaaaally
Looooooong®Word

---

You can see a live example on CodeSandbox with some basic styles to make it easier to test:

[![Edit reverent-chatterjee-6md6f](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reverent-chatterjee-6md6f?fontsize=14&hidenavigation=1&theme=dark)

---

Chrome DevTools give me this:

<img width="163" alt="softhyphen_chrome_devtools" src="https://user-images.githubusercontent.com/5282190/75043215-fb4f8200-54bf-11ea-9292-e89ac26fe7e1.png">

When rendered out in a Gatsby build, this is the resulting source:

```
<p>ThisIsAReaaaaaally<!-- -->­<!-- -->Looooooong<!-- -->®<!-- -->Word</p>
```

**Comment by ChristianMurphy** [comment]
@jdahdah I'm not able to reproduce the error with the examples you provided.
here's a screenshot from the sandbox

![Screenshot_2020-10-08 React App(1)](https://user-images.githubusercontent.com/3107513/95509440-5f4c8b00-0969-11eb-93e2-735b2a08b8b1.png)

they render the same.

A few possible reasons you may be seeing it.
1. https://shripadk.github.io/react/docs/jsx-gotchas.html#html-entities
2. an issue in Gatsby
