### ISSUE TITLE
Everything is rerendered on change

### ISSUE THREAD

**Issue by FerusAndBeyond** [remarkjs/react-markdown#393]
This makes it unusable for live editing, will this be changed at any point?

**Comment by beamercola** [comment]
having this problem too - images reload constantly.  Anybody have any workarounds for this?

**Comment by zolon4** [comment]
+1 to say i'm having the same issue

**Comment by ChristianMurphy** [comment]
For live editing, you do want it to rerender on change. :wink: 

I suspect what you mean is you want non-blocking rendering and potentially input debouncing. :slightly_smiling_face: 
#428 would make this easier, you can see a live demo at https://christianmurphy.github.io/react-remark/?path=/story/remark-component--default

some sample markdown with images to play with:

```markdown
# header

1. ordered
2. list

![](https://via.placeholder.com/150)

* unordered
* list

![](https://via.placeholder.com/250)
```
