### ISSUE TITLE
Content inside html element is rendered after the element

### ISSUE THREAD

**Issue by laurenskling** [remarkjs/react-markdown#396]
this is my markdown:
`please click <a href="/example">here</a>. Thank you`

The output is:
```
<p>
  "please click "
  <span>
    <a href="/example""></a>
  </span>
  "here"
  <span></span>
  ". Thank you"
</p>
```

It's rendering the text `here` _after_ the `<a>`

**Comment by aje** [comment]
This bug is making me crazy. It happens when the element has an attribute.

**Comment by ChristianMurphy** [comment]
I can't reproduce this.
Trying 

```markdown
please click <a href="/example">here</a>. Thank you
```
in https://remarkjs.github.io/react-markdown
results in the following HTML

```html
<p>please click <a href="/example">here</a>. Thank you</p>
```

Consider upgrading your version of react-markdown to get the latest fixes, as this appears to be a non-issue in latest
