### ISSUE TITLE
AMP throws validation error on images

### ISSUE THREAD

**Issue by rbelow** [remarkjs/react-markdown#399]
# Bug report

## Description

When an image is used in markdown and the Next.js page [is an AMP page ](https://nextjs.org/docs/api-reference/next/amp) the compiler logs this error: `/<page-path>  error  The parent tag of tag 'IMG-I-AMPHTML-INTRINSIC-SIZER' is 'p', but it can only be 'i-amphtml-sizer-intrinsic'.`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `npm init next-app`
2. `npm i react-markdown raw-loader`
3. Add to `next.config.js`:
```js
module.exports = {
  webpack: config => {
    config.module.rules.push({
      test: /\.md$/,
      use: 'raw-loader'
    });
    return config;
  },
  moreConfig {
    // more code
  }
}
```
4. [Activate AMP on a page](https://nextjs.org/learn/excel/amp/amp-only)
5. Create a markdown file with an image
6. Load the markdown file with `ReactMarkdown` on the page with activated AMP
7. `npm dev`
8. Open the browser and go to the page

## Expected behavior

No error.

## System information

- OS: Ubuntu LTS 18.04
- Version of Next.js: 9.2.2
- Version of react-markdown: 4.3.1
- Version of raw-loader: 4.0.0

**Comment by ChristianMurphy** [comment]
This sounds like it is the same as https://github.com/rexxars/react-markdown/issues/426

https://github.com/rexxars/react-markdown/issues/426#issuecomment-632189667 may resolve your issue
