### ISSUE TITLE
How can I parse "custom markdown" syntax

### ISSUE THREAD

**Issue by RodPaDev** [remarkjs/react-markdown#400]
I'm currently working with Hashnode's API and it returns markdown for the articles, so far so good react-markdown handles all of it fine, but they're using this syntax `%[http://url.com]` for a link preview?

Edit: I would like to return a `<code class="link-card">`

If someone could point me in the right direction I would be most grateful

**Comment by hbinduni** [comment]
i think you can use custom `renderer` like below:
```
const code = ({language, value}) => {
  if (language === 'link-card') {
    return <CustomComponent value={value} />;
  }
};
```

and use it in your react app:
```
import {renderer} from '../utils/MarkdownRenderer';

<Markdown source={markdown} renderers={renderer} />
```

**Comment by RodPaDev** [comment]
Yes, I thought that much I would need, what I'm struggling to find information is the part where the `%[url]` gets parsed into that renderer. I tried looking on the docs, but it points to so many other libraries I'm a bit lost

**Comment by savissimo** [comment]
I have the same problem. Could we get a simple example, please?

**Comment by gigincg** [comment]
> 
> 
> Yes, I thought that much I would need, what I'm struggling to find information is the part where the `%[url]` gets parsed into that renderer. I tried looking on the docs, but it points to so many other libraries I'm a bit lost

Hey, I'm also looking for something similar? Did you find any luck? If yes, could please share a code snippet or a gist?

**Comment by joaniffer** [comment]
I was planning to do something like this and found in another thread [this comment](https://github.com/rexxars/react-markdown/issues/218#issuecomment-538083943). I haven't tried it out yet, but it makes the most sense so far. You use the little language "fences"

**Comment by ChristianMurphy** [comment]
as @AlanLes mentions  https://github.com/remarkjs/remark/tree/master/packages/remark-parse#parserinlinetokenizers is a good resource for creating tokenizers to parse new content types.
You can also find a more general guide to unified/remark at https://unifiedjs.com/learn/
