### ISSUE TITLE
HTML parser: `Failed to execute 'removeChild' on 'Node'`

### ISSUE THREAD

**Issue by SimplyBallistic** [remarkjs/react-markdown#402]
Full Error: 
```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
The above error occurred in the <TextRenderer> component:
    in TextRenderer (created by ReactMarkdownWithHtml)
    in p (created by ReactMarkdownWithHtml)
    in Root (created by ReactMarkdownWithHtml)
```
This error happens when I change the props of a component. This component is a PureComponent which passes a portion of the props to ReactMarkdown for it to render.  

The website I'm building is a mini-test that serves several sequential questions to the user. I use React Markdown to render the questions which are written by others using markdown. When a question is complete, I change the props to my QuestionViewer component and it renders the new question. This component renders the ReactMarkdown object. I use WithHtml so question makers have more freedom. 

The system works fine initially but when I try switching questions (changing props), ReactMarkdown throws this error. 

How I use ReactMarkdown: 
```jsx
<ReactMarkdown renderers={{image: this.imageRenderer}} escapeHtml={false}
                                       source={question.explanationMarkdown}/>

imageRenderer(props) {//for markdown
        return <img alt='Question' {...props} style={{maxWidth: '100%', maxHeight: '250px'}} className='mx-auto'/>;

    }

```
Rough Hierachy:
```jsx
<App>//in App I change the props to QuestionViewer at a certain condition (when next question //needs to be shown)
<QuestionViewer question={question}/>
</App>

```

I had this error before when I was updating the state in the same QuestionViewer component. I fixed it however by converting my functional component to a class-based one. It seems to be triggered when a full re-render happens, which a class component can somehow go over - this is only a guess as I don't fully understand how React works under the hood.  

What I tried: 
1. Removing custom renderers. 
2. Also switching the 'App' to a class-based component,

Any help would be awesome :), not sure if its an underlying ReactMarkdown issue

**Comment by SimplyBallistic** [comment]
Update: managed to fix it by first rendering nothing, then rendering the next ReactMarkdown. I don't want to use this solution forever, but it seems that changing from one ReactMarkdown to another seemlessly triggers this error.

**Comment by ChristianMurphy** [comment]
@SimplyBallistic could you create a reproducable example of the issue? https://codesandbox.io/s/kind-ramanujan-jnyi5 is a good starting point

**Comment by SimplyBallistic** [comment]
> @SimplyBallistic could you create a reproducable example of the issue? https://codesandbox.io/s/kind-ramanujan-jnyi5 is a good starting point

Sure. I'll send a link here in a few days

**Comment by rayronvictor** [comment]
@SimplyBallistic I had the same issue and it was because [of this](https://github.com/remarkjs/react-markdown/pull/365).

I fixed the error disabling Google Translate on Chrome.

**Comment by wooorm** [comment]
@rayronvictor could you create a reproducable example of the issue? https://codesandbox.io/s/kind-ramanujan-jnyi5 is a good starting point

**Comment by SimplyBallistic** [comment]
> @SimplyBallistic I had the same issue and it was because [of this](https://github.com/remarkjs/react-markdown/pull/365).
> 
> I fixed the error disabling Google Translate on Chrome.
> 
> ```
> <html translate="no">
> ```

This actually might be the case. I'll try out your solution + test in Firefox and edge to see if this works.

**Comment by rayronvictor** [comment]
> @rayronvictor could you create a reproducable example of the issue? https://codesandbox.io/s/kind-ramanujan-jnyi5 is a good starting point

https://codesandbox.io/s/elastic-microservice-ylxlr

First, you need to enable "Offer to translate pages in this language" in chrome://settings/languages. I selected "Portuguese (Brazil)".

<img width="723" alt="Screen Shot 2020-12-09 at 14 44 18" src="https://user-images.githubusercontent.com/1683922/101667384-0e6f1680-3a2e-11eb-858b-9db9a916905a.png">

Then, accessing the fullscreen page https://ylxlr.csb.app you need to translate the portuguese text from the example to english (mark "Always Translate Portuguese" to see the error more easily).

<img width="384" alt="Screen Shot 2020-12-09 at 14 46 39" src="https://user-images.githubusercontent.com/1683922/101667859-9ce39800-3a2e-11eb-9932-8dab02a0b548.png">

<img width="1081" alt="Screen Shot 2020-12-09 at 14 47 01" src="https://user-images.githubusercontent.com/1683922/101667968-bb499380-3a2e-11eb-9290-a9f105d0fbf7.png">

Note that I changed the default language to "pt-br" in the index.html (`<html lang="pt-br">`)

**Comment by ChristianMurphy** [comment]
Thanks @rayronvictor tracing this back some more, this appear to be https://github.com/facebook/react/issues/11538
You can find a work around there as well https://github.com/facebook/react/issues/11538#issuecomment-417504600.
Given the performance impact of the work around, and that it's not specific to react-markdown, I don't think this is something that should be applied at the react-markdown level, but on a per-project basis, as need arises.
The long term fix is https://bugs.chromium.org/p/chromium/issues/detail?id=872770
