### ISSUE TITLE
Add yarn installation instructions

### ISSUE THREAD

**Issue by tjayrush** [remarkjs/react-markdown#403]
Excellent tool. Thanks for making it.

I'm relatively new to React/Javascript, and for one reason or another, I started by using `yarn` instead of `npm`. May I suggest that you add instructions for installing using `yarn` as well as `npm`?

I can figure it out (by searching the web) what the equivalent command is for installing using yarn (see below), but I find things much easier to use if the repo owner gives instructions for both `yarn` and `npm`.

Here's the equivalent command to install using yarn:

```
yarn add react-markdown
```

See [this page](https://shift.infinite.red/npm-vs-yarn-cheat-sheet-8755b092e5cc) for more `yarn` information.

**Comment by ChristianMurphy** [comment]
PRs are welcome!

**Comment by ChristianMurphy** [comment]
Since adding dependencies in yarn is well documented elsewhere, this isn't a critical priority.
I'm going to close this issue out, when you have some time, a PR adding it to the docs would still be welcome!
