### ISSUE TITLE
Table of contents links

### ISSUE THREAD

**Issue by davidsteed** [remarkjs/react-markdown#404]
I have some markup
```
1. [Top Level](#Top-Level)
   1. [Windows](#Windows)
   2. [OSX/Linux](#OSX/Linux)
   3. [Android](#Android)

## Top Level

## Windows

## OSX/Linux

## Android
```
In markup the table of conents links to the headers.  The HTML generated creates the right links
```
<a href="#Windows">Windows</a>
```
but the headings aren't anchored.  If they were 
```
<h1><a >Windows</a></h1>
```
It would work.  Is there a way of doing this?
```

**Comment by shyaniv7** [comment]
you would need to add an id to each one of the headers in order for the correct links to be generated.

I replaced my heading node in the renderers prop with HeadingRenderer

```js
import React from 'react';

const flatten = (text: string, child) => {
  return typeof child === 'string'
    ? text + child
    : React.Children.toArray(child.props.children).reduce(flatten, text);
};

/**
 * HeadingRenderer is a custom renderer
 * It parses the heading and attaches an id to it to be used as an anchor
 */
const HeadingRenderer = props => {
  const children = React.Children.toArray(props.children);
  const text = children.reduce(flatten, '');
  const slug = text.toLowerCase().replace(/\W/g, '-');
  return React.createElement('h' + props.level, { id: slug }, props.children);
};

export default HeadingRenderer;

```

**Comment by davidsteed** [comment]
So I should use
```
<ReactMarkdown
  source={markdown}
  escapeHtml={false}
  renderers={{'heading',HeadingRederer}}
/>
```

**Comment by shyaniv7** [comment]
> So I should use
> 
> ```
> <ReactMarkdown
>   source={markdown}
>   escapeHtml={false}
>   renderers={{'heading',HeadingRenderer}}
> />
> ```

No, it would be `renderers={{ heading: HeadingRenderer}}`

**Comment by davidsteed** [comment]
Thank you very much - had to remove toLowerCase() on line 16, but after doing that it works perfectly

**Comment by ChristianMurphy** [comment]
@davidsteed another approach could be to use a plugin to automatically add anchors to headings, like https://github.com/remarkjs/remark-slug
or even generate the entire table of contents automatically with a plugin using: https://github.com/remarkjs/remark-toc

**Comment by wenj91** [comment]
> you would need to add an id to each one of the headers in order for the correct links to be generated.
> 
> I replaced my heading node in the renderers prop with HeadingRenderer
> 
> ```js
> import React from 'react';
> 
> const flatten = (text: string, child) => {
>   return typeof child === 'string'
>     ? text + child
>     : React.Children.toArray(child.props.children).reduce(flatten, text);
> };
> 
> /**
>  * HeadingRenderer is a custom renderer
>  * It parses the heading and attaches an id to it to be used as an anchor
>  */
> const HeadingRenderer = props => {
>   const children = React.Children.toArray(props.children);
>   const text = children.reduce(flatten, '');
>   const slug = text.toLowerCase().replace(/\W/g, '-');
>   return React.createElement('h' + props.level, { id: slug }, props.children);
> };
> 
> export default HeadingRenderer;
> ```

Thank you very much!
