### ISSUE TITLE
Feature request: highlight code blocks with languages & diff

### ISSUE THREAD

**Issue by danksky** [remarkjs/react-markdown#406]
It would be nice to have code highlighting that supports both syntax highlighting and diff'ing. 

### Example of only JSX working in GitHub
``` jsx, diff
<a
   className="App-link"
   ref="https://reactjs.org"
+  target="_blank"
-  rel="noopener noreferrer"
 >
  Learn React
</a>
```

### Example of only diff working in GitHub
```diff, jsx
<a
   className="App-link"
   ref="https://reactjs.org"
+  target="_blank"
-  rel="noopener noreferrer"
 >
  Learn React
</a>
```
### Usage: 

\`\`\`jsx, diff
...
\`\`\`

**Comment by ChristianMurphy** [comment]
react-markdown is remark based, and supports plugins.
There are plugins for several highlighting systems you could use: see https://github.com/remarkjs/remark/blob/master/doc/plugins.md and search "highlight" in the page.
