### ISSUE TITLE
How would you implement `[[Wiki-style]]` links?

### ISSUE THREAD

**Issue by christiangenco** [remarkjs/react-markdown#411]
WikiLinks aren't included in the official markdown format and are gaining popularity in markdown-ish note taking apps like [Roam Research](https://roamresearch.com/). 

It's much easier to type a link to a page if the page's URL can be deduced from it's title, especially if your editor can autocomplete the link based on a list of existing document titles.

Here's how create a standard link in Markdown:

```markdown
Today I had a skype call with [Bill Gates](/Bill_Gates/).
```

And here's the simplified WikiLink syntax that would generate the same output:

```markdown
Today I had a skype call with [[Bill Gates]].
```

The [Python-Markdown](https://github.com/Python-Markdown/markdown/) library has [support for WikiLinks](https://python-markdown.github.io/extensions/wikilinks/) with their own definition of how they work.

How might we add support for `[[WikiLinks]]` in `react-markdown`? Is there a library-approved way of adding weird syntax, or would I be better served by running my markdown through a preprocessor that just finds and replaces all instances of `[[${title}]]` with `[${title}](/${escape(title)})`?

**Comment by ChristianMurphy** [comment]
Using https://github.com/djm/remark-shortcodes as an plugin in `plugins` https://github.com/djm/remark-shortcodes
