### ISSUE TITLE
<Fragment> instead of <p>

### ISSUE THREAD

**Issue by ghost** [remarkjs/react-markdown#412]
Is there a way to render a `Fragment` instead of the default `p` tag? My table doesn't allow nested paragraphs in the DOM nodes for the cells thus I need an empty container like a Fragment. Is there anyway to do that?

**Comment by jiminy-billy-bob** [comment]
```javascript
<ReactMarkdown
    source={content}
    renderers={{
        paragraph: props => <React.Fragment {...props} />
    }}
/>
```
