### ISSUE TITLE
Basic highlight

### ISSUE THREAD

**Issue by Altiano** [remarkjs/react-markdown#415]
How about something like basic syntax highlight by GitHub markdown

```javascript
var s = "JavaScript syntax highlighting";
alert(s);
```

instead of just \``` we use \```javasript

**Comment by ChristianMurphy** [comment]
This may already be able to be supported through plugins https://github.com/remarkjs/remark/blob/master/doc/plugins.md has several plugins for syntax highlighting.

Not sure if they'll work out of the box now, but they would with #428

**Comment by ChristianMurphy** [comment]
also see #191
