### ISSUE TITLE
editor is crashed when there are nested tags

### ISSUE THREAD

**Issue by annashipilo** [remarkjs/react-markdown#423]
Hello! We are using your editor. And we faced such an issue.
If markdown contains something like this `<span><span> ffff </span></span>`
the editor is crashed with such an error in the console

![image](https://user-images.githubusercontent.com/36773373/81301378-a6b0b180-9081-11ea-988e-883d64faee0a.png)

it's also reproduced on the demo here: https://rexxars.github.io/react-markdown/

**Comment by ChristianMurphy** [comment]
https://github.com/rexxars/react-markdown/pull/428 resolves this

**Comment by wooorm** [comment]
This is also a duplicate of https://github.com/remarkjs/react-markdown/issues/385, so I’ll close this, and we can continue discussing over there
