### ISSUE TITLE
[bug] Strike not working properly on v4.3.1

### ISSUE THREAD

**Issue by guilhermecastro-hotmart** [remarkjs/react-markdown#424]
Hey!

I am using your editor, and after some tests I faced this behavior. When I try to parse an strikethrough format it won't render if the string has blank spaces close to tilde (~).

`~~ teste ~~`
`~~teste ~~`
`~~ teste~~`

Results of these tests:
![image](https://user-images.githubusercontent.com/50368142/81335418-f8573d00-907d-11ea-83bc-00443f05dd13.png)

It's also reproduced on the demo here: https://rexxars.github.io/react-markdown/

**Comment by ChristianMurphy** [comment]
@guilhermecastro-hotmart this is how strike through works.
The spec defines strike through as an emphasis type https://github.github.com/gfm/#strikethrough-extension-

Example from emphasis explaining this behavior: https://github.github.com/gfm/#example-361

**Comment by ChristianMurphy** [comment]
@bdougie same goes for wrapping text in single `~`.
From the GFM spec:

> Strikethrough text is [...] wrapped in two tildes

https://github.github.com/gfm/#strikethrough-extension-

**Comment by bdougie** [comment]
I am happy to adhere to the spec. Thanks for linking it @ChristianMurphy, this is helpful.
