### ISSUE TITLE
Add types for `plugins/html-parser`

### ISSUE THREAD

**Issue by emil14** [remarkjs/react-markdown#433]
`import htmlParser from 'react-markdown/plugins/html-parser'` results to `Could not find a declaration file for module 'react-markdown/plugins/html-parser` when using TypeScript

I've seen this [fix](https://github.com/rexxars/react-markdown/pull/352) but still can't figure out how to use `plugins/html-parser`. I need `plugins/html-parser`, not `react-markdown/with-html` because I want to build my own parser and pass it to `astPlugins` prop

Am I missing something? Thank you

**Comment by ChristianMurphy** [comment]
It doesn't have typings yet.
Feel free to open a PR adding typings for it.

**Comment by ChristianMurphy** [comment]
it's also worth noting html-parser would be replaced by rehype if #428 is merged

**Comment by wooorm** [comment]
This should be solved by landing GH-563 today, which will soon be released in v6.0.0!
