### ISSUE TITLE
Checkboxes come in as "readonly" even if they are marked as "disabled"

### ISSUE THREAD

**Issue by jlag34** [remarkjs/react-markdown#436]
I'm pulling from a raw git repo readme and displaying it to my webpage. The markdown uses `[x]` to display the checked checkbox. When I inspect the checkbox on Github the input has the `disabled` property but this library gives it `readonly`. This results in the checkbox having a blue background instead of gray. Is this intended? If so I can use the solution from #294 but I'm unsure how to add the text that follows the checkbox.

**Comment by jlag34** [comment]
Ha, nvm. I fixed the issue right after I posted this using most of the code from the issue linked.

```
const renderListItem = (props) => {
  if (props.checked !== null && props.checked !== undefined) {
    return (
      <div>
        <input type="checkbox" disabled checked />
        {props.children}
      </div>
    )
  }
  // otherwise default to list item
  return defaultListItem(props)
}
```

My solution using help from the OP. Issue with the background color still exists though.

**Comment by ChristianMurphy** [comment]
> This results in the checkbox having a blue background instead of gray. Is this intended?

This would be coming from the browser/a stylesheet, no color is being set by react-markdown.
