### ISSUE TITLE
Improve TS type for ReactMarkdown.Renderers

### ISSUE THREAD

**Issue by Vadorequest** [remarkjs/react-markdown#439]
I've noticed the following implementation for 

```ts
interface Renderers {
    [key: string]: string | Renderer<any>
  }
```

Know that you can use the following instead:

```ts
interface Renderers {
  [key in ReactMarkdown.NodeType]?: string | ReactMarkdown.Renderer<any>;
}
```

This has the advantage of allowing intellisense for `Renderers` (e.g: `Renderers.link`, etc. Basically, keys can be autocompleted.

**Comment by ChristianMurphy** [comment]
@Vadorequest `NodeType` merely has the initial node types, plugins can add new node types which would also need renderers.
Limiting the keys would block TypeScript users from using custom node types.

**Comment by Vadorequest** [comment]
I see what you mean, it's not really a blocker though.

TS users could also extend the `NodeType` and add their own keys. 
But the best default could be to use `NodeType | string` so that it gets autocompleted but isn't too restricted. :)

**Comment by ChristianMurphy** [comment]
@Vadorequest if you want you can open a PR.
Another thing that may interest you #428 may move the project to native typescript.
