### ISSUE TITLE
https://rexxars.github.io/react-markdown/ is down

### ISSUE THREAD

**Issue by samascience** [remarkjs/react-markdown#440]
https://rexxars.github.io/react-markdown/ is not being rendered !

**Comment by ChristianMurphy** [comment]
![Screenshot_2020-06-15 react-markdown](https://user-images.githubusercontent.com/3107513/84706898-a32b0880-af12-11ea-9b7e-363ccaff909e.png)

It looks to be working, could you give more detail on what isn't rendered?
