### ISSUE TITLE
Xss filter -  transformImageUri

### ISSUE THREAD

**Issue by trish123** [remarkjs/react-markdown#441]
In the documentation, I saw that "uriTransformer" is applied to "transformLinkUri"  (pasting from the documentation-  **"The default link URI transformer acts as an XSS-filter, neutralizing things like javascript:, vbscript: and file: protocols."** )

 but it is not applied to transformImageUri .  Can anyone know about the reason why it is not applied to transformImageUri ?

**Comment by ChristianMurphy** [comment]
The `src` attribute of `img` tags doesn't run scripts, so it doesn't have a script filter.
You can try it out on the demo: https://rexxars.github.io/react-markdown/
with:
```html
<img src="javascript:alert('XSS?');" />

![](javascript:alert('XSS?');)
```
