### ISSUE TITLE
I  need  help，I meet a markdown grammar problem

### ISSUE THREAD

**Issue by SkyWongHZ** [remarkjs/react-markdown#448]
when I use react-markdown  library, I  meet  a markdown  grammar  problem.

I use ordered list and  unordered list  in  my  code,the  corrected display should  be look  like  this,
<img width="1376" alt="45A41698-889B-4ECD-80E5-654C9A5AA38C" src="https://user-images.githubusercontent.com/20575355/88018840-156aba80-cb5b-11ea-9dc4-5b1a7242d583.png">

but  when   I  use    it，the markdown's  render  is  wrong,  it  looks  like below,
![F987607A-3B2A-4E93-86B6-652CDC9834B6](https://user-images.githubusercontent.com/20575355/88018844-17cd1480-cb5b-11ea-958a-61f8d3ef2221.png)

In my  project，my   packjson   is  below:
<img width="960" alt="1A0ADFC4-F240-4C23-822E-17EDDA038A3A" src="https://user-images.githubusercontent.com/20575355/88018851-1ac80500-cb5b-11ea-9bc2-47c8a1632249.png">

I  try my  best  to   solve  this  problem get through  some solutions,but  i have  failed,could   anyone  help  me?

**Comment by ChristianMurphy** [comment]
@SkyWongHZ can you share a runnable example of the issue?

---

Trying the content

```markdown
* test
* test
* test
1. test
2. test
```

in the demo site https://rexxars.github.io/react-markdown
produces the correct result
![Screenshot_2020-07-21 react-markdown](https://user-images.githubusercontent.com/3107513/88076922-86947880-cb2f-11ea-8266-fad75b8dab37.png)

My guess is that you may have CSS that is hiding the list item markers.
But it's hard to tell without a runnable example of the issue.
