### ISSUE TITLE
in some cases does not set escapeHTML to true by default

### ISSUE THREAD

**Issue by ExtraHash** [remarkjs/react-markdown#450]
Hello,

I'm using your library in an application I'm writing. In the app, I have a large array of message objects, one key of which is a ReactMarkdown component, that sits in state. I don't want to re-render every single markdown component each time the array changes, so I'm rendering them beforehand on initial download like so:

```js
for (const message of messages) {
    message.markdown = parseMarkdown(message.comment)
}

function parseMarkdown(markdown) {
  const options = {
    source: markdown,
    linkTarget: '_blank',
  };
  return new ReactMarkdown(options);
}
```

This works great, and now I only render each message one time. However, I noticed that it seems to ignore the default `escapeHTML` setting when I do this, and it actually renders HTML by default and even allows javascript handlers to be rendered and such. 

Here's a minimal reproduction:
https://github.com/ExtraHash/react_markdown_bug_reprod/blob/master/src/App.js

```js
import ReactMarkdown from 'react-markdown';

function parseMarkdown(markdown) {
  const options = {
    source: markdown,
    linkTarget: '_blank',
  };
  return new ReactMarkdown(options);
}

const xssString = `<form onsubmit="alert('hello')">
<input type="submit">
</form>`;

function App() {
  return (
    parseMarkdown(xssString)
  );
}

export default App;
```

Setting `escapeHTML` to `true` explicitly makes it perform as expected, escaping HTML.

Is this just my usage error? I know it's not conventional to actually call `new` on a react component, but it does seem to work fine.

**Comment by ChristianMurphy** [comment]
> I don't want to re-render every single markdown component each time the array changes

React has solutions for this, a mix of https://reactjs.org/docs/lists-and-keys.html#keys and/or https://reactjs.org/docs/react-api.html#reactmemo should prevent unnecessary rerenders.

> However, I noticed that it seems to ignore the default escapeHTML setting when I do this

When you bypass https://reactjs.org/docs/react-api.html#createelement, you bypass prop type checking and defaults.
`escapeHTML: true`is set in `defaultProps`

https://github.com/rexxars/react-markdown/blob/2d991aa1097e95064f0209fc6d3a15b6300c07c7/src/react-markdown.js#L82-L92
