### ISSUE TITLE
disallowedTypes={["link"']} does not work if the link is empty

### ISSUE THREAD

**Issue by IcyTotem** [remarkjs/react-markdown#455]
[Minimal reproducible example](https://codesandbox.io/s/blissful-cloud-36flk?file=/src/App.js)

I have some python docs that has square brackets in it. They are rendered as links. I tried using `disallowedTypes` to check whether I could change the behaviour but apparently they are at the same time rendered as links but not treated as link nodes by `disallowedTypes`.

Please either:

- treat both well-formed links and square brackets as links and apply the same beahviour to both; or
- treat square brackets as malformed links and don't render them as such but treat them as text.

Also, it appears that the custom renderer for links does not work? You can see that in the second example from the sandbox.

**Comment by ChristianMurphy** [comment]
@IcyTotem the in both cases, the code is working as expected, `link` and `linkReference` are different types.
see https://github.com/rexxars/react-markdown#node-types and https://astexplorer.net/#/gist/15d151332a325d1f8828e16d9955e519/754cc5970ee3fd744c73404e582d1636d730023b
