### ISSUE TITLE
How do I use the definition node?

### ISSUE THREAD

**Issue by basith374** [remarkjs/react-markdown#458]
Sorry. But I searched everywhere but couldn't find any examples, demos. None of the other libraries mentions such a thing. In among the list of supported nodes, there is a 'definition' node. What is it & how does it work?

**Comment by ChristianMurphy** [comment]
See the documentation for `mdast` which describes `definition` https://github.com/syntax-tree/mdast#definition
For a walk through try https://commonmark.org/help/tutorial/07-links.html
