### ISSUE TITLE
Improving performance

### ISSUE THREAD

**Issue by nehalist** [remarkjs/react-markdown#459]
Currently the performance of this package is really torturing my browser as soon as the parsed markdown gets too big. It's easily reproducible by taking a look at the [demo](https://uiwjs.github.io/react-markdown-editor/) at https://github.com/uiwjs/react-markdown-editor which depends on this package. Just duplicate the editor content a few times and witness your browser giving its best trying not to die.

I initially thought the reason for this is CodeMirror, but as soon as the preview is disabled (not just hidden but literally removing the DOM element) everything works fine again.

Since having ~500 lines of content is not that rare these performance issues make it really hard to use this package. Is there any way to improve performance?

**Comment by ChristianMurphy** [comment]
@nehalist any parsing/processing will become computationally expensive given enough text.
A common approach to smoothing the experience is to apply a debounce ([overview](https://medium.com/@jamischarles/what-is-debouncing-2505c0648ff1), [lodash](https://lodash.com/docs#debounce), [react hook](https://beautifulinteractions.github.io/beautiful-react-hooks/#/useDebouncedFn))
Which reduces overhead by not rendering for every keystroke, and instead rendering after a keystroke and after some number milliseconds pass.
