### ISSUE TITLE
Need Markdown Table & Image Caption Support

### ISSUE THREAD

**Issue by upadhyayprakash** [remarkjs/react-markdown#463]
Thanks for this awesome markdown parser for React. I'm trying to find a way to support Table & Image Caption in markdown. For image, i'm using a HTML tag figure/figcaption in my Markdown. But for table, I needed to avoid using HTML tags, so looking for a way to support markdown table caption.

I found this discussion about same: https://github.com/rstudio/bookdown/issues/780

But it didn't work with react-markdown.

Could you help with this?

**Comment by ChristianMurphy** [comment]
[remark](https://github.com/remarkjs/remark) (the core library the handles markdown for react-markdown) is designed to offer [commonmark](https://commonmark.org/) out of the box.
Features outside of commonmark like captions can be added through plugins/extensions https://unifiedjs.com/learn, but are outside the scope of the defaults/out-of-the-box features.

Here are a few plugins that can be used as a starter:
https://github.com/dimerapp/remark-macro
https://github.com/djm/remark-shortcodes
https://github.com/landakram/remark-wiki-link

You can find more information on plugins here: https://unifiedjs.com/learn
And find more information on how to use remark plugins in react-markdown here: https://github.com/rexxars/react-markdown#options
