### ISSUE TITLE
Security feature request: a setting to block inline javascript

### ISSUE THREAD

**Issue by winterstein** [remarkjs/react-markdown#465]
Firstly, thank you for this useful package :+1: 

We want to allow html (so `escapeHtml={false}`) -- but not allow `onClick`, `onMouseOver`, `onX` etc handlers -- as these would allow an attacker to inject javascript traps.

I don't think there is a way to do this. So I'm requesting a feature to block inline javascript.

Meanwhile, we can achieve this by pre-filtering the input with a few regexs.

**Comment by codefull** [comment]
> Firstly, thank you for this useful package 👍
> 
> We want to allow html (so `escapeHtml={false}`) -- but not allow `onClick`, `onMouseOver`, `onX` etc handlers -- as these would allow an attacker to inject javascript traps.
> 
> I don't think there is a way to do this. So I'm requesting a feature to block inline javascript.
> 
> Meanwhile, we can achieve this by pre-filtering the input with a few regexs.

Hi, could you please share your approach to filter those elements.

**Comment by winterstein** [comment]
Sure - we're sniffing for onX in a tag. If we find it, we re-enable escapeHtml for safety:

	// security: no onClick etc traps	
	if ( ! escapeHtml) {
		let bad = source.match(/<[^>]+\bon[a-zA-Z]+=/g, ''); // match e.g. onClick within a tag
		if (bad) {
			console.warn("Dangerous content in markdown!", bad, source);
		}
		escapeHtml = true;
	}

**Comment by ChristianMurphy** [comment]
This would be supported more directly through #428, which supports https://github.com/rehypejs/rehype-sanitize

**Comment by wooorm** [comment]
This should be solved by landing GH-563 today, which will soon be released in v6.0.0!
