### ISSUE TITLE
Unordered list not working on Fluent UI Panel

### ISSUE THREAD

**Issue by sadaga99** [remarkjs/react-markdown#467]
![image](https://user-images.githubusercontent.com/57788190/94253834-7f308780-ff43-11ea-879e-30c34dc63945.png)

const markdown = '<ul><li>test</li><li>test 2</li></ul>';
<ReactMarkdown source={markdown} escapeHtml={false} />

This code runs fine in codesandbox, but when used on the web app, we are not able to see the bullets for unordered list (as shown in the image)

**Comment by sadaga99** [comment]
https://github.com/niklasvh/html2canvas/issues/177 - same issue for htmlcanvas2 issue. We are using React though.

**Comment by ChristianMurphy** [comment]
@sadaga99 testing the example in the playground it works fine https://remarkjs.github.io/react-markdown/
Most likely you have `list-style: none;` in your stylesheet hiding the bullet items.
