### ISSUE TITLE
Possible to insert an onClick event on 'a' tags ? 

### ISSUE THREAD

**Issue by stuartambient** [remarkjs/react-markdown#468]
This is for a message service running in Electron.  The desired result should be when the link is clicked a tab opens in the users default browser.  I have a handler that works fine but I can't find a way to call it with React-Markdown a tag generation.
Using the current way with react-markdown opens up the page in Electron.  Anyway workarounds ?

**Comment by ChristianMurphy** [comment]
Yes, using `renderers` you can customize the rendering of any element type
https://github.com/remarkjs/react-markdown#options
there is an example of usage here: https://github.com/remarkjs/react-markdown/blob/c63dccb8185869cfc73c257d098a123ef7a7cd33/demo/src/demo.js#L87-L94
