### ISSUE TITLE
CodeBlock missing meta

### ISSUE THREAD

**Issue by heri16** [remarkjs/react-markdown#471]
https://github.com/remarkjs/react-markdown/blob/c2809c17e9d004abe3fcc3157f6face756323af1/src/ast-to-react.js#L103

CodeBlock from mdast has a meta property that is not passed as props.

https://github.com/syntax-tree/mdast#code

```markdown
We'll transform this one:

~~~java https://stackoverflow.com/questions/4042434/converting-arrayliststring-to-string-in-java
List<String> list = ..;
String[] array = list.toArray(new String[0]);
~~~

But leave this the same:

~~~java
List<String> list = ..;
String[] array = list.toArray(new String[0]);
~~~
```

**Comment by wooorm** [comment]
This is on the v5 branch and will be released soon
