### ISSUE TITLE
Issue with parsing ordered lists

### ISSUE THREAD

**Issue by DmitriyF89** [remarkjs/react-markdown#473]
Hello, there is a problem with parsing ordered lists.

### Subject of the issue

If there is no blank line before the ordered list, then the list is merged into a paragraph with the text above it.

### Your environment

*   **OS**: Windows 10
*   **Packages**: "react-markdown": "^4.3.1"
*   **Env**: node v14.13.1

### Steps to reproduce

```
import React from 'react';
import ReactDOM from 'react-dom';
import ReactMarkdown from 'react-markdown';

const markdown = 'Some text\n1. item 1\n2. item 2';

test('should render correct ordered list', () => {
    const root = document.createElement('div');
    root.setAttribute('id', 'root');
    document.body.append(root);

    ReactDOM.render(<ReactMarkdown source={markdown} />, root);
    
    expect(root.innerHTML).toBe('<p>Some text</p><ol><li>item 1</li><li>item 2</li></ol>');
});
```

### Expected behavior

`<p>Some text</p><ol><li>item 1</li><li>item 2</li></ol>`

### Actual behavior

```
<p>Some text
1. item 1
2. item 2</p>
```

**Comment by wooorm** [comment]
This is the way markdown works. You can add a blank line instead to get your expected behavior:

```
const markdown = 'Some text\n\n1. item 1\n2. item 2';
```
