### ISSUE TITLE
<div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by SalahAdDin** [remarkjs/react-markdown#475]
Hi, I'm using a custom render to render an image inside of a markdown; while it isolates the code block to a `pre`/`code`, it does not happen with image blocks:
![Screen Capture_select-area_20201015011244](https://user-images.githubusercontent.com/5034215/96091331-20bb5100-0ed2-11eb-8f74-78e0f8b35d78.png)

As you can see, the image(wrapped inside of a div) is also wrapped inside of a `p` tag, which creates a validation error:
`react_devtools_backend.js:2273 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.`

### Your environment

*   **OS**: Manjaro Linux
*   **Packages**: react-markdown: ^4.3.1, react-player: ^2.6.0,
*   **Env**: Node.js Version: v14.12.0, NPM version: 6.14.7

### Steps to reproduce
1. Create a custom image renderer:
```jsx
const Image = ({ alt, src, previewSrc, className = "", ...rest }) => {
  const classes = useStyles()
  return (
    <Box style={{ display: "flex" }} className={className}>
      <img
        className={`lazyload ${classes.blurUp}`}
        alt={alt}
        src={previewSrc}
        data-srcset={src}
        style={{ margin: "auto", width: "100%" }}
        {...rest}
      />
    </Box>
  )
}
```
2. Add an image to the `markdown` content.
3. View the rendered content in the browser.

### Expected behavior
As we showed in the image, the image should be isolated to its own `html` tag, as it does with a code block, instead to be wrapped inside of the `p` tag like is working currently.

### Actual behavior
The image block is wrapped in a `p` `html` tag.

**Comment by wooorm** [comment]
Duplicate https://github.com/remarkjs/react-markdown/issues/184

**Comment by kfiroo** [comment]
in latest versions you could use the `components` prop to render all `p` elements as `div`s to solve the issue.
```tsx
<Markdown components={{ p: 'div' }}>{content}</Markdown>
```

**Comment by ChristianMurphy** [comment]
I would not recommend hurting accessibility by making the HTML less semantic to make a warning go away.
For a more accessibility answer see https://github.com/remarkjs/react-markdown/issues/184#issuecomment-705541966
