### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by wooorm** [remarkjs/react-markdown#479]
### Subject of the feature

remark has a giant ecosystem. This project is used a lot. It seems to be a good place to add common case examples of using math, footnotes, gfm, syntax highlighting, in the readme.

### Problem

Confusing to newcomers. Most things can be solved by plugins. But it’s unclear how.

### Expected behavior

A couple of examples. Not too many.

**Comment by ChristianMurphy** [comment]
Examples could help, another approach, taken in #428 but could also be applied to current is using Storybook to create interactive examples.

**Comment by wooorm** [comment]
Could also work! I definitely don’t want it exhaustive!

Somewhere in between might be manageable in storybook.

Where’s the line? What should go where?

**Comment by wooorm** [comment]
I’m assuming GFM to be the most used plugin, so it can probably go in the main Use example. We can skip footnotes as it’s very similar.

Math is interesting because it means a [syntax extension and handling nodes](https://github.com/remarkjs/react-markdown/blob/4f1a4075ccf4cca7d1807ff18bbe89bff22744a1/test/react-markdown.test.js#L664-L675).

Syntax highlighting is interesting because you’re dealing with potentially 500kb of JS. And can go with the plugin or react-syntax-highlighter approach. https://github.com/remarkjs/react-markdown/issues/191
