### ISSUE TITLE
Table markdown not rendered as table

### ISSUE THREAD

**Issue by blackr1234** [remarkjs/react-markdown#493]
### Your environment

*   **OS**: macOS `10.15.5`
*   **Packages**: `react-markdown@5.0.0`, `react@17.0.0`
*   **Env**: node `12.18.4`, npm `6.14.8`

---

### Steps to reproduce

Consider the following code (please read the comments):

```js
// import
import ReactMarkdown from "react-markdown";

// declare the source somewhere
	const md = `
## hello world

|header|header|
|--|--|
|cell|cell|
	`;

// put this in your component's return (of the `render()` method for class components)
<ReactMarkdown source={md} />
```

---

### Expected behavior

I expect tables to render correctly as `<table>` nodes. version `4.3.1` behaves correctly and renders a styleless `<table>` (without border).

I can get the following with version `4.3.1`:

<img width="369" alt="Screenshot 2020-10-21 at 2 20 54 PM" src="https://user-images.githubusercontent.com/13590610/96680725-a34b8100-13a8-11eb-9356-898bacb2a2e9.png">

---

### Actual behavior

Since version `5.0.0`, tables no longer render correctly as a `<table>` nodes but `<p>` instead. Probably the markdown parser no longer recognizes table markdown syntax.

Now I am getting with version `5.0.0`:

<img width="595" alt="Screenshot 2020-10-21 at 2 09 31 PM" src="https://user-images.githubusercontent.com/13590610/96679864-0dfbbd00-13a7-11eb-8830-94dbea046c7c.png">

**Comment by wooorm** [comment]
This is documented in the readme, several times: e.g., see here: https://github.com/remarkjs/react-markdown#use

**Comment by wooorm** [comment]
(and in the changelog: https://github.com/remarkjs/react-markdown/blob/main/changelog.md#upgrade-remark-parse)

**Comment by rkuang9** [comment]
First example in https://github.com/remarkjs/react-markdown?tab=readme-ov-file#use-a-plugin includes a simple table. Table cell borders are not rendered.

**Comment by wooorm** [comment]
yes they are! that works perfectly! if things don’t work for you, ask a new question and provide info!

**Comment by rkuang9** [comment]
For those who run into this issue, you have create a css file from https://github.com/micromark/micromark-extension-gfm-table#css and import it to your component. This adds styling to the otherwise bare rendered th/tr/td. I wish the demo included this information.
