### ISSUE TITLE
Update React version to React 17 (peerDependencies)

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [remarkjs/react-markdown#497]
### Subject of the feature

Update React version to React 17 in peerDependencies

### Problem

react-markdown does not support React 17

### Expected behavior

Support the latest version of React.

### Alternatives

/

**Comment by wooorm** [comment]
Do you get a warning that React 17 isn’t supported, or does something actually crash?

**Comment by Dev-CasperTheGhost** [comment]
Hi,

I'm getting an error when installing it from npm (see image).

Thanks for your fast response.

![image](https://user-images.githubusercontent.com/53900565/97081812-2ff27b00-1605-11eb-9f71-0b7114f8f8b7.png)

**Comment by wooorm** [comment]
Are you on npm 7 already? (`npm --version`)

If so, try the `--legacy-peer-deps` for now.

---

I was looking into React 17 a day or so ago, and it all worked well. However, this project is using `enzyme-adapter-react-16` and in dev-dependencies, and there isn’t a `enzyme-adapter-react-17` yet, so I was waiting on that.

**Comment by Dev-CasperTheGhost** [comment]
Alright, will do. Thanks for your help.

**Comment by wooorm** [comment]
Released!

**Comment by Dev-CasperTheGhost** [comment]
Thankyou!
