### ISSUE TITLE
Shortcode no longer works in version 5

### ISSUE THREAD

**Issue by lucascaton** [remarkjs/react-markdown#501]
### Subject of the issue

Hi there.

Shortcodes were working properly by following [this instruction](https://github.com/remarkjs/react-markdown/issues/113#issuecomment-387216043).

However, since [version 5](https://github.com/remarkjs/react-markdown/blob/main/changelog.md#500---2020-10-19), it no longer works.

I tried adding the new [`node` serializer property](https://github.com/remarkjs/react-markdown/blob/main/changelog.md#new-serializer-property-node) but it didn't solve the problem.

### Your environment

*   **OS**: macOS Catalina (10.15.7)
*   **Packages**: `react-markdown` (5.0.2)
*   **Env**: Node.js 14.15.0, Yarn 1.22.10

### Steps to reproduce

Everything works well in version 4 by following [this instruction](https://github.com/remarkjs/react-markdown/issues/113#issuecomment-387216043).

### Expected behavior

Shortcodes should be parsed.

### Actual behavior

Shortcodes are outputted as `[[ ... ]]` without being parsed.

**Comment by ChristianMurphy** [comment]
Thanks @lucascaton!
Looking into this, it appears to be related to remark 13 being used in remark-react 5, which changed how parsing works, and requires some plugins to update, including remark-shortcodes, this issue has been logged as https://github.com/djm/remark-shortcodes/issues/19
This isn't something which can/should be resolved inside react-markdown, it needs to be resolved upstream at https://github.com/djm/remark-shortcodes

In the meantime there are some alternatives which already work with remark 13 and micromark including https://github.com/remarkjs/remark-directive
