### ISSUE TITLE
Remove unnecessary margin bottom

### ISSUE THREAD

**Issue by shuotli** [remarkjs/react-markdown#503]
Subject of the issue
There is a margin bottom as a result of using <p> tag.  This can cause problem like unnecessary scroll bar.

Your environment
OS: Windows
Packages: react-markdown
Env: Chrome

Steps to reproduce
Inspect on the content of markdown and observe the computed.

Expected behavior
There should not be a margin bottom

Actual behavior
There is a margin bottom. This could cause problem like unnecessary scroll bar. (When there is a single line of text, a scroll bar appears because the paragraph takes up two lines.)

Please see attached screenshot
![Screenshot 2020-11-03 122319](https://user-images.githubusercontent.com/63325084/98036929-b100fd80-1dcf-11eb-8617-c6c9e9108226.png)

**Comment by ChristianMurphy** [comment]
Thanks for reaching out!

We require [the template](https://github.com/remarkjs/.github/blob/main/.github/ISSUE_TEMPLATE/1-bug.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by ChristianMurphy** [comment]
This being a visual bug/question, including a codesandbox would also be helpful.
https://codesandbox.io/s/react-markdown-debug-9n4eg is a good starter.

**Comment by shuotli** [comment]
> Thanks for reaching out!
> 
> We require [the template](https://github.com/remarkjs/.github/blob/main/.github/ISSUE_TEMPLATE/1-bug.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.
> 
> Thanks for understanding and meeting us half way 😀

Thank you for your response. I have updated my description.

**Comment by ChristianMurphy** [comment]
@shuotli trying out your example in codesandbox https://codesandbox.io/s/react-markdown-debug-forked-50q98
react-markdown isn't adding any margin, only the margin is the browser default, which can be adjusted with css.

**Comment by shuotli** [comment]
> @shuotli trying out your example in codesandbox https://codesandbox.io/s/react-markdown-debug-forked-50q98
> react-markdown isn't adding any margin, only the margin is the browser default, which can be adjusted with css.

I can see that <p></p> has a bottom margin. Is there a way to get rid of it with css when importing <ReactMarkdown />?

**Comment by ChristianMurphy** [comment]
@shuotli again, react-markdown doesn't add css.
Those margins are coming from the user agent stylesheet, which is the browser iteself.
![Selection_038](https://user-images.githubusercontent.com/3107513/98051493-4365c900-1df1-11eb-88b0-17f3da400aa9.png)

you can add css to the page if you want to remove the margin.
