### ISSUE TITLE
Strike does not work at all in v5.0.2

### ISSUE THREAD

**Issue by MatSeifert** [remarkjs/react-markdown#504]
### Subject of the issue

We just upgraded from version 4.3.1 to 5.0.2 and it seems like `~~` is not working anymore. I tried it in a clean new project, and the ouput is the same, it prints out `~~Test~~` instead of `<del>Test</del>`. However, other things like `__` for bold text works just fine.

### Expected behavior

It should correctly return `<del>content</del>`

### Actual behavior

it returns the plaintext: `~~content~~`

**Comment by wooorm** [comment]
Duplicate of GH-493.
