### ISSUE TITLE
Some Markdown elements do not render

### ISSUE THREAD

**Issue by richardrobinson0924** [remarkjs/react-markdown#505]
### Subject of the issue

Describe your issue here.

Some markdown elements such as headers and lists do not render.

This is *not* a place to ask questions.  For that, go to [discussions](https://github.com/remarkjs/remark/discussions)

### Your environment

*   **OS**: macOS 11.0.1
*   **Packages**: react-markdown ^5.0.2, remark ^13.0.0, remark-gfm ^1.0.0
*   **Env**:  node v14.10.1, Safari v14.0.1

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

```tsx
const parseMarkdown = (text: string): JSX.Element => <ReactMarkdown
  plugins={[remarkGfm]} children={text} />;

const text = `
## hello

* world
* goodbye
`

// ...
render() {
  return  <div> {parseMarkdown(text)} </div>
}
```

### Expected behavior

What should happen?

`hello` should be a header, and the rest should be rendered as a list

### Actual behavior

What happens instead?

The text is rendered as-is, with no formatting and with `##` and `*` still present.

**Comment by wooorm** [comment]
Weird.

Pasting that text in here works fine: https://codesandbox.io/s/react-markdown-debug-9n4eg.

Can you reproduce there, or in some other way, what’s up?

**Comment by wooorm** [comment]
Also: `<div {parseMarkdown(text)} </div>` is not valid JSX 🤔

**Comment by richardrobinson0924** [comment]
> Also: `<div {parseMarkdown(text)} </div>` is not valid JSX 🤔

Whoops, forgot to add the closing first `>` when I was typing this into the comment here

**Comment by richardrobinson0924** [comment]
@wooorm Oh it appears to be something in my CSS, since when I don't include my CSS file I can see it rendering properly. Any idea what it could be? I'm using TailwindCSS for reference

**Comment by lhennerley** [comment]
Also a similar issue I just tried to use this library 😄 

I think it's more of a tailwind issue than an issue with this library, though - tailwind the default for list is `list-none` https://tailwindcss.com/docs/list-style-type

Looks like there needs to be some changes in the `tailwind-config.js` to handle this, perhaps.

**Comment by wooorm** [comment]
Alright! Searchinf through the issues for css might help!

**Comment by lhennerley** [comment]
Just to fix the issue - you can install the tailwind Typography plugin 

https://tailwindcss.com/docs/typography-plugin

```
module.exports = {
    theme: {
    },
    variants: {},
    plugins: [
      require('@tailwindcss/typography')
    ]
}
```

You can then add the following:

```
<Markdown className='prose'>{markdownSource}</Markdown>
```

Adding `className='prose'` will tell tailwind to render the content - it looks something like this:

![image](https://user-images.githubusercontent.com/54267110/98722671-3fa1eb80-2389-11eb-816c-19dcc3349dc3.png)

**Comment by imanyakin** [comment]
Might be of interest to people reading in 2026 following removal of className from `<Markdown>` described [here](https://github.com/remarkjs/react-markdown/blob/main/changelog.md#remove-classname%3E)

A possible workaround as described [here](https://stackoverflow.com/questions/74607419/react-markdown-don%c2%b4t-render-markdown#74607475) is to reset the tailwindcss configuration by defining a class (for example in global.css)

```
.markdown > * {
  all: revert;
}
```

Then applying it to a <div> around the <Markdown> element:

```
<div className="markdown">
          <Markdown
              remarkPlugins={[remarkGfm, remarkMath]}
              rehypePlugins={[rehypeKatex, rehypeHighlight]}
          >
              {data.description}
          </Markdown>
          </div>
```
