### ISSUE TITLE
Script error when using unpkg/react-markdown@5.0.2

### ISSUE THREAD

**Issue by doveccl** [remarkjs/react-markdown#506]
Just create simple html file to test

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Test</title>
</head>
<body>
  <script src="https://unpkg.com/react-markdown@5.0.2"></script>
</body>
</html>
```

An error shows

```
Uncaught ReferenceError: module is not defined
    at react-markdown.min.js:15
```

**Comment by ChristianMurphy** [comment]
looks to be related to https://github.com/remarkjs/react-markdown/blob/6e38dd343ef653b6c5246625ac3476ffd94d0ebc/rollup.config.js#L12

we may need an `iife` or `umd` version for legacy browsers, and/or `es` for modern browsers.

**Comment by ChristianMurphy** [comment]
@doveccl would you be interested in opening a PR?

**Comment by doveccl** [comment]
@ChristianMurphy 
https://github.com/remarkjs/react-markdown/pull/510
is it ok?

**Comment by wooorm** [comment]
Have you tried it out locally? `npm install && npm test`, that should give you a file, which you can load with your HTML above. Does that work?

**Comment by doveccl** [comment]
@wooorm it works fine on my browser
