### ISSUE TITLE
Component not rendering HTML

### ISSUE THREAD

**Issue by Prottoy2938** [remarkjs/react-markdown#508]
It's not rendering html, like when I put:

`<h1>Hello World</h1>`, it renders  it as `<h1>Hello World</h1>`. It's treating HTML as text.

How I'm using it: 

```jsx
 <ReactMarkdown plugins={[gfm]}><h1>Hello World</h1></ReactMarkdown>
```

What am I doing wrong?

**Comment by wooorm** [comment]
This is documented in the readme
