### ISSUE TITLE
Add support for kbd tag

### ISSUE THREAD

**Issue by aashutoshrathi** [remarkjs/react-markdown#509]
### Subject of the feature

Most of the times MD we want to render contains kbd tags Eg: `<kbd>Some key</kbd>` [<kbd>Some key</kbd>]

### Problem

The current version of the package doesn't render <kbd> tag text as a separate thing.

### Expected behavior

It should render <kbd>Tag</kbd> to a stylized Keyboard button.

### Alternatives

This feature might be needed as most of the times we render MD from GitHub APIs and GitHub support kbd tag.

**Comment by wooorm** [comment]
From the HTML in markdown perspective, this is supported: see the readme.
From the CSS perspective, we’re not injecting styles. There are other projects that do that. See for example https://github.com/remarkjs/react-markdown/issues/100
