### ISSUE TITLE
Rendering issue - Latest version does not render "links" as expected (working fine in 4.3.1)

### ISSUE THREAD

**Issue by IrvingArmenta** [remarkjs/react-markdown#511]
### Subject of the issue

react-markdown not rendering links (anchor tags) as expected. 
I'm updating react-markdown from `^4.3.1` to the latest  `5.0.3` and I'm not seeing the links rendered as `<a>` tags, however it does work as expected on `^4.3.1` , perhaps I'm missing something.

### Your environment

*   **OS**: MacOS Big Sur v11
*   **Packages**: `react-markdown - 5.0.3`
*   **Env**: 
```
npm - 6.14.8
node - v14.15.1
react - ^17.0.1
react-dom - ^17.0.1
```
### Steps to reproduce

https://codesandbox.io/s/react-markdown-debug-forked-u26lh?file=/src/App.js

### Expected behavior

The link should be rendered as a working `<a>` tag.

### Actual behavior

the link is represented just as a plain string.

**Comment by ChristianMurphy** [comment]
react-markdown 5 is now based on commonmark, autolinking ins't part of commonmark, it's a part of gfm, it can be added with `remark-gfm`
https://codesandbox.io/s/react-markdown-debug-forked-vbbrv?
