### ISSUE TITLE
markdownd not redering with styles

### ISSUE THREAD

**Issue by saulpalv** [remarkjs/react-markdown#513]
I running the demo example in create react app and i get a page without any styling present in the demos, am i missing a css or something?

![Captura de pantalla 2020-11-22 141318](https://user-images.githubusercontent.com/19735362/99917352-e44af400-2ccc-11eb-9fa3-1b27bee79677.png)

**Comment by ChristianMurphy** [comment]
@saulpalv please follow the instructions from the issue template
![Screenshot_2020-11-22 remarkjs react-markdown(1)](https://user-images.githubusercontent.com/3107513/99917769-a13e5000-2ccf-11eb-9bac-f309e67de49d.png)
and direct questions to https://github.com/remarkjs/remark/discussions
Thanks for your understanding!
