### ISSUE TITLE
Support blockquotes with &gt;

### ISSUE THREAD

**Issue by Luke-zhang-04** [remarkjs/react-markdown#517]
### Subject of the feature

Describe your issue here.

I run my markdown through `DOMPurify.sanitize` in order to allow some raw HTML tags. Unfortunately, `&gt;` makes the blockquote turn into just a paragraph with `>`. If I disable `allowDangerousHtml`, I can't allow raw HTML tags anymore (I want the Markdown to be close to GitHub's markdown).

### Expected behavior

I think an escaped `&gt;` should be treated the same as an unescaped `>`.

### Alternatives

Maybe have an option to enable or disable it?

Or this idea is unrealistic, or would cause too much breaking change.

**Comment by ChristianMurphy** [comment]
@Luke-zhang-04 this is an [XY Problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem).
You need sanitation of HTML in markdown, the way to do this would be through [rehype-sanitize](https://github.com/rehypejs/rehype-sanitize) which will be supported with #427, you can try out the beta of this at https://github.com/ChristianMurphy/react-remark.
There's a demo of the behavior you're looking for here: https://christianmurphy.github.io/react-remark/?path=/docs/remark-component--mixed-html-sanitized
The behavior should be available in the next major release of react-markdown (coming in a few months, see #428 for context)
