### ISSUE TITLE
escapeHtml does't work properly in react-markdown

### ISSUE THREAD

**Issue by meizibupt** [remarkjs/react-markdown#520]
### Subject of the issue
escapeHtml does't work properly in react-markdown

Describe your issue here.
I am using 5.0.3 and looks like escapeHtml is enabled by default. If my input has special character encoding in the input string, it renders the special character instead of rending the original string.

For example, if the string is "This is euro & # 8 3 6 4;", when it renders, it renders "This is euro €"
This is *not* a place to ask questions.  For that, go to [discussions](https://github.com/remarkjs/remark/discussions)

### Your environment

*   **OS**: 
*   **Packages**: 
*   **Env**: 

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behavior

What should happen?
When there is special character encoding in the input string, it should render the string as is

### Actual behavior

What happens instead?
It renders the special character

**Comment by wooorm** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by meizibupt** [comment]
I added space between the encoding for & # 8 3 4 6, but there should be no space between them

**Comment by wooorm** [comment]
much of the template if not filled out.

See [here for how markdown works](https://commonmark.org/help/). If you want to show code in markdown (e.g., markdown in markdown), you can use `` `backticks around code` ``
