### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>' after upgrading to v5

### ISSUE THREAD

**Issue by piotrblasiak** [remarkjs/react-markdown#523]
### Subject of the issue

After upgrading to v5, webpack build completes successfully but in both safari & chrome I get:

`Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (client.js:25838)
    at Module../node_modules/is-plain-obj/index.js (client.js:25846)
    at __webpack_require__ (client.js:833)
    at fn (client.js:130)
    at Object../node_modules/unified/index.js (client.js:113755)
    at __webpack_require__ (client.js:833)
    at fn (client.js:130)
    at Object../node_modules/react-markdown/lib/react-markdown.js (client.js:76128)
    at __webpack_require__ (client.js:833)
    at fn (client.js:130)`

### Your environment

*   **OS**: macOS Big Sur 11.0.1
*   **Packages**: Webpack 4.44.2, react-markdown 5.0.3
*   **Env**: Chrome 87.0.4280.88, Safari 14.0.1

**Comment by ChristianMurphy** [comment]
@piotrblasiak could you fill out the full issue template? https://github.com/remarkjs/.github/blob/main/.github/ISSUE_TEMPLATE/1-bug.md
This isn't enough information to go off of.

I suspect this is a variation on https://github.com/remarkjs/react-markdown/issues/518, https://github.com/remarkjs/react-markdown/issues/514, and https://github.com/remarkjs/react-markdown/issues/492
but it's hard to tell without more concrete information on your environment and setup.
In particular a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would help.

**Comment by ChristianMurphy** [comment]
Closing this as the issue can't be reproduced.
If you have time, feel free to follow up with more information on reproducing the issue, and this can be revisited.
