### ISSUE TITLE
Checkboxes, Tables & Strikethrough don't work anymore 

### ISSUE THREAD

**Issue by dbuchet** [remarkjs/react-markdown#524]
### Subject of the issue
Updating to 5.0.3 breaks several features:
- Checkboxes are not rendered
- Tables are not rendered
- Strikethrought texts are not rendered

### Your environment

*   **OS**: All
*   **Packages**: react-markdown 5.0.3, React17, CRA 4
*   **Env**: all browsers

### Steps to reproduce
https://codesandbox.io/s/boring-chatterjee-6vt5s
Happens also on playground here: https://remarkjs.github.io/react-markdown/

Thanks!

**Comment by ChristianMurphy** [comment]
These features are part of GitHub Flavored Markdown (GFM), which is now a plugin.
This is documented in the changelog https://github.com/remarkjs/react-markdown/blob/main/changelog.md#upgrade-remark-parse
and an example of enabling these features is shown in the readme https://github.com/remarkjs/react-markdown#use

**Comment by wooorm** [comment]
See the readme, the change log, or recently closed issues

**Comment by dbuchet** [comment]
Oh sorry didn't notice. Thanks for your quick reply
