### ISSUE TITLE
Table is not shown properly

### ISSUE THREAD

**Issue by ppascualv** [remarkjs/react-markdown#525]
### Subject of the issue

As you can see in the example attached to the readme https://remarkjs.github.io/react-markdown/ tables are not shown properly this is something that has been broken recently.

### Expected behavior

It should be shown as a table.

### Actual behavior

It is shown as inline text

**Comment by ChristianMurphy** [comment]
Table support is explained in the changelog and in the readme.
As well as explained in the previous questions asked
https://github.com/remarkjs/react-markdown/issues/524
https://github.com/remarkjs/react-markdown/issues/516
https://github.com/remarkjs/react-markdown/issues/493
