### ISSUE TITLE
Tables not working on website

### ISSUE THREAD

**Issue by lorensr** [remarkjs/react-markdown#526]
### Subject of the issue

![image](https://user-images.githubusercontent.com/251288/102928091-226f3b00-4466-11eb-9582-5e2b403253dc.png)

### Your environment

*   **OS**: macOS 11.1
*   **Browser**: 

![image](https://user-images.githubusercontent.com/251288/102928021-08cdf380-4466-11eb-9a25-273f9bd7a2d7.png)

### Steps to reproduce

Visit https://remarkjs.github.io/react-markdown/

**Comment by ChristianMurphy** [comment]
Tables, and all GFM have moved to a plugin.
You can see an example of usage here https://github.com/remarkjs/react-markdown#use
and the note in the release notes here: https://github.com/remarkjs/react-markdown/blob/main/changelog.md#500---2020-10-19

The website accurately reflects that by default, react-markdown follows the CommonMark standard, which does not have Tables.

**Comment by lorensr** [comment]
I think it would be helpful to make note of that on the website

**Comment by wooorm** [comment]
@lorensr I think you’re right that the demo on the website should use GFM, and describe that tables/strikethrough etc are enabled through a plugin. A new issue or even a PR would be awesome!

**Comment by chloerice** [comment]
> Tables, and all other GFM have moved to a plugin. You can see an example of usage with tables here: https://github.com/remarkjs/react-markdown#use and the note in the release notes here: https://github.com/remarkjs/react-markdown/blob/main/changelog.md#500---2020-10-19
> 
> The website accurately reflects that by default, react-markdown follows the CommonMark standard, which does not have Tables.

[Here's the direct link](https://github.com/remarkjs/react-markdown#use-a-plugin) to the example referencing the `remark-gfm` plugin illustrating table parsing

**Comment by georgeportillo** [comment]
+1
