### ISSUE TITLE
html tag followed immediately by markdown text results in a single html callback

### ISSUE THREAD

**Issue by starpit** [remarkjs/react-markdown#533]
### HTML followed immediately by markdown text results in single html callback

```markdown
<img src="whatever">
Some **markdown** text
```

Results in a single `html` callback that conjoins the two; i.e. we receive no callback for the parsed markdown text, instead it is bundled, as plain text, in the props.value of the `html` callback.

Whereas

```markdown
<img src="whatever">

Some **markdown** text
```

yields the expected behavior.

### Your environment

*   **OS**: macOS 10.15.7
*   **Packages**: remark-parse@9.0.0
*   **Env**: electron 10

plugins: `[gfm]`

### Steps to reproduce

See above

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behavior

Two separate callbacks.

### Actual behavior

One callback.

**Comment by ChristianMurphy** [comment]
That is how markdown works.
Both in the commonmark soect: https://spec.commonmark.org/dingus/?text=%3Cimg%20src%3D%22whatever%22%3E%0ASome%20**markdown**%20text and https://spec.commonmark.org/0.29/#example-118
and on github flavored markdown spec:

```markdown
<img src="whatever">
Some **markdown** text
```

<img src="whatever">
Some **markdown** text

---

the empty newline is needed to leave the html block and go back to markdown.
