### ISSUE TITLE
react-markdown crushes if <li > element has spaces before it

### ISSUE THREAD

**Issue by gilisho** [remarkjs/react-markdown#535]
### Subject of the issue

Issues with `<li >` element with a space at the beginning.
This is the problematic snippet:
```
  <li>hey
  
  </li>
```

### Your environment

*   **Packages**: `react-markdown` version 5  is affected. See in the live demo as well.

### Steps to reproduce

`remark`: https://astexplorer.net/#/gist/19a843b97e350aaa80733876c81c1bed/60c88087318ea19410d99d798883b24a7733c520
`react-markdown`: https://codesandbox.io/s/react-markdown-debug-forked-o5rjw?file=/src/App.js

### Expected behavior

What should happen?
This text:
```
  <li>hey
  
  </li>
```

Should be rendered like in Github:

  <li>hey
  
  </li>

### Actual behavior

App crushes when putting this text in `react-markdown`, as can be seen from the link.
Even when adding the gfm plugin, it does not parse like Github:
https://codesandbox.io/s/react-markdown-debug-forked-o5rjw?file=/src/App.js

**Comment by ChristianMurphy** [comment]
This should be resolved by #427, in the meantime this is rendered as expected by `react-remark` https://github.com/remarkjs/react-remark (live demo: https://remarkjs.github.io/react-remark/?path=/story/remark-component--mixed-html-sanitized) which could be used as an alternative.
Closing as a duplicate, to follow along with progress, watch issues #385 and #302.

**Comment by gilisho** [comment]
Are you sure this is expected?
![image](https://user-images.githubusercontent.com/40733156/105378999-10271f00-5c15-11eb-80b0-52ec743cccae.png)

From the image above I thought `remark` parses it as two elements, which I think is an incorrect parsing.
and thanks!

**Comment by ChristianMurphy** [comment]
yes, from the CommonMark reference implementation https://spec.commonmark.org/dingus/?text=%20%20%3Cli%3Ehey%0A%20%20%0A%20%20%3C%2Fli%3E%0A
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document xmlns="http://commonmark.org/xml/1.0">
  <html_block>  &lt;li&gt;hey</html_block>
  <html_block>  &lt;/li&gt;</html_block>
</document>
```

there are two HTML blocks, which matches the described spec as well https://spec.commonmark.org/0.29/#html-blocks
