### ISSUE TITLE
magnet links parse as href="javascript:void(0)"

### ISSUE THREAD

**Issue by ExtraHash** [remarkjs/react-markdown#537]
### magnet links parse as href="javascript:void(0)"

Magnet links do not work as expected. Instead of the href being set correctly, the href is set to "javascript:void(0)". 

### Your environment

*   **OS**: macOS Catalina 10.15.7, ubuntu linux 20.04
*   **Packages**: react-markdown 5.0.3
*   **Env**: browser

### Steps to reproduce

Here's a simple reproduction of the behavior.

code: https://github.com/ExtraHash/react-markdown-repro
view in browser: https://extrahash.github.io/react-markdown-repro/

### Expected behavior

The library correctly detects and sets the href for magnet links.

### Actual behavior

The href is set to "javascript:void(0)".

### Possible Fix
I was able to work around this temporarily by doing something like this in my custom link renderer (quite messy but it works for now)

```
render() {
    // hacky way to get around bug in magnet link parsing
    const url = (this.props as any).children[0]?.props.children as string | undefined;
    
    return (
        <a href={url}>{this.props.children}</a>
    )
}

```

**Comment by ChristianMurphy** [comment]
This behavior is documented in the readme

> `transformLinkUri` (`(uri) => string`, default: `./uri-transformer.js`, optional)
> URL to use for links. The default allows only http, https, mailto, and tel, and is available at 
> ReactMarkdown.uriTransformer. Pass `null` to allow all URLs. See security

https://github.com/remarkjs/react-markdown#api

and it can be disabled with `null`
https://codesandbox.io/s/react-markdown-debug-forked-l2p90
