### ISSUE TITLE
'strikethrough' or 'strike' not working in 'allowedTypes' when using remark-gfm

### ISSUE THREAD

**Issue by Lillebo** [remarkjs/react-markdown#538]
### Subject of the issue

Adding `strikethrough` or `strike` to `allowedTypes` doesn't seem to work, despite using [`remark-gfm`](https://github.com/remarkjs/remark-gfm/).

```
const allowedTypes = [
	'paragraph',
	'text',
	'bold',
	'strikethrough',
	'strike',
	'emphasis',
	'strong',
	'blockquote',
	'image',
	'link',
	'linkReference'
];

<Markdown allowedTypes={allowedTypes} plugins={[gfm]}>{source}</Markdown>
```

⬆️ This config still renders any `~something~` or `~~something~~` as blank.

### Your environment

*   **OS**: macOS Big Sur 11.1
*   **Packages**: `"react-markdown": "^5.0.3"` with `"remark-gfm": "^1.0.0"`

**Comment by ChristianMurphy** [comment]
As noted in the readme https://github.com/remarkjs/react-markdown#appendix-b-node-types, the node type is `delete`.
https://codesandbox.io/s/react-markdown-debug-forked-lb7vs

**Comment by jordrake** [comment]
Just a heads up incase anybody runs into this problem in the latest version (9.0.1). It's changed and now you need to add `'del'` to `allowedElements`
