### ISSUE TITLE
Custom link renderer does not support a title prop

### ISSUE THREAD

**Issue by johnclary** [remarkjs/react-markdown#539]
### Custom link renderer does not support a `title` prop

Thank you for your work on this excellent package!

While trying to create a custom link renderer, it seems the `title` prop is undefined. Only `href` is supported.

### Your environment

*   **OS**: macOS Catalina 10.15
*   **Packages**: react-markdown 5.0.3
*   **Env**: Chrome v87

### Steps to reproduce

```javascript
const markdownRenderers = {
  link: ({ href, title }) => {
    console.log(title);
    // undefined
    return <span>I would like the link title text here</span>;
  },
};

const MyComponent = () => {
  const children = "[My Link](http://mylink.com)";
  return (
    <ReactMarkdown
      renderers={markdownRenderers}
      escapeHtml={false}
      children={description}
    />
  );
};

```

I've been able to work around this by parsing the text value from the child node:

```javascript
const markdownRenderers = {
  link: ({ children }) => {
    return <span>The link text is: {children[0].props.value}</span>;
  },
};
```

### Expected behavior

I *believe* the expected behavior is that it should be possible to destructure `{ href, text, target }` from the renderer args, but maybe I'm wrong!

### Actual behavior

Only the `href` arg can be accessed from the renderer function.

**Comment by johnclary** [comment]
Updated to reflect my best interpretation of the docs and reproduced on v5.0.3

**Comment by ChristianMurphy** [comment]
@johnclary I think the confusion is around markdown structure

in a link

```
[alpha](https://bravo.xyz "charlie")
 ^^^^^^^  ^^^^^^^^^^^^^^^ ^^^^^^^^^
children       href         title
```

You haven't set a title, so there isn't a title property.
here is the documentation for mdast link: https://github.com/syntax-tree/mdast#link

here is an example showing how title works: https://codesandbox.io/s/react-markdown-debug-forked-uog93

**Comment by johnclary** [comment]
Indeed the confusion is mine. Thanks!
