### ISSUE TITLE
Support custom link attributes through markdown

### ISSUE THREAD

**Issue by codler** [remarkjs/react-markdown#540]
### Subject of the feature

Support custom attributes through markdown

Example syntax

> `[link](url){:target="_blank"}`

### Problem

https://stackoverflow.com/a/4705645/304894
Im my case I want to be able to set different `rel` attribute from markdown

### Expected behavior

I would get the attributes from renderers

**Comment by ChristianMurphy** [comment]
By default react-markdown supports [CommonMark](https://commonmark.org/) only.
However, syntax extensions/plugins can be used to add new syntax features https://github.com/remarkjs/remark/blob/main/doc/plugins.md
The particular syntax you are looking for appears to be https://github.com/arobase-che/remark-attr, which can work with react-markdown but needs an update to do so https://github.com/arobase-che/remark-attr/issues/22

**Comment by david-sharer** [comment]
For anyone else who runs into this, I got this working with a custom component for my scenario (I needed call-to-action button-links). All buttons that have \<strong> as the first-child `[**text here**](... "custom:attribute title text")` are rendered as buttons and their `title` text is parsed for custom attribute strings. Highly limited, but worked for me!
![image](https://user-images.githubusercontent.com/26589071/117559364-72c3ef80-b039-11eb-8f11-fff4f1a1d538.png)


```typescript
// component rendering
import React, { ReactElement } from "react";
import ReactMarkdown from "react-markdown";
import { Components, ReactBaseProps, ReactMarkdownProps } from "react-markdown/src/ast-to-react";
import remarkGfm from "remark-gfm";
import { first, fromPairs } from "lodash";
import { Button } from "@material-ui/core";

const components: Components = {
  a: ({
    node,
    children,
    href,
    title,
    ...props
  }: ReactBaseProps & ReactMarkdownProps & { href: string; title: string }) => {
    // if the first child of the button is a bold element, make this a CTA button
    if ((first(children) as ReactElement)?.type === "strong") {
      const splitTitle = title.split(' ');
      const titleAttrEntries = splitTitle.filter(t => t.includes(':'));
      const remainingTitleEntries = splitTitle.filter(t => !t.includes(':'));
      const finalTitle = remainingTitleEntries.join(' ');
      const titleAttrPairs = titleAttrEntries.map(te => te.split(':'))
      const titleAttrs = fromPairs(titleAttrPairs);
      return (
        <Button variant="contained" href={href} title={finalTitle} {...props} {...titleAttrs}>
          {children}
        </Button>
      );
    }

    return <a href={href} title={title} children={children} {...props}></a>;
  },
};

export function renderMarkdown(markdown: string) {
  return (
    <ReactMarkdown
      plugins={[remarkGfm]}
      children={markdown}
      components={components}/>
  );
}
```

```markdown
<!-- markdown -->
[Regular Link](/where_to_go/)

[**CTA Button Link**](/where_to_go/ "color:primary any:attribute things without colons will be treated as the title")
```

output
![image](https://user-images.githubusercontent.com/26589071/117559345-5922a800-b039-11eb-9436-7379b4ae76a2.png)

**Comment by Ram-sys179** [comment]
@david-sharer Looks like the `ReactBaseProps` is deprecated??

**Comment by yuri2peter** [comment]
> {:target="_blank"}



> For anyone else who runs into this, I got this working with a custom component for my scenario (I needed call-to-action button-links). All buttons that have \<strong\> as the first-child `[**text here**](... "custom:attribute title text")` are rendered as buttons and their `title` text is parsed for custom attribute strings. Highly limited, but worked for me! ![image](https://user-images.githubusercontent.com/26589071/117559364-72c3ef80-b039-11eb-8f11-fff4f1a1d538.png)
> 
> ```ts
> // typescript component rendering
> import React, { ReactElement } from "react";
> import ReactMarkdown from "react-markdown";
> import { Components, ReactBaseProps, ReactMarkdownProps } from "react-markdown/src/ast-to-react";
> import remarkGfm from "remark-gfm";
> import { first, fromPairs } from "lodash";
> import { Button } from "@material-ui/core";
> 
> const components: Components = {
>   a: ({
>     node,
>     children,
>     href,
>     title,
>     ...props
>   }: ReactBaseProps & ReactMarkdownProps & { href: string; title: string }) => {
>     // if the first child of the button is a bold element, make this a CTA button
>     if ((first(children) as ReactElement)?.type === "strong") {
>       const splitTitle = title.split(' ');
>       const titleAttrEntries = splitTitle.filter(t => t.includes(':'));
>       const remainingTitleEntries = splitTitle.filter(t => !t.includes(':'));
>       const finalTitle = remainingTitleEntries.join(' ');
>       const titleAttrPairs = titleAttrEntries.map(te => te.split(':'))
>       const titleAttrs = fromPairs(titleAttrPairs);
>       return (
>         <Button variant="contained" href={href} title={finalTitle} {...props} {...titleAttrs}>
>           {children}
>         </Button>
>       );
>     }
> 
>     return <a href={href} title={title} children={children} {...props}></a>;
>   },
> };
> 
> export function renderMarkdown(markdown: string) {
>   return (
>     <ReactMarkdown
>       plugins={[remarkGfm]}
>       children={markdown}
>       components={components}/>
>   );
> }
> ```
> 
> ```
> 
> [Regular Link](/where_to_go/)
> 
> [**CTA Button Link**](/where_to_go/ "color:primary any:attribute things without colons will be treated as the title")
> ```
> 
> output ![image](https://user-images.githubusercontent.com/26589071/117559345-5922a800-b039-11eb-9436-7379b4ae76a2.png)

Very useful, thanks
