### ISSUE TITLE
`uri-transformer.js` link on README is 404

### ISSUE THREAD

**Issue by kenzoukenzou** [remarkjs/react-markdown#542]
### Subject of the issue

Hi, I found 404 error at README.
`./uri-transformer.js` link on README is 404 not found.

https://github.com/remarkjs/react-markdown/blob/v5/src/uri-transformer.js

### Your environment

*   **OS**: macOS Catalina v10.15.6
*   **Packages**: 
*   **Env**: 

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

- click [here](https://github.com/remarkjs/react-markdown/blob/v5/src/uri-transformer.js)
- 404 Not found page of GitHub appears

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behavior

What should happen?

is [this](https://github.com/remarkjs/react-markdown/blob/main/src/uri-transformer.js) correct link?

### Actual behavior

What happens instead?

[This](https://github.com/remarkjs/react-markdown/blob/v5/src/uri-transformer.js) is used in README.md.

**Comment by wooorm** [comment]
yup, I think the link you used in `Expected` is the correct one!

**Comment by kenzoukenzou** [comment]
@wooorm Thank you for reply. I will fix it!
