### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by mikkelbiz** [remarkjs/react-markdown#545]
### Subject of the issue

./node_modules/@uiw/react-markdown-preview/lib/esm/styles/markdowncolor.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@uiw/react-markdown-preview/lib/esm/index.js)

### Your environment

*   **OS**: Windows 10 running WSL Debian 10
*   **Packages**:
*  `    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-solid-svg-icons": "^5.15.1",
    "@fortawesome/react-fontawesome": "^0.1.14",
    "@tailwindcss/typography": "^0.3.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "@uiw/react-md-editor": "^2.0.3",
    "autoprefixer": "^10.0.4",
    "axios": "^0.21.1",
    "cssnano": "^4.1.10",
    "moment": "^2.29.1",
    "next": "latest",
    "postcss": "^8.1.10",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-markdown": "^5.0.3",
    "react-moment": "^1.1.1",
    "tailwindcss": "^2.0.2",
    "tailwindcss-markdown": "^1.0.1"`
*   **Env**: NPM Version 6.14.9

### Steps to reproduce

Really just need to install it on NextJS, its a policy they enforce.

### Expected behavior

It should be able to build properly, but because of the import of global CSS it does not.

### Actual behavior

info  - Creating an optimized production build  
Failed to compile.

./node_modules/@uiw/react-markdown-preview/lib/esm/styles/markdowncolor.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@uiw/react-markdown-preview/lib/esm/index.js

More info [https://github.com/vercel/next.js/issues/19936](https://github.com/vercel/next.js/issues/19936)

**Comment by ChristianMurphy** [comment]
@mikkelbiz two things:
1. `react-markdown` doesn't add any CSS, any CSS would be added by a downstream package or an implementer.
2. from your stacktrace, the issue is coming from `node_modules/@uiw/react-markdown-preview/lib/esm/index.js` issues with this package can be logged to https://github.com/uiwjs/react-markdown-preview/issues

**Comment by ChristianMurphy** [comment]
Also you may want to checkout https://github.com/uiwjs/react-markdown-preview/issues/38 which discusses Next support and includes an example.

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341
