### ISSUE TITLE
Changing `renderers` to `components`

### ISSUE THREAD

**Issue by wooorm** [remarkjs/react-markdown#549]
Currently, `react-markdown` allows users to define element types (i.e., tag names such as `'br'`, a functional component, a class, etc) for *markdown* constructs (`link`, `delete`, `break`, etc).

This has problems:

*   Users don’t know about markdown names (`thematicBreak`) or markdown peculiarities (that there are fully formed links *and* link references, the paragraphs in spread lists don’t show up)
*   It makes it impossible to support rehype plugins, which work *after* markdown
*   Markdown treats raw HTML in markdown as a black box, making parsing it hard. Most of the open issues are about HTML parsing. Supporting rehype plugins comes with `rehype-raw`, which is proper solution

I think it would be better to switch to allowing users to define element types for *HTML* constructs instead, as that solves the three above issues. I call it `components` and suggest using that field, because I like that name better, and because it aligns with `remark-react`, `rehype-react`, and `@mdx-js/mdx`.

Having both `renderers` and `components` is not ideal:

*   Supporting two ways to do something is a bad user experience, so it would be temporal and we’d suggest moving to `components`
*   It’s not just this one option, also `allowedTypes`, `disallowedTypes`, and `allowNode` would also come with an mdast (remark) and hast (rehype) version. What if they conflict?
*   Figure out the original shape of an mdast node at the hast/rehype stage, which is passed as `node` to the renderer and would be needed to detect other fields passed to renderers, is complex. And what about a `linkReference`?

Given the complexity of supporting both and that it’d be temporary anyway, I don’t see it as viable to support *both* `renderers` and `components` for one (or two) versions, and would prefer to rip the band aid off, provided that there are clear docs on how to upgrade.

**Comment by MuYunyun** [comment]
@wooorm  hi, if I want to write React in .md file, is it correct to use @mdx-js/mdx in `components` props?

**Comment by wooorm** [comment]
If you mean JSX in markdown, yes, `mdx-js/mdx` and `xdm` do that. `react-markdown` does not do that.
