### ISSUE TITLE
Math renderer not firing always uses inlineMath

### ISSUE THREAD

**Issue by KieranDotCo** [remarkjs/react-markdown#550]
### Subject of the issue
I'm trying to render math in a block. Using the example from the docs I can get inline math to work but I can't get block math to work.

### Steps to reproduce
https://codesandbox.io/s/eager-kilby-u6hq9?file=/src/App.js:228-364

See in the console that `'inline'` is returned from the renderer and not `'block'`

### Expected behavior
I would expect this text
`Inline: The lift coefficient ($C_L$) is a dimensionless coefficient.  \n Block: $${l}_B={r}_{03}-{r}_{02} $$ $${l}_A={r}_{02}-{r}_{01}$$`

To return
![Screenshot 2021-02-22 at 10 57 32](https://user-images.githubusercontent.com/4819071/108699157-ccb61e00-74fc-11eb-9d94-8f106a166ab2.png)

### Actual behavior
But instead, I get
![Screenshot 2021-02-22 at 10 57 36](https://user-images.githubusercontent.com/4819071/108699173-d475c280-74fc-11eb-9df9-ec18a096939e.png)

**Comment by wooorm** [comment]
Inline code in markdown can use one or more ticks: ` `` like so `` `, (inline) math here is the same.

To create a block, use two dollars *and* lines around them:

```
$$
C_L
$$
```

^-- does what you’re looking for

**Comment by KieranDotCo** [comment]
> Inline code in markdown can use one or more ticks: `` `` like so `` ``, (inline) math here is the same.
> 
> To create a block, use two dollars _and_ lines around them:
> 
> ```
> $$
> C_L
> $$
> ```
> 
> ^-- does what you’re looking for

Ah! Perfect thanks @wooorm 👍
