### ISSUE TITLE
Markdown table doesn't work in versions 5.0.1 - 5.0.3

### ISSUE THREAD

**Issue by jvermeir** [remarkjs/react-markdown#555]
### Subject of the issue

Markdown tables aren't rendered correctly. The markdown code is rendered without any formatting. 

### Your environment

*   **OS**: osx 11.2.3
*   **Packages**: react-markdown, versions 5.0.1, 5.0.2, 5.0.3
*   **Env**: npm 6.14.10, node v12.20.1, firefox 86 and chrome 89.0.4389.82

### Steps to reproduce

Create app: `npx create-react-app react-autocomplete-tutorial`
Add `"react-markdown": "5.0.3"` as a dependency. 
Copy this code in App.js 
```
export const Markdown = ({renderers, ...props}) => (
    <ReactMarkdown
        unwrapDisallowed
        renderers={{
            thematicBreak: () => <p color="lightBlue"/>,
            table: ({children}) => <table style={{borderSpacing: 0, borderCollapse: "collapse"}}>{children}</table>,
            tableCell: ({isHeader, children}) =>
                isHeader ? (
                    <th style={{border: "1px solid grey"}}>{children}</th>
                ) : (
                    <td style={{border: "1px solid grey", padding: 5}}>{children}</td>
                ),
            ...renderers
        }}
        {...props}
    />
);

const md = `# chapter

above table

| column heading |
| -------------- |
| line in table |

below table
`;
```

### Expected behavior

Properly rendered table like this

<img width="311" alt="tableFormattedAsExpectedInV4 3 1" src="https://user-images.githubusercontent.com/119214/110999688-0dc58380-8381-11eb-8bd0-c1f846a38fca.png">
:
### Actual behavior

Markdown table commands are show:
```
| column heading | | -------------- | | line in table |
```

**Comment by wooorm** [comment]
Please read the readme and the issues

**Comment by ChristianMurphy** [comment]
https://unifiedjs.com/learn/recipe/remark-table/

**Comment by jvermeir** [comment]
Thanks Christian, adding 

`import gfm from "remark-gfm";

export const Markdown = ({renderers, ...props}) => (
    <ReactMarkdown
        plugins={[gfm]}
`

solves my problem.

**Comment by mdaz78** [comment]
```
---
id: code-structure
title: Code Structure
sidebar_label: Code Structure
---
```

How do I render something like this as github renders it. React markdown with the `react-gfm` plugin renders it as `h2` but github renders it as `table`

## Github Output
<img width="495" alt="Screenshot 2022-05-25 at 5 48 15 PM" src="https://user-images.githubusercontent.com/4301878/170260171-6275f45b-2986-46fe-baf7-2c9f0ae83fb6.png">


## React markdown with react-gfm plugin output
<img width="659" alt="Screenshot 2022-05-25 at 5 48 59 PM" src="https://user-images.githubusercontent.com/4301878/170260329-7e3e58b8-e183-465e-9636-22f922f58d03.png">


## My Code
```React
<ReactMarkdown remarkPlugins={[remarkGfm]}>{content}</ReactMarkdown>
```

**Comment by ChristianMurphy** [comment]
@mdaz78 that isn't a table, it is a frontmatter.
frontmatter isn't universally supported by GitHub, if you paste your example into a github issue/comment directly you'll see that the expected output is in fact a header for GFM.

If you want a different output https://github.com/remarkjs/remark-frontmatter can be used.
If you have questions about frontmatter, feel free to start a discussion https://github.com/orgs/remarkjs/discussions
