### ISSUE TITLE
Markdown Tables

### ISSUE THREAD

**Issue by Patrick-W-McMahon** [remarkjs/react-markdown#556]
### Subject of the feature

to add markdown tables 

Example:
```
|Header1 |Header2  | Header3|
--- | --- | ---
|data1|data2|data3|
|data11|data12|data13|
```

### Problem

treated like normal text

### Expected behavior

render a table

|Header1 |Header2  | Header3|
--- | --- | ---
|data1|data2|data3|
|data11|data12|data13|

**Comment by ChristianMurphy** [comment]
Please see the readme, the changelog, the playground, and/or https://unifiedjs.com/learn/recipe/remark-table all explain how to enable tables
