### ISSUE TITLE
HTML parser: parsing HTML comments

### ISSUE THREAD

**Issue by admasodaniel** [remarkjs/react-markdown#558]
### HTML parser: doesn’t work well while parsing HTML comments with 3 dashes at the beginning of the MD.

trying to render this MD:
```
<!--- Some comment --->

# Hello world
```

### Expected behavior

Should render the Hello world as H1.

### Actual behavior

The parser doesn’t work.

example:
https://codesandbox.io/s/react-markdown-forked-f91yz?file=/src/App.js

**Comment by ChristianMurphy** [comment]
This is another version of https://github.com/remarkjs/react-markdown/issues/454
This will be resolved by https://github.com/remarkjs/react-markdown/issues/427 or you can use https://github.com/remarkjs/react-remark which is a related project which supports remark+rehype already.
