### ISSUE TITLE
script tag not work when using htmlParser plugin

### ISSUE THREAD

**Issue by maltoze** [remarkjs/react-markdown#562]
### Subject of the issue

`script` tag not work when using htmlParser plugin

### Your environment

*   **OS**: 
*   **Packages**: 
*   **Env**: 

### Steps to reproduce

https://codesandbox.io/s/admiring-river-5ekyn?file=/src/App.js

```jsx
import React from "react";
import ReactMarkdown from "react-markdown";
import htmlParser from "react-markdown/plugins/html-parser";

const parseHtml = htmlParser({
  isValidNode: () => true
});

const content = `
This is some paragraph text. 
  - This is a bullet point 
 - This is another one 
 - And a third 

<script>
console.log('hi');
alert('script');
</script>
`;

export default function App() {
  return (
    <div className="App">
      <ReactMarkdown
        source={content}
        escapeHtml={false}
        astPlugins={[parseHtml]}
      />
    </div>
  );
}
```

### Expected behavior

`script` tag should be work?

### Actual behavior

`script` tag not work

**Comment by wooorm** [comment]
How should script tags work in react? That's a massive security vulnerability
