### ISSUE TITLE
Remark-directive integration (Link to working solution included)

### ISSUE THREAD

**Issue by rjantoine** [remarkjs/react-markdown#564]
### Subject of the feature

Remark-directive integration (Link to working solution included)

### Problem

There is no smooth way to add custom markdown directives without using MDX, which is not client friendly.

### Expected behavior

I would love to see this integrated into your existing code, example <ReactMarkdownWithDirective /> or including it in your documentation as an available plugin.

### Description
I created the [react-markdown-remark-directive](https://github.com/rjantoine/react-markdown-remark-directive) plugin which neatly converts `:MyCustomDirective[myValue]{foo=bar}` to `<MyCustomDirective value="myValue" foo="bar" />`. Then, simply pass the MyCustomDirective component as a plugin argument.

```jsx
import ReactMarkdown from 'react-markdown'
import rmDirective from 'react-markdown-remark-directive'
import MyCustomDirective from './components/MyCustomDirective/'

<ReactMarkdown plugins={[[rmDirective.plugin, {[MyCustsomDirective]}]]} source=":MyCustomDirective[myValue]{foo=bar}" />
```

Note that textDirective and leafDirective work great, containerDirective is not currently supported as the children are not being rendered, value is simply being pulled form children[0] and container Directive has nested children.

**Comment by wooorm** [comment]
Cool!

P.S. `MyCustsomDirective` contains a typo.

> I would love to see this integrated into your existing code, example or including it in your documentation as an available plugin.

https://github.com/remarkjs/react-markdown/pull/563 brings us much closer to that.

---

Your project, and also #563, solve this nicely IMO? Is there something else you’re expecting or would like to see?

**Comment by rjantoine** [comment]
This looks good to me. However, I noticed in my project that I should be using astToReact instead of createElement so that the children are rendered as well.

Thanks

Robert Antoine

**Comment by wooorm** [comment]
ok, will close this then!
Keep an eye out for the next major, which’ll change this all a bit!

**Comment by rjantoine** [comment]
I updated my code to version 1.1.0 and use ‘parsedHtml’ and ‘virtualHtml’ in order for the children to be properly parsed.

However, I think the best way to solve this would be to change ast-to-react.js

Line 12
- var renderer = options.renderers[node.type]
+ var renderer = options.renderers[node.type] || options.renderers[node.name] || ( options.skipHtml ? ’text' : ‘virtualHtml’)

Line 76
+ case: ‘textDirective’:
+ case: ‘leafDirective’:
+ case: ‘containerDirective’:
+	if(renderer == ‘virtualHtml’) {
+		node.type = ‘virtualHtml'
+		node.tag = node.name
+	} else {
+		node.type = ‘parsedHtml'
+		node.element = astToReact(node, opts)
+	}

I haven’t tested it but it should work nicely and remove the need for my plugin.

Thanks,

Robert Antoine

**Comment by cassus** [comment]
Hi!
Is this use case somehow supported after the change from renderers to components?

**Comment by IGassmann** [comment]
I've built a package for this use case: [IGassmann/remark-directive-rehype](https://github.com/IGassmann/remark-directive-rehype). Check out the [react-markdown example](url) for how to use it.
