### ISSUE TITLE
CRACO ignores certain markdown format

### ISSUE THREAD

**Issue by theshivamgupta** [remarkjs/react-markdown#565]
I wanted to use tailwindcss in one of my projects, I created my react project with create-react-app for which CRACO configurations is required.
We need to change package.json scripts for it to work but after doing that certain markdown formats stopped working like Bold, BlockQuote.

```Before CRACO package.json```
```js
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "now-build": "react-scripts build",
    "deploy": "npx now --target production"
  }
```

```After Craco```
```js
"scripts": {
    "start": "craco start",
    "build": "craco build",
    "test": "craco test",
    "eject": "react-scripts eject",
  },
```

```craco.config.js```
```js
module.exports = {
  style: {
    postcss: {
      plugins: [require("tailwindcss"), require("autoprefixer")],
    },
  },
};
```

**Comment by ChristianMurphy** [comment]
See https://github.com/remarkjs/react-markdown/issues/505 tailwind adds styles which makes elements like bold and blockquote look different.
react-markdown is still parsing as expected, and react-markdown does not provide styles.
Styles on the tailwind side can be made to work better with markdown using typography and prose, as noted in https://github.com/remarkjs/react-markdown/issues/505#issuecomment-724911501
