### ISSUE TITLE
allowedElements prop not working?

### ISSUE THREAD

**Issue by lid3rs** [remarkjs/react-markdown#569]
V: "react-markdown": "^5.0.3",

```
 <ReactMarkdown allowedElements={['p', 'em']}>{content}</ReactMarkdown>
```

```
{content: `## Hello, *world*!`}
```
Prints 

```
<h2>Hello, <em>world</em>!</h2>
```
Or am I missing something in syntax?

**Comment by ChristianMurphy** [comment]
> :warning:  Note: the below readme is for the upcoming release of react-markdown@6.0.0. See the last released readme (5.0.3) here » https://github.com/remarkjs/react-markdown/tree/22bb78747d768181cb9ea8711b5e13c3768921d8#readme

`allowedElements` is a new prop in v6, in v5 the rough equivalent is `allowNode`
