### ISSUE TITLE
Inline Syntax-highlight does not work properly.

### ISSUE THREAD

**Issue by shuent** [remarkjs/react-markdown#573]
@jahirfiquitiva
> @lonkaars @wooorm
> 
> Would you mind helping me to fix this? I started using React Syntax Highlighter and now the inline code looks like this:
> 
> <img alt="Shot 2021-04-15 at 03-28-41@2x" width="939" src="https://user-images.githubusercontent.com/10360816/114839009-e6f0d780-9d9a-11eb-8885-b2e4fad34d7b.png">
> 
> But I was expecting it to look like this
> <img alt="Shot 2021-04-15 at 03-29-02@2x" width="377" src="https://user-images.githubusercontent.com/10360816/114839055-f1ab6c80-9d9a-11eb-8fd7-3a5289a53812.png">
> 
> Here's the code snippets:
> 
> ```ts
> const CodeRenderer = (props: any) => {
>   return <SyntaxHighlighter language={props.language} style={dracula}>
>     {props.children}
>   </SyntaxHighlighter>;
> };
> ```
> 
> ```ts
> <ReactMarkdown
>   plugins={[gfm]}
>   components={{
>     // @ts-ignore
>     // eslint-disable-next-line react/display-name
>     code: ({ node, ...props }) => <CodeRenderer {...props} />,
>   }}>
>   {mdBody}
> </ReactMarkdown>
> ```

same bug using in Next.js.

Previous version react-markdown@5.0.3 worked as expected.

It seams like in `code` tag, unnecessarly broken line at last line.

my md file. Sorry for not English, but it doesn't matter.
```md

手元でできた画面を確認してみてください。デフォルトの画面が立ち上がります。

\```sh
npm start
\```

プロジェクトフォルダの中の、基本的には`src/`の中にコードを書いていくことになります。
それぞれの初期ファイルの説明は公式ページを読んでみてください。
```

result: 
![Screen Shot 2021-04-16 at 19 09 41](https://user-images.githubusercontent.com/12546161/115010223-1cefa200-9ee8-11eb-86d1-90e16eda95dc.png)

_Originally posted by @shuent in https://github.com/remarkjs/react-markdown/issues/570#issuecomment-821069455_

**Comment by jahirfiquitiva** [comment]
I'd suggest not creating new issues if you already posted this in a comment.

Anyways, as mentioned in another comment in the other issue, just copy and paste the example from readme

https://github.com/remarkjs/react-markdown#use-custom-components-syntax-highlight

**Comment by wooorm** [comment]
Described in the readme!

**Comment by SalahAdDin** [comment]
The next error, could it be related to this?
``shell
Warning: Received `true` for a non-boolean attribute `inline`.

If you want to write it to the DOM, pass a string instead: inline="true" or inline={value.toString()}.
    in code (at content.js:75)
    in CodeBlock (created by ReactMarkdown)
    in a (created by ReactMarkdown)
    in p (created by ReactMarkdown)
    in ReactMarkdown (at content.js:155)
    in Content (at body.js:26)
    in section (created by ForwardRef(Typography))
    in ForwardRef(Typography) (created by WithStyles(ForwardRef(Typography)))
    in WithStyles(ForwardRef(Typography)) (at body.js:18)
    in DynamicZone (at body.js:55)
    in Body (at [slug].js:112)
    in main (created by ForwardRef(Container))
    in ForwardRef(Container) (created by WithStyles(ForwardRef(Container)))
    in WithStyles(ForwardRef(Container)) (at layout.js:10)
    in Layout (at [slug].js:49)
    in Post (at _app.js:55)
    in ThemeProvider (at _app.js:52)
    in FolioApp (created by AppWithTranslation)
    in I18nextProvider (created by AppWithTranslation)
    in AppWithTranslation
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root
```

**Comment by wooorm** [comment]
@SalahAdDin that’s a warning, not an error. That warning has no effect on whether syntax highlighting works or not.

**Comment by wooorm** [comment]
Sure, by not passing unknown props through. Fix your `code` component.
