### ISSUE TITLE
Custom parser does not return a component

### ISSUE THREAD

**Issue by SalahAdDin** [remarkjs/react-markdown#574]
### Subject of the issue

I did write a small plugin in order to catch videos from _markdown_ and render them with a custom component:
```js
const visit = require("unist-util-visit");

const allowedFiletypes = ["avi", "mp4", "mov", "mkv"];

function video() {
  function transformer(tree) {
    visit(tree, "image", (node) => {
      const fileType = node.url.split(".").pop();

      if (allowedFiletypes.includes(fileType)) {
        node.type = `video`;
        node.tagName = `video`;
      }
    });
  }

  return transformer;
}

module.exports = video;
```

The problem is, it changes the node type but it does not get the correct renderer even when I set up it correctly:
```js
components: {
    ...props.components,
    // math: ({ value }) => <BlockMath>{value}</BlockMath>,
    // inlineMath: ({ value }) => <InlineMath>{value}</InlineMath>,
    code: CodeBlock,
    img: ImageBlock,
    video: VideoBlock,
  },
```

The *VideoBlock* component is never called, making a empty _div_ tag to be called.

This is *not* a place to ask questions.  For that, go to [discussions](https://github.com/remarkjs/remark/discussions)

### Your environment

*   **OS**: Deepin 20.3
*   **Packages**: 
```json
"react-markdown": "6.0.0",
    "react-player": "^2.7.2",
    "react-syntax-highlighter": "^15.4.3",
    "rehype-raw": "^5.1.0",
    "rehype-sanitize": "^4.0.0",
    "remark-unwrap-images": "^2.0.0"
```
*   **Env**:
```shell
❯ node -v
v14.16.1
❯ npm -v
6.14.12
```

### Steps to reproduce

Pass a image with a url finished on `mp4` and try to make it rendered.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉
You can reproduce it here: https://codesandbox.io/s/react-markdown-debug-forked-m6vtt?file=/src/App.js

### Expected behavior

It should receive the image and convert its node to video, take this video node and render it with my custom component.

### Actual behavior
It just renders a empty `div` which is not listed on the components' tree.

**Comment by ChristianMurphy** [comment]
@SalahAdDin how do you apply the plugin?
Could you share a codesandbox with an example of what you tried?

**Comment by SalahAdDin** [comment]
@ChristianMurphy I just updated the issue.

**Comment by ChristianMurphy** [comment]
`video` isn't a mdast node type https://astexplorer.net/#/gist/7d1accb038398213f9809542bdb1d585/dd40999a06d46494403a70261e9463770a2dbbe5
To pass a node type that will carry through consider using `node.data.hName` and `node.data.hProperties` as documented in https://github.com/syntax-tree/mdast-util-to-hast#examples

For example https://codesandbox.io/s/react-markdown-debug-forked-e76z7 (note disabled react player since there is no suspense context in your example and used text to show `video` element is rendered)

**Comment by ChristianMurphy** [comment]
An alternative, would be to allow https://github.com/syntax-tree/mdast-util-to-hast#optionspassthrough to be configured in `react-markdown` /cc @wooorm 
Though I'm not sure mixing custom `mdast`-ish nodes in with `hast` is a good idea. :thinking:

**Comment by ChristianMurphy** [comment]
For some additional context

```
                                                           react-remark
+---------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                             |
|            +----------+        +----------------+        +---------------+       +----------------+       +--------------+                  |
|            |          |        |                |        |               |       |                |       |              |                  |
| -markdown->+  remark  +-mdast->+ remark plugins +-mdast->+ remark-rehype +-hast->+ rehype plugins +-hast->+  components  +-react elements-> |
|            |          |        |                |        |               |       |                |       |              |                  |
|            +----------+        +----------------+        +---------------+       +----------------+       +--------------+                  |
|                                                                                                                                             |
+---------------------------------------------------------------------------------------------------------------------------------------------+
```

is the flow.
components is interacting with `hast`, since your plugin is a remark/mdast focused one, it needs to provide context to `remark-rehype` on how to make it a `hast` / html element.

**Comment by wooorm** [comment]
This might be better suited for a rehype plugin. Or an `img` component?

**Comment by SalahAdDin** [comment]
@wooorm Why it should be a `rehype` plugin?
Thank you very much, I used the first answer and i worked like a charm, i will test the other ones.
