### ISSUE TITLE
React Markdown 6.0.0 with Remark GFM 1.0.0 - Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <table>. Make sure you don't have any extra whitespace between tags on each line of your source code.

### ISSUE THREAD

**Issue by fdcds** [remarkjs/react-markdown#576]
### Subject of the issue

When rendering:
```
  <ReactMarkdown
    plugins={[gfm]}
  >
    {`| table | md |
| --- | --- |
| row1 | more |
| row2 | text |`}
  </ReactMarkdown>
```

with React v17.0.2, React Markdown v6.0.0, Remark Parse 9.0.0, Remark Rehype 8.1.0, Remark GFM 1.0.0, Firefox 87.0 will display warnings in the web developer console.

### Your environment

*   **OS**: Fedora 33, KDE Spin
*   **Packages**: React 17.0.2, React Markdown 6.0.0, Remark Parse 9.0.0, Remark Rehype 8.1.0, Remark GFM 1.0.0
*   **Env**: NodeJS 15.11.0, NPM 7.6.0, Firefox 87.0

### Steps to reproduce

Minimal reproduction: https://codesandbox.io/s/react-markdown-debug-forked-otbbg

### Expected behavior

Table should render without React warnings.

### Actual behavior

```
Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <table>. Make sure you don't have any extra whitespace between tags on each line of your source code.
table
div
ReactMarkdown@http://localhost:3000/app/static/js/vendors~main.chunk.js:154250:42
[...]

Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <thead>. Make sure you don't have any extra whitespace between tags on each line of your source code.
thead
table
div
ReactMarkdown@http://localhost:3000/app/static/js/vendors~main.chunk.js:154250:42
[...]

Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <tr>. Make sure you don't have any extra whitespace between tags on each line of your source code.
tr
thead
table
div
ReactMarkdown@http://localhost:3000/app/static/js/vendors~main.chunk.js:154250:42
[...]

Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <tbody>. Make sure you don't have any extra whitespace between tags on each line of your source code.
tbody
table
div
ReactMarkdown@http://localhost:3000/app/static/js/vendors~main.chunk.js:154250:42
[...]
```

**Comment by wooorm** [comment]
Is that still a thing? I thought React had fixed that by now (also because there are a lot of tests that include tables but that won’t give warnings).

For a fix, you could add something [here](https://github.com/remarkjs/react-markdown/blob/a2b611babce101fd1e7225f0720819c020c40d94/src/ast-to-react.js#L255). It would check for `['table', 'thead', 'tbody', 'tfoot', 'tr']`, and filter `children` to remove `'\n'` values.

Care to PR a fix?

**Comment by fdcds** [comment]
> Care to PR a fix?

#577 makes the warnings vanish for me, but please review it carefully, since I have little experience with "raw" JavaScript and none with the React Markdown codebase and conventions.
