### ISSUE TITLE
Type collision when creating `ReactMarkdown` via `createElement`

### ISSUE THREAD

**Issue by thedeadferryman** [remarkjs/react-markdown#579]
### Subject of the issue

Assume the following TypeScript snippet:
```typescript
const renderMarkdown = (source: string): React.ReactNode => (
  React.createElement(
    ReactMarkdown,
    { children: source },
  )
);
```

When compiled in strict mode, this gives the following error, related to `propTypes` definition:

```
some/poor/file.ts:37:7 - error TS2769: No overload matches 
this call.
  Overload 1 of 8, '(type: FunctionComponent<ReactMarkdownOptions>, props?: (Attributes & CoreOptions & PluginOptions & LayoutOptions & RehypeFilterOptions & TransformOptions) | null | undefined, ...children: ReactNode[]): FunctionComponentElement<...>', gave the following error.
    Argument of type 'typeof ReactMarkdown' is not assignable to parameter of type 'FunctionComponent<ReactMarkdownOptions>'.
      The types of 'propTypes.children[nominalTypeHack]' are incompatible between these types.
        Type '{ type: string | null | undefined; } | undefined' is not assignable to type '{ type: string; } | undefined'.
          Type '{ type: string | null | undefined; }' is not assignable to type '{ type: string; }'.
            Types of property 'type' are incompatible.
              Type 'string | null | undefined' is not assignable to type 'string'.
                Type 'undefined' is not assignable to type 'string'.
  Overload 2 of 8, '(type: ClassType<ReactMarkdownOptions, ClassicComponent<ReactMarkdownOptions, any>, ClassicComponentClass<ReactMarkdownOptions>>, props?: (ClassAttributes<...> & ... 4 more ... & TransformOptions) | ... 1 more ... | undefined, ...children: ReactNode[]): CElement<...>', gave the following error.
    Argument of type 'typeof ReactMarkdown' is not assignable to parameter of type 'ClassType<ReactMarkdownOptions, ClassicComponent<ReactMarkdownOptions, any>, ClassicComponentClass<ReactMarkdownOptions>>'.
      Type 'typeof ReactMarkdown' is not assignable to type 'ClassicComponentClass<ReactMarkdownOptions>'.
        The types of 'propTypes.children[nominalTypeHack]' are incompatible between these types.
          Type '{ type: string | null | undefined; } | undefined' is not assignable to type '{ type: string; } | undefined'.
            Type '{ type: string | null | undefined; }' is not assignable to type '{ type: string; }'.
  Overload 3 of 8, '(type: string | FunctionComponent<ReactMarkdownOptions> | ComponentClass<ReactMarkdownOptions, any>, props?: (Attributes & ... 
4 more ... & TransformOptions) | ... 1 more ... | undefined, ...children: ReactNode[]): ReactElement<...>', gave the following error.
    Argument of type 'typeof ReactMarkdown' is not assignable to parameter of type 'string | FunctionComponent<ReactMarkdownOptions> | ComponentClass<ReactMarkdownOptions, any>'.
      Type 'typeof ReactMarkdown' is not assignable to type 'FunctionComponent<ReactMarkdownOptions>'.
```

### Environment

*   **Packages**: TS v3.8.3, R-MD v6.0.0, React v16.14.0

### Steps to reproduce

Use a `React.createElement` with `ReactMarkdown` in non-TSX file.

**Comment by ChristianMurphy** [comment]
This seems related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/38402

**Comment by ChristianMurphy** [comment]
I think this error is expected and appropriate.
ReactMarkdown processes Markdown text, which is captured in the typings as:
https://github.com/remarkjs/react-markdown/blob/15b4757082cf3f32a25eba0b8ea30baf751a8b40/src/react-markdown.js#L23

TSX supports this restriction https://codesandbox.io/s/stupefied-sun-olxpw?file=/src/App.ts

`FunctionComponent` and by extension `createElement` do not yet support it DefinitelyTyped/DefinitelyTyped#38402
Instead `@types/react` attempts to broaden the type to include components, fragments, portals, and other types; which `react-markdown` does not support (they aren't markdown) and will result with a runtime error.
There is a workaround in the meantime https://codesandbox.io/s/gifted-surf-ygr1j?file=/src/App.ts

```ts
import ReactMarkdownTsx, { ReactMarkdownOptions } from "react-markdown";

const ReactMarkdown = (ReactMarkdownTsx as unknown) as FunctionComponent<
  ReactMarkdownOptions
>;

createElement(ReactMarkdown, { children: source });
```

but be aware that this is only partially type safe, invalid children can be passed, and will result in a runtime error.

The most appropriate fix is to enhance `@types/react` to support narrowing children types DefinitelyTyped/DefinitelyTyped#38402

**Comment by wooorm** [comment]
@thedeadferryman Could you try adding `null|undefined` to our types locally, in `node_modules`? That might fix it?

**Comment by thedeadferryman** [comment]
I've replaced this line:
```javascript
  const children: PropTypes.Requireable<string>
```
with the following:
```javascript
  const children: string | null | undefined
```
and that did the trick, types are working correctly.

**Comment by thedeadferryman** [comment]
@ChristianMurphy thanks for the solution, perhaps I'll use this until the bug will be resolved.

**Comment by wooorm** [comment]
Could you point to which exact line you changed? I thought your error was a typescript one, not a proptypes one

**Comment by thedeadferryman** [comment]
@wooorm `react-markdown.d.ts:35`

**Comment by wooorm** [comment]
Hmm. Well, we can’t do anything about that. Typescript generates those from `PropTypes`. And `PropTypes.Requireable` is specifically allowing nullish values, so that should be okay?

**Comment by wooorm** [comment]
So, should we say this is an external issue that can be solved by fixing it in `@types/react`? `prop-types`? Or can it be solved here?

**Comment by wooorm** [comment]
We can’t seem to get consensus on what to do here. Closing as it’s apparently not important.
