### ISSUE TITLE
allowedElements not working

### ISSUE THREAD

**Issue by lid3rs** [remarkjs/react-markdown#581]
After =update to "react-markdown": "^6.0.1", allowedElements not working.

```
  const allowedElements = [
    'paragraph',
    'emphasis',
    'strong',
    'link',
    'image',
    'list',
    'listItem',
    'thematicBreak',
    'text',
  ];
```

```
<ReactMarkdown
          allowedElements={allowedElements}
        >
          {content}
        </ReactMarkdown>
```

This prints nothing. All works without allowedElements

**Comment by wooorm** [comment]
Please see the changelog on [`allowedTypes` -> `allowedElements`](https://github.com/remarkjs/react-markdown/blob/main/changelog.md#replace-allownode-allowedtypes-and-disallowedtypes)

**Comment by lid3rs** [comment]
Am I missing something?

"allowedTypes to allowedElements" in doc. `I am writing that allowedElements is not working.

**Comment by wooorm** [comment]
Read the rest of the section. And the example. You might also use the “Show conversion table” section, a few paragraphs earlier.

**Comment by lid3rs** [comment]
I completely removed node_modules, installed new ones, and allowedTypes isa working, not elements.

**Comment by wooorm** [comment]
That means you downgraded again?

**Comment by lid3rs** [comment]
No,

```
yarn list --pattern react-markdown
yarn list v1.22.5
└─ react-markdown@6.0.1
```

**Comment by lid3rs** [comment]
ok, somehow  yarn cache clean and reinstall helped.
