### ISSUE TITLE
Get pure value of node

### ISSUE THREAD

**Issue by lid3rs** [remarkjs/react-markdown#583]
Is there any way to get pure value of the node?

Example: 

```
li: ({ node }) => <ListItem>{node.children[1].children[0].value}</ListItem>,
```

This looks awful, but as I understood it's the only way? Right now '< li >' has '< li >< paragraph >' logics. Or maybe there is a way how can this paragraph be replaced/removed?

**Comment by wooorm** [comment]
What is “pure”?

`node` is a [hast node](https://github.com/syntax-tree/hast). There are tons of plugins and utilities for working with them

**Comment by lid3rs** [comment]
In this particular example even if li is 'rewritten' with custom function, it will include paragraph inside. Is there a way how to avoid that?

**Comment by wooorm** [comment]
This sounds like an [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem). I still don’t understand what “pure” is.

Please take the time to frame your question ([more info here](https://github.com/remarkjs/.github/blob/main/support.md#asking-quality-questions))

**Comment by ChristianMurphy** [comment]
@lid3rs if you want to change the structure of the syntax tree, you can do so with remark (markdown) or rehype (html) plugins. https://unifiedjs.com/learn/ introduces how to work with ASTs and plugins.
And if you're looking for some inspiration https://github.com/remarkjs/remark-unwrap-images is another plugin that does paragraph unwrapping.
