### ISSUE TITLE
Compile error when using plugin rehype-raw

### ISSUE THREAD

**Issue by Ethunxxx** [remarkjs/react-markdown#584]
### Subject of the issue

Compile error occurs when react-markdown is used with plugin rehype-raw.

### Your environment

*   **OS**:  Ubuntu 20.04.2 LTS
*   **Packages**: See the package.json file in the Github repo provided below
*   **Env**: 
    *node: v15.14.0
    *npm: v7.7.6
    *Firefox: v88.0

### Steps to reproduce

I created a MWE in [this Github repo](https://github.com/Ethunxxx/mwe-error-rehype-raw-plugin) with which the error can be reproduced. Simply run `npm install` and `npm start`.

### Expected behavior

No errors, code compiling and app starting normally.

### Actual behavior

I get this error:

![image](https://user-images.githubusercontent.com/25529527/116410878-7a171c00-a835-11eb-8567-c55068675567.png)

### Additional note

Removing the rehype plugin, makes the code compile and run normally.

**Comment by ChristianMurphy** [comment]
`rehype-raw` goes in `rehypePlugins`, not `remarkPlugin`.

**Comment by Ethunxxx** [comment]
Yes, you are right and I just pointlessly waisted hours of my time (and also maybe 2min of yours)... 
Sorry and thanks very much for the swift reply :+1: !

**Comment by doddi** [comment]
I would like to understand what the fix was here. I might be running into a similar problem? I can create a new issue if that is preferred.
I don't get any compile/runtime errors but it seems the HTML is not parsed.

A short example:

```
const msg = `<div class="note">

Some *emphasis* and <strong>strong</strong>!

</div>`;

return (
  <ReactMarkdown rehypePlugins={[rehypeRaw]} children={msg} />
);
```

but the output is as if the html was not parsed:
```
<div class="note">
Some emphasis and <strong>strong</strong>!

</div>
```

**Comment by Ethunxxx** [comment]
I erroneously put `rehype-raw` in the `remarkPlugin` parameter. The fix was to simply put it in the `rehypePlugins` parameter instead. Hope that helps.
As for your issue, I'm not sure what the problem is. @ChristianMurphy?

**Comment by wooorm** [comment]
@doddi I can’t reproduce.

**Comment by doddi** [comment]
Thanks for your fast feedback. It must be something related to my project. I will keep looking. Thanks again

**Comment by wooorm** [comment]
Here’s a little playground you can use: https://codesandbox.io/s/react-markdown-debug-9n4eg.
It might be that the `react-markdown` you have is out of date?
