### ISSUE TITLE
How to integrate remark-directive into react-markdown

### ISSUE THREAD

**Issue by rjantoine** [remarkjs/react-markdown#585]
Here is an example on how to integrate remark-directive with react-markdown. You can include it in your readme if you like.

```js
import ReactMarkdown from "react-markdown";
import directive from "remark-directive";
import visit from "unist-util-visit";

import "./styles.css";

function reactMarkdownRemarkDirective() {
  return (tree) => {
    visit(
      tree,
      ["textDirective", "leafDirective", "containerDirective"],
      (node) => {
        node.data = {
          hName: node.name,
          hProperties: node.attributes,
          ...node.data
        };
        return node;
      }
    );
  };
}

function MyDirective({node, ...props}) {
  return (
    <span className="doSomethingCustom" {...props} />
  );
}

export default function App() {
  return (
    <div className="App">
      <ReactMarkdown
        remarkPlugins={[directive, reactMarkdownRemarkDirective]}
        components={{ MyDirective }}
        children=":MyDirective[Content]{#me}"
      />
    </div>
  );
}
```

Here is a [working version on CodeSandbox](https://codesandbox.io/s/interesting-matsumoto-y6x6n?file=/src/App.js:0-865)

**Comment by Murderlon** [comment]
hi @rjantoine, I would say the readme covers enough about plugins and a very common use case: syntax highlighting. One can throw in lots of remark or rehype plugins so covering them all in the readme would be excessive. remark-directive is just one of those plugins and it isn't particularly popular enough to show it in the readme.

**Comment by wooorm** [comment]
I tend to agree with @Murderlon (“it isn't particularly popular enough to show it in the readme.”). I’ll close this for now, but welcome more conversation on the topic, and we can revisit it later!

**Comment by rafaelguedes** [comment]
Did someone manage to make this work alongside **rehype-raw** (`rehypePlugins={[rehypeRaw]}`)?

If you add `rehypeRaw`, it will create `<mydirective id="me">Content</mydirective>` instead of a `<span>`.

**Comment by wooorm** [comment]
https://github.com/remarkjs/react-markdown/issues?q=remark-directive

**Comment by wooorm** [comment]
@rafaelguedes how do you expect `mydirective` to turn into a span?

**Comment by rafaelguedes** [comment]
Because `MyDirective` is returning a span, I assume. If you run the sandbox shared by @rjantoine, you will get a span rendered.
Not sure if I'm missing something but I guess that the whole point of the example above, is rendering a custom node (or eventually a custom React component).

**Comment by wooorm** [comment]
`rehype-raw` passes everything through an actual HTML parser. For HTML, tag names are case-insensitive, so they are normalized to be lowercase.

If you use `mydirective` instead of `MyDirective`, it should work. Could you confirm whether it does?

Perhaps it would be even better to embrace “HTML” and use `my-directive` or so (so dashes in custom components).

**Comment by rafaelguedes** [comment]
It's working, using `mydirective`, @wooorm.
Thanks a lot for your help, mate. 👍

**Comment by rjantoine** [comment]
Looking at my sandbox, everything seems to be working correctly. The idea is:
1. Use :CustomComponent[value]{prop:value} in your markdown code
2. Add the reactMarkdownRemarkDirective() code, as is, into your code in order to catch those directives and render them using a custom component.
3. Create a component called CustomComponent, or MyDirective, or whatever follows the colon in the markdown.
4. Include this component in the list of components for ReactMarkdown.

You can use my code exactly, you would just have to customize what is inside of MyDirective to insert your custom feature. You can even use it to insert bootstrap by using :Button[value] for example in your markdown, and include the Button component inside of the ReactMarkdown components array.

**Comment by IGassmann** [comment]
I've built a package for this use case: https://github.com/IGassmann/remark-directive-rehype. Check out the [react-markdown example](https://github.com/IGassmann/remark-directive-rehype#example-react-markdown) for how to use it

**Comment by gabrielmlinassi** [comment]
It works well but typescript complains about not being a `known property`
