### ISSUE TITLE
the chars representing a node type which has been forbidden manually  cannot be output

### ISSUE THREAD

**Issue by flwzz** [remarkjs/react-markdown#586]
### Subject of the issue
the chars representing a node type which has been forbidden manually  cannot be output

Describe your issue here.

This is *not* a place to ask questions.  For that, go to [discussions](https://github.com/remarkjs/remark/discussions)

### Your environment
*   **OS**: wsl2 ubuntu-20.04
*   **Packages**:  react-markdown: ^5.0.3
*   **Env**: node: v12.18.0; googleChrome: v90.0.4430.93

### Steps to reproduce
Example:
1.  remove `emphasis` from allowTypes 
```
const allowedTypes = [
    'break',
    'paragraph',
    // "emphasis",
    ...
]
```
2. pass it to the `ReactMarkdown` component
 ```
 <ReactMarkdown
    allowedTypes={allowedTypes}
    {...otherProps}
/>
```
3. input something in a markdown-editor
![image](https://user-images.githubusercontent.com/48706298/116684268-5a255b00-a9e3-11eb-9974-3867cda539f9.png)

4. `ReactMarkdown` component can't show the string `*a*`
![image](https://user-images.githubusercontent.com/48706298/116684461-91940780-a9e3-11eb-9a69-854d5d582199.png)
![image](https://user-images.githubusercontent.com/48706298/116684684-d029c200-a9e3-11eb-8e93-61b392aca504.png)

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behavior

What should happen?
the node type i forbad should be parsed as a `text` node type.
### Actual behavior
it  behave like that nothing has been inputted in the editor.
What happens instead?
it just ignore the text representing a forbidden node type.

**Comment by wooorm** [comment]
These options aren’t about parsing, but about filtering nodes.
`react-markdown` parses standard compliant (commonmark, gfm) markdown, not custom markdown-like syntaxes

**Comment by flwzz** [comment]
Could you give me some advice on how to  implement  this  demand  that  it  parse just the syntaxes which i want support? I completely have no idea. Thank you very much!
