### ISSUE TITLE
Multi-line grave accent (`) string parsed as code block

### ISSUE THREAD

**Issue by TryphonX** [remarkjs/react-markdown#589]
### Multi-line grave accent string parsed as code block

Trying to get the most out of the grave accent (**\`**) string syntax, I use it often to make line breaks a lot easier on the eye without the need of `\n`.  After one line break like this, it seems like the component assumes it's code markdown (verified by checking the console and seeing the text given the classname "code").

### Your environment

*   **OS**:  Windows 10
*   **Packages**: None
*   **Env**: MS Edge

### Steps to reproduce

Declare a const / variable with a string using \` syntax and adding line breaks without `\n` (if the linebreaks are added using `\n` this will work as expected).

```jsx
const description = `Some text here first line
some text here second line
some text third line.`

const getDescription = (): JSX.Element => {
const paragraphElements: JSX.Element[] = [];
const paragraphs = description.split('\n');

paragraphs.forEach((paragraph) => {
	console.log(paragraph);
	paragraphElements.push(<ReactMarkdown>{paragraph}</ReactMarkdown>);
});

return (
	<p>
		{paragraphElements}
	</p>
    );
};
```

### Expected behavior

The text should not be rendered as a code block.

### Actual behavior

The text is rendered as a code block.

**Comment by ChristianMurphy** [comment]
@TryphonX what version of react markdown are you using?
Trying you example in latest appears to work as expected https://codesandbox.io/s/react-markdown-debug-forked-rf06z

**Comment by ChristianMurphy** [comment]
Also so you're aware `<p>` tags cannot be nested in HTML, instead consider returning the paragraphs directly, or wrapping in a fragment.

**Comment by TryphonX** [comment]
> @TryphonX what version of react markdown are you using?
> Trying your example in latest appears to work as expected https://codesandbox.io/s/react-markdown-debug-forked-rf06z

Version 6.0.1

Followed your Fragment advice as well. As, most likely, expected, it wasn't what's causing this. Still same result.
![image](https://user-images.githubusercontent.com/32367640/117236831-3b372680-ae32-11eb-9454-0793bd477683.png)

**Comment by ChristianMurphy** [comment]
@TryphonX could you share an example of the issue in a codesandbox?

**Comment by ChristianMurphy** [comment]
Another consideration, what line endings are you using?
You are parsing with `.split("\n")`, if you are using CRLF endings, the second and third line would start with space.
You may want to try `.split("\r\n")`

**Comment by TryphonX** [comment]
> Another consideration, what line endings are you using?
> You are parsing with `.split("\n")`, if you are using CRLF endings, the second and third line would start with space.
> You may want to try `.split("\r\n")`

Was trying to make a codesandbox when I saw the reply. Seems to be it. Switching to `\r\n` and it's working as expected now. Thank you very much for the very quick responses!

**Comment by TryphonX** [comment]
Okay, it happened again, but this time I managed to reproduce it in a codesandbox. Apparently, the issue was the tab (4 spaces) before the second line of the string. https://codesandbox.io/s/react-markdown-debug-forked-gdf14?file=/src/App.js

**Comment by ChristianMurphy** [comment]
That's how markdown works.
Indentation makes code blocks https://spec.commonmark.org/0.29/#indented-code-blocks
