### ISSUE TITLE
Demo crashes when trying code blocks

### ISSUE THREAD

**Issue by jacob14916** [remarkjs/react-markdown#590]
### Subject of the issue

The demo at https://remarkjs.github.io/react-markdown/ crashes when trying code blocks.

### Your environment

*   **OS**: Windows 10
*   **Env**: Chrome 90

### Steps to reproduce

Open the demo
Click near the top of the markdown file in the left panel
Type three backticks (`\``) and then "p" (I was trying to type "python3")

### Expected behavior

Code rendered as plain monospace

### Actual behavior

The page goes dark, console reports 
```
index.module.js:7 Error: Unknown language: `p` is not registered
```

**Comment by wooorm** [comment]
Fixed, thanks!
