### ISSUE TITLE
Add link and paragraph tags to types

### ISSUE THREAD

**Issue by kr8n3r** [remarkjs/react-markdown#592]
### Subject of the feature

Add types for link and paragraphs to receive classNames, something like

```
a: <function that adds css classNames>, 
p: <function that adds css classNames>, 
```

### Problem

Not every project allows global styling of `a` and `p` tags.

Move to prevent custom components has left a gap for the above case. Unfortunately `a` and `p` are not defined in `Partial<NormalComponents & SpecialComponents>` so the type  checking throws an error 

### Expected behavior

Be able to modify basic HTML elements.

**Comment by ChristianMurphy** [comment]
this was resolved in https://github.com/remarkjs/react-markdown/pull/582, please update to the latest version of `react-markdown`
