### ISSUE TITLE
Multiple blank lines collapse to no linebreak when disallowing paragraph

### ISSUE THREAD

**Issue by stevemk14ebr** [remarkjs/react-markdown#593]
![image](https://user-images.githubusercontent.com/6619205/117984769-1cd79c00-b306-11eb-89fe-e1401599440a.png)

![image](https://user-images.githubusercontent.com/6619205/117984821-28c35e00-b306-11eb-8560-d65f4d281eab.png)

This seems wrong, i'd expect the following output, where the multiple newlines are collapsed, but into a single newline rather than removed entirely:

![image](https://user-images.githubusercontent.com/6619205/117985077-6627eb80-b306-11eb-9b6e-df8a5c3386b8.png)

![image](https://user-images.githubusercontent.com/6619205/117985119-6d4ef980-b306-11eb-921c-c6caae645611.png)

I am using remark-break already. Obviously i can easily fix this by re-allowing paragraphs but this should still work when the unwrap option is on in my opinion.
```
 <ReactMarkdown remarkPlugins={[[RemarkGFM, { singleTilde: false }], RemarkBreaks]} children={text} style={{ height: "100%", width: "100%" }} disallowedElements={["p"]} unwrapDisallowed={true} components={{ ... stuff for link tags ... }}/>
```

**Comment by stevemk14ebr** [comment]
I am inserting custom link elements which are inserted via the components array. I did not want some links to be included with a parent of <p> so i disallowed that type and then set unwrap to true. But that has the side effect of breaking newline so i've had to disable that for now.

**Comment by stevemk14ebr** [comment]
![image](https://user-images.githubusercontent.com/6619205/118135500-1cf09e00-b3d1-11eb-8ce6-ffb6b46d47c8.png)

Replacing the link type with a custom react component throws a dom nesting error, which is the root cause and why I want this.

**Comment by wooorm** [comment]
Why use a div? Links can exist in several things, such as headings or list items. Wouldn’t it be better to use a span if you don’t want links to do anything?

**Comment by stevemk14ebr** [comment]
I've changed it to code for now. But the point is not my particular application, just that this setting has an unintended side effect which i think would be nice to fix.

**Comment by wooorm** [comment]
This is the exact intended result: by setting `disallowedElements={["p"]}` you say you don‘t want `p` elements to show. With `unwrapDisallowed={true}` you say to keep the text and other elements inside them

**Comment by stevemk14ebr** [comment]
Agree I do say that, but I don't say that formatting should be changed.

**Comment by wooorm** [comment]
browsers add styles to elements. For example, paragraphs are “blocks”. Without them, there are no such blocks.

**Comment by stevemk14ebr** [comment]
<br> tags could be inserted instead when p tags are unwrapped, no need to rely on the <p> tag styling
