### ISSUE TITLE
Reducing the bundle size

### ISSUE THREAD

**Issue by alexnault** [remarkjs/react-markdown#595]
### Problem

Since 6.0.0, the minified + gzipped bundle size went from [32.4kB](https://bundlephobia.com/result?p=react-markdown@5.0.3) to [39.4kB](https://bundlephobia.com/result?p=react-markdown@6.0.0) (a ~22% increase). Almost as big as react-dom. Are there any plans to reduce the bundle size?

**Comment by ChristianMurphy** [comment]
PRs improving bundle size are welcome!
