### ISSUE TITLE
subscript cutoff when background-color is set.

### ISSUE THREAD

**Issue by loganbnielsen** [remarkjs/react-markdown#596]
I noticed that when background color is set in my css that my ReactMarkdown equation gets its subscripts chopped off.

`
/* index.css */
* {
  margin: 0;
  font-family: "Calibri";
  color: #333;
  background-color: none;
}

/* App.js */ 
<div>
    <article>
        <h2>{topic.title}</h2>
        <div>{topic.body}</div>
    </article>
        {topic.equation}
        <Equation class="equation" equation="$y_i = x_i$"/>
</div>
`

It's interesting because the y that hangs lower than the subscript i does not get cut off but the i does.

**Comment by wooorm** [comment]
We don‘t do CSS. That’s up to you. Hence: it’s a bug in the CSS you’re using

**Comment by loganbnielsen** [comment]
> We don‘t do CSS. That’s up to you. Hence: it’s a bug in the CSS you’re using

Sorry, I'm not aware of a CSS repo. Could you point me in the right direction?

**Comment by wooorm** [comment]
- You removed the issue template we asked you to fill out: https://github.com/remarkjs/.github/blob/main/.github/ISSUE_TEMPLATE/1-bug.md
- Your code has nothing to do with markdown

**Comment by loganbnielsen** [comment]
> * You removed the issue template we asked you to fill out: https://github.com/remarkjs/.github/blob/main/.github/ISSUE_TEMPLATE/1-bug.md
> * Your code has nothing to do with markdown

I think you miss-understood what I was asking, I'm not asking for you to help me out with the bug, I'm asking where I should report the issue. (i.e. I'm not aware of CSS repo but I haven't been doing front-end work for very long so I could be ignorant)

**Comment by ChristianMurphy** [comment]
@loganbnielsen It's not clear that it is a bug in a library. It's very possibly an issue in the custom CSS you've written.
Since you mention it is related to `<Equation>`, which does not appear to be related to `react-markdown`, you may want to ask the maintainers of that component for assistance.
When you do, you may want to include a codesandbox (https://codesandbox.io) with a runnable example of what you are seeing.
