### ISSUE TITLE
Data object lost when using `rehype-raw` with `remark-gfm`

### ISSUE THREAD

**Issue by skoch** [remarkjs/react-markdown#597]
### Data object lost when using `rehype-raw` with `remark-gfm`

When using `rehype-raw` with `remark-gfm` the `node.data` object is lost for code fences.

eg:
```
~~~jsx noeditor
<Foobar />
~~~
```

With only `remark-gfm` we can see `node.data.meta` and when `rehype-raw` is added, the `node.data` object is lost.

### Your environment

*   **OS**: mac, big sur
*   **Packages**:
```
"markdown": "^0.5.0",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-markdown": "^6.0.2",
"rehype-raw": "^5.1.0",
"remark-gfm": "^1.0.0"
```
*   **Env**:
```
node: v12.16.1
npm: 7.5.3
Chrome: Version 90.0.4430.212 (Official Build) (x86_64)
```

### Steps to reproduce

Please see [the example repository](https://github.com/skoch/react-markdown-typescript) to reproduce.

### Expected behavior

The `node.data` object should be maintained when using both plugins.

### Actual behavior

The `node.data` object is lost when using both plugins.

**Comment by ChristianMurphy** [comment]
@skoch this doesn't appear to be specifically related to react-markdown, so much as rehype-raw/hast-util-raw?

---

Also I don't think it is specifically a bug, from hast-util-raw's readme:

> hast utility to parse the tree again, now supporting embedded raw nodes

It re-parses the content, it makes sense that metadata may be lost in the process.
It may be worth looking into enhancing the process to see if metadata can be preserved, that would be something to raise and discuss at hast-util-raw.

**Comment by skoch** [comment]
Understood. 

Will post the same to [hast-util-raw](https://github.com/syntax-tree/hast-util-raw).

**Comment by grossbart** [comment]
I’m also investigating this problem as it prevents me from upgrading `react-markdown` from version 5. In my case I need `rehype-raw` with `rehype-sanitize` to prevent XSS attacks, but I also need to parse the code fence metadata to provide custom components – as described above, this doesn't work at the moment.

What I found is that it seems to be possible to preserve this meta information in the `mdast` to `hast` conversion, as it was done in [mdast-util-to-hast](https://github.com/syntax-tree/mdast-util-to-hast/issues/46). I will try to figure out where exactly this info is lost and how this could be added to `rehype-raw`/`hast-util-raw`.

**Comment by wooorm** [comment]
You can use a plugin before `rehype-raw`/`hast-util-raw` that walks the tree to find `code.data.meta`, and when it does define it as the field you want. E.g., `code` will have a `properties` object, you could set `code.properties.dataMeta = code.data.meta`

**Comment by grossbart** [comment]
Thanks @wooorm, this helped me solve the issue 🙏 I also needed to tell `rehypeSanitize` to not filter out the properties I needed, which makes sense.

**Comment by wong2** [comment]
@grossbart Can you share your code?

**Comment by grossbart** [comment]
@wong2 Sure, here it is. You can find an example of this in [rehype-sanitize](https://github.com/rehypejs/rehype-sanitize#example-math)'s readme with the math example.

```
import React from "react";
import remarkMath from "remark-math";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";
import rehypeSanitize, { defaultSchema } from "rehype-sanitize";
import ReactMarkdown from "react-markdown";

const sanitizeSchema = {
  ...defaultSchema,
  attributes: {
    ...defaultSchema.attributes,
    // We need classNames for extracting the language meta from Markdown code fences
    code: [
      ...(defaultSchema.attributes?.["code"] ?? []),
      ["className", "text", "tex!"],
    ],
    div: [
      ...(defaultSchema?.attributes?.["div"] ?? []),
      ["className", "math", "math-display"],
    ],
    span: [
      ...(defaultSchema?.attributes?.["span"] ?? []),
      ["className", "math", "math-inline"],
    ],
  },
};

export const Markdown = ({ source }: { source: string }) => (
  <ReactMarkdown
    remarkPlugins={[remarkMath, remarkGfm]}
    rehypePlugins={[rehypeRaw, [rehypeSanitize, sanitizeSchema]]}
  >
    {source}
  </ReactMarkdown>
);
```
