### ISSUE TITLE
Vite & React-Markdown crashing site in production builds

### ISSUE THREAD

**Issue by krypticallusion** [remarkjs/react-markdown#598]
### Subject of the issue

Vite and React-Markdown don't seem to play well when building in production mode. (vite build)
Note:  I'm using the react template of vite. 
PS: However, the dev builds of said project seems to work just fine.

### Your environment

*   **OS**:  Linux

### Steps to reproduce

https://github.com/krypticallusion/test/tree/vite/react-markdown is a test repo I created, just `yarn serve` here. The bug should be apparent

### Expected behavior
Website should've loaded

### Actual behavior
![image](https://user-images.githubusercontent.com/28943200/120101802-8a3c5700-c165-11eb-8e2e-5c0a96ac3801.png)

**Comment by wooorm** [comment]
It looks like Vite in production cannot handle two files importing each other: https://github.com/syntax-tree/mdast-util-to-hast/blob/e623ab2ba14f223d75bc84e1307de6b101ef2d42/lib/all.js#L16.
There are millions of users of that project, that use it without a problem, so you might either configure vite to support it, or report it there

**Comment by liulunsheng** [comment]
> 

Did you solve the problem?

**Comment by wooorm** [comment]
Yes it's been solved since basically this issue.

**Comment by liulunsheng** [comment]
> Yes it's been solved since basically this issue.

i upgrade react-markdown to v8.0.2 and it worked well in vite
