### ISSUE TITLE
component prop generates a type error in typescript

### ISSUE THREAD

**Issue by dbroadhurst** [remarkjs/react-markdown#599]
component prop generates a type error in typescript. Using the example in the README.

````
import React from 'react'
import ReactMarkdown from 'react-markdown'
import {Prism as SyntaxHighlighter} from 'react-syntax-highlighter'
/* Use `…/dist/cjs/…` if you’re not in ESM! */
import {dark} from 'react-syntax-highlighter/dist/esm/styles/prism'
import {render} from 'react-dom'

const components = {
  code({node, inline, className, children, ...props}) {
    const match = /language-(\w+)/.exec(className || '')
    return !inline && match ? (
      <SyntaxHighlighter style={dark} language={match[1]} PreTag="div" children={String(children).replace(/\n$/, '')} {...props} />
    ) : (
      <code className={className} {...props} />
    )
  }
}

// Did you know you can use tildes instead of backticks for code in markdown? ✨
const markdown = `Here is some JavaScript code:

~~~js
console.log('It works!')
~~~
`

render(<ReactMarkdown components={components} children={markdown} />, document.body)
````

# Error

Type '{ code({ node, inline, className, children, ...props }: { [x: string]: any; node: any; inline: any; className: any; children: any; }): Element; }' is not assignable to type 'Partial<NormalComponents & SpecialComponents>'.
  Types of property 'code' are incompatible.
    Type '({ node, inline, className, children, ...props }: { [x: string]: any; node: any; inline: any; className: any; children: any; }) => Element' is not assignable to type 'keyof IntrinsicElements | CodeComponent'.
      Type '({ node, inline, className, children, ...props }: { [x: string]: any; node: any; inline: any; className: any; children: any; }) => Element' is not assignable to type 'CodeComponent'.
        Types of parameters '__0' and 'props' are incompatible.
          Type 'ReactBaseProps & ReactMarkdownProps & { inline?: boolean; }' is not assignable to type '{ [x: string]: any; node: any; inline: any; className: any; children: any; }'.
            Property 'inline' is optional in type 'ReactBaseProps & ReactMarkdownProps & { inline?: boolean; }' but required in type '{ [x: string]: any; node: any; inline: any; className: any; children: any; }'.

**Comment by ChristianMurphy** [comment]
In Typescript you need to type components.
See https://github.com/remarkjs/remark/discussions/714 for an example
