### ISSUE TITLE
[Question] Should I be using this if I need to render MDX?

### ISSUE THREAD

**Issue by ajaypillay** [remarkjs/react-markdown#600]
Hi, I'd just like to clarify something. I'm trying to create a blog with the posts being MDX files. If I need MDX, is it correct that I can't use this package at all, and I instead need to use the [MDX](https://github.com/mdx-js/mdx) package?

I want to be able to use LaTeX as well, and MDX supports that together with this. So the only missing piece is the MDX bit for this package.

Thanks!

**Comment by wooorm** [comment]
Hi, questions can go to other places.

Yes, if you need MDX (JSX *inside* markdown), use `mdx-js/mdx` or `xdm`.
If you need to turn markdown into React nodes, use this. Or many of the other tools we provide

**Comment by ajaypillay** [comment]
Thank you for the response, will direct further questions elsewhere. `xdm` looks interesting, will check that out too.
