### ISSUE TITLE
Custom Link not working on version 6

### ISSUE THREAD

**Issue by nigellima** [remarkjs/react-markdown#601]
### Subject of the issue

I recently migrated from version 4 to version 6 due to some vulnerabilities that were raised by `audit --fix`. 
For my Links in the markdown I had a custom renderer (which now is component) that would render the link using another library. However, after upgrading I saw that there were some major changes and also my links were not being rendered with my custom component. 

I came across [this](https://github.com/remarkjs/react-markdown/issues/511#issuecomment-730817081) answer in this issue here showing the correct way for version 5. I upgraded the react-markdown package to version 6 and it is reproducing the same behaviour in my side: no custom anchor tag

### Your environment

*   **OS**: Mac OSX - Big Sur
*   **Packages**: "react-markdown": "^6.0.2"
*   **Env**: node v12.10.0, yarn 1.22.0

### Steps to reproduce

https://codesandbox.io/s/react-markdown-debug-forked-w6c8c?file=/src/App.js

### Expected behavior

Should render anchor tag with custom component

### Actual behavior

Default anchor tags is being rendered

**Comment by wooorm** [comment]
Hi there!

Please peruse the changelog to find the `renderers` -> `components` change!

**Comment by nigellima** [comment]
@wooorm @ChristianMurphy  I updated the sandbox reproduction to use `components` instead of renders and it still does not work

**Comment by ChristianMurphy** [comment]
@nigellima again, read the changelog https://github.com/remarkjs/react-markdown/blob/main/changelog.md#change-renderers-to-components
It explains the difference.

**Comment by nigellima** [comment]
@ChristianMurphy Sorry, I had misunderstood the other answer. 
Thanks a lot, it works perfectly now
