### ISSUE TITLE
`allowedElements`, It doesn't work completely

### ISSUE THREAD

**Issue by A-ANing** [remarkjs/react-markdown#602]
### Subject of the issue
`allowedElements`, It doesn't work completely

### Steps to reproduce
```js
            var str = "<div>123</div><custom>this is custom</custom>" //success
            var fail_str1 = "<custom>this is custom</custom>" //fail
            var fail_str2 = "<span>this is span</span>" //fail
            
            return<ReactMarkdown
                    escapeHtml={false}
                    skipHtml={false}
                    children={fail_str1}
                    allowedElements={["span", "div","custom",'img','b']}
                    remarkPlugins={[gfm]}
                    rehypePlugins={[rehypeRaw]}
                >
                </ReactMarkdown>
```

### Expected behavior
`str` ,`fail_ str1` and `fail_ str2` can be displayed normally

### Actual behavior
only `str`  shows it

"react": "^16.12.0",
"react-markdown": "^6.0.0",
"rehype-raw": "^5.1.0",
 "remark-gfm": "^1.0.0"

**Comment by wooorm** [comment]
You seem to be on an old version of react-markdown: `escapeHtml` isn’t a thing anymore.

I’m not a fan of the filter options either. I suggest using `rehype-sanitize` instead

**Comment by A-ANing** [comment]
> You seem to be on an old version of react-markdown: `escapeHtml` isn’t a thing anymore.
> 
> I’m not a fan of the filter options either. I suggest using `rehype-sanitize` instead

I have an input box where I can select emoticons. Emoticons are composed of prescribed character formats. I use regular rules to replace the characters with html. For example, replace `:emoji-**:` with `<span><img src="https: //xxx/.gif"/></span` It was done in the version I knew before version 5, but after 6, I don’t know how to do it. I hope that the input label in the input box <> still displays the string, then the picture is displayed , Do you know what to do with your expression?

**Comment by wooorm** [comment]
Why not use actual unicode emoji characters?

Otherwise, can you provide more information so I can understand your question?

**Comment by A-ANing** [comment]
> 为什么不使用实际的 unicode 表情符号字符？
> 
> 否则，您能否提供更多信息以便我理解您的问题？
## this is textarea
![0af9376c43b650543bc3013da2fb43c](https://user-images.githubusercontent.com/43433064/121783841-85ef4f80-cbe3-11eb-8d14-dfeebcfe3449.jpg)

## This is after markdown rendering
![a1b577ce38ede13a82454deb875110d](https://user-images.githubusercontent.com/43433064/121783859-b6cf8480-cbe3-11eb-9386-0c6a8189627b.jpg)

Thank you for your reply, because you need to use a custom emoji;
Before version 6, I used `renderers` to output a `<emoji dangerouslySetInnerHTML={{ __html: "<img src="https://xxx/xxx.gif">"}} />` jsx object. Realize my needs, but now I don’t know how to implement it in versions after 6

**Comment by wooorm** [comment]
How are you storing those custom emoji in the markdown text?

**Comment by A-ANing** [comment]
> 你如何在降价文本中存储这些自定义表情符号？

![image](https://user-images.githubusercontent.com/43433064/121784166-09f60700-cbe5-11eb-99c3-eb80dda3d628.png)
```
    paragraph: ({ children }) => {
        var reslist = []
        Array.from(children).forEach((e, i) => {
            if (typeof (e.type.name) == "string") {
                var chilValue = e.props.value
                
                chilValue = chilValue.map((child_item, i) => {

                    emjcof.data.forEach((item) => {
                            var exg = "/:emj-bili-" + item.value + ":/g"
                            child_item = child_item.replace(eval(exg), `<img src="https://emoji/bili_${item.value}.gif">`)
                    })
                })

                return <><emoji dangerouslySetInnerHTML={{ __html: chilValue }} /></>
            }
        })
    }
    ```
   In the previous version, I replaced the characters corresponding to the emoji with regular expressions and replaced them with tags; then used react's `dangerouslySetInnerHTML` to do it; what should I do with the 6 version? `components` does not support `paragraph`

**Comment by A-ANing** [comment]
`children` must be of string type, it is easy to solve if it supports string and `jsx` object

**Comment by A-ANing** [comment]
![image](https://user-images.githubusercontent.com/43433064/121785004-d9649c00-cbe9-11eb-8e2d-60326218a4c9.png)
![image](https://user-images.githubusercontent.com/43433064/121785013-e6818b00-cbe9-11eb-83fd-ee9661104ac6.png)

Very bad, I just want to display the picture after generation, and the div characters remain unchanged

```js
<ReactMarkdown
                    skipHtml={false}
                    remarkPlugins={[gfm]}
                >
                    {typeof data === 'string' ? data.replace(/\n/g, '  \n') : data}
                    {/* 
                    Unfortunately, children only support string. 
                    When it is a jsx object, 
                    the condition is false and it will not be rendered. 
                    */}
                </ReactMarkdown>
```

**Comment by wooorm** [comment]
- I don’t understand where `data` is coming from in your last example
- You can still regex find-and-replace the strings in `children` in `components` — `components` **does** support `p` (see changelog)

**Comment by A-ANing** [comment]
Need a person who can control which children can be converted into html for display, instead of directly specifying the tag name, maybe multiple img tags, I only want one of the img to be displayed as a picture.

**Comment by wooorm** [comment]
I’m sorry, I don’t understand what you mean

**Comment by A-ANing** [comment]
> I’m sorry, I don’t understand what you mean

Thank you for your patience to answer, and finally I used the following method to achieve my needs;
```js
         var paragraph = (value) => {
                if (typeof (value) == "string") {
                    var newValue = value
                    emjcof.bili.text.forEach((item) => {
                        if (newValue.indexOf(':emj-bili-' + item.value + ':') >= 0) {
                            var exg = "/:emj-bili-" + item.value + ":/g"
                            newValue = newValue.replace(eval(exg), biliImgEmj(item.value, item.det))

                        }
                    })
                    return <emoji dangerouslySetInnerHTML={{ __html: newValue }} />;
                }
            }
         
            function myRehypePlugin() {
                return transform
                function transform(tree) {
                  visit(tree, 'text', onText)
                }
                function onText(result) {
                  var res = paragraph(result.value)
                  result.value = res
                }
              }
            return <ReactMarkdown
                    children={data}
                    skipHtml={false}
                    remarkPlugins={[gfm]}
                    rehypePlugins={[myRehypePlugin]}
                >
                    {/* {typeof data === 'string' ? data.replace(/\n/g, '  \n') : data} */}
                </ReactMarkdown>

```
The final look, hahaha, thank you very much;

![image](https://user-images.githubusercontent.com/43433064/121798001-5b8aaa00-cc56-11eb-833c-ec5102889670.png)

**Comment by A-ANing** [comment]
But there is a problem, all the text is wrapped by `emoji`
![image](https://user-images.githubusercontent.com/43433064/121798158-51b57680-cc57-11eb-89ff-08cf95442d41.png)

**Comment by A-ANing** [comment]
## The above problem has been solved

![image](https://user-images.githubusercontent.com/43433064/121800053-33a14380-cc62-11eb-9d86-844a30cdda9d.png)

## Code; Modified `paragraph` method
```js
            var paragraph = (value) => {
                if (typeof (value) == "string") {
                    var newValue = value
                    var emjdata=emjcof.bili.text
                    var resArr = []
                    console.log("newValue",newValue)
                    emjdata.forEach((item,index) => {
                        if (newValue.indexOf(':emj-bili-' + item.value + ':') >= 0) {
                            // var exg = "/:emj-bili-" + item.value + ":/g"
                            // newValue = <>{newValue.replace(eval(exg), <emoji dangerouslySetInnerHTML={{ __html: biliImgEmj(item.value, item.det) }} />)}</>
                            // newValue = newValue.split(":emj-bili-" + item.value + ":").join(<emoji dangerouslySetInnerHTML={{ __html: biliImgEmj(item.value, item.det) }} />)
                            var splitArr = newValue.split(":emj-bili-" + item.value + ":")
                            splitArr = splitArr.map((arritem,arrindex)=>{
                               return <>{arritem}{arrindex!=splitArr.length-1?<emoji dangerouslySetInnerHTML={{ __html: biliImgEmj(item.value, item.det) }} />:null}</>
                            })
                            resArr.push(splitArr)
                        }else{
                            if(index==emjdata.length-1&&resArr.length<1){
                               resArr.push(newValue)
                            }
                        }
                        
                    })
                    return resArr;
                }
            }
```

**Comment by wooorm** [comment]
Glad it works!

Some of the code you post here can in my opinion be better: cleaner, faster, more secure.
So when you have the time, it might be useful to invest in your knowledge of JavaScript itself, React, and maybe also how unified/remark/rehype and such work: https://unifiedjs.com/learn/

Good luck!
