### ISSUE TITLE
`sourcePosition` is undefined even when using rawSourcePos prop with gfm element (checkBox)

### ISSUE THREAD

**Issue by sevseux** [remarkjs/react-markdown#607]
### Subject of the issue

`sourcePosition` is undefined even when using rawSourcePos prop with gfm element (checkBox)

### Your environment

*   **OS**: Windows 10/WSL1(Debian)
*   **Packages**: "react-markdown": "^6.0.2", "remark-gfm": "^1.0.0",
*   **Env**: `node: v14.16.1` && `npm: 7.9.0`

### Steps to reproduce

https://codesandbox.io/s/react-markdown-debug-forked-ehyl8

### Expected behavior

The documentation seems to say that `rawSourcePos`  passed to the `Markdown` component is enough to get a valid `sourcePosition` object, in order to get infos about lines, columns, etc

### Actual behavior

As you can see in codesandbox, the variable is undefined when it is used with _input_, for some reason.

I tested with version 5.0.2, everything seems ok.

**Comment by wooorm** [comment]
Correct, in certain cases it’s impossible to know the input location.

**Comment by wooorm** [comment]
Does 5.0.2 really work? 🤔 What does it point to?

Do you know how we can make the docs clearer that it almost always works, but not exactly always?

**Comment by ypresto** [comment]
I tested 5.0.2 with above codesandbox and it also does not work.

**Comment by ypresto** [comment]
You can still retrieve sourcePosition of list item (`<li>`) element.

FYI: Below is my implementation of checkbox toggle that works with v6.0.2.

```tsx
const ListWrapper: SpecialComponents['li'] = ({
  checked,
  index,
  ordered,
  node,
  sourcePosition,
  siblingCount,
  ...props
}) => {
  const classes = useListWrapperStyles()
  const { onChangeCheckbox } = useContext(MarkdownEditContext)

  if (checked == null) {
    return React.createElement('li', props)
  }

  return React.createElement(
    'li',
    props,
    React.Children.map(props.children, child =>
      child &&
      typeof child === 'object' &&
      'type' in child &&
      child.type === 'input' &&
      child.props.type === 'checkbox' ? (
        // Manipulate input tag by React.cloneElement() or return customized checkbox. Below code is for material-ui.
        <Checkbox
          className={classes.checkboxRoot}
          color="primary"
          size="small"
          checked={child.props.checked}
          onChange={(_e, checked) => onChangeCheckbox(sourcePosition!, checked)}
          onClick={e => e.stopPropagation()}
        />
      ) : (
        child
      )
    )
  )
}
```

```tsx
<MarkdownEditContext.Provider
  value={{
    onChangeCheckbox: (sourcePosition, checked) => {
    const offset = sourcePosition.start.offset!
    const prefix = value.slice(0, offset)
    const newValue = prefix + value.slice(offset).replace(/^([-+*]\s+)\[[x ]\](\s)/, `$1[${checked ? 'x' : ' '}]$2`)
    updateText(newValue)
    }
  }}
>
  <ReactMarkdown plugins={[remarkGfm, remarkBreaks]} components={{ li: ListWrapper }} rawSourcePos>
</MarkdownEditContext.Provider>
```

**Comment by wooorm** [comment]
@sevseux Any thoughts on my (and @ypresto’s) comments?

**Comment by sevseux** [comment]
@wooorm 
Big thanks for your replies !

I followed everything from @ypresto and it is a success with `li` instead of `input`.

> Do you know how we can make the docs clearer that it almost always works, but not exactly always?

As I don't know the why behind the limitation with `input`, I am not sure how I can help with that.


Closing the issue, thanks again (and sorry for the delay)
