### ISSUE TITLE
html is not parsed with rehypeRaw plugin

### ISSUE THREAD

**Issue by anderperez15** [remarkjs/react-markdown#608]
example:

<ReactMarkdown rehypePlugins={[rehypeRaw]} remarkPlugins={[gfm]} children={value} />

this transforms the html to plain text

**Comment by ChristianMurphy** [comment]
Please fill out the issue template https://github.com/remarkjs/.github/blob/main/.github/ISSUE_TEMPLATE/1-bug.md
This issue cannot be trialed without some details as to what is happening

**Comment by ChristianMurphy** [comment]
here is an example of how it works https://codesandbox.io/s/react-markdown-debug-forked-86z27?file=/src/App.js
