### ISSUE TITLE
Text option in custom components

### ISSUE THREAD

**Issue by Fanner487** [remarkjs/react-markdown#609]
I'm trying to upgrade from `v4.3.1` to `v6.0.2`. All is going well with refactoring the `renderers` prop to `components`.

However, I am having issues finding a way to create a custom component on the `text` attribute that was in `v4.3.1`. Reading the [Changelog](https://github.com/remarkjs/react-markdown/blob/main/changelog.md) and the conversion table I see that there is no conversion for the `text` attribute so my code won't get rendered properly. I was wondering if there is a way to do it in the latest version?

| Type (`renderers`) | Tag names (`components`) |
| - | - |
| `blockquote` | `blockquote` |
| `break` | `br` |
...
| `tableCell` | `td`, `th`**‡** |
| `text` | |
| `thematicBreak` | `hr` |

### This is my code:

```js
const components = {
  text: ({node, ...props}) => {
    return props.value.split(' ').map((word, index) => (
      <CustomComponent />
    ));
  },
  inlineCode: (props) => {
    return props.value.split(' ').map((word, index) => (
      <span key={index}>{`${word} `}</span>
    ));
  },
};
```

```js
<ReactMarkdown
  children={formattedSource}
  linkTarget={'_blank'}
  components={components}
/>
```

### Versions
```json
{
  "react": "^17.0.2",
  "react-markdown": "^6.0.2",
}
```

**Comment by ChristianMurphy** [comment]
See the related discussion https://github.com/remarkjs/remark/discussions/700
It sounds like you have a similar use case

**Comment by Fanner487** [comment]
Thank you very much for pointing me in the right direction!

**Comment by ChristianMurphy** [comment]
A concrete example of how this can be supported in the latest version https://codesandbox.io/s/react-markdown-wrap-text-79e70?file=/src/App.js
