### ISSUE TITLE
Preserving Spacing between two elements.

### ISSUE THREAD

**Issue by sarmad1995** [remarkjs/react-markdown#610]
### Add space between two different type of texts.

If I use the react-markdown this way 
```
<ReactMarkdown> Hello, **world**!</ReactMarkdown>
```
The space between hello and , will be lost, ofcourse I can add &nbsp; but what if the string is coming from somewhere else.

This is *not* a place to ask questions.  For that, go to [discussions](https://github.com/remarkjs/remark/discussions)

### Your environment

*   **OS**: mac os 
*   **Packages**: 6.0.2
*   **Env**: yarn 1.22.10  

### Steps to reproduce

```jsx
<ReactMarkdown> Hello how are , **you**!</ReactMarkdown>
```
After rendering this, the space is lost between "are" and "you" , so it will render something like this
### Expected behavior
There should be a way to preserve space.

**Comment by sarmad1995** [comment]
<img width="299" alt="Screenshot 2021-06-30 at 8 07 48 PM" src="https://user-images.githubusercontent.com/38377482/123980036-db4a9f80-d9de-11eb-9cfe-a47cc9dc92bf.png">

**Comment by wooorm** [comment]
Please make this reproducible. It doesn’t happen on the demo: https://remarkjs.github.io/react-markdown/

**Comment by sarmad1995** [comment]
@wooorm  yes, just checked and it works on a new project.
The issue was that my h1,h2 and other tags had `display: flex`. Removing flex properties from them resolved this.
closing the issue.
