### ISSUE TITLE
Newlines between elements, breaking `white-space: pre-wrap`

### ISSUE THREAD

**Issue by LoganDark** [remarkjs/react-markdown#611]
### Subject of the issue

I want to use `white-space: pre-wrap` on my Markdown container, but there are newlines between `<p>` elements, and lists, etc. causing huge gaps between everything.

### Your environment

*   **OS**: Windows 10 2004
*   **Packages**: `react-markdown` 6.0.2
*   **Env**: npm 7.18.1 running on Node 16.4.0

### Steps to reproduce

Put `white-space: pre-wrap` on a container with Markdown in it: https://codesandbox.io/s/remark-rehype-debug-forked-r5520

![image](https://user-images.githubusercontent.com/4723091/124217940-1962c480-daae-11eb-84b7-b5c49e9a6b4e.png)

### Expected behavior

There should be no whitespace between the HTML elements

### Actual behavior

There is

**Comment by wooorm** [comment]
react-markdown renders markdown according to the CommonMark and GFM specs, so yes, there should be whitespace.
This sounds like an [XY problem](https://xyproblem.info): don’t use `white-space: pre-wrap`. There might be a good reason why you want to, but perhaps you can solve it in a different way.

**Comment by dvaldivia** [comment]
Are there any alternatives to using `white-space: pre-wrap` so markdown longer than it's container wraps inside the pre @wooorm ?

**Comment by wooorm** [comment]
You have some complex question that can’t be explained in 1 line. I can‘t help you well if I don’t know what you’re actually dealing with. Perhaps open a discussion? Or search discussions: folks ask many things, often things that have been asked before.

**Comment by LoganDark** [comment]
> This sounds like an [XY problem](https://xyproblem.info): don’t use `white-space: pre-wrap`.

Years late, but I think the original reason why I did this was to try to prevent single line breaks in paragraphs from being swallowed, though I'm no longer a part of that project.

**Comment by wooorm** [comment]
That’s `remark-breaks`.

**Comment by LoganDark** [comment]
> remark-breaks

[This one?](https://github.com/remarkjs/remark-breaks)
