### ISSUE TITLE
Render context broken when input not-closed script tag

### ISSUE THREAD

**Issue by Valen-Pony** [remarkjs/react-markdown#613]
### Subject of the issue

The rendered content broken when input not closed script tag, like `<script`, `<script>`, `<script></script`.
![makrdown](https://user-images.githubusercontent.com/83207497/125030610-f5127380-e0bd-11eb-97d2-b2d917a907b0.png)

This is *not* a place to ask questions.  For that, go to [discussions](https://github.com/remarkjs/remark/discussions)

### Your environment

*   **OS**: Ubuntu 18.04
*   **Packages**: online play ground https://remarkjs.github.io/react-markdown/
*   **Env**: Chrome 90.0.4430.9390.0.4430.93

### Steps to reproduce

Just go to the online demo and input `<script` somewhere, all the context after will run into a mess.

### Expected behavior

just render `<script` for `<script`

### Actual behavior

`<script` and all contet following will render as normal text

**Comment by wooorm** [comment]
That’s how CommonMark, the markdown specification used by most places and followed here, works.
