### ISSUE TITLE
@types/react peer dependency causes npm/yarn warnings

### ISSUE THREAD

**Issue by KieraDOG** [remarkjs/react-markdown#614]
### Subject of the issue

We don't use TypeScript in our project and after updating to the latest react-markdown version we started getting the following warning during the dependencies installation:

`warning " > react-markdown@6.0.2" has unmet peer dependency "@types/react@>=16".`

### Your environment

*   **OS**: MacOS
*   **Packages**: 
*   **Env**: 

node -v: v13.12.0
npm -v: 6.14.4

### Steps to reproduce

`npm init --yes && npm i react react-dom react-markdown`

### Expected behavior

Maybe the field peerDependenciesMeta can be added to package.json, so the dependency may be made optional.

With this, if the dependency is found on the project, versions will be compared, but no warning will be thrown if not installed.

```
  "peerDependenciesMeta": {
    "@types/react": {
      "optional": true
    }
  },
```

### Actual behavior

react-markdown installed in the non typescript env without peer dependency warning

**Comment by ChristianMurphy** [comment]
@KieraDOG I tested your example locally.

With latest `node` and `npm`
```
$ node --version
v16.4.2
$ npm --version
7.18.1
$ npm init --yes && npm install react react-dom react-markdown
```
I see no warning or error

---

I also tried walking back to node 12 and npm 6
```
$ node --version
v12.20.1
$ npm --version
6.14.10
$ npm init --yes && npm install react react-dom react-markdown
```
still no warning or error

---

and with yarn

```
$ node --version
v16.4.2
$ yarn --version
1.22.10
$ yarn init --yes && yarn add react react-dom react-markdown
```

still no error.

**Comment by ChristianMurphy** [comment]
Could you expand on why this is an issue?
Is it blocking a build processes? Or causing an issue with tests?

Typings don't contribute to bundle or build size, and even if TypeScript isn't explicitly used, they are often used by editors like VSCode, Atom, WebStorm, etc to improve code completion.

**Comment by KieraDOG** [comment]
> Could you expand on why this is an issue?
> Is it blocking a build processes? Or causing an issue with tests?
> 
> Typings don't contribute to bundle or build size, and even if TypeScript isn't explicitly used, they are often used by editors like VSCode, Atom, WebStorm, etc to improve code completion.

Not everybody are using typescript, so they won't have `@types/react` in the `package.json`, and also it does not make sense to have it in a JS react project

**Comment by ChristianMurphy** [comment]
> Not everybody are using typescript, so they won't have `@types/react` in the `package.json`

Right, and non of the package managers require you add it to your `package.json`, not even `yarn`.

> and also it does not make sense to have it in a JS react project

Again, it already is an optional choice whether to add it to `package.json` or not
And it can make sense to add it to a JS react project for improved developer experience in editors.

**Comment by wooorm** [comment]
I think a warning for non-TS users is better than an error for TS users.

**Comment by KieraDOG** [comment]
`peerDependenciesMeta` is exactly for this situation, with this, if the dependency is found on the project(typescript React), versions will be compared, but no warning will be thrown if not installed.

**Comment by KieraDOG** [comment]
> I think a warning for non-TS users is better than an error for TS users.

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

peerDependenciesMeta
When a user installs your package, npm will emit warnings if packages specified in peerDependencies are not already installed. The peerDependenciesMeta field serves to provide npm more information on how your peer dependencies are to be used. Specifically, it allows peer dependencies to be marked as optional.

For example:

{
  "name": "tea-latte",
  "version": "1.3.5",
  "peerDependencies": {
    "tea": "2.x",
    "soy-milk": "1.2"
  },
  "peerDependenciesMeta": {
    "soy-milk": {
      "optional": true
    }
  }
}
Marking a peer dependency as optional ensures npm will not emit a warning if the soy-milk package is not installed on the host. This allows you to integrate and interact with a variety of host packages without requiring all of them to be installed.

**Comment by wooorm** [comment]
> Specifically, it allows peer dependencies to be marked as optional.

If no warning is emitted anymore, then, well, that quite defeats the purpose of having it at all? And we do need it for TS users: TS users should handle on the warning, you can ignore the warning.

**Comment by wooorm** [comment]
See https://github.com/remarkjs/react-markdown/pull/615#issuecomment-877374710
