### ISSUE TITLE
Module not found: Can't resolve 'property-information/hast-to-react.json'

### ISSUE THREAD

**Issue by foucdeg** [remarkjs/react-markdown#617]
### Subject of the issue

When running my app with a newly installed react-markdown 6.0.2, I get the following warning in the console, and my build fails:

> Module not found: Can't resolve 'property-information/hast-to-react.json'

### Your environment

*   **OS**: Ubunt / frontend running inside Docker Alpine
*   **Packages**: react-markdown 6.0.2
*   **Env**: Node 14 + npm

### Steps to reproduce

- `npm install react-markdown --save`
-  Import ReactMarkdown into a component
- `npm start`

### Expected behavior

My app should build properly.

### Actual behavior

My app doesn't build.

In node_modules/property-information, there is indeed no file named 'hast-to-react.json'.

**Comment by ChristianMurphy** [comment]
@foucdeg could you try clearing *node_modules* and running `npm install` again?
The file exists in the published package https://unpkg.com/browse/property-information@5.6.0/hast-to-react.json

The most likely scenarios of what could have happened include:

1. Your build tool isn't configured to import json files (please share what build tool you are using)
2. a network issue happened and npm was unable to download it
3. a script/process on your machine deleted the file
4. a manual resolution has been set that overrides the version of `property-information`

---

If you are looking for an example of a fully setup environment, see this codesandbox with create-react-app as the build tool https://codesandbox.io/s/react-markdown-debug-forked-xjk8q

**Comment by harrygr** [comment]
I have the same problem (`react-markdown` 6.0.2). 

I can see the version of `property-information` that was installed as a dependency of `react-markdown` is 5.1.0 (not 5.6.0 as in your example. We can see that the file does not exist in 5.1.0: https://unpkg.com/browse/property-information@5.1.0

```
$ yarn why property-information                                             
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "property-information"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "property-information@5.1.0"
info Reasons this module exists
   - "react-markdown" depends on it
   - Hoisted from "react-markdown#property-information"
   - Hoisted from "@svgr#webpack#@svgr#plugin-jsx#rehype-parse#hast-util-from-parse5#property-information"
   - Hoisted from "@svgr#webpack#@svgr#plugin-jsx#rehype-parse#hast-util-from-parse5#hastscript#property-information"
info Disk size without dependencies: "156KB"
info Disk size with unique dependencies: "192KB"
info Disk size with transitive dependencies: "192KB"
info Number of shared dependencies: 1
✨  Done in 0.46s.
```

Perhaps `react-markdown` should declare `^5.3.0` for `property-information` as this seems to be the earliest version that includes this file.

**Comment by wooorm** [comment]
@harrygr could you try and follow Christian’s advise on updating dependencies?

**Comment by harrygr** [comment]
@wooorm I did try that advise with no success. However I declared a selective resolution in my package.json which fixed it:

```
"resolutions": {
   "property-information": "^5.6.0"
 }
```

I think the dependency version for `property-information` should be updated in this repo though
