### ISSUE TITLE
Add attribute to every generated element for scoped CSS

### ISSUE THREAD

**Issue by LoganDark** [remarkjs/react-markdown#620]
### Problem

I use scoped CSS. What this means is the CSS only applies to elements that are marked with a `data-v-<hash>` attribute ([library here](https://github.com/gaoxiaoliangz/react-scoped-css/)). The problem is that `react-markdown` does not allow me to add this attribute to the elements it generates, meaning my CSS does not apply unless I use `/deep/`.

### Feature suggestion

Let me specify props to be passed to all children - it could include the `data-v-<hash>` attribute so that my styles apply.

### Alternatives

Perhaps you could document how to do this with existing features, or leave a pointer in this issue's comments

**Comment by ChristianMurphy** [comment]
This can be done with a rehype plugin that visits every element adding attributes.
http://unifiedjs.com/learn/recipe/tree-traversal/ and http://unifiedjs.com/learn/guide/create-a-plugin/ introduce how to do this.
