### ISSUE TITLE
Takes many milliseconds to render a small document, which adds up

### ISSUE THREAD

**Issue by LoganDark** [remarkjs/react-markdown#621]
### Subject of the issue

Hello, I'm currently having an issue with react-markdown where even with no plugins it is taking a couple (or more) milliseconds to process a document - I'm displaying around a hundred previews on-screen at once and this causes my renders to take upwards of 150ms.

### Your environment

*   **OS**: Windows 10 Home 2004 build 19041.928
*   **Packages**: react-markdown 6.0.2
*   **Env**: Node 16.4.0, npm 7.18.1, create-react-app with react-scripts 4.0.3, Google Chrome 91.0.4472.77

### Steps to reproduce

Render around a hundred small markdown documents on-screen.

Pop this URL into your browser https://tc5uu.csb.app/ and start the React profiler. Click the button and you'll see that each re-render easily takes 100ms or more.

Is this my fault? Is there some optimization opportunity I should take or...?

**Comment by wooorm** [comment]
What is a real world use case for rendering 100 of live changing documents? 🤔
It's quite the task to set up 100 live regions, so maybe an alternative solutions is better.
Imo this seems fine for this edge case

**Comment by LoganDark** [comment]
> What is a real world use case for rendering 100 of live changing documents? 🤔
None, that's not what I'm using it for. But react-markdown offers no way to process a non-changing document only once. So every render takes 150ms

**Comment by wooorm** [comment]
Your example generates a new state every rerender. That it is the same, is something React can’t know because it’s not in the state. react-markdown does not provide special hooks for this because React can already handle state.

**Comment by LoganDark** [comment]
> Your example generates a new state every rerender. That it is the same, is something React can’t know because it’s not in the state. react-markdown does not provide special hooks for this because React can already handle state.

My method of updating state is just a way to cause the component to re-render. Here the only thing that changes is the onClick prop of the button since that is not in a useCallback. But all the react-markdowns re-render their content causing the render to take 150ms.

**Comment by ChristianMurphy** [comment]
> None, that's not what I'm using it for. But react-markdown offers no way to process a non-changing document only once

If the document is unchanging consider rendering serverside at build time.
https://github.com/remarkjs/react-remark offers a static hook for next.js
https://github.com/wooorm/xdm#integrations offers integrations with many build tools, which could be used directly if you want mdx, or could be adapted to work with remark/markdown.

> Should ReactMarkdown be a pure component?

No, `PureComponent` and `memo` come with memory overhead, it becomes significant when each render comes with different content, which many/most `react-markdown` users will have.
It should not be enabled by default.
https://dmitripavlutin.com/use-react-memo-wisely

**Comment by ChristianMurphy** [comment]
> I slapped a `React.memo` over my `Markdown` component, and performance instantly got WAY better.

That certainly is one approach.
Another would be to add a `key` to content https://reactjs.org/docs/lists-and-keys.html#keys so React can identify if they have changed, without needing to keep many copies of the content.
Or even better, since the content is static, server side rendering, as noted in my previous comment.

**Comment by LoganDark** [comment]
> > None, that's not what I'm using it for. But react-markdown offers no way to process a non-changing document only once
> 
> If the document is unchanging consider rendering serverside at build time.
> https://github.com/remarkjs/react-remark offers a static hook for next.js
> https://github.com/wooorm/xdm#integrations offers integrations with many build tools, which could be used directly if you want mdx, or could be adapted to work with remark/markdown.

This is UGC fetched at runtime, it cannot be statically compiled.

> > Should ReactMarkdown be a pure component?
> 
> No, `PureComponent` and `memo` come with memory overhead, it becomes significant when each render comes with different content, which many/most `react-markdown` users will have.
> It should not be enabled by default.
> https://dmitripavlutin.com/use-react-memo-wisely

I'll continue to use it for my own use case because that cuts down renders significantly (almost by an order of magnitude).

> > I slapped a `React.memo` over my `Markdown` component, and performance instantly got WAY better.
> 
> That certainly is one approach.
> Another would be to add a `key` to content https://reactjs.org/docs/lists-and-keys.html#keys so React can identify if they have changed, without needing to keep many copies of the content.

How would that prevent ReactMarkdown from re-rendering?

> Or even better, since the content is static, server side rendering, as noted in my previous comment.

Content is not static, it is just never changed after being rendered the first time

**Comment by LoganDark** [comment]
I'll close this issue since avoiding re-renders seems to be _the_ solution to this problem; maybe re-open it if you would like to track making renders less computationally expensive.

**Comment by ChristianMurphy** [comment]
> This is UGC fetched at runtime, it cannot be statically compiled.

Next.js can serverside render dynamically fetched content

> How would that prevent ReactMarkdown from re-rendering?

`key` is how react decides whether to rerender content or not.
It is often used in lists for efficient change detection, however it can be used on most elements, including those outside lists.

> Content is not static, it is just never changed after being rendered the first time

not changing is literally definition of static :slightly_smiling_face: 

---

To round out, rendering Markdown (rendering anything really) takes time.
Saying "I wish it was faster" will get agreement all around, but isn't actionable or helpful.
Concrete suggestions to improving the rendering pipeline informed by runtime profiling are welcome!

Rendering less is often a good approach to managing performance.
Caching rarely is, and can often come with unintended side effects.

**Comment by LoganDark** [comment]
> Next.js can serverside render dynamically fetched content

This is not a web application and will not be used over the Internet.

> `key` is how react decides whether to rerender content or not.

No it's not. `key` is how React decides whether to keep an existing component instance from before, or update it with new props. It has nothing to do with whether or not the component gets re-rendered.

> not changing is literally definition of static 🙂

By static I assumed you meant bundled with the application at build time. My bad.

> Rendering less is often a good approach to managing performance.
> Caching rarely is, and can often come with unintended side effects.

I am being as conservative as possible here. I have concluded that any Markdown component with the same plugins, options & text content will always render the same output. And I have also concluded that having it re-rendered every time a parent component updates is far too expensive and causes very noticeable lag and freezing. So caching is the only thing to do here. Especially since you say the slowness is expected behavior.

**Comment by ChristianMurphy** [comment]
> This is not a web application and will not be used over the Internet

These are important details.
What is your intended delivery method?
What are react and react-dom being used for if not for a web app or web view?

> Especially since you say the slowness is expected behavior.

This library is designed to handle dynamic content on the web.
You are using it to handle static content (not on the web?).

For it's intended use, it's fairly fast.
It may not be suited for your intended use.

From the tidbits you've shared I gather it is a storefront of some kind.
Could you share more? remark and unified have a number of ways to use them, one may be a better fit.

> I have concluded that any Markdown component with the same plugins, options & text content will always render the same output.

That is not always the case.
Both plugins and custom component renderers can have side effects, where the same content will not produce the same end document.

**Comment by LoganDark** [comment]
> Both plugins and custom component renderers can have side effects, where the same content will not produce the same end document.

Sorry, I should have been more clear - I don't use any non-deterministic plugins.

Anyway, I realize I'm raising more questions which I can't really answer - I have solved my issue now, thank you for your input.
