### ISSUE TITLE
A lot of types breaking on 6.0.3

### ISSUE THREAD

**Issue by heldr** [remarkjs/react-markdown#625]
Hi,

With the Typescript strict [code style refactor](https://github.com/remarkjs/react-markdown/commit/1562cfa827a546a2656ecc2cf0638e5f2231a07a) from v6.0.2 to v6.0.3 a lot of types are breaking. Example:

- React.memo markdown elements
- Props are mismatching in most of custom components

Shouldn't this be a major release?

**Comment by ChristianMurphy** [comment]
@heldr sorry you ran into some trouble.
Could you please fill out the issue template https://raw.githubusercontent.com/remarkjs/.github/main/.github/ISSUE_TEMPLATE/1-bug.md
and provide an example of what you're seeing either in a [codesandbox](https://codesandbox.io/) or [fenced codeblock](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown)
You haven't provided enough information for us to be able review and suggest next steps.

**Comment by heldr** [comment]
Never mind, the reason was removal of `ReactBaseProps` type.
