### ISSUE TITLE
Table render failed. react-markdown + remak-gfm

### ISSUE THREAD

**Issue by luffyZh** [remarkjs/react-markdown#629]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown: latest  remark-gfm: latest

### Steps to reproduce

![image](https://user-images.githubusercontent.com/17840558/128842019-568631a2-d5fe-467e-b203-bd262d658b56.png)

```js
import ReactMarkdown from "react-markdown";
import gfm from "remark-gfm";

const value = `
# 标题1

## 标题2

可以的，写得不错

## 代码

## 图片

![](https://musicfe.nos-jd.163yun.com/582d36e7-9097-4e14-a269-047ba2c41ea5.png)

## 表格
|  表头   | 表头  |
|  ----  | ---- |
| 单元格  | 单元格 |
| 单元格  | 单元格 |
`;

export default function App() {
  return (
    <div>
      <ReactMarkdown remarkPlugins={[gfm]} children={value} />
    </div>
  );
}

```

https://codesandbox.io/s/crimson-rain-uzxig?file=/src/App.js

### Expected behavior

no crash，no throw error，table render normal

### Actual behavior

Throw Error

### Runtime

Node v14

### Package manager

npm v6

### OS

macOS

### Build and bundle tools

Webpack

**Comment by sdjnes** [comment]
Also experiencing the same issue.

It seems the issue is with `remark-gfm@2.0.0`. An interim solution is to downgrade to `1.0.0`.

**Comment by luffyZh** [comment]
@sdjnes yes，downgrade `1.0.0` works, but i think the bug needs to be fixed~

**Comment by wooorm** [comment]
https://github.com/remarkjs/react-markdown/issues/626

**Comment by wooorm** [comment]
Solved in https://github.com/remarkjs/react-markdown/commit/02bac837bf141cdb8face360fb88be6fa33ab194
