### ISSUE TITLE
Issue with multi-line code (triple backtick)?

### ISSUE THREAD

**Issue by GonzaloGM** [remarkjs/react-markdown#630]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.0.0

```### Steps to reproduce

import React from 'react'
import ReactDOM, { render } from 'react-dom'
import Markdown from 'react-markdown'

const input = `
Most of the data you want is here:
\`\`\`{
  "test": "ok",
  "test2": "ok2"
}\`\`\`
`
render(
  <Markdown
    children={input}
    components={{
      code: props => {
        console.log('CODE2222 props', props)
        return <div></div>
      }
    }}
  />,
  document.getElementById('root')
)

```

### Expected behavior

Code inside backticks should be correctly parsed. The first part should not be chopped.

### Actual behavior

The first part of the code is chopped, and if you log the `props` when using `components`, you get this:

```{className: "language-{", node: Object, children: ["  \"test\": \"ok\",↵  \"test2\": \"ok2\"↵}↵"]}```

![image](https://user-images.githubusercontent.com/77448/128937036-498ccc4b-711f-4d10-a602-2177fbc41082.png)

![image](https://user-images.githubusercontent.com/77448/128937780-6b81f6ce-11c8-46ab-a42c-29d443fde1d2.png)

It happened with an old version (4.x), I just upgraded to 6.0.0 and the issue seems to persist.

Not quite sure if the issue is `react-markdown` or one of its dependencies. If so, please let me know and I'll file the issue where it corresponds. Thanks for your work, btw, it works great!

Using this in a React app with react-app-rewired, running in Chrome latest.

### Runtime

Other (please specify in steps to reproduce)

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment]
This isn't a bug, it's how markdown works https://spec.commonmark.org/0.30/#fenced-code-blocks,
if you try the same content on GitHub (also CommonMark besed) for example:

````markdown
```{
  "test": "ok",
  "test2": "ok2"
}```
````

renders as:

```{
  "test": "ok",
  "test2": "ok2"
}```
```

this is because the content after the first `\`\`\`` is part of the code fence, while the part after the second is not.
And is why the output shows `language-{` for the block.

If you want to show json in a code block, use
````markdown
```json
{
  "test": "ok",
  "test2": "ok2"
}
```
````

which renders as 

```json
{
  "test": "ok",
  "test2": "ok2"
}
```

**Comment by GonzaloGM** [comment]
@christianmurphy thanks for the explanation and link to the docs, Christian, I really appreciate it! Sorry for the no-issue and I'll see how I can work around this then :)
