### ISSUE TITLE
 Module "assert" has been externalized for browser compatibility and cannot be accessed in client code.

### ISSUE THREAD

**Issue by Snnny** [remarkjs/react-markdown#632]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.0

### Steps to reproduce

import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm'
<ReactMarkdown children={'# hello'} remarkPlugins={[remarkGfm]}></ReactMarkdown>

### Expected behavior

show hello

### Actual behavior

Uncaught Error: Module "assert" has been externalized for browser compatibility and cannot be accessed in client code.
    at Object.get (browser-external:assert:3)
    at go (create-tokenizer.js:213)
    at main (create-tokenizer.js:198)
    at Object.write (create-tokenizer.js:124)
    at fromMarkdown (index.js:117)
    at parser (index.js:15)
    at Function.parse2 [as parse] (index.js:273)
    at ReactMarkdown (react-markdown.js:102)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)

### Runtime

Node v12

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
Vite seems to specify that, in development, development code is loaded: https://github.com/vitejs/vite/blob/ed16488591b7dfac7e54d96f67c6f3674368b0cc/packages/vite/src/node/plugins/resolve.ts#L654.
The development code for micromark includes assertions: https://github.com/micromark/micromark#size--debug.
As importing certain builtin node modules is quite common, e.g., code often depends on `path` or `url`, I’m assuming you can configure vite to include `assert`, too. Other bundlers allow this as well, so Vite should too.
These options might help: https://vitejs.dev/config/#dep-optimization-options

**Comment by Snnny** [comment]
but I never config ,here is my vite.config.ts:


export default () => {
  return {
    // css 预处理器
    css: {
      preprocessorOptions: {
        less: {
          javascriptEnabled: true,
        },
      },
    },
    // 别名
    resolve: {
    },
    // 接口代理
    server: {
      proxy: {
      },
    },
    // 打包
    build: {
      rollupOptions: {
        cssCodeSplit: true,
      },
      outDir: currConf.outputPath,
      commonjsOptions: { transformMixedEsModules: true },
    },
    // 插件
    plugins: [
      reactRefresh(),
      checker({
        typescript: true,
        overlay: false,
        // enableBuild: false,
        eslint: { files: ['./src'], extensions: ['.ts', '.tsx'] },
      }),
    ],
  };
};

**Comment by ChristianMurphy** [comment]
https://github.com/vitejs/vite/discussions/4479#discussioncomment-1121552 suggests using browserify polyfills.
Or as @wooorm suggests https://vitejs.dev/config/#dep-optimization-options may be able to be used to tell vite to include a dependency like `assert` anyway.

**Comment by or2008** [comment]
getting the same error with webpack 5, why is the issue closed?

**Comment by wooorm** [comment]
because it’s not an issue here, but with how your bundler is configured.

**Comment by JounQin** [comment]
I'm using browserify `assert` polyfill on development, and `@rollup/plugin-strip` and `alias: { assert: 'src/libs/none.ts' }` on production. `src/line/none.ts` is an empty file. It runs very well now. But I'd prefer it can be 'fixed' in `micromark`.

**Comment by wooorm** [comment]
> and `alias: { assert: 'src/libs/none.ts' }` on production

micromark does not include `assert` in production, so that should not be needed.

**Comment by JounQin** [comment]
> micromark does not include assert in production, so that should not be needed.

Wow, that's great to hear.

**Comment by mellson** [comment]
@JounQin can you share your config file so I can see how you use the assert polyfill?

**Comment by JounQin** [comment]
> @JounQin can you share your config file so I can see how you use the assert polyfill?

Just `yarn add -D assert`, and add `'process.env.NODE_DEBUG': undefined` into `define` of `vite.config.ts` for [`node-util`](https://github.com/browserify/node-util/pull/62#issuecomment-908343918).

**Comment by ChristianMurphy** [comment]
I'd recommend against pinning outdated/unmaintained versions of dependencies.

Instead consider the polyfilling approach suggested in https://github.com/remarkjs/react-markdown/issues/632#issuecomment-909123237

**Comment by wooorm** [comment]
Assert isn't used for about a year now. Run 'npm install' or equivent to get updates.

**Comment by olejorgenb** [comment]
> Assert isn't used for about a year now. Run 'npm install' or equivent to get updates.

Not directly, but I got the same and similar errors from the the transient dependency micromark (I'm at react-markdown 8.0.3): 

```
$ yarn list | grep react-markdown
├─ react-markdown@8.0.3
$ yarn why micromark-factory-label
=> Found "micromark-factory-label@1.0.0"
info Reasons this module exists
   - "_project_#react-markdown#remark-parse#mdast-util-from-markdown#micromark#micromark-core-commonmark" depends on it
```

`yarn install` (not sure about npm) did not upgrade these transient dependencies as a result of upgrading react-markdown. Deleting my lock-file and node_modules and reinstalling would likely have worked come to think of it.

I can report that yarn does not downgrade the packages after removing the `resolutions` section after a install, so this step can luckily be used non-permanently.


> I'd recommend against pinning outdated/unmaintained versions of dependencies.

They're not pinned though? Only a lower limit on the versions. But yeah, it's not pretty. But neither is poly-filling something for a dependency IMO.

**Comment by wooorm** [comment]
```
$ npm info micromark-factory-label version
1.0.2
```

> yarn install (not sure about npm) did not upgrade these transient dependencies 

It should.

**Comment by olejorgenb** [comment]
Not sure how valuable it is to continue this thread further, but I ended up digging more for my own sake, so might as well note it here in the off-chance someone find it helpful.

- I use yarn **1.x** (1.22.10), yarn workspaces and have a lockfile
- Rolling back my lockfile and package.json, upgrading `react-markown`, and running `yarn install` does not upgrade the `micromark-*` packages on my system. (`yarn list --depth | grep micromark` and the error is trigged in my development build)
- Removing the lockfile and running `yarn install` result in the latest versions of the `micromark-*` packages

Based on this I believe yarn (1.x) does not touch transient dependencies unless required when using a lockfile [1]. This (https://github.com/yarnpkg/yarn/issues/4986) open yarn issue about `yarn upgrade` seems to be related, although running `yarn upgrade` **does** upgrade the `micromark-*` packages here. (but not `yarn upgrade react-markdown@8.0.3`)

To avoid havoc in the lockfile the temporarily `"resolutions" { ... }` section seems like a cumbersome trick to make yarn do what I want.

That being said, my project contains a number of dependencies so there might be something going on with one package blocking another which I've missed.

PS: I didn't understand what you meant by the `npm info micromark-factory-label version` command? This just shows the latest version of the package, no?

[1]  I guess that makes sense in some way - less changes -> less chance of trouble? But the upgraded package is likely tested the most using the most up to date dependencies so I'm not convinced of this logic. Assuming yarn is able to distinguish transiently-dependent-only packages from other "root" packages my gut-feeling is that it would be better to upgrade them. The equation might be more complex if the packages is dependent on by multiple other packages though.
