### ISSUE TITLE
ReactMarkdown v7 error in TypeScript

### ISSUE THREAD

**Issue by minimal-ui-kit** [remarkjs/react-markdown#633]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"react-markdown": "^7.0.0"

### Steps to reproduce

```sh
node_modules/react-markdown/lib/react-markdown".ReactMarkdown' has no exported member 'ReactMarkdownOptions'.
```

```js
export default function Markdown({ ...other }: ReactMarkdown.ReactMarkdownOptions) {
  return (
    <MarkdownWrapperStyle>
      <ReactMarkdown
        rehypePlugins={[rehypeRaw, rehypeHighlight]}
        components={components}
        {...other}
      />
    </MarkdownWrapperStyle>
  );
}

```

Usage : 

```js
<Markdown children={source} />
```

### Expected behavior

No error

### Actual behavior

Works fine in version 6

### Runtime

Node v14

### Package manager

npm v7

### OS

macOS

### Build and bundle tools

Create React App

**Comment by wooorm** [comment]
Soo, what’s the error? 🤔

**Comment by minimal-ui-kit** [comment]
```sh
node_modules/react-markdown/lib/react-markdown".ReactMarkdown' has no exported member 'ReactMarkdownOptions'.
```

I get this error when I upgrade to version 7

**Comment by wooorm** [comment]
It's now called 'Options'

**Comment by minimal-ui-kit** [comment]
``` js
import ReactMarkdown, { Options } from 'react-markdown';

export default function Markdown({ ...other }: Options) {
  return (
    <MarkdownWrapperStyle>
      <ReactMarkdown
        rehypePlugins={[rehypeRaw, rehypeHighlight]}
        components={components}
        {...other}
      />
    </MarkdownWrapperStyle>
  );
}

```

@wooorm  It's working, Thanks!
