### ISSUE TITLE
Markdown doesn't display hyperlinks anymore

### ISSUE THREAD

**Issue by vivekkeswaran** [remarkjs/react-markdown#634]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

5.0.0 - latest

### Link to runnable example

The below code displays hyperlinks with v4.3.1

### Steps to reproduce

The below code displays hyperlinks with v4.3.1:

```
import React from "react";
import Markdown from "react-markdown";

export default function App() {
  const instructions =
    "Note   -    Below are the links\n\nLink 1 - http://google.com\n\nLink 2 - http://google.com";

  return (
    <Markdown escapeHtml linkTarget="_blank">
      {instructions}
    </Markdown>
  );
}
```

Converted DOM Elements:
```
<div id="root">
     <p>Note   -    Below are the links</p>
     <p>Link 1 - <a target="_blank" href="http://google.com">http://google.com</a></p>
     <p>Link 2 - <a target="_blank" href="http://google.com">http://google.com</a></p>
</div>
```

<img width="382" alt="Screen Shot 2021-08-16 at 11 12 43 AM" src="https://user-images.githubusercontent.com/25623782/129595224-fb02b5dd-7675-4c02-b1e7-70d8e9a554d2.png">

The same code stopped working from v5.0.0:

```
<div id="root">
      <p>Note   -    Below are the links</p>
      <p>Link 1 - http://google.com</p>
     <p>Link 2 - http://google.com</p>
</div>
```

<img width="335" alt="Screen Shot 2021-08-16 at 11 14 00 AM" src="https://user-images.githubusercontent.com/25623782/129595428-e461de00-6f72-4c2e-a135-bc19a3ee6ced.png">

### Expected behavior

Display as hyperlinks when a string contains link

### Actual behavior

Doesn't render as hyperlink instead a plain string in a p tag

### Runtime

Node v12

**Comment by wooorm** [comment]
Please read the changelog or readme: use `remark-gfm`: https://github.com/remarkjs/react-markdown

**Comment by vivekkeswaran** [comment]
@wooorm thanks for pointing me to the new implementation. Can you help me how this use can be converted to use the new remark-gfm?

**Comment by ChristianMurphy** [comment]
@vivekkeswaran https://github.com/remarkjs/react-markdown#use

**Comment by wooorm** [comment]
(specifically the second example)
