### ISSUE TITLE
Creating a custom renderer for an image does not affect the style of the rendered image (and probably also other types of elements)

### ISSUE THREAD

**Issue by J0eppp** [remarkjs/react-markdown#636]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown@7.0.0

### Link to runnable example

https://codesandbox.io/s/react-markdown-debug-forked-g789i?file=/src/App.js

### Steps to reproduce

# Step to reproduce
I wanted to add the `max-width` property to the images that are rendered with this library through a custom `img` renderer. 
I tried doing this with the code you can see in the CodeSandbox. 

# Hacky workaround
Adding the following style to your CSS file fixes the issue, but it might cause other issues:
```css
p > img {
    max-width: 80%;
}
```

### Expected behavior

![Expected behavior](https://i.imgur.com/yFDS0os.jpg)
[Imgur URL](https://imgur.com/a/mlJyX3c)

### Actual behavior

![Actual behavior (zoom 100%)](https://i.imgur.com/nbK1y0I.png)
![Actual behavior (zoom 30%)](https://i.imgur.com/NofSz9v.png)
[Imgur URL](https://imgur.com/a/mlJyX3c)

### Runtime

Node v14

### Package manager

npm v7

### OS

Linux

### Build and bundle tools

Create React App

**Comment by J0eppp** [comment]
Note: I might be making a small mistake or trying to use an outdated method, if that's the case please tell me :)

**Comment by ChristianMurphy** [comment]
in version 6 and later `renderers` became `components`, and it now uses the html name `img` instead of `image` https://github.com/remarkjs/react-markdown/blob/main/changelog.md#600---2021-04-15

For example https://codesandbox.io/s/react-markdown-debug-forked-6789z

**Comment by J0eppp** [comment]
Thank you! I noticed `renderers` where deprecated and I indeed changed it to `components` but it still didn't work, I didn't know about the `img` part though so that fixes it. Thanks!

**Comment by pkonda2019** [comment]
@ChristianMurphy Thanks for your answer. It helps me a bit, but not completely because I need it in bit different way.
In markdown source I have some other content along with image, like below:
```
const markdownSource = `
![Image](https://www.iheartradio.ca/image/policy:1.15731844:1627581512/rick.jpg?f=default&$p$f=20c1bb3)Exclusive **Aloe Vera Bio Ferment** helps skin retain moisture. Created using responsibly sourced and Certified Organic **Aloe Extract Powder, Lactobacillus** and **Activated Aloe Water**.

`;
```

I want image should be render in separate <div> and text content should be render in another <div>.
Using your example [](https://codesandbox.io/s/react-markdown-debug-forked-6789z) I can add <div> element to Image but not able to add the same to text content. Below is the sample:

```
<Markdown
      components={{
        img: (props) => <div><img {...props} style={{ maxWidth: "80px" }} alt="" /></div>
      }}
    >
      {markdownSource}
    </Markdown>
```
Can you please help me hover here if you have any idea about how to do it ?
Thanks in advance.

**Comment by ChristianMurphy** [comment]
@pkonda2019 folks are happy to help.
Please open a [new discussion](https://github.com/orgs/remarkjs/discussions/new) for a new question, rather than tacking on to an unrelated issue, thanks!
Link to discussions: https://github.com/orgs/remarkjs/discussions
