### ISSUE TITLE
Remark Breaks and other bunch of remark plugins are stop working in > 6.0.0 version after removed plugins

### ISSUE THREAD

**Issue by ubsdev** [remarkjs/react-markdown#637]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.0

### Steps to reproduce

```javascript
import breaks from 'remark-breaks';
import newlines from 'remark-new-lines';

// in render
<ReactMarkdown
                remarkPlugins={[newlines, breaks]}
            > 'markdown syntax'</ReactMarkdown>
```

### Expected behavior

Other remarks plugins should work fine

### Actual behavior

Only remark-gfm plgin is working. 

### Runtime

Node v14

### Package manager

npm v6

### OS

Windows

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
Make sure to update both plugins and `react-markdown`
However, `remark-breaks` should work fine. What error are you seeing?

**Comment by ubsdev** [comment]
> Make sure to update both plugins and `react-markdown`
> However, `remark-breaks` should work fine. What error are you seeing?

Both are latest 
remark-breaks: v3.0.1

I have tried only one plugin at a time. but still, it gives the same error.

**Comment by wooorm** [comment]
Which error?

**Comment by ubsdev** [comment]
I am getting this error
`Missing parser to attach 'remark-breaks'`

**Comment by wooorm** [comment]
That is not an error remark-breaks 3 or even 2 throws. It’s an error that remark-breaks v1 [used to throw](https://github.com/remarkjs/remark-breaks/blob/e5251cc377ecb9b72387bd30d5684391acb84867/index.js#L13). Please update all your remark and remark-markdown related projects and try again

**Comment by ubsdev** [comment]
Updating all remarks dependency this issue is solved.

Thanks, @wooorm.
