### ISSUE TITLE
New 7.x version contains nodejs related code which breaks in browsers

### ISSUE THREAD

**Issue by jalik** [remarkjs/react-markdown#641]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.1

### Steps to reproduce

Run any code with <ReactMarkdown /> component with Webpack 5 + Babel to compile.

### Expected behavior

No error should be thrown in the browser's console.

### Actual behavior

First, there is a compilation error when Webpack tries to compile the project, stating that "assert" needs to be polyfilled. It was automatically done in webpack <5, so now the error arises, this can be fixed by installing the "assert" package which polyfills the assert module from nodejs.

Secondly, after fixing the previous error, another one comes out, it says that "process is not defined", again something related to nodejs, it can be found in the "util" npm package that contains this line `if (process.env.NODE_DEBUG) {`. It can be fixed by defining the NODE_DEBUG environment variable in webpack config.

Both errors are related to nodejs and many React apps are rendered in browsers as SPA. So I really think that the lib and its dependencies must not contain nodejs related code like "assert" and "process". It's a pain to have to change the config or add extra packages manually just to fix errors that could be avoided by using browser friendly packages.

Also I was surprised to not see any issue about this, so I think that a lot of people are still using bundlers that polyfills automatically (like Webpack 4), but when they will upgrade to newer versions, they will obviously face this problem.

### Runtime

Node v16

### Package manager

npm v7

### OS

Linux

### Build and bundle tools

Webpack

**Comment by ChristianMurphy** [comment]
assert is not used in `react-markdown` itself, but in `micromark`.
Please follow and/or add to the discussion there (https://github.com/micromark/micromark/issues/87)

There was also some related discussion for `vite` which may also apply to webpack, specifically around handling of `--conditions` and whether the development or production version of micromark is used (https://github.com/remarkjs/react-markdown/issues/632)

**Comment by bmakan** [comment]
Until this gets resolved properly, you can use this workaround with webpack 5:
```js
npm i -D assert process

// webpack.config.js
const { ProvidePlugin } = require('webpack');

...
plugins: [
    new ProvidePlugin({
         'process/browser',
    }),
],
...
```

**Comment by helixd-2k18** [comment]
It doesn't working for React 18 and Webpack 5. Even not working through providing.
