### ISSUE TITLE
Do not work with next.js

### ISSUE THREAD

**Issue by akucharczyk** [remarkjs/react-markdown#642]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

^7.0.0

### Steps to reproduce

1. Create a nextjs Project
2. Create page with loading react-markdown 
```
import React from 'react'

import ReactMarkdown from 'react-markdown'

export function Markdown({ markdown }: { markdown: string }) {
  return (
    <article>
      <ReactMarkdown>{markdown}</ReactMarkdown>
    </article>
  )
}
```

### Expected behavior

The markdown should be render my markdown

### Actual behavior

I get following error

<img width="948" alt="Screenshot 2021-09-01 at 15 26 43" src="https://user-images.githubusercontent.com/25926746/131679637-fc6c88cc-e9ac-4c25-92e2-4d4f1684f921.png">

### Runtime

Node v14

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
@akucharczyk sorry you ran into a spot of trouble.
The solution to this is linked from the readme  and the changelog (https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c, the "I'm having problems with ESM and Next.js" section)
Specifically see https://nextjs.org/blog/next-11-1#es-modules-support
