### ISSUE TITLE
react-is version doesn't match react version

### ISSUE THREAD

**Issue by guoyunhe** [remarkjs/react-markdown#643]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown@6.0.3

### Steps to reproduce

```
npm i -S react@16 react-dom@16 react-markdown
npm list react-is
```

In my project, I still use react 16.x. When installing react-markdown, it forces react-is@17.x. It works fine but it won't be deduped with other react-is@16.x. So in my build result, it contains two version of react-is.

### Expected behavior

It should allow react-is 16.x and 17.x

### Actual behavior

It only allows react-is 17.x

### Runtime

Node v14

### Package manager

npm v7

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
Closing as the corresponding PR (GH-644) was also closed.
