### ISSUE TITLE
ReactMarkdown tag doesn't render when passed a state property

### ISSUE THREAD

**Issue by junk1ord** [remarkjs/react-markdown#647]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"react-markdown": "^7.0.1",

### Steps to reproduce

I am using the `SimpleMDE` editor, whose handler function updates the `body` property from the state of my class component,

```javascript
state = {
    imageUrl: "",
    title: "",
    excerpt: "",
    body: "",
    submitMessage: "",
    submitMessageTextColor: "",
    optionsForMDE: {
      hideIcons: ["preview", "side-by-side", "fullscreen"],
    },
  };
```

Outside of the return statement,

```javascript
const {
      imageUrl,
      title,
      body,
      submitMessage,
      submitMessageTextColor,
      optionsForMDE,
    } = this.state;
```

This is how I call the SimpleMDE editor in the return statement of my render function of the class component.

```javascript
<SimpleMDE onChange={this.onBodyChange} options={optionsForMDE} />
<ReactMarkdown source={body} />
```

While the body property of the state is being updated dutifully each time I add on to the MDE, but the `ReactMarkdown` tag doesn't render in the DOM.

### Expected behavior

This is my current UI. 

![image](https://user-images.githubusercontent.com/55103906/132992211-326ac18f-e583-4928-99bf-21db12634204.png)

Whatever inputs I give in the field should be updated in the space at right, like upon adding a sample image URL, a title and some excerpt along with the content of the Project, this is what is should look like.

![image](https://user-images.githubusercontent.com/55103906/132992272-d8aaab8a-b291-4354-a0c2-3f040d90fd6f.png)

### Actual behavior

The contents of the MDE Editor are not rendered as expected. In fact in the developer tools, the whole `<ReactMarkdown />` is missing and isn't at all rendered.

### Runtime

Node v14

### Package manager

npm v6

### OS

Windows

### Build and bundle tools

Webpack, Create React App

**Comment by ChristianMurphy** [comment]
`source` is not a valid property.
Use `children` to pass markdown to `react-markdown`
for example https://codesandbox.io/s/react-markdown-debug-forked-mlvlj?file=/src/App.js
