### ISSUE TITLE
Cannot compile with webpack 5

### ISSUE THREAD

**Issue by zhangriyueming** [remarkjs/react-markdown#652]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.1.0

### Steps to reproduce

Set webpack configuration as [here](https://github.com/vfile/vfile/issues/38#issuecomment-640479137).

Build with webpack 5.

### Expected behavior

Compiled without errors.

### Actual behavior

Got errors below:

```
ERROR in ./node_modules/uvu/node_modules/kleur/index.mjs 4:11-18
Module not found: Error: Can't resolve 'process/browser' in '/Users/sowicm/repos/monoweb/packages/web/node_modules/uvu/node_modules/kleur'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

### Runtime

Node v12

### Package manager

npm v6

### OS

macOS

### Build and bundle tools

Webpack

**Comment by nikhilDigiplusIT** [comment]
Can anyone provide me the solution for this ?

**Comment by nikhilDigiplusIT** [comment]
> @zhangriyueming were you able to solve it, and if so, how?

What can be the solution for this ?
` plugins: [
      new webpack.ProvidePlugin({
             process: 'process/browser',
      }),
  ]`
I tried this but didn't work.

**Comment by ChristianMurphy** [comment]
This discussion is continuing at https://github.com/remarkjs/remark/discussions/903

**Comment by ashleydavis** [comment]
This issue is still happening, yet this is issue is marked as closed.

**Comment by ChristianMurphy** [comment]
@ashleydavis read the previous comment before yours, and the solution in that thread
