### ISSUE TITLE
Support Autolinking Phone Numbers

### ISSUE THREAD

**Issue by steverecio** [remarkjs/react-markdown#655]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

There is support to autolinking URLs but phone numbers have to be manually linked, ie: `[+1 (800) 111-1111](tel:1800111111)`

### Solution

Would be great if phone numbers are autolinked similarly to URLs

### Alternatives

The alternatives are building the links directly with markdown syntax or creating another plugin for this functionality

**Comment by wooorm** [comment]
You can create a plugin.
It’s not standard markdown.
This project is about  standard markdown.
You can do many other things with plugins.

**Comment by ChristianMurphy** [comment]
To add on, the unified (remark) website includes guides introducing plugins https://unifiedjs.com/learn/
And there are some plugins which could help inspire how it could work like remark-gemoji https://github.com/remarkjs/remark-gemoji
