### ISSUE TITLE
Emphasis after comma or full stop is broken

### ISSUE THREAD

**Issue by JayChetty** [remarkjs/react-markdown#656]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

5.0.0 - 7.1.0

### Link to runnable example

https://codesandbox.io/s/react-markdown-playground-forked-ozl7e?file=/src/App.js

### Steps to reproduce

Added emphasis starting before a full stop (see sandbox example)

### Expected behavior

Text shows emphasised

### Actual behavior

Stars(*) appear in output

### Runtime

Node v16

### Package manager

yarn v2

### OS

macOS

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
This is how markdown works, try it on GitHub:

```markdown
This*,appears to be*,broken
```

This*,appears to be*,broken
