### ISSUE TITLE
Line breaks are not respected in blockquotes, and inline code blocks

### ISSUE THREAD

**Issue by EvHaus** [remarkjs/react-markdown#659]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown@7.0.1

### Link to runnable example

https://codesandbox.io/s/still-monad-5p15j?file=/src/app.tsx

### Steps to reproduce

It appears that line breaks for blockquotes aren't respected and they all get merged into one line. To reproduce use this markdown:

```
> each one of these
> should be on
> a new line
```

### Expected behavior

The expected output is something like this:

```
<blockquote>
  each one of these<br/>
  should be on<br/>
  a new line
</blockquote>
```

or 

```
<blockquote>
  <p>each one of these</p>
  <p>should be on</p>
  <p>a new line</p>
</blockquote>
```

### Actual behavior

The actual current output is:

```
<blockquote>
  <p>
    each one of these
    should be on
    a new line
  </p>
</blockquote>
```

### Runtime

Node v16

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Webpack

**Comment by EvHaus** [comment]
Maybe related, but it seems like code blocks have the same problem:

```
`On one line`
`On another line`
```

The above code should be on two separate lines, but it ends up all on one line. [Link to sandbox](https://codesandbox.io/s/misty-butterfly-wu528?file=/src/app.tsx).

**Comment by wooorm** [comment]
Re block quotes: This is how markdown works.
Re “code blocks”: those are not code blocks. [See this cheatsheet, tutorial, and spec for more info](https://commonmark.org/help/).

If you custom behavior, use plugins. Such as https://github.com/remarkjs/remark-breaks

**Comment by EvHaus** [comment]
`remark-breaks` was what I needed. Sorry I missed that and thanks for the quick response!

**Comment by get-codin** [comment]
@EvHaus hey man, how did you solve the issue? I'm still having problems even if I added remark-breaks.

```
const processedContent = await remark()
      .use(html)
      .use(remarkBreaks)
      .process(matterResult.content)
   const contentHtml = processedContent.toString()
```

**Comment by EvHaus** [comment]
@get-codin Hmm. For me, just adding `remark-breaks` did the trick. I'm using it through `react-markdown` so the implementation is a bit different.

I did notice that the order of plugins often makes a big difference. Maybe try swapping the order of `.use(html)` and `.use(remarkBreaks)`?

**Comment by soichih** [comment]
Commenting to myself..  if I need to *preserve* newlines between lines, I need to add backslash (\) at the end of the line

```
> each one of these \
> should be on \
> a new line
```

Becomes 

```
<blockquote>
  <p>
    each one of these<br>
    should be on<br>
    a new line
  </p>
</blockquote>
```
