### ISSUE TITLE
react-markdown v4 with vfile >=4.2.1?

### ISSUE THREAD

**Issue by janpe** [remarkjs/react-markdown#660]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I am still using react-markdown v4 because I depend on some of the remark plugins that are not supported for v5 and newer. One problem with this is that react-markdown v4 is using unified v6 which is using vfile v2 and I'd like to have vfile 4.2.1 or newer to have this feature included: https://github.com/vfile/vfile/pull/59

Do you see that a update to react-markdown v4 could be possible still?

### Solution

Update react-markdown to use a version of unified that has at least 4.2.1 of vfile. Or possibly also do a new v6 release of unified which has at least 4.2.1 of vfile.

### Alternatives

Porting the unsupported remark plugin, but that is a task that seems to require a lot more effort and learning to understand the plugins on a deeper lever.

**Comment by wooorm** [comment]
`react-markdown` v4 and vfile v2 is seriously old. Trying to upgrade things inside v4 will result in breaking changes. So it can’t be a “backport”.

---

I strongly recommend updating, a lot of things have been improved. Do ask questions about plugins if you have them.
