### ISSUE TITLE
iFrame Not Rendering

### ISSUE THREAD

**Issue by jrock2004** [remarkjs/react-markdown#661]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.1.1

### Steps to reproduce

I am trying to get my iframe to embed YouTube videos and when it renders, all I see is the markup text and not that actual iframe. Here is the link to my repo where the Next.js code is https://github.com/jrock2004/personal-blog . I even tried forking one of the code sandbox above and see the same issue https://codesandbox.io/s/eloquent-agnesi-x39sn

### Expected behavior

When page loads, I should see an iframe

### Actual behavior

Just see the code text

### Runtime

Node v16

### Package manager

npm v6

### OS

macOS

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
Sorry you ran into a spot of trouble @jrock2004 

It looks like you want to have HTML mixed in markdown?
Have you tried https://github.com/remarkjs/react-markdown#appendix-a-html-in-markdown ?

**Comment by jrock2004** [comment]
@ChristianMurphy Sorry that I missed this link. That makes it work. Thank you
