### ISSUE TITLE
Feature: Improve dev experience for clickable remark-gfm task lists

### ISSUE THREAD

**Issue by EvHaus** [remarkjs/react-markdown#662]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

At ZenHub, we're trying to build an experience of a markdown editor similar to GitHub's. Specifically we want to have users be able to create task lists and then allow those task lists to be clickable. Like this:

- [ ] Task One
- [ ] Task Two
- [ ] Task Three

Note how in GitHub you can click on the checkboxes to mark them as completed without having to open the markdown editor. When clicking the checkbox GitHub is smart to understand what markdown implication this has (ie. going from `[ ]` to `[x]`) and submits the edit to the backend service accordingly.

Trying to do this with `react-markdown` and `remark-gfm` is proving to be more difficult than I was hoping it would be. To accomplish this my first strategy was to:

## First attempt

- Let `remark-gfm` generate the `<input />` checkboxes as it does.
- Ensure `rawSourcePos` is enabled
- Replace those input checkboxes in `react-markdown` via the `components` prop so that a custom `onChange` event can be added to control the interactivity

Here is what that looks like: https://codesandbox.io/s/lucid-kare-ivito?file=/src/app.tsx

As you can see, there's a problem. There is no way to determine which checkbox is clicked from the `onChange` event if we replace the `input` element because those elements don't include the "sourcePosition" property. I couldn't find a way around this, so I moved on to another solution...

## Second attempt

To get around the first problem, my next attempt was to:

- Let `remark-gfm` generate the `<input />` checkboxes as before
- Ensure `rawSourcePos` is enabled
- Replace all `li` component in `react-markdown` via the `components` prop
- Look for `li` elements with the `task-list-item` class to determine if they are task list checkbox items, if they are, inject an `onChange` event and pass along the source position value from the `li` element to determine which checkbox is clicked.

Here is what that solution looks like: https://codesandbox.io/s/determined-water-9hmwy?file=/src/app.tsx

Things work great! Bug there's a serious bug. The code assumes that the `<input />` element is always the first child of of the `<li />` for the task list. But it turns out that this is not a reliable way to select the `<input />` because if you can put paragraphs in your lists like this:

```
- [ ] Task One

- [ ] Task Two

- [ ] Task Three
```

Then the `<input />` is nested in a `<p>` and its location is not as easy to determine. I could hack around this to consider this scenario but it's starting to make the code quite fragile and difficult to maintain.

I wonder if maybe there's a better solution.

## Option 1

I think the best solution here would be to somehow ensure that `sourcePosition` is passed down into the `input` element that `remark-gfm` generates. Then I can simply replace the `input` component as I tried in my first solution and guarantee that I can find that checkbox no matter where it gets rendered.

## Option 2

Create an option in `remark-gfm` that allows me to pass custom props to the `<input />` element. Ideally I would be able to pass the `onChange` handler to that input and that hander would have access to the current position value. I could take it from there.

### Alternatives

🤷 Do nothing. I can just hack around it to ensure all possible nested `input` cases are supported in my implementation.

**Comment by ChristianMurphy** [comment]
cross linking with https://github.com/remarkjs/react-markdown/issues/607
in some cases source position cannot be known https://github.com/remarkjs/react-markdown/issues/607#issuecomment-864175918
a suggested solution from that issue https://github.com/remarkjs/react-markdown/issues/607#issuecomment-864361480 may address the edge case where the `<input>` is not the first child.

**Comment by EvHaus** [comment]
Thanks @ChristianMurphy. That looks like the same issue as I'm having as well!

**Comment by wooorm** [comment]
I’m open to a guide somewhere that shows how to do this, for example similar to [how GitHub handles heading IDs safely](https://github.com/rehypejs/rehype-sanitize#example-headings-dom-clobbering), but I don’t think this requires changes in the core and existing libraries.

I recommend looking at how GitHub implements this. In chrome, in the sources tab, you can search for `task-lists`, which is the custom element they use. GH ships source maps to production (or at least Chrome picks them up), which will point you to `app/assets/modules/github/behaviors/task-list.ts`.

In short, it looks like they don’t worry about positional info, but instead operate “on the AST” (actually, they use regexes). Every list item with a tasklist checkbox has a `data-position="x,y"`, presumably of the pattern `x,y{,x,y}*` where each `x` is the position of the list in its parent and `y` the position of the item in its parent list. When (un)checking a checkbox, a regex pattern looks for it, and attempts to move it to a different place.

You before worry about making the code fragile: well, looking at how GH implements this, it gets ***much*** more fragile.

Note that, in React event handlers, you can also access normal DOM events, which lets you access parent DOM nodes!

---

I’m closing this, as this does not currently reflect a change needed in this package, but instead seems to be more of a question. I’m open to discussing some more, though perhaps somewhere else?
