### ISSUE TITLE
Installing react-markdown causes build error with AWS Amplify

### ISSUE THREAD

**Issue by SpencerMiller23** [remarkjs/react-markdown#663]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Latest

### Steps to reproduce

I have been working on a React/Amplify project and once I installed react-markdown I was no longer able to deploy the project. Using npm 8.1.0.

### Expected behavior

I should be able to build/deploy the project as usual.

### Actual behavior

                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2021-12-09T13:05:09.143Z [WARNING]: npm
2021-12-09T13:05:09.143Z [WARNING]: WARN prepare removing existing node_modules/ before installation
2021-12-09T13:05:12.969Z [WARNING]: npm
2021-12-09T13:05:12.970Z [WARNING]: ERR! bindings not accessible from watchpack-chokidar2:fsevents
2021-12-09T13:05:12.990Z [WARNING]: 
2021-12-09T13:05:12.990Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2021-12-09T13_05_12_969Z-debug.log
2021-12-09T13:05:12.990Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [
                                 1 verbose cli   '/root/.nvm/versions/node/v12.21.0/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v12.21.0/bin/npm',
                                 1 verbose cli   'ci'
                                 1 verbose cli ]
                                 2 info using npm@6.14.11
                                 3 info using node@v12.21.0
                                 4 verbose npm-session 405d773babed1dd9
                                 5 info prepare initializing installer
                                 6 verbose prepare starting workers
                                 7 verbose prepare installation prefix: /codebuild/output/src788184865/src/niftable--app
                                 8 verbose prepare using package-lock.json
                                 9 warn prepare removing existing node_modules/ before installation
                                 10 verbose checkLock verifying package-lock data
                                 11 verbose teardown shutting down workers.
                                 12 info teardown Done in 0.001s
                                 13 verbose stack Error: bindings not accessible from watchpack-chokidar2:fsevents
                                 13 verbose stack     at reqAddr (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:159:17)
                                 13 verbose stack     at /root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:129:22
                                 13 verbose stack     at Array.forEach (<anonymous>)
                                 13 verbose stack     at addChild (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:128:40)
                                 13 verbose stack     at /root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:133:7
                                 13 verbose stack     at Array.forEach (<anonymous>)
                                 13 verbose stack     at addChild (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:128:40)
                                 13 verbose stack     at /root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:133:7
                                 13 verbose stack     at Array.forEach (<anonymous>)
                                 13 verbose stack     at addChild (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:128:40)
                                 13 verbose stack     at /root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:133:7
                                 13 verbose stack     at Array.forEach (<anonymous>)
                                 13 verbose stack     at addChild (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:128:40)
                                 13 verbose stack     at /root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:133:7
                                 13 verbose stack     at Array.forEach (<anonymous>)
                                 13 verbose stack     at addChild (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:128:40)
                                 14 verbose cwd /codebuild/output/src788184865/src/niftable--app
                                 15 verbose Linux 4.14.252-195.483.amzn2.x86_64
                                 16 verbose argv "/root/.nvm/versions/node/v12.21.0/bin/node" "/root/.nvm/versions/node/v12.21.0/bin/npm" "ci"
                                 17 verbose node v12.21.0
                                 18 verbose npm  v6.14.11
                                 19 error bindings not accessible from watchpack-chokidar2:fsevents
                                 20 verbose exit [ 1, true ]
2021-12-09T13:05:13.001Z [ERROR]: !!! Build failed
2021-12-09T13:05:13.001Z [ERROR]: !!! Non-Zero Exit Code detected
2021-12-09T13:05:13.001Z [INFO]: # Starting environment caching...
2021-12-09T13:05:13.001Z [INFO]: # Uploading environment cache artifact...
2021-12-09T13:05:13.101Z [INFO]: # Environment caching completed
Terminating logging...

### Runtime

Node v16

### Package manager

Other (please specify in steps to reproduce)

### OS

Windows

### Build and bundle tools

Create React App

**Comment by ChristianMurphy** [comment]
@SpencerMiller23 The error you shared points to chokidar2 and fsevents, which are not part of `react-markdown`, the relevant line from the logs being:
```
19 error bindings not accessible from watchpack-chokidar2:fsevents
```
And look to be related to trying to install MacOS specific dependency (https://github.com/fsevents/fsevents) on a Windows machine.

If there are additional logs which indicate this is `react-markdown` related, please share them.
