### ISSUE TITLE
Cant generate external link with React-markdown

### ISSUE THREAD

**Issue by obsd** [remarkjs/react-markdown#665]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.1

### Steps to reproduce

I'm trying to create an external link, like that: 
```md
[(Click here to install Docker)]("https://docs.docker.com/get-docker/")
```
```js
        <ReactMarkdown
            linkTarget="_blank"
            components={{
              code({ node, inline, className, children, ...props }) {.....            },
          }}
        >
          {instructions.find((lang) => lang.language === activeLanguage)?.instructions}
        </ReactMarkdown>

```

### Expected behavior

Open the link in new tab

### Actual behavior

Url is:
`about:blank#blocked`
![image](https://user-images.githubusercontent.com/1475778/146681500-c4e28fef-8bfd-4554-872a-6336b81b2372.png)

### Runtime

Node v16

### Package manager

npm v6

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
That’s not how markdown works. Please read up on how markdown works.

**Comment by ChristianMurphy** [comment]
Adding some additional context, you can learn about markdown syntax here: https://commonmark.org/help/
Your particular issue is that the link you generated isn't a valid markdown link, for example https://codesandbox.io/s/markdown-links-dtq21?file=/src/app.tsx

**Comment by obsd** [comment]
Thank you for the context @ChristianMurphy !
