### ISSUE TITLE
Why is that converting the MD file to HTML doesn't include any line breaks?

### ISSUE THREAD

**Issue by get-codin** [remarkjs/react-markdown#670]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

^8.0.0

### Steps to reproduce

This is from the NextJS learning path.

Here is the link to the steps I followed

https://nextjs.org/learn/basics/dynamic-routes/polishing-post-page#:~:text=%3Cdiv%20dangerouslySetInnerHTML%3D%7B%7B%20__html%3A%20postData.contentHtml%20%7D%7D%20/%3E

![image](https://user-images.githubusercontent.com/78736225/153448586-760313f1-314a-4ec3-8f29-0dda34196d3d.png)

Basically, after passing the processed MD file (postData.contentHtml) to dangerouslySetInnerHTML, once you view it on the page, it ignores the basic property of the p tags, wherein there should be line breaks before and after them.

This is the code that I followed in the NextJS tutorial that uses Remark
https://nextjs.org/learn/basics/dynamic-routes/render-markdown#:~:text=const%20processedContent%20%3D%20await%20remark()%0A%20%20%20%20.use(html)%0A%20%20%20%20.process(matterResult.content)%0A%20%20const%20contentHtml%20%3D%20processedContent.toString()

### Expected behavior

There should line breaks in this rendered article

![image](https://user-images.githubusercontent.com/78736225/153449017-c3461cc0-84a0-4a54-a371-e55b3a379334.png)

### Actual behavior

this is the result upon rendering in NextJS

![image](https://user-images.githubusercontent.com/78736225/153448205-5d3a675c-b78d-413b-8599-07e3af80f987.png)

And the HTML that's passed is this:

![image](https://user-images.githubusercontent.com/78736225/153448440-8b4030d0-e766-4c3f-99e4-2be8bc1beadc.png)

### Runtime

Node v16

### Package manager

npm 8

### OS

Windows

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Hi Dominique. Your actual / expected are the same picture.

But you’re likely looking for this answer: **this is how markdown and HTML work**. There should not be “linebreaks” in random places.

**Comment by get-codin** [comment]
Thank you for the reply!

So, this is the markdown file that I processed using remark:

![image](https://user-images.githubusercontent.com/78736225/153551258-9e073987-9a4c-4203-9aa4-dcfab2abf343.png)

I expected it to have breaks between paragraphs like in the picture after it is processed into HTML. I'm wondering as to why it doesn't have those spaces after it is processed.

Processed result:

![image](https://user-images.githubusercontent.com/78736225/153551363-1fae4437-f47c-4517-a3ad-0ae976036783.png)

**Comment by wooorm** [comment]
That can be done with CSS. And it normally happens.

But you have CSS on your website that explicitly says to remove all that space between paragraphs and headings!
