### ISSUE TITLE
`components` should recieve `source` for `sourcePosition` to be useful.

### ISSUE THREAD

**Issue by futpib** [remarkjs/react-markdown#671]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I'd like to access the source string in a custom component I pass in `components` prop. I get `sourcePosition` and could've used to to slice the source to get the source code of the component, but I do not get the source string in props.	

### Solution

`components` should receive `source` next to `sourcePosition`.

### Alternatives

Capture the source from lexical environment of the component, this would force me to re-create `components` on each re-render.

**Comment by wooorm** [comment]
the `sourcePos` you want is already support. See the readme.

For `source`, you can pass the `children` you’re passing to this component, also to your components, as you mention. You can prevent the recreation you note, by doing something like this:

```js
<Markdown children={state.value} components={createComponents(state)} />


function createComponents(state) {
  return {
    div(props) {
      console.log(props, state);
    }
  }
}
```

**Comment by futpib** [comment]
That's exactly what I write in `Alternatives` and it is a sub-optimal solution (recreating components on each re-render).
