### ISSUE TITLE
HTML is not rendered

### ISSUE THREAD

**Issue by Sjeiti** [remarkjs/react-markdown#677]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.1

### Steps to reproduce

`<ReactMarkdown>{'here is a <strong>strong</strong> **element**'}</ReactMarkdown>`

### Expected behavior

Since Markdown is an HTML superset all HTMLElements are expected to be rendered correctly. 

### Actual behavior

HTML is rendered as text.

### Runtime

Node v14

### Package manager

yarn 2

### OS

Windows

### Build and bundle tools

Webpack

**Comment by ChristianMurphy** [comment]
This is expected and explained in the readme https://github.com/remarkjs/react-markdown#appendix-a-html-in-markdown
As well as how to enable HTML if wanted.
