### ISSUE TITLE
Component is invoked twice -- once without console.log enabled?

### ISSUE THREAD

**Issue by cwellsx** [remarkjs/react-markdown#681]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.0

### Link to runnable example

https://codesandbox.io/s/dazzling-johnson-97lgd5?file=/src/app.tsx

### Steps to reproduce

Run the runnable example

### Expected behavior

Rendering the markdown should invoke HeadingRenderer which as a side-effect should write the headings to the h2Links array.

Then the h2Links array is rendered as a table-of-contents.

### Actual behavior

Each heading is written twice into the h2Links array and so appears twice in the table of contents.
Using a debugger with a breakpoint shows that HeadingRenderer is called twice for each heading.

What's very strange is that the console.log output looks like this (twice):

```
Rendering 
pushing first 0 
pushing second 2
```

instead of like this: 

```
Rendering 
pushing first 0 
pushing first 1 
pushing second 2
pushing second 3
```

as if the console.log is ineffective when it's called for the second time.

**Comment by ChristianMurphy** [comment]
Taking several steps back, if you want a table of contents, consider using https://github.com/remarkjs/remark-toc

In your example it's unclear what issue the increment would cause.
Nor is it clear that `react-markdown` is causing it, it seems more likely to be a conflict arising from some combination of:
* nesting components
* using both `useRef` and `useState` for state management
* potential conflict between the `useEffect` and the multiple types of state

**Comment by wooorm** [comment]
It’s a React thing that things are called multiple times and should avoid side effects, so I’ll close this as its expected behavior: it’s not a problem that can be solved in `react-markdown`. Feel free to ask questions in Discussions, though you might have more luck asking on React-specific boards. As Christian mentions, if you want a table of contents, consider using [`remarkjs/remark-toc`](https://github.com/remarkjs/react-markdown/issues/681) (or a similar remark/rehype plugin).
