### ISSUE TITLE
Re render children components

### ISSUE THREAD

**Issue by denisso** [remarkjs/react-markdown#684]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.2

### Link to runnable example

[See console log in this example ](https://codesandbox.io/s/7zi185?file=/src/App.tsx)

### Steps to reproduce

Using props children and update state component in which ReactMarkdown is placed. 

### Expected behavior

I expected that when processing the same markdown, the generated html would not change.

### Actual behavior

I connected MutationObserver for show mutations in html. And and use console.log in children components. We can see in the console log that the children components start every time and the html changes when the state of the component in which ReactMarkdown is located changes.

### Runtime

Node v17

### Package manager

npm 8

### OS

Windows, Linux

### Build and bundle tools

Create React App

**Comment by wooorm** [comment]
If you want to cache things in React, use hooks, e.g., https://reactjs.org/docs/hooks-reference.html#usememo.

**Comment by denisso** [comment]
Thank you for the answer dear wooorm.
How will hooks help me cache html changes? and why? I didn't ask for it. What worries me first of all is that imgs in html are being recreated, in the unchanged original markdown

**Comment by denisso** [comment]
And I've used hooks everywhere I can. Cool answer Bro

**Comment by ChristianMurphy** [comment]
Cross referencing the recent related discussion from `rehype-react` which gave some approaches https://github.com/rehypejs/rehype-react/issues/38

**Comment by denisso** [comment]
I will try to change my approach made in the [my exampleб which is published at the beginning](https://codesandbox.io/s/7zi185?file=/src/MarkdownComponent.tsx:1116-1890) using use Memo to the [proposed ](https://github.com/rehypejs/rehype-react/issues/38) memo 

```
 const ReactMarkdownMemo = React.useMemo(() => {
    // console.log("ReactMarkdownMemo render");

    const ComponentConstructor = () => (
      <ReactMarkdown
        children={markdown}
        components={{
          h1: headerParser,
          h2: headerParser,
          h3: headerParser,
          h4: headerParser,
          h5: headerParser,
          h6: headerParser,
          img({ node, className, children, ...props }) {
            const { src, alt, ...other } = props;
            console.log("render image");
            return (
              <img data-src={src} alt={alt} {...other} {...{ className }} />
            );
          }
        }}
      />
    );
    return ComponentConstructor;
  }, [headerParser, markdown]);
  return <ReactMarkdownMemo />;
```

**Comment by ChristianMurphy** [comment]
Right, and that is discussed further down the discussion in https://github.com/rehypejs/rehype-react/issues/38.

React manages the render pipeline, and chooses what to render using referential equality.
Markdown is dynamic content so it doesn't necessarily have consistent references, so it can (and will) re-render at times.
So if you want a custom component, passed to the `components` prop, to only render when it's properties have changed, wrap the custom component with `useMemo` (in your example, the custom `img` element).

**Comment by denisso** [comment]
[Christian Murphy](https://github.com/ChristianMurphy), Thank you very much, React.memo helped

[My example with React.memo](https://codesandbox.io/s/react-markdown-re-render-forked-rw2okp?file=/src/MarkdownComponent.tsx)

**Comment by kolyabazlov** [comment]
@ChristianMurphy u can't just image how u helped me, I spent 4 days have been trying different approaches, thx
