### ISSUE TITLE
Render error with react markdown in storybook

### ISSUE THREAD

**Issue by DawnMD** [remarkjs/react-markdown#686]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

^8.0.3

### Steps to reproduce

Use `ReactMarkdown` inside a component and use the parent component as a story for the storybook.

### Expected behavior

Storybook should render the markdown as a html block with the specific designs attached.

### Actual behavior

It throws an error 'vfile__WEBPACK_IMPORTED_MODULE_1__.VFile is not a constructor` and sometimes storybook renders nothing and sometimes it shows 
![image](https://user-images.githubusercontent.com/34785917/166186199-5370ecec-b8fe-4999-a4b9-a0eb9f8e3bbe.png)

But when `ReactMaekdown` is removed the story renders just fine

### Runtime

Node v16

### Package manager

yarn 1

### OS

Windows

### Build and bundle tools

Gatsby

**Comment by wooorm** [comment]
This package is ESM-only. This error message seems to indicate that your tools are not configured for ESM. More information is linked in the [install section](https://github.com/remarkjs/react-markdown#install) and can be found in many of the other issues asking similar things.
