### ISSUE TITLE
React Markdown Broken On Remix 

### ISSUE THREAD

**Issue by mehulmpt** [remarkjs/react-markdown#688]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Latest

### Steps to reproduce

- ReactMarkdown component errors out with the following error when deploying to Cloudflare Pages + Remix

![Screenshot 2022-05-07 at 3 27 10 AM](https://user-images.githubusercontent.com/10388889/167221485-8cfcdceb-dcc0-4568-8ae8-0b2afefddc07.png)

Steps:
1. Clone this repo: https://github.com/mehulmpt/react-markdown-cloudflare-remix (this repo is Remix barebones TS + Cloudflare Pages starter template)
2. `npm install` and `npm run dev`
3. You'll see this error:

<img width="749" alt="Screenshot 2022-05-07 at 3 34 24 AM" src="https://user-images.githubusercontent.com/10388889/167222075-4db5a824-0856-4376-aa31-e241916d97d1.png">

### Expected behavior

ReactMarkdown should work fine

### Actual behavior

It crashes with an error

**Comment by ChristianMurphy** [comment]
This is an issue in the polyfill being provided by Remix.
And is likely related to this step in the ESBuild process https://github.com/remix-run/remix/blob/b4fd6eeb98a29f4cd1170ecf67f610ebee45da3b/packages/remix-dev/compiler.ts#L353
This is an issue which should be raised to the remix team https://github.com/remix-run/remix/issues
