### ISSUE TITLE
Bold & Italics adjacent to Bold starting with non-alphanumeric characters parsed incorrectly

### ISSUE THREAD

**Issue by g-leon-bj** [remarkjs/react-markdown#691]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.3

### Steps to reproduce

This might be an issue with some underlying parser or any other related library, I'm not sure.

If you write something like `***bold & italics*****. only bold**` the last part is not parsed correctly. This happens when you start the only-bold part with any non-alphanumeric character.

Here is an example:

![image](https://user-images.githubusercontent.com/105813451/170517147-b6577192-dcc1-4e64-badd-0405fe6045d8.png)

### Expected behavior

`***bold & italics*****. only bold**`

should render as:

> _**bold & italic**_**. only bold**

### Actual behavior

`***bold & italics*****. only bold**`

renders as:

> _**bold & italic**_\*\*. only bold**

**Comment by wooorm** [comment]
That's commonmark, see: ***bold & italics*****. only bold**
