### ISSUE TITLE
Links with underscore at the end are not properly handled

### ISSUE THREAD

**Issue by wack-overflow** [remarkjs/react-markdown#693]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.3

### Link to runnable example

https://codesandbox.io/s/react-markdown-link-ending-in-underscore-bug-tsbdzw?file=/src/App.js

### Steps to reproduce

If the source includes a link that ends in an underscore, it will not include the underscore in the link, and navigate to the incorrect url. Example: https://twitter.com/albert_

### Expected behavior

The underscore should be included in the link

### Actual behavior

It is not included

### Runtime

Node v16

### Package manager

npm 8

### OS

Windows

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
Did you see how GH does this in your "problem" section?
This is expected behavior

**Comment by ChristianMurphy** [comment]
The GitHub flavored markdown (GFM) plugin is expected to match GFM standard.
If you believe the GFM standard should change, it should be raised with them https://github.com/github-community/community

**Comment by wooorm** [comment]
You use `remark-gfm`, it follows GFM.
