### ISSUE TITLE
Ability to collapse multiple line breaks into a maximum of 2 line breaks

### ISSUE THREAD

**Issue by paule89123** [remarkjs/react-markdown#694]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

When a user enters some text into a markdown component, all of the linebreaks get preserved. This is better than not preserving them at all, but it means that if a user enters lots of linebreaks, all of those linebreaks are preserved which leads to big empty spaces, which looks a bit messy.

### Solution

It would look cleaner if multiple linebreaks collapsed into a maximum of 2 linebreaks, so that you get a nice sized space between 2 paragraphs, not a giant space between paragraphs.

### Alternatives

Not aware of any solutions.

**Comment by wooorm** [comment]
The behaviour in a textarea, which you seem to mention, is not handled by this project.

**Comment by wooorm** [comment]
This sounds unrelated
