### ISSUE TITLE
Multiline not supported

### ISSUE THREAD

**Issue by lavablelavs** [remarkjs/react-markdown#695]
### Initial checklist

- [x] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"react-markdown": "^8.0.3"

### Steps to reproduce

Enter multiline text

### Expected behavior

Multiline text should appear

### Actual behavior

Only one line is rendered
<img width="1620" alt="Screen Shot 2022-06-25 at 11 32 07 AM" src="https://user-images.githubusercontent.com/64797361/175758054-cb64eefb-e553-4c82-90ee-17f7e9fe5d19.png">

### Runtime

Node v16

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
What you're seeing is how markdown works.
See https://commonmark.org/help/tutorial/03-paragraphs.html

If you want to add breaks where markdown usually wouldn't add them, consider using https://github.com/remarkjs/remark-breaks

**Comment by lavablelavs** [comment]
Ahh okay - thank you for the clarification!
