### ISSUE TITLE
Add a FAQ to the readme

### ISSUE THREAD

**Issue by rexxars** [remarkjs/react-markdown#70]
Things like how to do syntax highlighting and anchoring headers comes up a lot. Should probably add some links to solutions for those kind of problems to the readme.

**Comment by JikkuJose** [comment]
Yes, same questions here! Any where to find the solution for them?

**Comment by QuicheSama** [comment]
@rexxars, advice on anchoring headers would be super rad.  If you give me the details I can add it to the README and get a PR ready.  Just let me know! 😃

**Comment by wooorm** [comment]
There are now many more examples in the readme
