### ISSUE TITLE
Ordered List's number overlaps

### ISSUE THREAD

**Issue by sanjipun** [remarkjs/react-markdown#701]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown v 8.0.3

### Steps to reproduce

- Add custom component for Ordered List
<img width="480" alt="image" src="https://user-images.githubusercontent.com/64313011/180598016-27b438ff-4e84-499a-ac8d-650e36c51198.png">

- Add Markdown 
![image](https://user-images.githubusercontent.com/64313011/180598054-e10bbbe4-51dd-473c-818c-7e82fe50c33f.png)

- Ordered list number overlaps for first ordered list
![image](https://user-images.githubusercontent.com/64313011/180598077-a3c15db2-6bc7-4d47-963a-447ad54424a8.png)

### Expected behavior

The number should not collapse for first ordered list

### Actual behavior

Number for first ordered list overlaps
![image](https://user-images.githubusercontent.com/64313011/180598114-13553106-563e-4417-a69f-e7d31bc91d70.png)

### Runtime

Node v16

### Package manager

yarn 1

### OS

macOS

### Build and bundle tools

Gatsby

**Comment by wooorm** [comment]
This is a problem with how you are using your components: it seems to be a different library.

You are wrapping all list items inside a single `<ListItem>` component.
You should instead overwrite `li` to use that component.
