### ISSUE TITLE
Display is wrong when using sub-list in list item greater than 10

### ISSUE THREAD

**Issue by martinratinaud** [remarkjs/react-markdown#705]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.3

### Steps to reproduce

Go to your demo https://remarkjs.github.io/react-markdown/

Paste this code

```
6.  **chapter 6**.
    
    1.  **subchapter i**. looks ok ...
        
7.  **Chapter 7**. with no subchapter seems ok too
        
8.  **Chapter 8**.
    
    1.  **Entire Agreement**. still ok

9.  **Chapter 9**.
    
    1.  **Entire Agreement**. still ok

10.  **Chapter 10**.
    
    1.  **Entire Agreement**. not ok anymore
 
11.  **Chapter 11**.
    
    1.  **Entire Agreement**. not ok anymore
```

### Expected behavior

list items are displayed the same way for list numbers above 10 and below 10

### Actual behavior

the sublist in 10 and 11 item are formatted as a `pre`

### Runtime

Node v16

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Next.js

**Comment by martinratinaud** [comment]
Some more infos:
- it's correct on https://markdownlivepreview.com/ 
- Github has the same problem, See below

----
6.  **chapter 6**.
    
    1.  **subchapter i**. looks ok ...
        
7.  **Chapter 7**. with no subchapter seems ok too
        
8.  **Chapter 8**.
    
    1.  **Entire Agreement**. still ok

9.  **Chapter 9**.
    
    1.  **Entire Agreement**. still ok

10.  **Chapter 10**.
    
    1.  **Entire Agreement**. not ok anymore
 
11.  **Chapter 11**.
    
    1.  **Entire Agreement**. not ok anymore

**Comment by remcohaszing** [comment]
It’s not a bug. Your indentation needs to match the position of the text after the list marker. For example:

```diff
  6.  **chapter 6**.
      
      1.  **subchapter i**. looks ok ...
          
  7.  **Chapter 7**. with no subchapter seems ok too
          
  8.  **Chapter 8**.
      
      1.  **Entire Agreement**. still ok
  
  9.  **Chapter 9**.
      
      1.  **Entire Agreement**. still ok
  
- 10.  **Chapter 10**.
+ 10. **Chapter 10**.
      
      1.  **Entire Agreement**. not ok anymore
   
  11.  **Chapter 11**.
      
-     1.  **Entire Agreement**. not ok anymore
+      1.  **Entire Agreement**. not ok anymore
```

As per the commonmark spec:

> The most important thing to notice is that the position of the text after the list marker determines how much indentation is needed in subsequent blocks in the list item. If the list marker takes up two spaces of indentation, and there are three spaces between the list marker and the next character other than a space or tab, then blocks must be indented five spaces in order to fall under the list item.



https://spec.commonmark.org/0.30/#example-254

**Comment by wooorm** [comment]
`markdownlivepreview.com` is wrong. Not remark or GFM, which all follow CommonMark.

**Comment by martinratinaud** [comment]
Thanks a lot for this thorough explanation and sorry for reporting a non-bug
