### ISSUE TITLE
Allow passing options for `remark-parse`

### ISSUE THREAD

**Issue by Ashish-Bansal** [remarkjs/react-markdown#706]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Hi there!

For the`remark-parse`, there's no way to provide the options to the parser. 

https://github.com/remarkjs/remark/blob/99179c6745a2173d07d5c3b46bad7df767e1989d/packages/remark-parse/lib/index.js#L9-L27

If someone needs to add `mdastExtensions`, we need to use `unified` directly. 

### Solution

Add a way to provide options for `remark-parse`. 

### Alternatives

N.A.

**Comment by ChristianMurphy** [comment]
Extensions can be added via remark plugins.
For example, that is what `remark-gfm` does https://github.com/remarkjs/react-markdown#use

Most existing extensions have a remark plugin already.
If you have a truly custom one, follow the same approach `remark-gfm` does https://github.com/remarkjs/remark-gfm/blob/b7af7f28a64f334ddd5514296743ede5aa4ba184/index.js#L18

**Comment by Ashish-Bansal** [comment]
cool, the way `remark-gfm` did it, it would work for us. 

Thanks for the quick help! @ChristianMurphy
