### ISSUE TITLE
MathJax in react-markdown

### ISSUE THREAD

**Issue by vladtimss** [remarkjs/react-markdown#708]
I tried to use rehypeMathJax and rehypeKatex plugins but it doesn't render syntax as 
```
\begin{align}
P(A \mid B) = \frac{P(B \mid A) \, P(A)}{P(B)}
\end{align}
```

it is my code
```
<ReactMarkdown
                remarkPlugins={[remarkMath, [remarkGfm, { singleTilde: false }]]}
                rehypePlugins={[
                    [
                        rehypeMathJaxCHtml,
                        {
                            chtml: {
                                fontURL: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/output/chtml/fonts/woff-v2',
                            },
                        },
                    ],
                    rehypeRaw,
                ]}
            >
                {value || ''}
            </ReactMarkdown>
```

which config should i use to render syntax as above?

only if i wrap in $ $
it will be render, but not center, although should render center

**Comment by ChristianMurphy** [comment]
> only if i wrap in `$ $` it will be render

Right, `$` the necessary syntax for math in markdown
https://github.com/remarkjs/remark-math/tree/main/packages/remark-math#syntax

> but not center, although should render center

Markdown by default does not add extra alignment styles.
The browser default of left align is followed.
If you'd like to center align content on the page you are welcome to add your own css.

**Comment by vladtimss** [comment]
@ChristianMurphy as we can see vscode ipynb or colab, we could see that in markdown cell they can render without $ and render syntax like this 
```
\begin{align}
P(A \mid B) = \frac{P(B \mid A) \, P(A)}{P(B)}
\end{align}
```

**Comment by ChristianMurphy** [comment]
>  we can see vscode ipynb or colab

I can't see, you haven't shared any runnable example, in a sandbox with react markdown or of colab.

> we could see that in markdown cell they can render without $ and render syntax like this

python and especially ipynb have their own flavor of markdown.
Remark and react markdown follow the commonmark standard https://commonmark.org/ and it's extensions.
They have significant differences.

You could customize the parser to support alternative syntax https://github.com/micromark/micromark#extending-markdown
But I'd caution against it, python's markdown flavor has a lot of non-standard and poorly documented quirks.

> could you explain what's wrong in my understanding of mathjax

This is a layer above mathjax, understanding markdown itself and its flavors.

**Comment by vladtimss** [comment]
@ChristianMurphy thank you very much for your explanation and help!
