### ISSUE TITLE
Can't parse two single-item ordered lists that are separated by a new line

### ISSUE THREAD

**Issue by ApplePieGiraffe** [remarkjs/react-markdown#709]
### Steps to reproduce

Create two (or more) ordered lists with a single item each and separate them with a new line:

```
- list 1

- list 2
```

### Expected behavior

The rendered output should be two ordered lists:

- list 1

- list 2

### Actual behavior

Two ordered lists are created, but the content inside each list item is wrapped in a `p` tag, causing the list item content to appear beneath its preceding bullet point:

```
-
    list 1
-
    list 2
```

### Runtime

Node v16

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
That's how markdown works, you can see it here on github too. You have a **blank line** between the two items. That makes the list loose. Loose lists get paragraphs.
See the spec for more information.
Remove the blank line of you don't want it.

**Comment by ApplePieGiraffe** [comment]
> That's how markdown works, you can see it here on github too. You have a **blank line** between the two items. That makes the list loose. Loose lists get paragraphs. See the spec for more information. Remove the blank line of you don't want it.

I see. Sorry for the trouble, then!

**Comment by ApplePieGiraffe** [comment]
> That's how markdown works, you can see it here on github too. You have a **blank line** between the two items. That makes the list loose. Loose lists get paragraphs. See the spec for more information. Remove the blank line of you don't want it.

Ohh—I see. Sorry for the trouble, then! 😅
