### ISSUE TITLE
Explicitly typed components cannot be easily passed due to broken children prop type

### ISSUE THREAD

**Issue by PurkkaKoodari** [remarkjs/react-markdown#711]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown@8.0.3

### Link to runnable example

https://stackblitz.com/edit/github-uwhlug?file=src%2Findex.tsx

### Steps to reproduce

I'm working in a codebase that uses a lot of components explicitly declared as `const SomeComponent: React.FC<Props>`. I'd like to pass an existing component to `react-markdown` without wrapping it in a function:

```tsx
import React, { HTMLAttributes, FC } from 'react';
import { HTMLAttributes, FC } from 'react'
import { Components } from 'react-markdown'
import { HeadingProps } from 'react-markdown/lib/ast-to-react'

// This is a <h1> with the props accepted by HTML's <h1>...
type H1Props = HTMLAttributes<HTMLHeadingElement>
const HtmlH1: FC<H1Props> = () => null

const components: Components = {
  // It doesn't work:
  h1: HtmlH1,
  // Works, but ugly:
  h2: (props) => <HtmlH1 {...props} />,
}

// This is a <h1> with the prop types wanted by react-markdown...
const ReactMarkdownH1: FC<HeadingProps> = () => null

// It can't be easily used as-is:
const element = <ReactMarkdownH1>Foo</ReactMarkdownH1>
```

### Expected behavior

I would expect the "vanilla" `h1` component to work with `react-markdown`.

### Actual behavior

I need to wrap the component to make it work.

Even though `HeadingProps` is assignable to `HTMLAttributes`, `ComponentType<HTMLAttributes>` isn't compatible with `ComponentType<HeadingProps>` since it would need the props to be assignable both ways.

### Potential fix

Changing [`ReactMarkdownProps.children`](https://github.com/remarkjs/react-markdown/blob/main/lib/complex-types.ts#L9) to `ReactNode` would seem to make the prop types compatible. However, it may be a breaking change for people who expect to get an array in `children` from `react-markdown`.

**Comment by ChristianMurphy** [comment]
@PurkkaKoodari This may be a bug, but I don't think it's one in `react-markdown`.
It seems to be more likely an issue in `@types/react`
If you trace the type back, the type being used comes from https://github.com/remarkjs/react-markdown/blob/85bb1e19d6e87c59e6bd864ebda5b1f04bc01937/lib/ast-to-react.js#L58

`ComponentPropsWithoutRef<'h1'>` reflects `HTMLAttributes<HTMLHeadingElement>`, minus the `ref` attribute which is not supported.

---

> Changing [ReactMarkdownProps.children](https://github.com/remarkjs/react-markdown/blob/main/lib/complex-types.ts#L9) to ReactNode would seem to make the prop types compatible.

I don't think so.
`NormalComponents` isn't used for `h1`.
`NormalComponents` is used for anything which isn't part of `SpecialComponents`
https://github.com/remarkjs/react-markdown/blob/85bb1e19d6e87c59e6bd864ebda5b1f04bc01937/lib/ast-to-react.js#L88

and `h1` is a special component
https://github.com/remarkjs/react-markdown/blob/85bb1e19d6e87c59e6bd864ebda5b1f04bc01937/lib/ast-to-react.js#L73-L75

**Comment by PurkkaKoodari** [comment]
The definition of `HeadingProps` as `ComponentPropsWithoutRef<'h1'> & ReactMarkdownProps` includes `children` both from `@types/react` (where it's `ReactNode`) and `ReactMarkdownProps` (where it's `ReactNode[]`). This results in a type of `ReactNode & ReactNode[]`, which looks a bit weird and is only satisfiable by `ReactNode[]`.

Like I said, it's mostly about choosing if you want to guarantee it being an array, or make the type compatible with ordinary components.

>>Changing [ReactMarkdownProps.children](https://github.com/remarkjs/react-markdown/blob/main/lib/complex-types.ts#L9) to ReactNode would seem to make the prop types compatible.

>I don't think so.

I tested this - modifying the `react-markdown` typings to `children: ReactNode` makes `HtmlH1` from my example assignable to `HeadingComponent`. (It doesn't make `ReactMarkdownH1` usable as-is, as it still requires `node`, but it also removes the error from having only one child.)

**Comment by remcohaszing** [comment]
Typically React children should be defined as `ReactNode`, not `ReactNode[]`. `ReactNode` is a union that includes an iterable of itself. One rarely needs to specify anything else as the `children` type.

Note that prior to `@types/react@18`, this is also how `FunctionComponent` was typed.

I’m not entirely sure how this is used, but I’m included to believe @PurkkaKoodari is correct and the type needs to be changed to `ReactNode` on our end.

**Comment by wooorm** [comment]
Resolved in https://github.com/remarkjs/react-markdown/commit/de252e8187d3458241a9e0b9ea16cab0f013ca92.
lib/complex-types.d.ts#L9 there was a) not needed, b) causing this.

We now use types based on `JSX.Element`, from `hast-util-to-jsx-runtime` (see https://github.com/remarkjs/react-markdown/commit/434627686e21d4bcfb4301417e0da2bb851d4391).

Released soon!
