### ISSUE TITLE
Cannot use react hooks where ReactMarkdown is rendered

### ISSUE THREAD

**Issue by karosowka13** [remarkjs/react-markdown#715]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.04

### Link to runnable example

Full example can be see [here](https://playcode.io/1025199).

### Steps to reproduce

I want to set up sections menu based on headers that are in the markdown.
When I call set state in `components` parser I've got an error.

e.g.

```
const headerParser = ({ node, className, children, level, ...props }: any) => {
      if (children === undefined) {
        console.log("returnm empty block");
        return <></>;
      }
      let text = children[0]?.props?.children[0];
      let href = children[0]?.props?.href;
      let id = href === "#" ? href.slice(1) : href;
      setSections([...sections, {title:text, level}])
      return (
        <node.tagName {...props} {...{ className }} id={id}>
          <a href={href}>{text}</a>
        </node.tagName>
      );
}
```

When I move set state to parent component and add `React.memo`, it works. But I cannot reset the sections menu when the components rerender. It just adds more records to it from previous views, which is no a goal.

The same with any other hook like `useEffect` etc.

### Expected behavior

The state should be change without infinite loop.

### Actual behavior

Error 

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Webpack, Create React App

**Comment by aaronkarpati** [comment]
I experienced the same issue! The example attached shows the problem clearly❗️Seems like the **component renderer** and a component scoped state change/hook causes an **infinite loop**.

**Comment by Murderlon** [comment]
Hi, note that this is not an issue with react-markdown, you break React patterns by incorrectly setting state inside a render causing an infinite loop.

I'm guessing you probably want something like this:

```js
import remark from 'remark'
import remarkHeadings from '@vcarl/remark-headings';

function Component ({content}) {
  const headings = useMemo(() => {
    const file = remark().use(remarkHeadings).processSync(content)
    return file.data.headings
  }, [content])
}
```

**Comment by karosowka13** [comment]
Yeah you are definitely right.
Thank you very much for your answer! 
I will close the issue.
