### ISSUE TITLE
Code Snippet with Copy Button

### ISSUE THREAD

**Issue by arnonrdp** [remarkjs/react-markdown#720]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

There is no copy button in code snippets.

### Solution

Is there any possibility to have a copy button in code snippets like in GitHub markdowns?

<img width="401" alt="Arrow pointing to copy button" src="https://user-images.githubusercontent.com/26576201/210234056-528692b3-bda6-41d7-8fab-81fb5af004d3.png">

### Alternatives

Select the text and copy.

**Comment by Murderlon** [comment]
Hi, there is no plugin for it but it should be easy with [remark-code-extra](https://github.com/s0/remark-code-extra), as per their readme:

> For example, you can add dedicated links to code snippets that copy the code [...]

Closing this as it's not the responsibility of this plugin but we can continue the discussion (usually better asked in [discussions](https://github.com/remarkjs/remark/discussions)).

**Comment by JcbPrn** [comment]
@arnonrdp What solution did you chose?
