### ISSUE TITLE
Table syntax not work

### ISSUE THREAD

**Issue by DonRP** [remarkjs/react-markdown#722]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.4

### Steps to reproduce

i tried to insert a table in my site and it didn't work.      
then i saw that it doesn't work in your wiki either so i decided to report this bug     
 
![image](https://user-images.githubusercontent.com/67595890/212486878-2c5f4618-250e-4670-bc70-ee4cbc99a5f2.png)    
![image](https://user-images.githubusercontent.com/67595890/212486880-c869bfe8-3e70-44f6-89b5-c20272d9f134.png)    

### Expected behavior

i tried to insert a table in my site and it didn't work.      
then i saw that it doesn't work in your wiki either so i decided to report this bug     
 
![image](https://user-images.githubusercontent.com/67595890/212486878-2c5f4618-250e-4670-bc70-ee4cbc99a5f2.png)    
![image](https://user-images.githubusercontent.com/67595890/212486880-c869bfe8-3e70-44f6-89b5-c20272d9f134.png)    

### Actual behavior

i tried to insert a table in my site and it didn't work.      
then i saw that it doesn't work in your wiki either so i decided to report this bug     
 
![image](https://user-images.githubusercontent.com/67595890/212486878-2c5f4618-250e-4670-bc70-ee4cbc99a5f2.png)    
![image](https://user-images.githubusercontent.com/67595890/212486880-c869bfe8-3e70-44f6-89b5-c20272d9f134.png)    

### OS

Windows

**Comment by wooorm** [comment]
The text includes the answer. The readme explains it: use remark-gfm. That's not standard markdown. It's GFM
