### ISSUE TITLE
Markdown trims source string

### ISSUE THREAD

**Issue by mateuszs** [remarkjs/react-markdown#725]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown 8.0.3

### Steps to reproduce

On version 4.3.1 which I was using previously I could put space at the beginning and end of the source and it was not trimmed. On newest version it is:

https://codesandbox.io/s/pedantic-tdd-ygrkdu

Is it possible to get back old behavior somehow?

### Expected behavior

There is a space between a b and c like `a b c`

### Actual behavior

There is no space between a b and c - `abc`

### Package manager

npm 7

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
That’s how markdown works. Try it on GH or see https://commonmark.org.
