### ISSUE TITLE
Markdown breaks by character sequence

### ISSUE THREAD

**Issue by tvorojjog** [remarkjs/react-markdown#726]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown 8.0.4

### Steps to reproduce

Try to parse this strings by react-markdown:
```
'[1 String]: \n[2 String]: some text'
'[1 String]: - \n[2 String]: some text'
'[1 String]: - \n\n[2 String]: some text'
```
Unfortunately, react-markdown return result that I don't expected.
In the first case it will be nothing, just an empty markdown container. In the second case it will be half of the string. In the third case it will be the same as the second case but with an empty string in the beginning.
I guess the main problem is that react-markdown can't parse `\n[` simbols, becouse if I add the zero width space (`&#8203;`) between them like this `\n&#8203;[`, markdown works well.

### Expected behavior

In the output:
```
[1 String]: 
[2 String]: some text
```
```
[1 String]: - 
[2 String]: some text
```
```
[1 String]: - 

[2 String]: some text
```

### Actual behavior

In the output:
1. Empty container
2. [2 String]: some text
3. empty string + [2 String]: some text

### Runtime

Node v16

### Package manager

npm 8

### OS

Windows

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
Please use markdown code (`code`) to show markdown code. I can’t read this.

**Comment by tvorojjog** [comment]
> Please use markdown code (`code`) to show markdown code. I can’t read this.

Is it OK now?

**Comment by wooorm** [comment]
Better, yeah, thanks!

These are definitions in markdown: https://spec.commonmark.org/0.30/#link-reference-definitions.

If you don’t want those, you have to escape them:

```markdown
[this is a definition]: url

\[this is not definition]: url
```
