### ISSUE TITLE
What version of react-syntax-highlighter should react-markdown work?

### ISSUE THREAD

**Issue by christopher-francisco** [remarkjs/react-markdown#732]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-syntax-highlighter

### Steps to reproduce

1. Install a brand new next 13 project
2. Pull both react-markdown and react-syntax-highlighter on latest versions
3. Use the integration example in the readme
4. Run your app

### Expected behavior

Should work

### Actual behavior

I get the error:

```
Server Error
TypeError: Super expression must either be null or a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
_inherits
node_modules/@babel/runtime/helpers/inherits.js (4:10)
ReactAsyncHighlighter
node_modules/react-syntax-highlighter/dist/cjs/async-syntax-highlighter.js (44:31)
_react
node_modules/react-syntax-highlighter/dist/cjs/async-syntax-highlighter.js (168:4)
eval
node_modules/react-syntax-highlighter/dist/cjs/light-async.js (22:55)
(sc_server)/./node_modules/react-syntax-highlighter/dist/cjs/light-async.js
file:///nextjs/blog/.next/server/app/blog/[slug]/page.js (3757:1)
__webpack_require__
file:///nextjs/blog/.next/server/webpack-runtime.js (33:42)
require
node_modules/react-syntax-highlighter/dist/cjs/index.js (59:41)
(sc_server)/./node_modules/react-syntax-highlighter/dist/cjs/index.js
file:///nextjs/blog/.next/server/app/blog/[slug]/page.js (3724:1)
__webpack_require__
file:///nextjs/blog/.next/server/webpack-runtime.js (33:42)
eval

### Runtime

Node v17

### Package manager

_No response_

### OS

_No response_

### Build and bundle tools

_No response_

**Comment by ChristianMurphy** [comment]
Welcome @christopher-francisco!
Sorry you ran into a spot of trouble.

It works with the latest versions (at the time of writing) of each.
* next 13
* react-markdown 8
* react-syntax-highlighter 15

You can see a full running demo here: https://stackblitz.com/edit/nextjs-6ekssc?file=pages%2Findex.js

Also a heads up, the issue tracker is for actionable issues and feature in the project.
General questions are also welcome, but should be directed to the discussion forum https://github.com/orgs/remarkjs/discussions/categories/q-a

**Comment by christopher-francisco** [comment]
My apologies @ChristianMurphy, I’ll make sure to direct my questions to the right place. 

Thank you for your reply, I’ll take a look at the example.

**Comment by kwt1326** [comment]
i using Next.js 13, react-markdown 8, react-syntax-highlighter 15.
It worked when 'use client' was written to the component.
