### ISSUE TITLE
Throw error When build with webpack

### ISSUE THREAD

**Issue by joket1999** [remarkjs/react-markdown#739]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.2, 7.1.2

### Steps to reproduce

yarn add react-markdown

webpack

### Expected behavior

build success

### Actual behavior

![图片](https://user-images.githubusercontent.com/6611880/232467796-62eb75f2-65aa-4a9b-bb78-d09880e3675a.png)

### Runtime

Node v16

### Package manager

yarn 2

### OS

macOS

### Build and bundle tools

Webpack

**Comment by remcohaszing** [comment]
Duplicate of #697
