### ISSUE TITLE
Allow a way to replace `\n` with a React component

### ISSUE THREAD

**Issue by shirshendubhowmick** [remarkjs/react-markdown#741]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I am trying to use `react-markdown` with `react-pdf`.

In `react-pdf` all strings should be inside a `<Text>` component exported by them.

In `react-markdown` its possible to replace all components with a custom one. However there is no option to for `\n`.

For example for a new line render properly with `react-pdf` it should be something like `<Text>{"\n"}</Text>`

### Solution

Allow an option replace `\n` with a custom component just like other component maybe ?

### Alternatives

I have read all possible docs and issues to find any alternative for this, however was unable to find anything meaningful.

Any alternative suggestion will be helpful.

**Comment by remcohaszing** [comment]
In markdown a single `\n` has no meaning.

```md
foo
bar
```

is equivalent to:

```md
foo bar
```

A line break in markdown can be denoted using 2 strailing spaces, or a backslash. (`·` represents a space in this example.)

```md
foo\
bar··
baz
```

You can use [`remark-breaks`](https://github.com/remarkjs/remark-breaks) if you want to turn newlines into breaks. Note that this means you’re deviating from standard markdown.

**Comment by shirshendubhowmick** [comment]
The `\` or double space method you mentioned, I tried that.

So what I did is something like this:

```TS
const updatedSource = source.replace(/\n/g, '\\')
```

and then passing the `updatedSource` to `react-markdown`

For a test markdown like this:
```MD
# This is heading 1
## This is heading 2
### This is heading 3
#### This is heading 4
##### This is heading 5
###### This is heading 6
 
This is a paragraph

**This is bold text**


- First item
- Second item
- Third item
- Fourth item
```

It got rendered like this:
![image](https://user-images.githubusercontent.com/12836504/236698602-4c722cab-a4d3-43b9-8840-56eaa7047186.png)


You will notice that the heading and other didn't get parsed properly, which I am not exactly sure why.

**Comment by shirshendubhowmick** [comment]
I now got your point.

I guess you were talking about rendering the an actual line break.

However my problem is

A markdown like this:
```md
# This is heading 1
## This is heading 2
```

Gets transform into 3 elements:
```
<H1>This is heading 1</H1>
\n
<H2>This is heading 1</H2>
```

And this `\n` is causing the problem

**Comment by wooorm** [comment]
What problem?

**Comment by shirshendubhowmick** [comment]
I think I tried explaining the problem. I will try explaining it once more here.

I am using `react-markdown` along with `react-pdf` to render md content in a PDF file.

In react PDF all strings should be inside of a `<Text />` component exported by them.

In my previous example:
The react component tree for the markdown given below
```MD
# This is heading 1
## This is heading 2
```

Looks something like this:
```
<H1>This is heading 1</H1>
\n
<H2>This is heading 1</H2>
```
Where `H1` and `H2` are custom header components compatible with React PDF.

The problem is with that `\n`, React PDF complains that this string is orphaned and it must be inside their `<Text>` component.


Also I tried checking `remark-breaks` before raising this issue, I guess the purpose of it is bit different from what I need.

**Comment by wooorm** [comment]
Wouldn’t *removing* `\n` between elements then be what you want?

**Comment by wooorm** [comment]
This project supports plugins. You are looking for a plugin that removes inter-element whitespace: https://github.com/rehypejs/rehype-minify/tree/main/packages/rehype-minify-whitespace#rehype-minify-whitespace.

**Comment by ToniRV** [comment]
Hi @shirshendubhowmick  would be awesome if you could share your solution! I want to render markdown to PDF and download it as a file using javascript/react. Any help would be great! thx!

**Comment by wooorm** [comment]
Please see the comment before your comment

**Comment by supuwoerc** [comment]
> This project supports plugins. You are looking for a plugin that removes inter-element whitespace: https://github.com/rehypejs/rehype-minify/tree/main/packages/rehype-minify-whitespace#rehype-minify-whitespace.这个项目支持插件。您正在寻找一个删除元素间空格的插件：https://github.com/rehypejs/rehype-minify/tree/main/packages/rehype-minify-whitespace#rehype-minify-whitespace。

Thanks a lot, this solved my problem!
