### ISSUE TITLE
Issue by text from inputs

### ISSUE THREAD

**Issue by nicolas-goyon** [remarkjs/react-markdown#742]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

App techs : React, Tailwindcss, Typescript, Node v20.0.0, npm v9.6.4

Here is the example : [https://pastecode.io/s/xkam8qaf](https://pastecode.io/s/xkam8qaf)

Goal : i'm trying to be able to input text and have the preview bellow.

Issue : 
- When the text is not changes (raw text from input to Markdown component) each new line (\n) is not printed in the area.
- When i'm trying to escape the \n to \\n, it works but not with headers has "\" printed, and when i'm making new lines, the last one has "\" until i make a make a new letter. 

### Expected behavior

I would like to have these examples : 
```markdown
# Example 1 : 
my example
```
should be 
```markown
# Example 1 : 
my example 
```

and this example : 
```markown
My multiple lines 



```
Should be : 
```markown
My multiple lines 



```

### Actual behavior
With the escape 
```markdown
# Example 1 : 
my example
```
Actually is : 
```markown
# Example 1 : \
my example 
```

```markdown
# Example 1 : 
my example

```
Actually is : 
```markown
# Example 1 : \
my example 
\
```

and this example : 
```markown
My multiple lines 



```
Actually is : 
```markown
My multiple lines


\
```

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Create React App

**Comment by wooorm** [comment]
Please use markdown code blocks for code. I unfortunately can’t read this

**Comment by nicolas-goyon** [comment]
Done

**Comment by nicolas-goyon** [comment]
The issue is because i take the markdown from a text area, when im doing it statically inside the code, it works but as soon as i get the code from a text area i have the issues shown above

**Comment by wooorm** [comment]
Then you need to explain how you do that?

The demo above also takes stuff from a textarea, and it works.
