### ISSUE TITLE
yellow highlight does not work

### ISSUE THREAD

**Issue by sergenti** [remarkjs/react-markdown#743]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Link to runnable example

https://codesandbox.io/s/new-dawn-345387?file=/src/app.tsx

### Steps to reproduce

try it here: https://codesandbox.io/s/new-dawn-345387?file=/src/app.tsx

### Expected behavior

markdown viewer. it should make it yellow
![image](https://github.com/remarkjs/react-markdown/assets/55017307/f54bd306-997d-4a4b-9368-ebc75bfab6c8)

### Actual behavior

react markdown. it does not
![image](https://github.com/remarkjs/react-markdown/assets/55017307/b221ad16-6762-4021-b62e-23cadb9530d9)

### Runtime

Node v17, Node v16, Node v14, Node v12

### Package manager

npm 8

### OS

Linux

### Build and bundle tools

Webpack, Create React App

**Comment by fylls** [comment]
these do not work either

` ==highlight==`

` ^^highlight^^`

`<mark>highlight</mark>`

`<span style="background-color: #FFFF00">Marked text</span>`

**Comment by wooorm** [comment]
Please read the readme: https://github.com/remarkjs/react-markdown#appendix-a-html-in-markdown

**Comment by fylls** [comment]
`^^text^^`

`==text==`

`<span style="background-color: #FFFF00">text</span>`

these don't work either

**Comment by fylls** [comment]
omg, that was the fastest answer I've ever received in a Github Issue, thanks a lot @wooorm

**Comment by wooorm** [comment]
:)

**Comment by jcsumlin** [comment]
> these do not work either
> 
> ` ==highlight==`
> 
> ` ^^highlight^^`
> 
> `<mark>highlight</mark>`
> 
> `<span style="background-color: #FFFF00">Marked text</span>`

Sorry to revive a closed thread, but is it possible to use any of these to create the yellow highlighting elements without enabling HTML?

**Comment by ChristianMurphy** [comment]
Use HTML https://github.com/remarkjs/react-markdown#appendix-a-html-in-markdown
or directives https://github.com/remarkjs/remark-directive

I'd highly discourage coming up with yet another non-standard Markdown syntax, the features of CommonMark.
