### ISSUE TITLE
Markdown not parsed

### ISSUE THREAD

**Issue by cpetit636** [remarkjs/react-markdown#744]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown@8.0.7

### Steps to reproduce

The following JSX :

```jsx
<ReactMarkdown>{`
  # Title:
  * Item 1
  * Item 2
  * Item 3
`}</ReactMarkdown>
```

### Expected behavior

Should render like it:

```html
<h1>Title:</h2>
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ul>
```

### Actual behavior

But it dosn't render at all and give:

```
# Title:
* Item 1
* Item 2
* Item 3
```

### Runtime

Node v16

### Package manager

npm 8

### OS

Windows

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
Welcome @cpetit636! 👋 

This is expected, what you are running into is a misunderstanding of CommonMark and JavaScript template strings.

```markdown
# Title:
* Item 1
* Item 2
* Item 3
```

is valid and will render:

# Title:
* Item 1
* Item 2
* Item 3

---

```markdown
    # Title:
    * Item 1
    * Item 2
    * Item 3
```

is a codeblock, and will render


    # Title:
    * Item 1
    * Item 2
    * Item 3

---

if you want to render the title and list, remove the leading spaces with:

```js
<ReactMarkdown>{`
# Title:
* Item 1
* Item 2
* Item 3
`}</ReactMarkdown>
```

or use dedent https://www.npmjs.com/package/dedent

```js
<ReactMarkdown>{dedent`
  # Title:
  * Item 1
  * Item 2
  * Item 3
`}</ReactMarkdown>
```

**Comment by cpetit636** [comment]
Ok. Thanks.
