### ISSUE TITLE
react-markdown can't render MathJax CHTML

### ISSUE THREAD

**Issue by alex-titarenko** [remarkjs/react-markdown#745]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown: 8.0.7

### Link to runnable example

https://codesandbox.io/s/crimson-architecture-8qkw9w?file=/src/app.tsx

### Steps to reproduce

See the CodeSandbox link above

### Expected behavior

I'm expecting MathJax CHTML to be properly rendered with React-Markdown

### Actual behavior

You see blank space when rendered math expression should be.

After the investigation, I see where the problem is:

MathJax (one of the most popular libraries out there to render Latex) when outputting the result to CHTML is using custom HTML elements (example: mjx-container, mjx-math, etc).
The problem happens in ast-to-react.js when it tries to translate AST properties into react properties. In the case of `className` or `class` it will always translate it to `className`, but React can't handle `className` property for non-standard HTML tags.
See GitHub issue here: https://github.com/facebook/react/issues/4933
And instead, React will just render `classname` property instead of class.

<img width="665" alt="image" src="https://github.com/remarkjs/react-markdown/assets/3290313/343ba470-fb90-4e61-8a81-ad69e435c84f">

What I'm expecting from React-Markdown library in case of custom HTML tags in AST (custom tags always should have at list one dash character, so should be easy to check, like mjx-container) it should rename className to class or if class property already there don't change it to className. After this change, it should properly render in React.

### Runtime

Node v17

### Package manager

npm 8

### OS

Windows, macOS

### Build and bundle tools

Create React App

**Comment by wooorm** [comment]
- Would be probably tough to solve
- I understand why React doesn’t touch `className`, given that a web component could indeed accept such a `classname` prop, but it does feel weird that React does `className` everywhere else but not here: custom elements too use the `className` DOM prop to represent the `class` HTML attribute

**Comment by alex-titarenko** [comment]
@wooorm ok, if you don't want to automatically change `className` to `class`, just don't automatically change `class` to `className` if it's a **custom component**. This will help as well since I'm in control when creating AST and can make sure to have `class` property, but currently React-Markdown will change it to `className` and will break everything.

**Comment by wooorm** [comment]
> just

yeah, no, that’s not how it works.

**Comment by wooorm** [comment]
Your idea doesn’t work. Take a look at the code. `react-markdown` isn’t responsible for doing that. The AST used here [*specifies* that `className` must be used](https://github.com/syntax-tree/hast#exceptions), so some other place also shouldn‘t do it. `react` doesn’t support web components well anyway and is going to change how they support web components so perhaps any work done here is useless.

**Comment by alex-titarenko** [comment]
@wooorm React-Markdown is absolutely responsible for this.
Look at the code here: https://github.com/remarkjs/react-markdown/blob/d044e34b4f22caa24545c0b355d2205de42dfc32/lib/ast-to-react.js#L371

If property name is `class` then `info` will get `className`.
What I was proposing is in case of custom html tag (easy to check, just look for dashes in the name) make a quick check and keep `class` property name.

React-Markdown library is all about rendering markdown in React. What I'm describing is absolutely valid scenario for React and React library supports my scenario. That is why I'm not quite sure I understand your opposition for the proposal. React supports this scenario, but you don't want even so library is all about rendering in React?

**Comment by wooorm** [comment]
> valid scenario

I have no problem with your problem.

> React-Markdown is absolutely responsible for this.

I understand that the code looks like that, but no. The plugin `rehype-mathjax` chooses `className`. So `addProperty` is called with `className`. Your idea expects it to be called with `class`, which doesn’t happen.

---

My concerns are about more than 500 repos. We at unified work on many projects that integrate with React. I am concerned with how to support custom elements everywhere. Correctly. In all cases.

**Comment by alex-titarenko** [comment]
I have my own implementation of `rehype-mathjax` where I make sure to have `class` property instead of `className`, but ReactMarkdown auto-converts `class` to `className` even so React does not support className for custom tag names.

The concern about backward compatibility is valid on your case, but I can't imagine a case where your current users expecting to have `classname` (with lowercase) property in rendered React. That is unexpected behavior.

> P.S. There is no problem with `rehype-mathjax` library since it's agnostic of rendering engine like React, but the problem with React-Markdown which produces invalid result in React.

**Comment by wooorm** [comment]
> I have my own implementation of rehype-mathjax

That breaks our specification of hast — you are not supposed to do that. `react-markdown` fixes your bug.

> The concern about backward compatibility is valid on your case

I have no concern with backwards compat. I have concerns with solving this correctly. Your ideas do not solve this correctly. I am looking for ideas that solve this.

> That is unexpected behavior.

Sure.

> There is no problem with rehype-mathjax library since it's agnostic of rendering engine like React

Correct.

> but the problem with React-Markdown which produces invalid result in React.

Please see my first comment: https://github.com/remarkjs/react-markdown/issues/745#issuecomment-1589051596.
The problem is either the design of the entire ecosystem or React.
It’s not *just* react-markdown.

**Comment by wooorm** [comment]
Let’s track this over at https://github.com/remarkjs/remark-math/issues/85. As it has more to do with what that project generates!

**Comment by igloo1505** [comment]
Hey everybody... this is still an issue in 14+, but I thought I'd leave this here. It's definitely not a permanent solution, but it's a bandaid that works for those using Next and having this issue.

```
import { getRandomId } from '#/utils/ui'
import Script from 'next/script'
import React from 'react'


interface ImmediateNoteContentContainerProps {
    children: React.ReactNode
}



const ImmediateNoteContentContainer = ({ children }: ImmediateNoteContentContainerProps) => {
    const id = `nt-cnt-${getRandomId(8)}`
    return (
        <>
            <Script strategy="lazyOnload" id={`${id}-scrt`}>{`let em = document.getElementById("${id}");
let children = em.querySelectorAll("[classname]");
for (const k of children){
    let cl = k.getAttribute("classname")?.split(" ")
    if(cl && cl.length > 0){
        cl.forEach((c) => {
            k.classList.add(c)
        })
    }
}
`}</Script>
            <div
                className={"note-base-layout pt-8 space-y-2 md:space-y-3"}
                id={id}
            >
                {children}
            </div>
        </>
    )
}


ImmediateNoteContentContainer.displayName = "ImmediateNoteContentContainer"


export default ImmediateNoteContentContainer;
```
