### ISSUE TITLE
How to avoid trim whitespaces and \n?

### ISSUE THREAD

**Issue by lucasjinreal** [remarkjs/react-markdown#748]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

How to avoid trim whitespaces and \n?

### Solution

How to avoid trim whitespaces and \n?

### Alternatives

How to avoid trim whitespaces and \n?

**Comment by ChristianMurphy** [comment]
Welcome @lucasjinreal! 👋 

Please see the answers from any of the numerous times this has been asked before https://github.com/remarkjs/react-markdown/issues?q=is%3Aissue+newline+is%3Aclosed and https://github.com/orgs/remarkjs/discussions?discussions_q=is%3Aopen+newline
