### ISSUE TITLE
Issue with typings with later versions of `hast`

### ISSUE THREAD

**Issue by benjdlambert** [remarkjs/react-markdown#750]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown

### Steps to reproduce

Install `react-markdown` and run typescript with `--skipLibCheck=false`

### Expected behavior

Types are happy and the library has 0 typescript errors

### Actual behavior

```
node_modules/react-markdown/lib/rehype-filter.d.ts:2:43 - error TS2344: Type 'Root' does not satisfy the constraint 'void | Node<Data>'.
  Type 'Root' is not assignable to type 'Node<Data>'.
    Types of property 'data' are incompatible.
      Type 'import("/tmp/backstage-e2e-Ukrwaf/test-app/node_modules/@types/hast/node_modules/@types/unist/index").Data | undefined' is not assignable to type 'import("/tmp/backstage-e2e-Ukrwaf/test-app/node_modules/@types/unist/index").Data | undefined'.
        Type 'import("/tmp/backstage-e2e-Ukrwaf/test-app/node_modules/@types/hast/node_modules/@types/unist/index").Data' is not assignable to type 'import("/tmp/backstage-e2e-Ukrwaf/test-app/node_modules/@types/unist/index").Data'.
          Index signature for type 'string' is missing in type 'Data'.

2   this: import('unified').Processor<void, import('hast').Root, void, void>,
                                            ~~~~~~~~~~~~~~~~~~~

node_modules/react-markdown/lib/rehype-filter.d.ts:6:35 - error TS2344: Type 'Root' does not satisfy the constraint 'Node<Data>'.

6   | import('unified').Transformer<import('hast').Root, import('hast').Root>
                                    ~~~~~~~~~~~~~~~~~~~
```

Looks like there's some type incompatibility with later packages that have been released. This is blocking our pipeline and E2e tests for Backstage. We've had a suggestion that a potential fix is to bring in ` @types/unist@<3.0.0`, maybe that needs implementing here or should we open an issue over there?

https://github.com/backstage/backstage/pull/18643

**Comment by remcohaszing** [comment]
This is an upstream issue that’s being worked on. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65789#issuecomment-1628082328 for details and a workaround.

**Comment by wooorm** [comment]
External as Remco mentions, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66029.
