### ISSUE TITLE
KaTeX Display Mode (non-inline math) not working

### ISSUE THREAD

**Issue by AnuragGowda** [remarkjs/react-markdown#751]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown@8.0.3

### Link to runnable example

https://codesandbox.io/s/react-math-markdown-forked-tqxgnp?file=/src/math.js

### Steps to reproduce

https://codesandbox.io/s/react-math-markdown-forked-tqxgnp?file=/src/math.js

### Expected behavior

Display mode math should appear on separate line, html should be tagged with class math-display

### Actual behavior

Math appears inline, html has class 'math-inline'

### Runtime

Node v17

### Package manager

npm 8

### OS

Windows

**Comment by ChristianMurphy** [comment]
Welcome @AnuragGowda! 👋 
A newline determines where math is inline or block, not the number of dollars.
Please see the readme of `remark-math` for examples https://github.com/remarkjs/remark-math/tree/main/packages/remark-math#syntax

**Comment by kkensuke** [comment]
Thanks, @ChristianMurphy !
Finally, I understand what is the problem.
For Latex users, the following notation is completely the same, which confuses me a lot.

🚫:
```
$$ a + b = c $$
```
✅:
```
$$
a + b = c
$$
```
