### ISSUE TITLE
React typscript: Getting error: Warning: Received `true` for a non-boolean attribute `ordered`, for custom <ul> component

### ISSUE THREAD

**Issue by adamleithp-mystic** [remarkjs/react-markdown#752]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown@8.0.7

### Steps to reproduce

use the following setup in react/typescript;

Node runtime:
```v19.0.0```

Package manager:
```yarn@1.22.19```

**relavant packages**:
```
"next": "^13.4.0",
"react-markdown": "^8.0.7",
"typescript": "^5.2.0-dev.20230606",
```

**Markdown**
```tsx
const md = `
1. item-1
   1. sub-item-1
   2. sub-item-2
2. item-2
   1. sub-item-3
   2. sub-item-4
3. item-3
`;
```

and then use `react-markdown`
```tsx
import type { Components } from "react-markdown";

<ReactMarkdown
    // rehypePlugins={[rehypeRaw]}
    // remarkPlugins={[remarkGfm]}
    children={md}
    components={MarkdownComponents}
/>
```

and using custom components (passed in above)

```tsx
export const MarkdownComponents: Components = {
   ul: ({ node, ...props }) => (
    <ul {...props} />
  ),
  ol: ({ node, ...props }) => (
    <ol {...props} />
  ),
  li: ({ node, ...props }) => (
    <li {...props} />
  ),
}
```

How it renders:
<img width="235" alt="image" src="https://github.com/remarkjs/react-markdown/assets/101415864/2cbb136e-4154-4be0-b627-498f43f649b1">

**The error:**

```console
Warning: Received `true` for a non-boolean attribute `ordered`.

If you want to write it to the DOM, pass a string instead: ordered="true" or ordered={value.toString()}.
li
li@webpack-internal:///(app-client)/./components/utils/MarkdownComponents.tsx:123:35
ol
ol@webpack-internal:///(app-client)/./components/utils/MarkdownComponents.tsx:112:35
ReactMarkdown@webpack-internal:///(app-client)/./node_modules/react-markdown/lib/react-markdown.js:88:42
div
...
```

The issue was mentioned here: https://github.com/orgs/remarkjs/discussions/873 but wasn't resolved from what I can tell...

thanks for your time

### Expected behavior

* not have an error in client console

### Actual behavior

* show an error in client console

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

macOS

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
Welcome @adamleithp-mystic! 👋 
This was explained, [solved](https://github.com/orgs/remarkjs/discussions/873#discussioncomment-1466154), and discussed at length in https://github.com/orgs/remarkjs/discussions/873.
Please read the discussion thoroughly and in particular this comment: https://github.com/orgs/remarkjs/discussions/873#discussioncomment-1466154
