### ISSUE TITLE
Support 'file' URI schema

### ISSUE THREAD

**Issue by DzmitrySudnik** [remarkjs/react-markdown#755]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Hi,

I want to render urls which use `file` schema, pointing to local file system files, for example:
* `file:///etc/hosts`

Since URI supports `file` schema (RFC: https://datatracker.ietf.org/doc/html/rfc8089) and browsers open such links just fine I think it's reasonable to add support for it to react-markdown.

Thanks

### Solution

I think just adding 'file' to the protocol list in https://github.com/remarkjs/react-markdown/blob/8.0.7/lib/uri-transformer.js will do it.

### Alternatives

Can't think if anything more simple than adding 'file' to the protocols list.

**Comment by wooorm** [comment]
You can pass your own uri transformer?

**Comment by wooorm** [comment]
Passing your own `uriTransformer` is a viable alternative. It’s in my opinion also better because it does not change the behavior for every user of react-markdown ever.
