### ISSUE TITLE
color in html can't render

### ISSUE THREAD

**Issue by PDmeaning** [remarkjs/react-markdown#759]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

5.0.3 version

### Steps to reproduce

 <ReactMarkdown
                    children={input}
                    plugins={[gfm]}
                    escapeHtml={false}
                    renderers={{ code: CodeBlock }}
                  />
input="<font color="#ff0000">text</font>",
but the output of html show as "<span><font color="#ff0000"></font></span><span>text</span>",
so the color cant show right

### Expected behavior

the color of text is "#ff0000"

### Actual behavior

the color of text is default(black)

### Runtime

Node v16

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
Please use markdown, this question is not readable

**Comment by PDmeaning** [comment]
I‘m sorry,
input:"<font color=\"#ff0000\">text</font>";
output:"<span><font color=\"#ff0000\"></span><span>text</span><span></span>"

**Comment by PDmeaning** [comment]
input: `<font color=\"#ff0000\">text</font>`;
output:`<span><font color=\"#ff0000\"></span><span>text</span><span></span>`

**Comment by wooorm** [comment]
Don‘t use font? It’s ancient and not supported by React? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font
 https://github.com/facebook/react/issues/2627.

**Comment by PDmeaning** [comment]
input:`<span style="color:#ff0000">aaaaaaaaaaa</span>`;
output:`<span><span style="color:#ff0000"></span></span><span>aaaaaaaaaaa</span><span></span>`

**Comment by PDmeaning** [comment]
> Don‘t use font? It’s ancient and not supported by React? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font [facebook/react#2627](https://github.com/facebook/react/issues/2627).

but the span also can't render right
input:<span style="color:#ff0000">text</span>;
output:<span><span style="color:#ff0000"></span></span><span>text</span><span></span>

**Comment by PDmeaning** [comment]
> input:`<span style="color:#ff0000">aaaaaaaaaaa</span>`;
> output:`<span><span style="color:#ff0000"></span></span><span>aaaaaaaaaaa</span><span></span>`

but the span also render right, there are extra html elements;
input:`<span style="color:#ff0000">text</span>`;
output:`<span><span style="color:#ff0000"></span></span><span>text</span><span></span>`

**Comment by ChristianMurphy** [comment]
@PDmeaning I'm not sure what you are doing/using.
`react-markdown` and `rehype-raw` do not add extra spans.
https://stackblitz.com/edit/github-tun7qz?file=src%2Fapp.tsx

<details>
<summary>source from sandbox</summary>

```typescript
import React from 'react';
import Markdown from 'react-markdown';
import rehypeRaw from 'rehype-raw';

const markdownSource = `
<span style="color:#ff0000">text</span>
`;

const App = () => (
  <Markdown rehypePlugins={[rehypeRaw]}>{markdownSource}</Markdown>
);

export default App;
```

</details>

If you have any follow up questions, please read the support guidelines on how to ask quality questions: https://github.com/remarkjs/.github/blob/main/support.md
