### ISSUE TITLE
how can I click picture and enlarge it？

### ISSUE THREAD

**Issue by lush-99** [remarkjs/react-markdown#764]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

![image](https://github.com/remarkjs/react-markdown/assets/77112588/bc5523f7-ba47-4240-a234-d7a3dc6ffb77)
i want to click this picture and enlarge it, what can i do? help me please

### Solution

enlarge this picture when i click it

### Alternatives

tell me how to do

**Comment by remcohaszing** [comment]
You can use the `components` prop to pass a custom `img` component.

```js
function ClickableImage(props) {
  function handleClick(event) {
    // Handle the click event here.
    console.log(props)
  }

  return <img {...props} onClick={handleClick} />
}

const components = {
  img: ClickableImage
}

// …

<ReactMarkdown
  components={components}
  // …
/>
```
