### ISSUE TITLE
can't use React Markdown with Next JS

### ISSUE THREAD

**Issue by mshaheeruddin** [remarkjs/react-markdown#767]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.7

### Steps to reproduce

I was working on a Next JS application. 

As I installed react-markdown by using npm install react-markdown, and started dev server, it crashed with the error: 

**Server Error
TypeError: Cannot read properties of null (reading 'useContext')

This error happened while generating the page. Any console logs will be displayed in the terminal window.**

I tried cleaning my cache [as it also happened with another package but after cleaning cache and running npm install it resolved]  but it didn't solve the issue. 

As I uninstall react-markdown, my app runs fine without any issues.

P.S: Just to be clear, I haven't used Context API anywhere (no state management tool at all) 

**Also my Node version is latest Node.js v18.16.1.**

### Expected behavior

It should show my app working fine

### Actual behavior

Server Error
TypeError: Cannot read properties of null (reading 'useContext')

This error happened while generating the page. Any console logs will be displayed in the terminal window.

### Runtime

Other (please specify in steps to reproduce)

### OS

Windows

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
https://github.com/search?q=repo%3Aremarkjs%2Freact-markdown%20useContext&type=code

This is not a problem here. Needs more info

**Comment by ChristianMurphy** [comment]
Welcome @mshaheeruddin! 👋 
Sorry you ran into a spot of trouble.
As @wooorm notes, `react-markdown` doesn't leverage the `useContext` API, highly unlikely, nearly impossible for `react-markdown` to be the root cause.
Some things to consider:
* Are there any other components on the page which may be leveraging context?
* Are you including multiple different versions of `react` on the page? (though dependencies, check your package lock file)
* Are you sure your build tool is configured correctly?

**Comment by mshaheeruddin** [comment]
Can this be an issue from Next JS side?

I am really sure that I haven't used Context API anywhere
Problem is getting resolved as soon as I uninstall react-markdown package (have checked this twice) 

I don't know how to check for this: 

Are you including multiple different versions of react on the page? (though dependencies, check your package lock file)
Are you sure your build tool is configured correctly?

**Comment by ChristianMurphy** [comment]
Issues are not the place for Q&A, I'm copying this over to https://github.com/orgs/remarkjs/discussions/1228.
Let's continue the conversation there.
