### ISSUE TITLE
Reading from "node:path" is not handled by plugins 

### ISSUE THREAD

**Issue by rubas** [remarkjs/react-markdown#773]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.0

### Steps to reproduce

We are using the plugin in our gatsby installation.

After upgrade to the version `9.0.0`, we are getting build failures with from webpack.

~~~
Error Generating SSR bundle failed
Reading from "node:path" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
~~~

### Expected behavior

:sun:

### Actual behavior

```
Reading from "node:path" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

**Comment by Murderlon** [comment]
Hi, there is not enough information to help, you left most things we ask in the template blank. My gut feeling is your Node and/or Gatsby is outdated and should be upgraded.

**Comment by ChristianMurphy** [comment]
Welcome @rubas! 👋 
Sorry you ran into a spot of trouble.

As @Murderlon mentions, `node:path` is valid.
It is also supported by Gatsby, since https://github.com/gatsbyjs/gatsby/pull/36506

Make sure you are running a recent version of Gatsby.
If you cannot upgrade Gatsby, hold on the previous version on `react-markdown` until you can upgrade both.

**Comment by rubas** [comment]
Thanks for the quick answers - and sorry for not adding enough information. I was in a rush 👎 👎 👎 

---

This is not a technical issue with the library itself as `node:path` is valid, but one can run into issues downstream with it.

It breaks the build with current gatsby (5.12.5) with node (18.17.1). As @ChristianMurphy pointed out, Gatsby with its Webpack implementation should be able to handle it but it's not.

Probably relates to: https://github.com/gatsbyjs/gatsby/pull/38516

**Comment by littlefengers** [comment]
Hey, FYI, I had the same issue with the same setup as @rubas, so I had to downgrade to 8.0.7.

There was another user on Netlify's forum that had same issue today. It seems to only happen during gatsby build though, gatsby develop does not have this issue.

**Comment by ChristianMurphy** [comment]
Thanks for adding on @rubas and @littlefengers, it would be good to let the Gatsby team know so they can prioritize fixing this.
Either on the existing https://github.com/gatsbyjs/gatsby/pull/38516 or generating a new issue if you believe this is a different issue than the one in the PR https://github.com/gatsbyjs/gatsby/issues
