### ISSUE TITLE
Cannot run the code after upgrading the library: missing property `code.inline` and changed the type of `p.ref`

### ISSUE THREAD

**Issue by MartinXPN** [remarkjs/react-markdown#776]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"react-markdown": "^9.0.0",

### Steps to reproduce

I have the following component that used to work fine:
```tsx
                    <ReactMarkdown components={{
                        p: ({node, ...props}) => <Typography whiteSpace="pre-wrap" {...props} />,
                        code: ({node, inline, className, children, ...props}) => {
                            const match = /language-(\w+)/.exec(className || '')
                            return !inline && match
                                ? <LazyCode content={String(children)} language={match[1]} />
                                : <code className={className} {...props}>{children}</code>
                        },
                    }}>{conversation.raw?.trim()}
                    </ReactMarkdown>
```

Now, I get the following errors:
1.  p.ref -->        Type 'string' is not assignable to type '((instance: HTMLSpanElement | null) => void) | RefObject<HTMLSpanElement> | null | undefined'.
2. code.inline -->   TS2339: Property 'inline' does not exist on type 'ClassAttributes  & HTMLAttributes  & ExtraProps'.

I'm using node@18.17.0 with next@13.5.4

### Expected behavior

It used to work fine using the previous version

### Actual behavior

The code does not compile

### Runtime

Other (please specify in steps to reproduce)

### Package manager

yarn 2

### OS

Linux, macOS

### Build and bundle tools

Next.js

**Comment by Murderlon** [comment]
Hi! Have you checked the changelog before upgrading?

Particularly this:
https://github.com/remarkjs/react-markdown/blob/main/changelog.md#remove-extra-props-passed-to-certain-components

**Comment by Murderlon** [comment]
This is some pseudo-code I typed without testing but probably something like this. I think you can also use `pre: () => {}` in `components` for code block components.

```js
import {visit} from 'unist-util-visit'

function rehypePluginAddingIndex() {
  /**
   * @param {import('hast').Root} tree
   * @returns {undefined}
   */
  return function (tree) {
    visit(tree, 'code', function (node, index) {
      if (parent && parent.tagName === 'pre') {
        node.properties.inline = false;
      } else {
        node.properties.inline = true;
      }
    })
  }
}
```

**Comment by AlphaNecron** [comment]
And how do we get code language like using `class-name` in v8?

**Comment by AlphaNecron** [comment]
It does not work at all, className is undefined

**Comment by wooorm** [comment]
Nope.

Can you read the support guide on how to ask questions: you need to provide information.

**Comment by AlphaNecron** [comment]
![image](https://github.com/remarkjs/react-markdown/assets/57827456/c7f96de5-b552-48af-9916-955d891ad01b)
In v8, I was able to get the language of above code using `className` prop. However, in this release, there's no className or props passed to `pre` at all.
![image](https://github.com/remarkjs/react-markdown/assets/57827456/47118883-5ca1-44a6-8c8e-7d2b6380fa99)
I removed the custom renderer of `pre` and DevTools shows this:
![image](https://github.com/remarkjs/react-markdown/assets/57827456/8adf6c41-3032-45b5-b623-ff254813f398)

**Comment by Murderlon** [comment]
Take a look at this example. You probably want to use `code` not `pre` for this: https://github.com/remarkjs/react-markdown#use-custom-components-syntax-highlight

**Comment by AlphaNecron** [comment]
Thanks.
