### ISSUE TITLE
I'm sorry, I just want to get this demo source code: https://remarkjs.github.io/react-markdown/

### ISSUE THREAD

**Issue by miki-long** [remarkjs/react-markdown#780]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

--

### Steps to reproduce

--

### Expected behavior

--

### Actual behavior

--

**Comment by wooorm** [comment]
This has been asked before. Do a search!
And this isn’t an issue, but a question!

Anyway, here: https://github.com/remarkjs/react-markdown/tree/website
