### ISSUE TITLE
It seems that there is typo in changelog

### ISSUE THREAD

**Issue by vzhn** [remarkjs/react-markdown#782]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.0

### Steps to reproduce

Look at the latest changelog:

https://github.com/remarkjs/react-markdown/blob/main/changelog.md#remove-includeelementindex

There is code here:
```     
visit(tree, function (node, index) {
  if (node.type === 'element' && typeof index === 'number') {
    node.properties === index
  }
})
```

### Expected behavior

But it looks that here should be something like that:
```
visit(tree, function (node, index) {
  if (node.type === 'element' && typeof index === 'number') {
    node.properties.index = index
   }
})
```

### Actual behavior

The code of plugin sample just does not work. It does not set index into props. Index is not passed.

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Other (please specify in steps to reproduce)

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Thanks!
