### ISSUE TITLE
It's not parsing LaTex syntax correctly

### ISSUE THREAD

**Issue by lyzy0906** [remarkjs/react-markdown#784]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.0

### Steps to reproduce

Here my original input text is a LaTex formula surrounded with \\[ ... \\] , but after it goes into the remark tree, the slash at the beginning is gone. Another slash before the last square is also gone.
Then it is not going to identify LaTex formula correctly with the pattern \\[ ... \\]
Please see the screenshot, I have console.log the input text, and the remark tree nodes. 

![image](https://github.com/remarkjs/react-markdown/assets/148552643/00c3fc90-b975-4820-a0e4-cf9607e93fca)

### Expected behavior

The slashes should be kept.

### Actual behavior

The slashes are gone

**Comment by wooorm** [comment]
Read the readme on how to do math: https://github.com/remarkjs/react-markdown#use-remark-and-rehype-plugins-math.

**Comment by lyzy0906** [comment]
> Read the readme on how to do math: https://github.com/remarkjs/react-markdown#use-remark-and-rehype-plugins-math.

Actually, I'm already using these plugins: remarkGfm, remarkMath, rehypeKatex.
But I found the plugin cannot identify LaTex syntax with this format: \\[ ... \\]
It only recognize LaTex with $$ ... $$ format.
So I am trying to parse the \\[ ... \\] syntax myself, and found the text will be modified by the component.
