### ISSUE TITLE
It's not parsing LaTex syntax correctly, even with plugins

### ISSUE THREAD

**Issue by lyzy0906** [remarkjs/react-markdown#785]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.0

### Steps to reproduce

https://github.com/remarkjs/react-markdown/issues/784

Actually, I'm already using these plugins: remarkGfm, remarkMath, rehypeKatex!
But I found the plugins CANNOT identify LaTex syntax with this format: \\[ ... \\]
It only recognize LaTex with $$ ... $$ format.

So I am trying to parse the \\[ ... \\] syntax myself, and found the text will be modified by the component, which is the slashes are gone after going through the component!
Please look into my screenshot. The slashes in the middle are kept. Only the start and end ones are gone. Why is this happening?

![image](https://github.com/remarkjs/react-markdown/assets/148552643/a2d7c636-3909-45b5-9066-4859857799c4)

### Expected behavior

The slashes should be kept.

### Actual behavior

The slashes are gone.

**Comment by wooorm** [comment]
You don’t have to open new issues. Closed ones can still be commented on.
Also, questions go to discussions, these aren’t issues. See the support docs.

That’s not how math works with remark-math. See the examples in the docs. The one I mentioned earlier and https://github.com/remarkjs/remark-math#examples.

**Comment by lyzy0906** [comment]
> You don’t have to open new issues. Closed ones can still be commented on. Also, questions go to discussions, these aren’t issues. See the support docs.
> 
> That’s not how math works with remark-math. See the examples in the docs. The one I mentioned earlier and https://github.com/remarkjs/remark-math#examples.

Sorry, I thought I cannot comment after closed. And I think this is a bug, not a question………………

So let's not talk about formula, any regular string, starts with "\\[", will be parsed into "[" only. Here my input is: '\\[ something ]', and the output is:
![image](https://github.com/remarkjs/react-markdown/assets/148552643/8f7e63ca-65a1-494d-b2ec-948b1c69f1d7)

**Comment by wooorm** [comment]
You probably need to provide more info. Please read the support guide. Don’t post a screenshot. Post code. Post what versions you are using.

You use `\[`. **That is not supported**. See the examples. Use dollars. Read the syntax section.

**Comment by lyzy0906** [comment]
> You probably need to provide more info. Please read the support guide. Don’t post a screenshot. Post code. Post what versions you are using.
> 
> You use `\[`. **That is not supported**. See the examples. Use dollars. Read the syntax section.

OK. My code is something like:
`<ReactMarkdown remarkPlugins={[remarkMath, texPlugin]} rehypePlugins={[rehypeKatex]}>
        {'\\[ something ]'}
      </ReactMarkdown>`

And I expect is to show \\[ something ], but it is showing [ something ].

**Comment by lyzy0906** [comment]
BTW, I cannot use dollars. Because the LaTex input is generated by ChatGPT automatically, which is in  \\[ ... \\] format. So I am trying to parse it myself.

**Comment by wooorm** [comment]
Then ask ChatGPT to solve it.

Dollars are what is used here, not `\\[` and such.

Escapes working as escapes is how markdown works. If you put `&copy;` in HTML, you see `©`, not those literal characters. It’s the same here.
And it’s the same as you do with JS: `\\` turns into `\`.

**Comment by lyzy0906** [comment]
> Then ask ChatGPT to solve it.
> 
> Dollars are what is used here, not `\\[` and such.
> 
> Escapes working as escapes is how markdown works. If you put `&copy;` in HTML, you see `©`, not those literal characters. It’s the same here. And it’s the same as you do with JS: `\\` turns into `\`.

?
But the component only omit the first slash. Let's say my input is:
`<ReactMarkdown remarkPlugins={[remarkMath, texPlugin]} rehypePlugins={[rehypeKatex]}>
        {'\\[ \\something ]'}
      </ReactMarkdown>`

Not the output is `[ \something ]`. The middle slash is there. Only the first slash is gone……

**Comment by wooorm** [comment]
right, that’s how markdown works. Escapes work on punctuation. `[` is punctuation, so `\[` turns into `[`. `s` is not punctuation so `\s` remains as `\s`. See https://spec.commonmark.org/0.30/#backslash-escapes

**Comment by lyzy0906** [comment]
> right, that’s how markdown works. Escapes work on punctuation. `[` is punctuation, so `\[` turns into `[`. `s` is not punctuation so `\s` remains as `\s`. See https://spec.commonmark.org/0.30/#backslash-escapes

I see. Thank you for your detailed explaination. I was not aware that [ is punctuation.

**Comment by wooorm** [comment]
No problem!

**Comment by mandeep511** [comment]
> No problem! Good luck! :)

So how do you recommend we solve it? In ChatGPT's web-ui they are somehow parsing \[ \ ] properly. So there must be a simple way to take care of all corner cases when compiling latex and react

**Comment by wooorm** [comment]
Regexp? Build your own plugins?

They parsing things does not equal that it is simple.

**Comment by prashantbhudwal** [comment]
For processing chatgpt or openai latex.

```ts
export const preprocessLaTeX = (content: string) => {
  // Replace block-level LaTeX delimiters \[ \] with $$ $$

  
  const blockProcessedContent = content.replace(
    /\\\[(.*?)\\\]/gs,
    (_, equation) => `$$${equation}$$`,
  );
  // Replace inline LaTeX delimiters \( \) with $ $
  const inlineProcessedContent = blockProcessedContent.replace(
    /\\\((.*?)\\\)/gs,
    (_, equation) => `$${equation}$`,
  );
  return inlineProcessedContent;
};
```

**Comment by evgeny3322** [comment]
> Для обработки латекса чатгпт или опенай.
> 
> ```ts
> export const preprocessLaTeX = (content: string) => {
>   // Replace block-level LaTeX delimiters \[ \] with $$ $$
> 
>   
>   const blockProcessedContent = content.replace(
>     /\\\[(.*?)\\\]/gs,
>     (_, equation) => `$$${equation}$$`,
>   );
>   // Replace inline LaTeX delimiters \( \) with $ $
>   const inlineProcessedContent = blockProcessedContent.replace(
>     /\\\((.*?)\\\)/gs,
>     (_, equation) => `$${equation}$`,
>   );
>   return inlineProcessedContent;
> };
> ```

how can your example be used in my code?


                <MemoizedReactMarkdown
                  remarkPlugins={[remarkGfm, remarkMath]}
                  rehypePlugins={[rehypeMathjax]}
                >
                  {message.content}
                </MemoizedReactMarkdown>

**Comment by shubh675** [comment]
@prashantbhudwal  it's good idea

**Comment by pavloko** [comment]
@mandeep511 @shubh675 @prashantbhudwal I'm investigating the same issue and wondering how `chatgpt.com` is doing it because they seem to be using react-markdown....

I'm sorry this discussion is obviously not related to react-markdown, but I guess many people will come here looking for this answer.

<img width="888" alt="Screenshot 2024-06-05 at 18 04 29" src="https://github.com/remarkjs/react-markdown/assets/12280422/cf51d662-02a5-407d-a124-60d1b5cbd145">

**Comment by prashantbhudwal** [comment]
@pavloko this is just additional preprocessing to handle latex edge cases. Everything else is done with react-markdown with plugins.

You can give examples of how to format latex and most of the times katex plugin will render it. If it doesn't, this might help.

**Comment by prashantbhudwal** [comment]
@pavloko They are using this property for the math plugin -   [remarkMath, { singleDollarTextMath: false }],

That could change stuff. Please feel free to try. 

![Screenshot 2024-06-05 at 9 21 33 PM](https://github.com/remarkjs/react-markdown/assets/11509983/13cf11df-d771-44dd-8630-83937f986c3a)

**Comment by danny-avila** [comment]
Just want to add to the discussion. 
`[remarkMath, { singleDollarTextMath: false }],`

It makes sense for them to do this because enabling it (default behavior, I believe) will cause issues when users don't expect LaTeX at all, i.e.:

> I have $50 in my wallet and $100 in the bank.

Their pre-processing may involve detecting LaTeX more robustly for single-line, perhaps converting them to multi-line formatting, I'm not sure, since the setting drops the native in-line rendering, or maybe the settings is triggered on by specific LaTeX identifiers, who knows.

Before @prashantbhudwal suggested his function, I'd implemented my own pre-processing function. Upon revisiting this problem, I was inspired to tackle some edge cases users of [LibreChat](https://github.com/danny-avila/LibreChat) have experienced with the LaTeX rendering taking some lessons learned from this thread, so I'm here to share back, since the solution and others, including my previous implementation, exhibit those edge cases.

We can set `singleDollarTextMath` to `true` but we need to escape several uses of `$` as suggested, otherwise, users will see weird rendering for the simple "wallet" statement above, to name one of the edge cases.

I was inspired by the implementation here: https://github.com/lobehub/lobe-ui/pull/168 but it was not complete.

[Here's what I came up with](
https://github.com/danny-avila/LibreChat/blob/ea5140ff0fa53d8659ec4892b1cd2b2dc5aaf942/client/src/utils/latex.ts#L50) after several hours of trial and error:
```ts
/**
 * Preprocesses LaTeX content by replacing delimiters and escaping certain characters.
 *
 * @param content The input string containing LaTeX expressions.
 * @returns The processed string with replaced delimiters and escaped characters.
 */
export function preprocessLaTeX(content: string): string {
  // Step 1: Protect code blocks
  const codeBlocks: string[] = [];
  content = content.replace(/(```[\s\S]*?```|`[^`\n]+`)/g, (match, code) => {
    codeBlocks.push(code);
    return `<<CODE_BLOCK_${codeBlocks.length - 1}>>`;
  });

  // Step 2: Protect existing LaTeX expressions
  const latexExpressions: string[] = [];
  content = content.replace(/(\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\]|\\\(.*?\\\))/g, (match) => {
    latexExpressions.push(match);
    return `<<LATEX_${latexExpressions.length - 1}>>`;
  });

  // Step 3: Escape dollar signs that are likely currency indicators
  content = content.replace(/\$(?=\d)/g, '\\$');

  // Step 4: Restore LaTeX expressions
  content = content.replace(/<<LATEX_(\d+)>>/g, (_, index) => latexExpressions[parseInt(index)]);

  // Step 5: Restore code blocks
  content = content.replace(/<<CODE_BLOCK_(\d+)>>/g, (_, index) => codeBlocks[parseInt(index)]);

  // Step 6: Apply additional escaping functions
  content = escapeBrackets(content);
  content = escapeMhchem(content);

  return content;
}
```

I also wrote [some tests](https://github.com/danny-avila/LibreChat/blob/main/client/src/utils/latex.spec.ts) for this:
```bash
  preprocessLaTeX
    ✓ returns the same string if no LaTeX patterns are found (1 ms)
    ✓ escapes dollar signs followed by digits
    ✓ does not escape dollar signs not followed by digits
    ✓ preserves existing LaTeX expressions (1 ms)
    ✓ handles mixed LaTeX and currency
    ✓ converts LaTeX delimiters
    ✓ escapes mhchem commands
    ✓ handles complex mixed content
    ✓ handles empty string
    ✓ preserves code blocks
    ✓ handles multiple currency values in a sentence
    ✓ preserves LaTeX expressions with numbers
    ✓ handles currency values with commas
    ✓ preserves LaTeX expressions with special characters
```

I'm sure it's not perfect, nor the most optimal, but it handles both those expecting LaTeX to render correctly with most AI model providers (OpenAI, Anthropic, Llama3.1, whose formatting of LaTeX largely depend on their training)

I'm happy to share and collect feedback, and be corrected on this approach, maybe the way OpenAI does with ChatGPT is the better route, but I chose this one as it was more apparent to me.

Example rendering:
![image](https://github.com/user-attachments/assets/553ae67c-1d96-45b4-88c8-5bf89d9c6cf0)

**Comment by pavloko** [comment]
@danny-avila This is great. Thank you very much! I'll try to use the shared solution and get back to you.

**Comment by supuwoerc** [comment]
@danny-avila Your drilling spirit helps everyone, thank you very much, I researched for two hours and you saved me

**Comment by joseph-mccombs** [comment]
@danny-avila this algo is amazing. i was having similar issues with some of the other algorithms, but yours took care of every single issue. 🐐

**Comment by gaurav404** [comment]
@danny-avila thanks for this amazing algo, it works like a charm
Can anyone suggest why "\\[\nn = \\frac{2 \\, \\text{atm} \\times 10 \\, \\text{L}}{0.0821 \\, \\text{L·atm/(K·mol)} \\times 300 \\, \\text{K}}\n\\]\n\\[\nn = \\frac{20}{24.63} \\approx 0.812 \\, \\text{mol}\n\\]"
is rendering cdot, thanks if anyone can help... rest I am debugging
<img width="375" alt="image" src="https://github.com/user-attachments/assets/4b8cef24-271a-4be7-b6e8-100d4be12d2f">

**Comment by GorvGoyl** [comment]
I'm replacing katex with double dollar sign and it's working fine for different scenarios I could think of. Here's the implementation for reference:

```js

 const markdownWithKatexSyntax = processKatexInMarkdown(renderedMarkDown);

    return (
        <MemoizedReactMarkdown
            remarkPlugins={[remarkGfm, [remarkMath, { singleDollarTextMath: false }]]}
            rehypePlugins={[
                () => {
                    return rehypeKatex({ output: 'htmlAndMathml'});
                },
            ]}
            >
            {markdownWithKatexSyntax}
        </MemoizedReactMarkdown>
    );

export function processKatexInMarkdown(markdown: string) {
    const markdownWithKatexSyntax = markdown
        .replace(/\\\\\[/g, '$$$$') // Replace '\\[' with '$$'
        .replace(/\\\\\]/g, '$$$$') // Replace '\\]' with '$$'
        .replace(/\\\\\(/g, '$$$$') // Replace '\\(' with '$$'
        .replace(/\\\\\)/g, '$$$$') // Replace '\\)' with '$$'
        .replace(/\\\[/g, '$$$$') // Replace '\[' with '$$'
        .replace(/\\\]/g, '$$$$') // Replace '\]' with '$$'
        .replace(/\\\(/g, '$$$$') // Replace '\(' with '$$'
        .replace(/\\\)/g, '$$$$'); // Replace '\)' with '$$';
    return markdownWithKatexSyntax;
}
```

**Comment by hhh2210** [comment]
> I'm replacing katex with double dollar sign and it's working fine for different scenarios I could think of. Here's the implementation for reference:我正在用双美元符号替换 katex，并且在我想得到的各种场景中都能正常工作。以下是实现供参考：
> 
> ```js
>  const markdownWithKatexSyntax = processKatexInMarkdown(renderedMarkDown);
> 
>     return (
>         <MemoizedReactMarkdown
>             remarkPlugins={[remarkGfm, [remarkMath, { singleDollarTextMath: false }]]}
>             rehypePlugins={[
>                 () => {
>                     return rehypeKatex({ output: 'htmlAndMathml'});
>                 },
>             ]}
>             >
>             {markdownWithKatexSyntax}
>         </MemoizedReactMarkdown>
>     );
> 
> export function processKatexInMarkdown(markdown: string) {
>     const markdownWithKatexSyntax = markdown
>         .replace(/\\\\\[/g, '$$$$') // Replace '\\[' with '$$'
>         .replace(/\\\\\]/g, '$$$$') // Replace '\\]' with '$$'
>         .replace(/\\\\\(/g, '$$$$') // Replace '\\(' with '$$'
>         .replace(/\\\\\)/g, '$$$$') // Replace '\\)' with '$$'
>         .replace(/\\\[/g, '$$$$') // Replace '\[' with '$$'
>         .replace(/\\\]/g, '$$$$') // Replace '\]' with '$$'
>         .replace(/\\\(/g, '$$$$') // Replace '\(' with '$$'
>         .replace(/\\\)/g, '$$$$'); // Replace '\)' with '$$';
>     return markdownWithKatexSyntax;
> }
> ```

How need I apply this?
just add to client/src/utils/latex.js doesn't work

**Comment by Saran33** [comment]
Thanks @GorvGoyl that seems like the best solution for our purposes, avoiding all potential single $ edge cases. It seems that substituting $ blocks with $$ blocks results in the exact same HTML. I didn't realise this until trying your suggestion. Therefore, I can't see any reason to ever need single $ blocks, unless I'm overlooking something.

Perhaps the criteria by which `remark-math` determines whether LaTeX expressions should be inlined or blocked is based on other markdown parsing rules, not just the delimiters?

With the above approach, even when using $$ for everything, the `.katex-display` classes are still correctly only being set on expressions intended to be blocks.

```css
.katex-display {
  margin: 1em 0;
  text-align: center;
  font-size: 1.2em; /* slightly larger */
}
```
The above CSS will only apply changes to expressions separated from text by blank lines or newlines, even if using $$ delimiters for everything.

Perhaps if ChatGPT is setting `singleDollarTextMath` to false, they could be relying on this $$ for everything approach?
