### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by eurobob** [remarkjs/react-markdown#787]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

This package is adding 438kb to my rendered bundle size

This was previously brought up around the time of v6.0.0, nearly 3 years ago regarding an increase from 23.5kb to 32.4kb
https://github.com/remarkjs/react-markdown/issues/595

438kb seems incredibly excessive, is there any way to optimise this?

### Solution

Not sure the specifics, does it need tree shaking?

### Alternatives

Unsure

**Comment by wooorm** [comment]
Change your tools.
See the badge in the readme: https://github.com/remarkjs/react-markdown#react-markdown.
Within the constraints of the goal of this project (support CM, plugins, useful default options), it isn’t going to get smaller.

**Comment by Murderlon** [comment]
Also good to note that the package is [42.6kB (minified + gzipped)](https://bundlephobia.com/package/react-markdown@9.0.0). If bundle size is critical, considering server-side rendering your markdown to HTML so you don't have client-side libraries for this.
