### ISSUE TITLE
Options linkTarget and renderers are no-longer available

### ISSUE THREAD

**Issue by MiguelGuthridge** [remarkjs/react-markdown#789]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"react-markdown": "^9.0.0"

### Link to runnable example

https://codesandbox.io/p/sandbox/awesome-jerry-lh8lp8?file=%2Fsrc%2Fapp.tsx%3A3%2C75

### Steps to reproduce

Using Node 18, NPM 10.

I am attempting to make links open in a new tab as documented in #379 and #65, but using either the `linkTarget` or `renderers` options give a TypeScript error, and fail to render.

How can I make links open in a new tab, given that these options are no-longer available?

### Expected behavior

I can make links open in a new tab easily by specifying a simple option or overriding a simple renderer.

### Actual behavior

I cannot find a simple way to accomplish this common behaviour.

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Hey! See the changelog: https://github.com/remarkjs/react-markdown/blob/main/changelog.md#add-urltransform, https://github.com/remarkjs/react-markdown/blob/main/changelog.md#remove-linktarget.

**Comment by ivoiv** [comment]
What a senseless change about linkTarget.
Makes the package useless for our company.
Time to find something else.
