### ISSUE TITLE
Bold not render in some cases

### ISSUE THREAD

**Issue by MrHGJ** [remarkjs/react-markdown#790]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.7

### Steps to reproduce

![image](https://github.com/remarkjs/react-markdown/assets/33540797/6518a285-c280-4b9c-939b-011bb637d9c2)

### Expected behavior

![image](https://github.com/remarkjs/react-markdown/assets/33540797/27e3bbfb-eb2d-416d-8d67-ad79d501f8e4)

### Actual behavior

**bold:**test

**Comment by wooorm** [comment]
That’s how markdown works.
