### ISSUE TITLE
Support passing 'id' (or any other arbitrary 'div' tags)

### ISSUE THREAD

**Issue by CHE1RON** [remarkjs/react-markdown#792]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

When rendering `Markdown`, it wraps all content inside a `<div>`, but does not provide any means to pass arbitrary or even the most basic props to this element (`className` being the only one).

I stumbled across https://github.com/remarkjs/react-markdown/issues/242, which *I think* is about exactly this, but was discarded as 'add props to components being rendered *inside* this `div` tag' - however, the issue still stands 😁 

### Solution

I'd be happy to open a PR for at least `id` to be an allowed property - think of `aria-labelledby` referencing this *without* having to wrap it in yet another `div`!

### Alternatives

It might be solved by having `div` props being passed as single argument 🤔

**Comment by wooorm** [comment]
Hey!

We don’t generate a `div` normally. Only with `className`.
If you want a `div` with an `id` or whatever else, write one:

```jsx
<div id="x">
  <Markdown><Markdown>
</div>
```

This seems more like #781. Either we can remove `className`, and this `div`, or we can pass all other properties through to a `div`. Leave a comment there if you feel for one or the other!
