### ISSUE TITLE
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for html-url-attributes@^3.0.0

### ISSUE THREAD

**Issue by dimpu** [remarkjs/react-markdown#795]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown@9.0.0

### Steps to reproduce

OS: Mac OS(14.0 (23A344)) Apple M1 Pro
Node: v18.18.2
pnpm: 8.10.0

run 

`pnpm add react-markdown@latest
`

` pnpm view html-url-attributes versions
` 
 [ '1.0.0', '1.0.1', '1.0.2', '1.0.3', '2.0.0' ]

### Expected behavior

Install latest react-markdown

### Actual behavior

 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for html-url-attributes@^3.0.0

### Runtime

Node v17

### Package manager

pnpm

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment]
Hey @dimpu! 👋 
Sorry you ran into a spot of trouble.

Version 3.0.0 was published several months ago, and is live on the npm registry https://www.npmjs.com/package/html-url-attributes/v/3.0.0
Either you are using a custom registry/registry proxy.
Or there is a bug in `pnpm` https://github.com/pnpm/pnpm
