### ISSUE TITLE
Package dependencies error: ./node_modules/mdast-util-to-hast/lib/index.js Module not found: Can't resolve 'devlop'

### ISSUE THREAD

**Issue by Jonathan-de-Villiers** [remarkjs/react-markdown#798]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"react-markdown": "^9.0.1",

### Steps to reproduce

I've just installed the package using yarn. imported it to a file and tried to use it.

### Expected behavior

Hoped it would work 

### Actual behavior

it gave me the error and even when I added devlop it still isn't working 

### Runtime

Node v16

### Package manager

yarn 1

### OS

Windows

**Comment by wooorm** [comment]
Are you using webpack 4, create react app?

**Comment by Jonathan-de-Villiers** [comment]
I'm not sure it is an old app that started development back in 2018

**Comment by wooorm** [comment]
You're using outdated and unmaintained tools. Switch to maintained and modern ones in order to use maintained and modern packages. Or use old versions of packages.

**Comment by remcohaszing** [comment]
This sounds like the latest of Expo doesn’t support support package exports. It’s a bug on their end.

**Comment by ChristianMurphy** [comment]
@bartvanandel sorry you ran into a spot of trouble.
The issue remains with Expo, which in return relies on metro.
Metro has known issues handling standard ESM and export specifiers https://github.com/search?q=repo%3Afacebook%2Fmetro+esm&type=issues
Metro and Expo need to resolve their issues.
