### ISSUE TITLE
Bug on old safari(14.1.1)  macos 11.4

### ISSUE THREAD

**Issue by VuHoi** [remarkjs/react-markdown#800]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.0

### Steps to reproduce

![Screen Shot 2023-11-16 at 10 17 42](https://github.com/remarkjs/react-markdown/assets/22574773/b5f85a7e-afb6-47c4-b6cf-d438aa813597)
When i run on old version safari. some function JS is not support. Please help me to fix it.

### Expected behavior

Support old version safari

### Actual behavior

Get error when run on old version safari

### Runtime

Node v17

### Package manager

yarn 1

### OS

macOS

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
Welcome @VuHoi! 👋 
Sorry you ran into a spot of trouble.

This is not a bug in `react-markdown`, this library targets ES2022.
If you need to support browsers which do not fully implement ES2022, like Safari 14.
You need to configure your build tool.
In Next.js this is through the `browserslist` option https://nextjs.org/docs/architecture/supported-browsers, make sure your browsers list includes the browsers you want to support.

Next.js should automatically polyfill it with the correct settings.
If it does not, follow their guide on manually polyfilling from the same page, and apply the Core.js polyfill https://github.com/zloirock/core-js#ecmascript-object
