### ISSUE TITLE
Classname is always `undefined`

### ISSUE THREAD

**Issue by jpwallace22** [remarkjs/react-markdown#802]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown@9.0.1

### Steps to reproduce

- Receive text from an LLM response such as ChatGPT or Llama-2 
  - ensured the response from the LLM included proper syntax and language name on gate
- Pass text to `ReactMarkdown` as such: 
![Screenshot 2023-12-18 at 4 20 05 PM](https://github.com/remarkjs/react-markdown/assets/93415734/41173cd1-8f8f-4884-b367-b3b8490c0617)
- console.log(className)

### Expected behavior

Classname should include the language

### Actual behavior

Class name is `undefined` no matter what. 

### Runtime

Node v17

### Package manager

yarn 1

### OS

macOS

### Build and bundle tools

Remix

**Comment by JounQin** [comment]
Reproduction please.

**Comment by jpwallace22** [comment]
> Reproduction please.

@JounQin Not sure the best way to make a reproduction without exposing API keys for an LLM.

**Comment by ChristianMurphy** [comment]
@jpwallace22 that is part of producing a minimally reproducible example. https://stackoverflow.com/help/minimal-reproducible-example
If you believe the issue is with `react-markdown` and not with the LLM or another library, show an example of the issue without those pieces.
If it is an issue with `react-markdown` you can reproduce it with just the markdown that was produced from the LLM, which can be hardcoded.

**Comment by ChristianMurphy** [comment]
There are also an assortment of sandboxes which can help simplify the process.
| description | codesandbox | stackblitz |
| - | - | - |
| remark only (for markdown to markdown) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-vite) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-vite) |
| remark and rehype (for markdown to html) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-vite) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-vite) |
| react-markdown | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-vite) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-vite) |

**Comment by jpwallace22** [comment]
@ChristianMurphy Thank you so much for sandbox links. I was having trouble finding them on my own. 😅 
Good call on getting it to repeat with the LLM, I can't get it to reproduce. Which leads me to believe the failure is on my end somewhere. 
I will close this out and if I need to reopen down the road I will do so with a better ticket and reproduction. 
Happy holidays!
