### ISSUE TITLE
Usage of `Object.hasOwn` breaks web pages on iPad OS (iPad Air, Safari & Chrome)

### ISSUE THREAD

**Issue by grisha87** [remarkjs/react-markdown#804]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown

### Steps to reproduce

You would need to create a web page using `react-markdown` and open it on an iPad Air. Both Safari and Chrome for iOS crash on this particular ssie

### Expected behavior

The react based page should load correctly.

### Actual behavior

The react app gets broken (displays a white page instead of any content) and the logs point out to the fact that `Object.hasOwn` is not defined.

AS per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn, it's supported from Safari 15. I'd like to make use of `react-markdown`, but it's not usable for my users that would run Safari 14 as a browser.

### Runtime

Other (please specify in steps to reproduce)

### OS

macOS

---

I could contribute the relevant change from `Object.hasOwn` to `Objet.prototype.hasOwnProperty` if that's OK with the maintainers.

**Comment by wooorm** [comment]
Modern tools can indeed not be usable in older browsers depending on what you choose to target.
Our target (Node 16) is made clear in the docs. A major release is used to update it.

Use tools such as esbuild or babel to target your particular users. Or use older versions.

**Comment by ktalebian** [comment]
@wooorm what does "older browser" mean here? What browsers/OS versions are considered old?

**Comment by ChristianMurphy** [comment]
Again @ktalebian this project targets Node 16.

The closest browser equivalent is Chrome version 90+.
All browsers will need some build tools.
The older the browser the more polyfills you will need.

Nitpicking at the definition of "new" versus "old" is a waste of time.

**Comment by joebnb** [comment]
same issue happened,is any progress about it?

**Comment by ChristianMurphy** [comment]
@joebnb see the comment before yours.
There's nothing to fix at the library level, configure your build tool to work for your browser matrix.

If you have a question on usage ask it in a Q&A discussion post https://github.com/orgs/remarkjs/discussions/new?category=q-a
