### ISSUE TITLE
rehypeKatex with remarkMath is not working for latex math

### ISSUE THREAD

**Issue by sami-lab** [remarkjs/react-markdown#805]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

^8.0.2

### Link to runnable example

[sandbox](https://codesandbox.io/p/sandbox/react-markdown-katex-latex-mathjax-ks38j8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqohd6yy0006356j6o5hoonv%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqohd6yx0002356j0291d7no%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqohd6yx0003356j470o8b7z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqohd6yx0005356jva72s93r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B48.77371143897298%252C51.22628856102702%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqohd6yx0002356j0291d7no%2522%253A%257B%2522id%2522%253A%2522clqohd6yx0002356j0291d7no%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqohgywj003v356jongfhbrg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A2%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A4%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FMarkDown.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqohgywj003v356jongfhbrg%2522%257D%252C%2522clqohd6yx0005356jva72s93r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqohd6yx0004356jma4qx4fj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqohd6yx0005356jva72s93r%2522%252C%2522activeTabId%2522%253A%2522clqohd6yx0004356jma4qx4fj%2522%257D%252C%2522clqohd6yx0003356j470o8b7z%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqohd6yx0003356j470o8b7z%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

I have chat AI bot in which i am using react-markdown. But markdown is not working with latex formulas. I have attached my implementation

[sandbox](https://codesandbox.io/p/sandbox/react-markdown-katex-latex-mathjax-ks38j8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqohd6yy0006356j6o5hoonv%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqohd6yx0002356j0291d7no%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqohd6yx0003356j470o8b7z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqohd6yx0005356jva72s93r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B48.77371143897298%252C51.22628856102702%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqohd6yx0002356j0291d7no%2522%253A%257B%2522id%2522%253A%2522clqohd6yx0002356j0291d7no%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqohgywj003v356jongfhbrg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A2%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A4%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FMarkDown.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqohgywj003v356jongfhbrg%2522%257D%252C%2522clqohd6yx0005356jva72s93r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqohd6yx0004356jma4qx4fj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqohd6yx0005356jva72s93r%2522%252C%2522activeTabId%2522%253A%2522clqohd6yx0004356jma4qx4fj%2522%257D%252C%2522clqohd6yx0003356j470o8b7z%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqohd6yx0003356j470o8b7z%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Expected behavior

Latex formulas should be format like usuall

### Actual behavior

Currently it is rendering as text

**Comment by ChristianMurphy** [comment]
Welcome @sami-lab! 👋 
What is your question or concern?
In the sandbox you shared, the `react-markdown` example labeled "Katex" renders the formula correctly and fully styled.
![Screenshot 2023-12-31 at 11-32-20 react markdown katex latex mathjax - CodeSandbox](https://github.com/remarkjs/react-markdown/assets/3107513/6d4a7ed1-eda5-4319-a5e7-50bd26a5d7c7)

**Comment by iArchin** [comment]
i have the same problem, did you find the solution? @sami-lab

**Comment by wooorm** [comment]
There is no problem. See thread. I can’t look in your head. Share things.

**Comment by LeonsCd** [comment]
<img width="1045" alt="Image" src="https://github.com/user-attachments/assets/04ece4f4-044a-4402-ab62-a2c3e64183fb" />
Do you mean the meaning in this picture? If there is no space or other symbol between the two formulas, it will cause an error, but in pure MathJax, it won't. This is the problem I found in actual use. Of course, I think Markdown has its own reasons for doing so. Here it is.
