### ISSUE TITLE
Support for inapp links

### ISSUE THREAD

**Issue by daniil00d** [remarkjs/react-markdown#809]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

When inputting a link formatted as `[hello]({any_app}://something)` or `<{any_app}://something>`, a link node with an empty href is created.

### Solution

 I'd like the library to support this case: we input a link to an application (installed on the current device), and upon clicking said link, the application is opened. An example being: [click me](notion://daniil00t.notion.site/Hello-there-d92b643ece0a410ea8a643e824cc619c)

### Alternatives

One potential solution could be to give the user more control over the transformation of links obtained from the text. This could be achieved, for example, by extending the `transformLinkUri` prop, where it would be possible to access the protocol, domain, pathname, query, etc.

**Comment by ChristianMurphy** [comment]
Welcome @daniil00d! 👋 

They are supported, but disabled by default as they are insecure.
You can set your own URL transform in the options https://github.com/remarkjs/react-markdown#options
See https://github.com/remarkjs/react-markdown/issues/774 for some examples

**Comment by ChristianMurphy** [comment]
Duplicate of #774
