### ISSUE TITLE
Possible inconsistency with handling emphasis and strong when immediately followed by emphasis

### ISSUE THREAD

**Issue by puopg** [remarkjs/react-markdown#812]
When processing the MD string 
```
***123****456*

<em>
  <strong>123</strong>
</em>
<em>456</em>
```
React markdown renders what seems to be some additional asterisks?

![Screenshot 2024-01-31 at 1 15 46 PM](https://github.com/remarkjs/react-markdown/assets/7741481/d0abc96b-06a3-4346-9ea1-76d69c89dff0)

### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.1

### Steps to reproduce

Compare the result of:
- [https://spec.commonmark.org/dingus/?text=***123****456*](https://spec.commonmark.org/dingus/?text=***123****456*)
- https://codesandbox.io/p/sandbox/sad-kilby-ggxhdp

This is just 1 word, where the first half is both italicized and bolded, the 2nd half is only italicized.

The MDAST that gets created from unified() => rehypeParse => rehypeRemark looks correct, so to me the issue seems to be either:
1. The syntax generated from the processing flow is incorrect.
2. The syntax is correct, and its React-Markdown's rendering of the syntax that is not correct.

### Expected behavior

![Screenshot 2024-01-31 at 1 15 38 PM](https://github.com/remarkjs/react-markdown/assets/7741481/f0a96f1f-6651-4a86-bfbe-011b153d5fc6)

### Actual behavior

![Screenshot 2024-01-31 at 1 15 46 PM](https://github.com/remarkjs/react-markdown/assets/7741481/d0abc96b-06a3-4346-9ea1-76d69c89dff0)

**Comment by ChristianMurphy** [comment]
Thanks @puopg!

Tracing this further into the stack.
This is coming from the markdown parser `react-markdown` uses, `micromark` https://stackblitz.com/edit/stackblitz-starters-n2yquc

I know there is at least one emphasis related issue open https://github.com/micromark/micromark/issues/92
But this feels different, would you be interested/able to post an issue to `micromark` @puopg?

**Comment by puopg** [comment]
Sure thing, lemme open one and ill link it here

**Comment by wooorm** [comment]
Thanks, moving the discussion there :)
