### ISSUE TITLE
rermarkgfm showing tasklist wrong

### ISSUE THREAD

**Issue by OpenJarvisAI** [remarkjs/react-markdown#817]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.2

### Link to runnable example

ferf

### Steps to reproduce

ferfer

### Expected behavior

gerger

### Actual behavior

gferg

<img width="47" alt="image" src="https://github.com/remarkjs/react-markdown/assets/136460643/d0896f7e-731d-44a3-97d1-3c2014a974f2">
<img width="95" alt="image" src="https://github.com/remarkjs/react-markdown/assets/136460643/82acaac8-6434-4fee-9d65-d51b822760a8">

bad and odd.

### Runtime

Node v17

### Package manager

npm 8

### OS

Windows

### Build and bundle tools

Rollup

**Comment by remcohaszing** [comment]
This issue contains no information and can't be acted upon.

**Comment by OpenJarvisAI** [comment]
@remcohaszing Can your lib render task list right???

**Comment by ChristianMurphy** [comment]
Yes, you can see working example on the demo page https://remarkjs.github.io/react-markdown/

Take some time to frame your question  (https://github.com/remarkjs/.github/blob/main/support.md#asking-quality-questions)
A runnable example of what you are trying inside a sandbox gives context on what you are trying to do in the code.

**Comment by OpenJarvisAI** [comment]
<img width="1166" alt="image" src="https://github.com/remarkjs/react-markdown/assets/136460643/6ced766e-3371-4d58-959f-40fad9cd3bb9">

- [ ] fff
- [ ] rtgrt

**Comment by OpenJarvisAI** [comment]
I am a 10 years front-end developer, and I have set

<Markdown remarkPlugins={[remarkGfm]}>{markdown}</Markdown>

plugin on,not work

**Comment by ChristianMurphy** [comment]
> I am a 10 years front-end developer

Great, act like it then 🙂 

> ```
> <Markdown remarkPlugins={[remarkGfm]}>{markdown}</Markdown>
> ```

That doesn't answer my question, how are you running it?
There are millions of possible build tools.
Here is a minimal reproducible example showing it working with latest vite, react-markdown, and remark-gfm
https://stackblitz.com/edit/github-j5vjzd?file=package.json,src%2Fapp.tsx

Show a minimal reproducible example of what you are seeing.

**Comment by OpenJarvisAI** [comment]
@ChristianMurphy hi, am just using nextjs.

**Comment by OpenJarvisAI** [comment]
Oh, I looked it jusst like mine, the blaxk dot is can be invisiable?

- [ ] ddd
- [ ] ddd

look at github

**Comment by ChristianMurphy** [comment]
> am just using nextjs

There are 14 major versions of next and many possible build configurations share a reproducible example.
https://next.new could be a starter.

> the black dot is can be invisible?

I don't understand what you are asking.
What black dot?

Broadly speaking you can style HTML to look like anything.
Check your style sheet to see how you are customizing the page appearance, you may be styling check lists to not appear.

Tailwind CSS is particularly well known to have styles which break markdown rendering by default.

**Comment by ChristianMurphy** [comment]
@OpenJarvisAI that is how markdown works, it is specified in the standard. https://github.github.com/gfm/#task-list-items-extension-

Markdown does not specify the styles, that is completely up to you and your application.
If you want to style it exactly how GitHub does apply a stylesheet like https://github.com/sindresorhus/github-markdown-css or you can make your own https://www.w3schools.com/CSS/css_list.asp.

**Comment by OpenJarvisAI** [comment]
I have never (or very rare) see a markdown checklist have black dots before.

I am prefer just using people usually understand way, besides, I am already using gfm and you saying `If you want to style it exactly how GitHub does` which I am very hard to understand.

Nevertheless, this is the very unique markdown default styling looks so abnormal.

**Comment by ChristianMurphy** [comment]
> I have never (or very rare) see a markdown checklist have black dots before.

Because almost everyone applies a stylesheet to theme content to match their application.

> Nevertheless, this is the very unique markdown default styling looks so abnormal.

That is how HTML looks 🤷 
If you want it to look different style it.

> How can I just applying the css linked above to my react & next13 project?

By following the Next JS guide on adding external stylesheets https://nextjs.org/docs/pages/building-your-application/styling/css-modules#import-styles-from-node_modules

**Comment by OpenJarvisAI** [comment]
well,  why not add right css as default?

**Comment by OpenJarvisAI** [comment]
I sitll don't know , how to set css in it.

**Comment by remcohaszing** [comment]
When it comes to web development, React is quite advanced. I suggest you start with a tutorial to understand the basics of HTML, then work up to CSS, then JavaScript, then React. A good starting point would be https://www.w3schools.com/html/default.asp.

**Comment by OpenJarvisAI** [comment]
OK, so if I have to  set all <li> css for this markdown? Don't think it will overwrite all other components?

**Comment by wooorm** [comment]
Please take some time to learn markdown and CSS. You write markdown here on GH, that `<li>` gets interpreted. And for the CSS, learn how to write good CSS and do everything you want.

Locking this. This is not free customer service.
