### ISSUE TITLE
Tables do not display correctly when they have spaces at the beginning (remark-gfm)

### ISSUE THREAD

**Issue by Xing97** [remarkjs/react-markdown#819]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown 9.0.1 & remark-gfm 4.0.0

### Steps to reproduce

Runtime: Node v20

This input:
```
Value | Type
----: | --------
    0 | fighting
    1 | flying
    2 | poison
    3 | ground
    4 | rock
    5 | bug
    6 | ghost
    7 | steel
    8 | fire
    9 | water
   10 | grass
   11 | electric
   12 | psychic
   13 | ice
   14 | dragon
   15 | dark
```

It seems that the problem is because of the leading spaces in the rows. If they are removed, it displays correctly. Is the table formatted wrong or is it a defect of react-markdown with remark-gfm?

### Expected behavior

![image](https://github.com/remarkjs/react-markdown/assets/33090500/fff177f9-6bd3-441b-a002-6ab976249c0f)

### Actual behavior

![image](https://github.com/remarkjs/react-markdown/assets/33090500/26e89054-4b61-4a42-bb12-48757e8734e8)

### Runtime

Other (please specify in steps to reproduce)

### Package manager

pnpm

### OS

Windows

### Build and bundle tools

Vite

**Comment by ChristianMurphy** [comment]
Welcome @Xing97! 👋 
Sorry you ran into some confusion.
That is not how tables work.
The rules of tables as defined by GFM are noted here: https://github.github.com/gfm/#tables-extension-
In particular you are running into a conflict with indented code blocks https://github.github.com/gfm/#indented-code-blocks

Consider adding pipe symbols around the table to resolve the conflict.

---

For future reference: You can see the behavior is the same on GitHub itself below.

---

Value | Type
----: | --------
    0 | fighting
    1 | flying
    2 | poison
    3 | ground
    4 | rock
    5 | bug
    6 | ghost
    7 | steel
    8 | fire
    9 | water
   10 | grass
   11 | electric
   12 | psychic
   13 | ice
   14 | dragon
   15 | dark
