### ISSUE TITLE
Custom Components Always Re-rendered

### ISSUE THREAD

**Issue by Ramon-W** [remarkjs/react-markdown#821]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown@9.0.1, react-markdown@latest

### Link to runnable example

https://codesandbox.io/p/devbox/boring-kepler-mzcxps?file=%2Fsrc%2Fapp.tsx%3A56%2C9

### Steps to reproduce

On the sandbox:

1. Replace any component with a custom component, in this case ``p``.
2. Inspect element and observe how the ``p`` tag is being re-rendered even when it is not changing, and the non-custom components are not being re-rendered.

### Expected behavior

The custom component should act normal and not be re-rendered unnecessarily. I believe regular components are given a key equal to the index, but I am unable to figure out how to apply this index on custom components, which might fix this issue. I have also attempted using ``memo`` but it did not work for me.

My specific issue is that I am streaming very long outputs from LLMs and passing them into react markdown, and I am using many stateful, custom components. However, these custom components are always being re-rendered and are unusable until the streaming stops.

### Actual behavior

The custom components re-renders every time ``children`` changes.

### Runtime

Node v17

### Package manager

npm 8

### OS

Linux, macOS

### Build and bundle tools

Vite

**Comment by JounQin** [comment]
<img width="600" alt="image" src="https://github.com/remarkjs/react-markdown/assets/8336744/ad688e73-3d63-495a-80dc-57aa25f7347a">

**Comment by Ramon-W** [comment]
Fixed link

**Comment by JounQin** [comment]
That's because your `components` prop always changes on every render.

See also https://github.com/remarkjs/react-markdown/issues/791#issuecomment-1933576418
