### ISSUE TITLE
Not compatible to Chrome 90 or older

### ISSUE THREAD

**Issue by guoyunhe** [remarkjs/react-markdown#822]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.1

### Steps to reproduce

1. Install Chrome 90 or use https://www.browserstack.com/
2. Visit https://remarkjs.github.io/react-markdown/

### Expected behavior

Should render

### Actual behavior

Nothing render. Console show errors.

![image](https://github.com/remarkjs/react-markdown/assets/5836790/c4f76a22-f29a-436a-9178-9571b338c335)

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm 8

### OS

Windows

### Build and bundle tools

Webpack

**Comment by JounQin** [comment]
Chrome 90 is too old, and https://remarkjs.github.io/react-markdown is only for demo usage, I don't get why should we support Chrome 90.

**Comment by guoyunhe** [comment]
@JounQin the project's [README](https://github.com/remarkjs/react-markdown?tab=readme-ov-file#compatibility) claims:

> They work in all modern browsers (essentially: everything not IE 11).

The reason why the package is not compatible to Chrome < 93 is that it uses `Object.hasOwn`. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn#browser_compatibility

**Comment by JounQin** [comment]
> They work in all modern browsers (essentially: everything not IE 11).

That's depends on how **moder** means, we can not support Chrome v1.0 of course.

**Comment by guoyunhe** [comment]
> That depends on what **modern** means, we can not support Chrome v1.0 of course.

You could add more clear definition in README.

**Comment by remcohaszing** [comment]
This project is compatible with Node.js 16 and greater. That’s an exact definition. We don’t test across a matrix of different browser versions, so we don’t define the exact meaning of _modern browser_.

If you need to use modern features in an older browser, you can add a polyfill for missing APIs, or transpile modern syntax using Babel.

**Comment by JounQin** [comment]
> You could add more clear definition in README.

Indeed, `unified` projects basically require non-legacy node versions, but browsers support it's not well defined.

Or maybe that section should just be removed considering https://github.com/remarkjs/react-markdown/issues/772#issuecomment-1740920922 and https://github.com/remarkjs/react-markdown/issues/804#issuecomment-1866383351

cc @wooorm and @ChristianMurphy

**Comment by wooorm** [comment]
`Object.hasOwn` is intentional. Previous versions did not have it. The latest version does.
10 years ago I had browser matrix tests. Browser tests are error prone and don’t add much. Browsers nowadays are evergreen: they automatically update.
That’s why the text in the readme says: “They work in all modern browsers (essentially: everything not IE 11)”.

I don’t think we need to add a definition of every word in the readme. I think that the current description is sufficient.

**Comment by marshallcool** [comment]
in the browser `ios Safari 15.1` I get an error - "Object.hasOwn is not a function. (In 'Object.hasOwn(e,t.from)', 'Object.hasOwn' is undefined)",  why don’t you have processing?

**Comment by ChristianMurphy** [comment]
@marshallcool see the comment earlier.
> That’s why the text in the readme says: "They work in all modern browsers"

`react-markdown` will work in evergreen browsers.

Safari 15 is two major versions behind.
You can polyfill your browser with https://github.com/zloirock/core-js if you want.
