### ISSUE TITLE
Please add syntax for `{.tabset} `

### ISSUE THREAD

**Issue by KhoiUna** [remarkjs/react-markdown#825]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I'd love to use `{.tabset}` syntax for markdown, like mentioned here https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html

### Solution

n/a

### Alternatives

n/a

**Comment by ChristianMurphy** [comment]
Welcome @KhoiUna! 👋 

`micromark` and `remark` and their downstream packages follow commonmark https://commonmark.org/
tabset is not part of commonmark, so will not be added by default.

That said, `micromark` and `remark` support syntax plugins.
You could use an existing one like `remark-directive` (recommended) https://github.com/remarkjs/remark-directive
Or create your own syntax extension https://github.com/micromark/micromark?tab=readme-ov-file#extending-markdown
