### ISSUE TITLE
sup element rendering with remark-gfm plugin is painfully slow. 

### ISSUE THREAD

**Issue by tgram-3D** [remarkjs/react-markdown#827]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown 9.0.1, remark-gfm 4.0.0

### Steps to reproduce

I'm using ReactMarkdown to render streaming LLM tokens, which seems to be a common use-case, and I'm trying to get it to render footnotes correctly. It works, but basically the entire paragraph renders fine in markdown but the [^1], [^2] formatted footnotes just sit there basically and don't get rendered as sup until the entire p element is complete.  

```
<ReactMarkdown
                        remarkPlugins={[remarkGfm, remarkMath]}
                        rehypePlugins={[
                            rehypeKatex,
                            [
                                //@ts-expect-error version 6.0.0
                                rehypeHighlight,
                                {
                                    detect: true,
                                    ignoreMissing: true,
                                    subset: codeLanguageSubset
                                }
                            ]
                        ]}
                        components={components}
                    >
                        {content}
                    </ReactMarkdown>
```

I tried a custom component for sup and same deal. Is there a better way to do this sort of thing? I'm thinking I just get rid of remarkGfm and target superscript formatting in my custom p component directly, but it seems like there should be a better solution. 

One thing that's kind of interesting is the back-ref a tags in the footnotes section render just fine, but not the actual sup elements.  

Using node 20.12.0 and npm 10.5.0

### Expected behavior

Footnotes rendered on streaming.  

### Actual behavior

Footnote rendering lags significantly and doesn't work until entire paragraph element is rendered. 

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Windows

### Build and bundle tools

Vite

**Comment by remcohaszing** [comment]
Markdown can’t be streamed. Footnotes and definitions can appear at the end of a document, meaning the entire markdown document needs to be parsed in order to know whether or not something that looks like a footnote reference of link reference is actually a reference or just plain text.

This doesn’t stop people from streaming markdown anyway.

---

```markdown
This paragraph has only one footnote[^1][^2].

[^1]: Footnote
```

This paragraph has only one footnote[^1][^2].

[^1]: Footnote

**Comment by wooorm** [comment]
This is what I am assuming too.

Nothing is “painful” here. You’re just streaming things and observe that things are streamed.

**Comment by tgram-3D** [comment]
> Markdown can’t be streamed. Footnotes and definitions can appear at the end of a document, meaning the entire markdown document needs to be parsed in order to know whether or not something that looks like a footnote reference of link reference is actually a reference or just plain text.
> 
> This doesn’t stop people from streaming markdown anyway.
> 
> ```
> This paragraph has only one footnote[^1][^2].
> 
> [^1]: Footnote
> ```
> 
> This paragraph has only one footnote[1](#user-content-fn-1-bdef20a270ab878aea9caaca039dbe69)[^2].
> 
> ## Footnotes
> 1. Footnote [↩](#user-content-fnref-1-bdef20a270ab878aea9caaca039dbe69)

Ah, duh. That makes sense. I guess I don't understand how it's actually inferring the href for the a tags in the footnotes, cause I'm seeing the same behavior with totally fake content. I'll mark this as closed and figure something else out. Thanks for the replies.
