### ISSUE TITLE
React 18.3.0/19.0.0 support for react-markdown ^6.0.0

### ISSUE THREAD

**Issue by janpe** [remarkjs/react-markdown#828]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

React 18.3.0 gives deprecation warnings for `defaultProps` usage still present in v6. This would be needed for users that are unable to support pure ESM at this point.

### Solution

Remove `defaultProps` usage in v6 and publish a new release with the changes.

### Alternatives

Without this change users are unable to move to React 19 with react-markdown if they need to support commonjs.

**Comment by wooorm** [comment]
Hey! Use v9.

It’s time to use ESM. You can upgrade your tools to support it.
