### ISSUE TITLE
React-markdown isn't rendering phone number links anymore

### ISSUE THREAD

**Issue by aligreene** [remarkjs/react-markdown#829]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown v9.0.0

### Link to runnable example

https://codesandbox.io/p/devbox/react-markdown-telephone-link-bug-3vsqry

### Steps to reproduce

We recently updated from react-markdown ^8.0.3 to ^9.0.0 and since then, any phone link renders with no value in the link href.

See sandbox for runnable example, or follow steps below:

1. Create a markdown telephone link e.g.:
`[123 456 789](tel:123456789)`
2. Check the output.

### Expected behavior

The link is rendered in HTML with a href value:
`<a href="tel:123456789">123 456 789</a>`

### Actual behavior

The link renders without a href value:
`<a href="">123 456 789</a>`

**Comment by wooorm** [comment]
See the changelog: https://github.com/remarkjs/react-markdown/blob/main/changelog.md#add-urltransform.

**Comment by aligreene** [comment]
Thanks very much
