### ISSUE TITLE
rst support

### ISSUE THREAD

**Issue by 100tomer** [remarkjs/react-markdown#830]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

It will be great to have rst (reStructuredText) supported too like markdown is supported. (maybe this belong in a new npm package but it felt like something this npm package might do great

### Solution

The markdown parser can maybe detect if the input is rst and then parse it differently then markdown

### Alternatives

Currently the only solution is to convert rst files to markdown files (the only good convertor I found is pandoc)

**Comment by ChristianMurphy** [comment]
Welcome @100tomer! 👋 
react-markdown is a project for parsing markdown.
reStructuredText is not markdown.

It is possible to build something like that, and even to leverage unified js (https://unifiedjs.com/, the foundation of this project)
But that is a non-goal for react-markdown.

If you have questions on how to connect reStructuredText with syntax trees or unified, feel free to reach out at https://github.com/orgs/syntax-tree/discussions or https://github.com/orgs/unifiedjs/discussions !
