### ISSUE TITLE
Can't drag-over select text to copy a section

### ISSUE THREAD

**Issue by johnsonfamily1234** [remarkjs/react-markdown#831]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.1

### Steps to reproduce

I am using react-markdown in an Electron application. When I try to drag the cursor over a section of text to highlight it for copying I am unable to do so - when I let go the highlighting just goes away and I can't copy anything.

The code looks like a standard implementation - 

`<Markdown className={'font-serif'}
 children={output} 
 remarkPlugins={[remarkGfm]} 
 components={{
  h1(props) {
  const {node, ...rest} = props
  return <div className="text-3xl my-4" {...rest} />
 },
  ... more custom elements
 }}
 />
`

I've done a lot of research but can't find anything related to highlighting or just copying a section of the rendered markdown.

npm v 10.1.0

Has anyone else experienced this? Is there a workaround or something we can change to fix this? 

Thanks!

### Expected behavior

Would expect to be able to drag cursor over a section of rendered text to copy it like anything else.

### Actual behavior

The highlighting disappears when the mouse button is released so the copy area no longer exists.

### Runtime

Electron

### Package manager

Other (please specify in steps to reproduce)

### OS

Windows, macOS

### Build and bundle tools

Webpack

**Comment by ChristianMurphy** [comment]
Welcome @johnsonfamily1234!
Sorry you ran into some confusion.

React-markdown renders static text with no styles and no listeners.
It sounds like you have a stylesheet and potentially event listener issue too.
Those would be coming from code you wrapped around react-markdown.

Reading between the lines, your class names look very tailwind like.
Tailwind breaks plain HTML styles pretty bad, you may want to apply prose styling to the whole markdown section (see https://github.com/remarkjs/react-markdown/issues/505)

**Comment by johnsonfamily1234** [comment]
@ChristianMurphy You were right. I appreciate your quick response and for pointing me in the right direction. It was not an issue with react-markdown and I was able to resolve the issue on my end as a result of your response. Thank you very much.
