### ISSUE TITLE
Identify `last-child`

### ISSUE THREAD

**Issue by aress31** [remarkjs/react-markdown#835]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I would like to see a built-in solution to identify the last-child of a series, this would allow for customisation, for instance:

```js
const components = {
  a: ({ node, ...props }) => (
    <Link target="_blank" rel="noopener noreferrer" {...props} />
  ),
  p: ({ node, ...props }) => (
    <Typography align="justify" color="text.secondary" paragraph {...props} />
  ),
};
```

In the above component/styling, you can see the `paragraph` attribute, I would like to be able to control it on a per item basis, by item I mean, having access to an identifier for the currently processed node.

### Solution

Exposing a `currentIndex` property.

### Alternatives

Hacky CSS tricks...

**Comment by ChristianMurphy** [comment]
Welcome @aress31! 👋 
That feature is built in already through your browser
https://developer.mozilla.org/en-US/docs/Web/CSS/:last-child

I'd recommend using the CSS properties over trying to hack into the JS of the render process to simulate the built in feature.

**Comment by wooorm** [comment]
Use a plugin, use css.
But probably: don’t.
What is `index` even? Index of elements in their parent? What about the whitespace between them? What about other elements between them?
“identifier for the currently processed node” that sounds like a `key`, not a number, which `index` implies.

> Hacky

CSS is not hacky; CSS is great.
