### ISSUE TITLE
TypeError: (0 , unist_util_visit__WEBPACK_IMPORTED_MODULE_1__.visit) is not a function

### ISSUE THREAD

**Issue by adam-magyar-instructure** [remarkjs/react-markdown#840]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.1

### Steps to reproduce

`import React from 'react';
import { Heading, Img, Link, Text } from '@own-ui-lib';
import Markdown from 'react-markdown';

export function OwnUIMarkdown({ markdown }: { markdown: string }) {
    return (
        <Markdown
            components={{
                h1: ({ node, className, children, ...props }) => <Heading level="h1">{children}</Heading>,
                h2: ({ node, className, children, ...props }) => <Heading level="h2">{children}</Heading>,
                h3: ({ node, className, children, ...props }) => <Heading level="h3">{children}</Heading>,
                h4: ({ node, className, children, ...props }) => <Heading level="h4">{children}</Heading>,
                h5: ({ node, className, children, ...props }) => <Heading level="h5">{children}</Heading>,
                strong: ({ node, className, children, ...props }) => <Text weight="bold">{children}</Text>,
                em: ({ node, className, children, ...props }) => <Text fontStyle="italic">{children}</Text>,
                a: ({ node, className, children, ...props }) => (
                    <Link href={props.href} target="_blank">
                        {children}
                    </Link>
                ),
                img: ({ node, className, children, ...props }) => <Img src={props.src ?? ''} alt={props.alt} />,
                text: ({ node, className, children, ...props }) => <Text size="medium">{children}</Text>,
                p: ({ node, className, children, ...props }) => (
                    <Text as="p" size="medium">
                        {children}
                    </Text>
                ),
            }}>
            {markdown}
        </Markdown>
    );
}
`

When using the component below I got the following error in the console and it breaks our application:

![image](https://github.com/remarkjs/react-markdown/assets/163856318/da19a9b2-2ffd-4ba9-988b-99ab4d74b2b0)

### Expected behavior

It should not break the application and should render the markdown.

### Actual behavior

It breaks the application.

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Webpack

**Comment by remcohaszing** [comment]
Another potential cause:

- You’re possibly using npm `overrides` / yarn `resolutions`. You should never use this unless you’re absolutely sure what you’re doing.
