### ISSUE TITLE
Syntex for showing underlined text

### ISSUE THREAD

**Issue by ahadullah8** [remarkjs/react-markdown#841]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

There is nothing to show underlined content.

### Solution

double ++ can be used to identify the content to be underlined

### Alternatives

Not that I know of

**Comment by ChristianMurphy** [comment]
Duplicate of https://github.com/remarkjs/react-markdown/issues/209
