### ISSUE TITLE
custom syntax and custom components are not working

### ISSUE THREAD

**Issue by fengliner** [remarkjs/react-markdown#847]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown@9.0.1

### Steps to reproduce

I want to add a custom syntax, which is warped by :::tip::: and :::/tip:::，will render by my custom component. But, it is not working. My demo code is blow

```js
function customInfoPlugin() {
  return (tree) => {
    let tipOpen = false;
    let tipNode = null;

    visit(tree, 'text', (node) => {
      const value = node.value.trim();
      if (value === ':::tip:::') {
        if (!tipOpen) {
          tipOpen = true;
          tipNode = { type: 'tip', children: [], value: '' };
          node.value = ''; // Clear the opening tag
        } else {
          throw new Error('Nested tips are not allowed.');
        }
      } else if (value === ':::/tip:::') {
        if (tipOpen) {
          tipOpen = false;
          node.value = ''; // Clear the closing tag
          tree.children[0].children.splice(tree.children.indexOf(node.parent), 1, tipNode);
        } else {
          throw new Error('Closing tip without opening.');
        }
      } else if (tipOpen) {
        tipNode.value = value;
      }
    });
  };
}

<ReactMarkdown
      remarkPlugins={[RemarkBreaks as () => undefined, customInfoPlugin]}
      components={
        {
          tip: (infoProps) => {
            return <div>=====test=====</div>;
          },
        } as any
      }
    >
      {`:::tip:::       
      This is a custom tip!
      :::/tip:::`}
    </ReactMarkdown>
```

### Expected behavior

The content warped by :::tip::: and :::/tip::: will render by tip component.

### Actual behavior

It was rendered as text.

**Comment by ChristianMurphy** [comment]
Welcome @fengliner! 👋 
The markdown doesn't have a `tip` node type, so it doesn't know what to do with your custom node and skips it.
I think you are looking for data hName and hProperties which influence the HTML output/components.

https://github.com/syntax-tree/mdast-util-to-hast?tab=readme-ov-file#fields-on-nodes

**Comment by wooorm** [comment]
It looks like you are trying to make your own version of https://github.com/remarkjs/remark-directive. Perhaps you can use that instead btw!
