### ISSUE TITLE
Unable to parse latex using rehypeKatex plugin

### ISSUE THREAD

**Issue by agrajgarg** [remarkjs/react-markdown#851]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown:^9.0.0

### Steps to reproduce

Run the following code

```
const preprocessLaTeX = (content) => {
        // Replace block-level LaTeX delimiters \[ \] with $$ $$
        const blockProcessedContent = content.replace(
          /\\\[(.*?)\\\]/gs,
          (_, equation) => `$$${equation}$$`,
        );
        // Replace inline LaTeX delimiters \( \) with $ $
        const inlineProcessedContent = blockProcessedContent.replace(
          /\\\((.*?)\\\)/gs,
          (_, equation) => `$${equation}$`,
        );
        return inlineProcessedContent;
    };


{text && text.length > 0 &&
                            text.map((message, index) => (
                                <div key={index} className="markdown" id="bot-msg">
                                    <ReactMarkdown
                                        remarkPlugins={[remarkMath]} 
                                        rehypePlugins={[rehypeRaw, rehypeKatex]}
                                        components={{
                                            img: ({node, ...props}) => <img style={{maxWidth: '100%'}} {...props} />
                                        }}
                                    >
                                        {preprocessLaTeX(message)}
                                    </ReactMarkdown>
                                </div>
                            ))
                        }
```

### Expected behavior

Should render latex equations on the page3

### Actual behavior

giving error:

**_propertyInformation.hastToReact is undefined**

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Parcel

**Comment by wooorm** [comment]
Please fix your markdown. I cannot read this.

**Comment by wooorm** [comment]
Thanks!

Next step, when raising an issue, is to try to make your reproduction smaller.
As small as can be.
Remove everything that’s not related to the error.
I am quite sure that an `_propertyInformation.hastToReact` error does not come from your `img` component. Or from `preprocessLaTeX`.

Then, search through the existing issues. If you look for `hastToReact` here, you will find: https://github.com/remarkjs/react-markdown/issues/747

So, it seems that this error occurs because you use an older bundler with bugs: likely Parcel. Can you confirm this is the case?

**Comment by agrajgarg** [comment]
> Thanks!
> 
> Next step, when raising an issue, is to try to make your reproduction smaller. As small as can be. Remove everything that’s not related to the error. I am quite sure that an `_propertyInformation.hastToReact` error does not come from your `img` component. Or from `preprocessLaTeX`.
> 
> Then, search through the existing issues. If you look for `hastToReact` here, you will find: #747
> 
> So, it seems that this error occurs because you use an older bundler with bugs: likely Parcel. Can you confirm this is the case?

Yes, I checked the issue disappeared by manually doing 

`npm install property-information`

and 

`import 'property-information'`
in my component.
