### ISSUE TITLE
Dynamic children break the component

### ISSUE THREAD

**Issue by jonathandewitt-dev** [remarkjs/react-markdown#854]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [x] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown

### Steps to reproduce

Occasionally, through some whimsical magic, React will choose to render a single string passed to `children` as an array containing one string. I can't seem to reproduce this scenario reliably, it just happens at what seems like random times.

This being the case, however, means that there are valid markdown strings being passed as children which this component is not resilient enough to handle.  I keep getting variations of the error message:

```
Unexpected value `test` for `children` prop, expected `string`
```

Where "test" was simply my text string passed as the sole child to the Markdown component. Upon inspection, I was able to discover that my `string` was being converted to `string[]` and then rejected by the package. Not a great experience because there's quite literally nothing that can be done within my control when facing this situation.

I was able to fix the problem by temporarily modifying this library's code in my node_modules, from this:

```ts
  if (typeof children === 'string') {
    file.value = children
  } else {
    unreachable(
      'Unexpected value `' +
        children +
        '` for `children` prop, expected `string`'
    )
  }
  ```
  
  to this:

```ts
  const allChildrenAreStrings = Array.isArray(children) ? children.every((child) => typeof child === 'string') : typeof children === 'string';

  if (allChildrenAreStrings) {
    file.value = Array.isArray(children) ? children.join('\n') : children
  } else {
    unreachable(
      'Unexpected value `' +
        children +
        '` for `children` prop, expected `string`'
    )
  }
```

### Expected behavior

It should handle `string[]` children by confirming that each child is indeed of type `string` and then `Array.join('\n')` them to continue processing the markdown.

### Actual behavior

For `string[]` arrays, it reports an error and crashes the app.

**Comment by wooorm** [comment]
Hi!

`children` is the value *you* pass in. Sometimes through JSX. But it’s your choice how to pass it. You can pass weird things: `<Markdown>{1}{2}{3}</Markdown>`.

It will always be a simple string, if you are explicit, like is shown in the readme: `<Markdown children={`# some string`} />` or `<Markdown>{`# some string`}</Markdown>`.

**Comment by jonathandewitt-dev** [comment]
Hey there :wave: 

So I think there's a misunderstanding here. The string value we pass in is certainly _not_ always interpreted as a string, which is why I'm saying there is valid markdown text not supported by this package. We have no control over how our simple strings get parsed into JSX under the hood.

Here's some evidence I'm telling God's honest truth. :slightly_smiling_face: 

the type being passed:
![image](https://github.com/user-attachments/assets/76fbc80b-d4cc-438f-b5df-321705d96070)

the error:
![image](https://github.com/user-attachments/assets/030757dc-1099-408c-b926-2152c14b2ca2)

the type evaluated at runtime:
![image](https://github.com/user-attachments/assets/c534112a-7ccb-446c-976c-b6ca268dd20b)

the runtime type after it's been transformed by React/JSX:
![image](https://github.com/user-attachments/assets/5c6b6091-0539-45c1-bd86-3dddb70e9172)

**Comment by jonathandewitt-dev** [comment]
On a side note, I don't think it's adding all that much ambiguity to accept a list of strings, regarding https://github.com/remarkjs/react-markdown/pull/855#issuecomment-2309679735

Due to the way JSX works, I think it would be perfectly acceptable to support mapped children (although I don't know why you would need to, it seems like something we shan't judge if it's easy enough to permit it.) As long as the array passed in is checked to be sure each item in the array is only a string, I don't see how it could introduce much confusion.

**Comment by wooorm** [comment]
> The string value we pass in is certainly not always interpreted as a string, which is why I'm saying there is valid markdown text not supported by this package. We have no control over how our simple strings get parsed into JSX under the hood.

Here's some evidence I'm telling God's honest truth. 🙂

**Comment by jonathandewitt-dev** [comment]
> Your evidence is: TypeScript says it’s so.
> But TypeScript lies. TypeScript isn’t real

That is not the totality of my evidence. See the final two screenshots. Runtime doesn't lie.

**Comment by jonathandewitt-dev** [comment]
Here's some additional evidence if you're still not convinced.

![image](https://github.com/user-attachments/assets/c1b2fbb9-3db1-4f28-9337-6229a6798a83)

![image](https://github.com/user-attachments/assets/dbd5f74d-4bc6-46d2-8e8e-bf8be76d372b)

**Comment by wooorm** [comment]
Right. I also mentioned some other points though. Why would nobody else see this? Why could you not make a reproduction? My next assumption, as nobody else sees this, is that you have an uncommon JSX transform. Or a custom JSX runtime. Are there other things you can do to make the problem occur or disappear?

**Comment by jonathandewitt-dev** [comment]
Rest assured, I'm desperately trying to identify the root cause, because I find it as bizarre and unbelievable as you do. I'll let you know if and when I identify what's different about my scenario that confuses the transformer and causes it to become an array. There's nothing special about my project, it's just an ordinary Next.js project with all the default babel transforms OOTB.

I will also say this is not the first time I've encountered this (intermittent) error, but it's the first time I decided to contribute rather than hack around it or shop around for a different package - which is what I assume is happening for others, hence the silence around the matter.

Putting aside the reproduction, (which I am actively attempting to isolate on the side,) I wonder more about the reasoning behind the resistance to the change? Do you believe accepting `string[]` is going to introduce problems for users?

**Comment by wooorm** [comment]
There’s lots of things that can be thought up, such as: bugs need to be squashed, not shoved under the rug. Stuff like that.
Any bug that cannot be reproduced is highly suspicious. Any code that is not needed, or cannot be tested correctly, cannot be maintained well, is a problem for users.
I don’t want to maintain code in 10 years that I do not understand.

**Comment by sorintamas90** [comment]
I've got a similar issue just now. 

In my case the problem was that the text that I was fetching from my endpoint was too long. Once I reduced the length of the string that I was dynamically passing to the `<ReactMarkdown />` element everything worked again.

**Comment by wooorm** [comment]
How could that be an issue?

**Comment by sorintamas90** [comment]
> How could that be an issue? Can you please provide exactly how you are using `react-markdown`.

the following code is crashing my app ` <ReactMarkdown
        children="name@domain.com"
        remarkPlugins={[remarkGfm]}
      />`

as I previously said, if I add a space anywhere in the email address the code works fine

see the error bellow
![image](https://github.com/user-attachments/assets/9e80dedb-a2e4-4fa1-a466-567e5dd3614b)

**Comment by wooorm** [comment]
So you don’t have dynamic children, which is what this issue is about. Your problem seems to be Parcel being broken: https://github.com/remarkjs/react-markdown/issues/747#issuecomment-1674930974. Hiding these comments so we can focus on the OP.

**Comment by jonathandewitt-dev** [comment]
@wooorm 

Alright, I figured it out. It's not an intermittent JSX behavior after all. It's due to my package [react-shadow-scope](https://github.com/jonathandewitt-dev/react-shadow-scope)  emulating DSD with `React.Children.map()` [here](https://github.com/jonathandewitt-dev/react-shadow-scope/blob/master/src/children-utils.tsx#L9). All I need to do is add something like `resultChildren.length === 1 ? resultChildren[0] : resultChildren` and it works.

So I admit it, it's an upstream issue, not a problem with JSX or this package. :slightly_smiling_face:

(Though I still think it's a harmless addition that may avoid such weirdness in the future, but that's your discretion)

**Comment by wooorm** [comment]
Thanks but no thanks!
