### ISSUE TITLE
Attach onClick attribute to the elements

### ISSUE THREAD

**Issue by MuthuChess** [remarkjs/react-markdown#856]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I want to understand if it is allowed to attach an onClick event when mapping tag names to components. When the Markdown renders, the onclick attribute is not seen in the DOM. 

> <Markdown
         children={"some markdown content with a tag"}
        components={{
          a: (props) =>  <button onClick={() => console.log('alert clicked')}>  {props.children} </button>
        }}
      />

### Solution

Would like to know if there is a way to call onClick attribute

### Alternatives

Would like to know if there is a way to have a method called on click of an 'a' tag

**Comment by wooorm** [comment]
Your question has to do with React.
But you post an issue here on react-markdown.
Try the same out, *without* react-markdown, and see the same happening.
