### ISSUE TITLE
Table support

### ISSUE THREAD

**Issue by pejman-hkh** [remarkjs/react-markdown#862]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Please add table support

`
| th | th | th | | -- | -- | -- | | td | td | td | | td | td | td |
`

### Solution

You give us

### Alternatives

No alternative

**Comment by wooorm** [comment]
Read the docs please. Or at least search through them.
