### ISSUE TITLE
Newline and list do not work nicely together

### ISSUE THREAD

**Issue by ktalebian** [remarkjs/react-markdown#863]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9*

### Link to runnable example

https://codesandbox.io/p/sandbox/react-markdown-playground-forked-k4tsvz

### Steps to reproduce

Run the code

```js
import React from "react";
import ReactMarkdown from "react-markdown";
import remarkBreaks from "remark-breaks";

export default function App() {
  const input =
    "est1\n\n* test2\n\ntest3\n\n\n\n\n\n\n\ntest4\n\nas\n\nasdasdasd";
  const input2 = input.replace(/\n\n/g, "&nbsp;\n");

  return (
    <div className="App">
      <ReactMarkdown remarkPlugins={[remarkBreaks]}>{input}</ReactMarkdown>
    </div>
  );
}
```

If you pass `input`, you get a properly listed result, but multi-newlines are not working.

If you pass `input2`, you get multiple new lines, but the link is improper (by that I mean all the text after `* test2` all go inside the `<li>` tag - you can inspect the Element and see). This is not just aesthetic - the problem is, because all the text is in `<li>`, any change I make to the text affects all the other texts as well.

### Expected behavior

To be able to have multiple line and list working together

### Actual behavior

see above

### Affected runtime and version

node@22

### Affected package manager and version

npm@10

**Comment by wooorm** [comment]
> but multi-newlines are not working.

How do you think they should work?

Because this is how markdown works. Try it out. Here on GH. Other places. Or https://spec.commonmark.org/dingus/
