### ISSUE TITLE
tel: href tag not working

### ISSUE THREAD

**Issue by vitalijalbu** [remarkjs/react-markdown#865]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.1

### Steps to reproduce

Basically I added a simple phone tel: link and it not passing href props

![Screenshot 2024-10-17 alle 10 40 17](https://github.com/user-attachments/assets/c5b8a47b-363d-40f5-a2f1-25ecfe301295)

### Expected behavior

It should work as expected

### Actual behavior

Not passing props.

my code:

  ```
const components = {
    p: PComponent,
    h1: H1Component,
    h2: H2Component,
    h3: H3Component,
    h4: H4Component,
    h5: H5Component,
    h6: H6Component,
    strong: StrongComponent,
    em: EmComponent,
    a: AComponent,
    ul: UlComponent,
    ol: OlComponent,
    img: ImgComponent,
    blockquote: QuoteComponent,
    table: TableComponent,
  };
  
  <Markdown
        remarkPlugins={[
          remarkGfm,
          remarkCustomHeaderId,
          remarkParse,
          remarkLinkTarget,
        ]}
        rehypePlugins={[rehypeRaw]}
        components={components}
      >
        {markdown}
      </Markdown>
  
function AComponent({ children, href = '#', ...props }: LinkProps) {
  console.log('AComponent', {href, props, children});
  if (href.startsWith('tel:')) {
    return (
      <a href={href} {...props}>
        {children}
      </a>
    );
  } else {
    return (
      <TextLink href={href} {...props}>
        {children}
      </TextLink>
    );
  }
}

```

### Affected runtime and version

node 20

**Comment by vitalijalbu** [comment]
Tried also on your md editr online and not working

**Comment by wooorm** [comment]
It is working. It is removed. Read the docs. You want to define `urlTransform`.
