### ISSUE TITLE
Adding support of "highlight", 'strikethrough"

### ISSUE THREAD

**Issue by amitkroutthedev** [remarkjs/react-markdown#867]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

While developing a application, I faced rendering issues in highlight functionality (==text==) and strike-through functionality.

### Solution

Addition of supported component in components list(attribute). I can also help in finding solutions for it.

### Alternatives

N/A

**Comment by wooorm** [comment]
Hi!

Strikethrough is part of GFM. Please read the readme on how to do GFM.

Highlight is not part of a one of the common extensions that are supported.
It is also not common. Most places don’t support it.
You can make custom extensions. But it is not recommend. See https://github.com/micromark/micromark#extensions

**Comment by amitkroutthedev** [comment]
Thank You!
