### ISSUE TITLE
Peer Dependency Issue: React-markdown not compatible with Next.js 15 (React 19 RC)

### ISSUE THREAD

**Issue by justrach** [remarkjs/react-markdown#871]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

eact-markdown: 9.0.1 react: 19.0.0-rc-69d4b800-20241021 next: 15

### Steps to reproduce

# Create minimal reproduction
npx create-next-app@latest my-app --use-npm
cd my-app
npm install react-markdown

Steps to reproduce

Create a new Next.js 15 project
Try to install react-markdown
Observe the following error:

npm error While resolving: psych_frontend@0.1.0                      
npm error Found: react@19.0.0-rc-69d4b800-20241021                   
npm error node_modules/react
npm error   react@"19.0.0-rc-69d4b800-20241021" from the root project

npm error Could not resolve dependency:
npm error peer react@">=18" from react-markdown@9.0.1
npm error node_modules/react-markdown
npm error   react-markdown@"^9.0.1" from the root project

### Expected behavior

react-markdown should install successfully with React 19 RC, as it's a newer version than the specified peer dependency requirement of >=18.

### Actual behavior

Installation fails due to peer dependency constraints not recognizing React 19 RC as a valid version.

### Affected runtime and version

Node: 20.11.0 npm: 10.2.4

### Build and bundle tools

Vite, Next.js

**Comment by ChristianMurphy** [comment]
@justrach it is compatible, React 18 is still supported by next.js

> In version 15, the App Router uses React 19 RC, and we've also introduced backwards compatibility for React 18 with the Pages Router based on community feedback. If you're using the Pages Router, this allows you to upgrade to React 19 when ready.

https://nextjs.org/blog/next-15#react-19

**Comment by ChristianMurphy** [comment]
React 19 support will be considered here when it is GA.

**Comment by ChristianMurphy** [comment]
@j2ghz you can nudge the next team to maintain support in app router as well.

For react-markdown

> React 19 support will be considered here when it is GA.

**Comment by Akuukis** [comment]
React 19 is GA now since [Dec 5](https://react.dev/blog/2024/12/05/react-19) :rocket:
@ChristianMurphy will `react-markdown` support it?

**Comment by ChristianMurphy** [comment]
@j2ghz yes, React 19 is planned.
If you would like to accelerate the effort feel free to open a PR.
React 19 is a bit more involved than changing the version range, the typescript types have been completely redone for JSX.

**Comment by j2ghz** [comment]
I think you meant to mention @Akuukis. Could the issue be reopened so it's clear it's up for grabs or if there's any updates?

**Comment by ChristianMurphy** [comment]
> I think you meant to mention https://github.com/Akuukis

I did, adjusted

> or a new issue of something, so people can find it more easily

A new issue would be better, we won't support React 19 RC, only GA.
And will be more focused on React 19 generally than Next per se.

**Comment by prichey** [comment]
I created a new issue for React 19 support here: https://github.com/remarkjs/react-markdown/issues/877
