### ISSUE TITLE
Cannot add overflow property to table 

### ISSUE THREAD

**Issue by derikpham** [remarkjs/react-markdown#872]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.1

### Steps to reproduce

1. Render a bigger markdown table that has many columns to require horizontal scroll. 
2. Add a paragraph into the markdown content. 
3. The horizontal scroll is applied to the entire react markdown component (include the paragraph and table)

### Expected behavior

The horizontal scroll should only be applied to the table. 
I have to insert the <table> into a <div> that it has fixed size, and in <div> style I have to set overflow: scroll
But currently react-mark is not wrapping the table in a div making scroll localized to the table (and not the entire markdown content) impossible

### Actual behavior

Scroll to the right make the entire markdown content scroll.

### Affected runtime and version

react 18.3.1, node 23.0.0

### Build and bundle tools

Create React App

How table is being rendered currently
![image](https://github.com/user-attachments/assets/baf4a589-3670-4803-add9-22d20eca3434)

Expected table to be wrapped in div block
![image](https://github.com/user-attachments/assets/f74761dc-36d3-43fa-9769-4257c05fc719)

**Comment by ChristianMurphy** [comment]
Welcome @derikpham! 👋 
React Markdown by default generates Commonmark standard output, which does not include these attributes.
Nor does GFM another common flavor supported.

A plugin could add additional attributes to style
https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins
https://github.com/rehypejs/rehype/blob/main/doc/plugins.md

Or override the table component to add you desired custom CSS
https://github.com/remarkjs/react-markdown?tab=readme-ov-file#components
