### ISSUE TITLE
NPM installation failed

### ISSUE THREAD

**Issue by adetorodev** [remarkjs/react-markdown#873]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react 

### Steps to reproduce

Install react-markdown

### Expected behavior

to install reat-markdown

### Actual behavior

code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: cleverai@0.1.0
npm error Found: react@19.0.0-rc-66855b96-20241106
npm error node_modules/react
npm error   react@"19.0.0-rc-66855b96-20241106" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@">=18" from react-markdown@9.0.1
npm error node_modules/react-markdown
npm error   react-markdown@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.

### Affected runtime and version

node 20.18.0

### Affected package manager and version

npm

**Comment by ChristianMurphy** [comment]
Hey @adetorodev! 👋 
There is no bug, you are using a pre-release of react.
We support the stable release, and will consider react 19 support when it becomes stable.

**Comment by jsomdev** [comment]
React 19 is marked stable @ChristianMurphy .

**Comment by ChristianMurphy** [comment]
@jsomdev pull requests are welcome!
I suspect this one will be more involved, react 19 redoes the JSX types which this package relies on.
