### ISSUE TITLE
After rewriting the img components, each rolling of the page will cause Image to reload, and the page flickering

### ISSUE THREAD

**Issue by QiaoLi1996** [remarkjs/react-markdown#881]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=issues) and [discussions](https://github.com/orgs/remarkjs/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

"react-markdown": "^9.0.1",   "next": "15.0.4-canary.31",

### Steps to reproduce

I need to add attributes `Crossorigin = "Anonymous"` to support the cross -domain of image resources. I did not find a good method, so I rewritten IMG components. As shown below:
```javascript
 components={{
                img({ src, alt }) {
                    return <img src={src} alt={alt} crossOrigin="anonymous" />
                },
            }}
```
Then the error happened

### Actual behavior

Each rolling of the page will cause Image to reload, and the page flickering.
But the default behavior is normal, remove the iMage rewriting code to return to normal.

### Expected behavior

After rewriting the img components, each rolling of the page not reload the image

**Comment by remcohaszing** [comment]
You should define the `img` component outside of any other components
