### ISSUE TITLE
Feature request: Footnotes

### ISSUE THREAD

**Issue by vadimshvetsov** [remarkjs/react-markdown#94]
First of all, thank you for your awesome work!

Is there any way to use [footnotes](https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide#footnotes) within this component?

As I know it is a part of an extended [MultiMarkdown](https://github.com/fletcher/MultiMarkdown/wiki/What-Is-MultiMarkdown) syntax of Markdown.

**Comment by wallawe** [comment]
@vadimshvetsov What did you end up using as a solution?

**Comment by vadimshvetsov** [comment]
I've didn't found good solution and reject this feature :(

**Comment by Andrewjeska** [comment]
https://www.npmjs.com/package/markdown-to-jsx

**Comment by Andrewjeska** [comment]
^These guys support it

**Comment by ChristianMurphy** [comment]
Footnote support can be added to react markdown through plugins, specifically https://github.com/remarkjs/remark-footnotes

**Comment by wooorm** [comment]
The answer is indeed to use plugins.
